let a: [string, number];
let b: [string, number?];
let c: [string, ...number[]];
let d: [a: string, b: number];
let e: [first: string, second?: number];
let f: [...rest: number[]];
let g: [A, B?, ...C];
let h: [number?, boolean?];
let i: [a: 1, b?: 2 | undefined];
let j: [];
let k: [(A | B), C];
let l: [A][0];
let m: [A][];
