let a: keyof T;
let b: keyof Person;
let c: keyof T[];
let d: unique symbol;
let e: readonly number[];
let f: readonly [string, number];
let g: readonly A[][];
let h: keyof A | keyof B;
let i: A & keyof B;
let j: readonly keyof T;
let k: keyof keyof T;
let l: readonly (string | number)[];
let m: keyof { a: 1; b: 2 };
let n: Array<keyof T>;
let o: [a: keyof T, b?: readonly U[]];
let p: T extends keyof U ? X : Y;
