import { parse } from "yuku-parser";

const source = await Bun.file("test/index.js").text();

parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);
parse(source);

console.time("parse");
parse(source);
console.timeEnd("parse");
