version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "yuku-*"
      - dependency-name: "@yuku-*/*"
