// AST transfer format v8, the wire format in both FFI directions. little endian, no
// version byte. the extern structs define the layout the serializer, deserializer, and
// the decoder generated by tools/estree/decoder.zig all share
//
// buffer sections, in order
//
//   header             HEADER_SIZE bytes, section counts and flags
//   nodes              node_count * NODE_SIZE bytes, one PackedNode each
//   extra              extra_count * 4 bytes, flat u32 array backing IndexRange
//   strings            string_pool_len bytes of raw UTF-8, zero-padded to a 4-byte boundary
//   attached_offsets   (node_count + 1) u32 prefix sums, only with FLAG_ATTACHED_COMMENTS
//   attached_comments  attached_comment_count * ATTACHED_COMMENT_SIZE bytes
//   comments           comment_count * COMMENT_SIZE bytes in source order, only with FLAG_COMMENTS
//   tokens             token_count * TOKEN_SIZE bytes, one `Token` each, copied as is
//   diagnostics        variable length, written by the encoder and skipped by the decoder
//
// node packing, per field type
//
//   bool              1 flag bit
//   enum              ceil(log2(n)) flag bits, where n is the variant count
//   NodeIndex         1 u32 slot, 0xFFFFFFFF marks null
//   IndexRange        the first two keep a u16 length in field0/field0b and take 1 u32 slot
//                     each for start, any later one takes 2 u32 slots, start then length
//   String            2 u32 slots (start, end)
//   ?ImportPhase      1 flag bit for presence plus enum bits for the value
//   ?Hashbang         1 flag bit for presence plus 2 u32 slots (start, end)
//
// string handles
//
//   start <  source_len   a slice of the original source buffer
//   start >= source_len   a slice of the string pool, at offset (start - source_len)
//
// diagnostics, diag_count entries of
//
//     1 byte    severity (0 error, 1 warning, 2 hint, 3 info)
//     4 bytes   span_start
//     4 bytes   span_end
//     4 bytes   message_len
//     n bytes   message text (UTF-8)
//     1 byte    has_help flag
//     when has_help is 1:
//       4 bytes   help_len
//       n bytes   help text (UTF-8)
//     4 bytes   label_count
//     per label:
//       4 bytes   span_start
//       4 bytes   span_end
//       4 bytes   message_len
//       n bytes   message text (UTF-8)

const std = @import("std");
const ast = @import("parser").ast;

/// The analyzer's semantic sections, layered on this format.
pub const semantic = @import("semantic.zig");

// field order defines the wire layout
const Header = extern struct {
    node_count: u32,
    extra_count: u32,
    string_pool_len: u32,
    source_len: u32,
    comment_count: u32,
    attached_comment_count: u32,
    token_count: u32,
    diag_count: u32,
    program_index: u32,
    flags: u32,
    // positions below this are an identity map for the decoder's position conversion
    first_non_ascii: u32,
};

// the first two IndexRanges of a struct keep their u16 length in field0 and field0b
// and take one slot each for start, any later one takes two slots
const PackedNode = extern struct {
    tag: u8,
    _pad0: u8 = 0,
    flags: u16,
    field0: u16,
    field0b: u16,
    field1: u32,
    field2: u32,
    field3: u32,
    field4: u32,
    field5: u32,
    field6: u32,
    field7: u32,
    span_start: u32,
    span_end: u32,
};

// `flags` bit 0 is the type, 0 line and 1 block
const PackedComment = extern struct {
    flags: u8,
    _pad: [3]u8 = .{ 0, 0, 0 },
    value_start: u32,
    value_end: u32,
    span_start: u32,
    span_end: u32,
};

pub const COMMENT_TYPE_BIT: u8 = 0;

// the host node is implicit from the entry index and the offsets table, `flags` packs
//   bit 0     type       (0 line, 1 block)
//   bits 1-2  position   (0 before, 1 after, 2 inside)
//   bit 3     same_line
const PackedAttachedComment = extern struct {
    flags: u8,
    _pad: [3]u8 = .{ 0, 0, 0 },
    value_start: u32,
    value_end: u32,
};

pub const ATTACHED_COMMENT_POSITION_SHIFT: u8 = 1;
pub const ATTACHED_COMMENT_POSITION_MASK: u8 = 0b11 << ATTACHED_COMMENT_POSITION_SHIFT;
pub const ATTACHED_COMMENT_SAME_LINE_BIT: u8 = 3;

pub const HEADER_SIZE: u32 = @sizeOf(Header);
pub const NODE_SIZE: u32 = @sizeOf(PackedNode);
pub const COMMENT_SIZE: u32 = @sizeOf(PackedComment);
pub const ATTACHED_COMMENT_SIZE: u32 = @sizeOf(PackedAttachedComment);
pub const TOKEN_SIZE: u32 = @sizeOf(ast.Token);

pub const HDR_NODE_COUNT_U32: u32 = @offsetOf(Header, "node_count") / 4;
pub const HDR_EXTRA_COUNT_U32: u32 = @offsetOf(Header, "extra_count") / 4;
pub const HDR_STRING_POOL_LEN_U32: u32 = @offsetOf(Header, "string_pool_len") / 4;
pub const HDR_SOURCE_LEN_U32: u32 = @offsetOf(Header, "source_len") / 4;
pub const HDR_COMMENT_COUNT_U32: u32 = @offsetOf(Header, "comment_count") / 4;
pub const HDR_ATTACHED_COMMENT_COUNT_U32: u32 = @offsetOf(Header, "attached_comment_count") / 4;
pub const HDR_TOKEN_COUNT_U32: u32 = @offsetOf(Header, "token_count") / 4;
pub const HDR_DIAG_COUNT_U32: u32 = @offsetOf(Header, "diag_count") / 4;
pub const HDR_PROGRAM_INDEX_U32: u32 = @offsetOf(Header, "program_index") / 4;
pub const HDR_FLAGS_U32: u32 = @offsetOf(Header, "flags") / 4;
pub const HDR_FIRST_NON_ASCII_U32: u32 = @offsetOf(Header, "first_non_ascii") / 4;

pub const FLAG_TS: u32 = 1 << 0;
pub const FLAG_ATTACHED_COMMENTS: u32 = 1 << 1;
pub const FLAG_COMMENTS: u32 = 1 << 2;
/// Semantic sections follow the diagnostics section. Decoders that stop at diagnostics
/// never see them.
pub const FLAG_SEMANTIC: u32 = 1 << 3;

pub const NODE_FLAGS_OFFSET: u8 = @offsetOf(PackedNode, "flags");
pub const NODE_FIELD0_OFFSET: u8 = @offsetOf(PackedNode, "field0");
pub const NODE_FIELD0B_OFFSET: u8 = @offsetOf(PackedNode, "field0b");
pub const NODE_HEADER_U32S: u8 = @offsetOf(PackedNode, "field1") / 4;
pub const NODE_SPAN_START_U32: u8 = @offsetOf(PackedNode, "span_start") / 4;
pub const NODE_SPAN_END_U32: u8 = @offsetOf(PackedNode, "span_end") / 4;

pub const NODE_DATA_SLOTS: u8 = NODE_SPAN_START_U32 - NODE_HEADER_U32S;
pub const NODE_FLAG_BITS: u8 = @bitSizeOf(@FieldType(PackedNode, "flags"));

pub const COMMENT_FLAGS_OFFSET: u8 = @offsetOf(PackedComment, "flags");
pub const COMMENT_VALUE_START_OFFSET: u8 = @offsetOf(PackedComment, "value_start");
pub const COMMENT_VALUE_END_OFFSET: u8 = @offsetOf(PackedComment, "value_end");
pub const COMMENT_SPAN_START_OFFSET: u8 = @offsetOf(PackedComment, "span_start");
pub const COMMENT_SPAN_END_OFFSET: u8 = @offsetOf(PackedComment, "span_end");

pub const ATTACHED_COMMENT_FLAGS_OFFSET: u8 = @offsetOf(PackedAttachedComment, "flags");
pub const ATTACHED_COMMENT_VALUE_START_OFFSET: u8 = @offsetOf(PackedAttachedComment, "value_start");
pub const ATTACHED_COMMENT_VALUE_END_OFFSET: u8 = @offsetOf(PackedAttachedComment, "value_end");

// u32 columns of a token entry
pub const TOKEN_START_U32: u8 = (@offsetOf(ast.Token, "span") + @offsetOf(ast.Span, "start")) / 4;
pub const TOKEN_END_U32: u8 = (@offsetOf(ast.Token, "span") + @offsetOf(ast.Span, "end")) / 4;
pub const TOKEN_TAG_U32: u8 = @offsetOf(ast.Token, "tag") / 4;
pub const TOKEN_FLAGS_U32: u8 = @offsetOf(ast.Token, "flags") / 4;

comptime {
    std.debug.assert(TOKEN_SIZE == 16);
    std.debug.assert(@offsetOf(ast.Token, "flags") % 4 == 0);
}

comptime {
    validateAllNodeLayouts();
}

// layout helpers shared with the decoder generator in tools/estree/decoder.zig

/// Flag bits consumed by field `field_idx` of struct `T`.
pub fn flagBitCount(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == bool) return 1;
    if (f.type == ?ast.ImportPhase) return 1 + enumBitWidth(ast.ImportPhase);
    if (f.type == ?ast.Hashbang) return 1;
    if (comptime isEnumType(f.type)) return enumBitWidth(f.type);
    if (f.type == ast.NodeIndex or f.type == ast.IndexRange or f.type == ast.String) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// First flag bit of field `target` in struct `T`.
pub fn flagBitForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var bit: u8 = 0;
        for (0..target) |i| bit += flagBitCount(T, i);
        return bit;
    }
}

/// The u32 slots consumed by field `field_idx` of struct `T`. The first two IndexRanges
/// take one slot, later ones two.
pub fn fieldU32Count(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == ast.NodeIndex) return 1;
    if (f.type == ast.IndexRange) return if (rangeIndexOf(T, field_idx) < 2) 1 else 2;
    if (f.type == ast.String) return 2;
    if (f.type == ?ast.Hashbang) return 2;
    if (f.type == bool or f.type == ?ast.ImportPhase or comptime isEnumType(f.type)) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// First u32 slot of field `target` in struct `T`.
pub fn u32SlotForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var slot: u8 = 0;
        for (0..target) |i| slot += fieldU32Count(T, i);
        return slot;
    }
}

/// Position of the IndexRange field `target` among the IndexRange fields of struct `T`.
pub fn rangeIndexOf(comptime T: type, comptime target: usize) u8 {
    comptime {
        std.debug.assert(std.meta.fields(T)[target].type == ast.IndexRange);
        var idx: u8 = 0;
        for (std.meta.fields(T)[0..target]) |f| {
            if (f.type == ast.IndexRange) idx += 1;
        }
        return idx;
    }
}

/// Flag bits needed to hold every variant of `E`.
pub fn enumBitWidth(comptime E: type) u8 {
    return std.math.log2_int_ceil(usize, @typeInfo(E).@"enum".fields.len);
}

pub fn isEnumType(comptime T: type) bool {
    return @typeInfo(T) == .@"enum";
}

/// Total u32 slots used by struct `T`.
pub fn totalU32Slots(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += fieldU32Count(T, i);
        return total;
    }
}

/// Total flag bits used by struct `T`.
pub fn totalFlagBits(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += flagBitCount(T, i);
        return total;
    }
}

fn validateAllNodeLayouts() void {
    @setEvalBranchQuota(10_000);
    for (@typeInfo(ast.NodeData).@"union".fields) |field| {
        const T = field.type;
        if (@typeInfo(T) != .@"struct") continue;
        if (totalU32Slots(T) > NODE_DATA_SLOTS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} u32 slots",
            .{ field.name, NODE_DATA_SLOTS },
        ));
        if (totalFlagBits(T) > NODE_FLAG_BITS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} flag bits",
            .{ field.name, NODE_FLAG_BITS },
        ));
    }
}

/// String pool length rounded up to the 4-byte boundary it occupies on the wire.
pub inline fn alignPool(len: usize) usize {
    return (len + 3) & ~@as(usize, 3);
}

pub fn bufferSize(tree: *const ast.Tree) usize {
    std.debug.assert(tree.nodes.len <= std.math.maxInt(u32));
    std.debug.assert(tree.extras.items.len <= std.math.maxInt(u32));
    std.debug.assert(tree.source.len <= std.math.maxInt(u32));
    // severity, span_start, span_end, message_len, has_help, label_count
    const diag_fixed = 1 + 4 + 4 + 4 + 1 + 4;
    const help_prefix = 4; // help_len
    const label_fixed = 4 + 4 + 4; // start, end, message_len

    var size: usize = HEADER_SIZE +
        tree.nodes.len * NODE_SIZE +
        tree.extras.items.len * 4 +
        alignPool(tree.strings.extra.items.len) +
        tree.attached_comment_offsets.len * 4 +
        tree.attached_comments.len * ATTACHED_COMMENT_SIZE +
        tree.comments.len * COMMENT_SIZE +
        tree.tokens.len * TOKEN_SIZE;

    for (tree.diagnostics.items) |d| {
        size += diag_fixed + d.message.len;
        if (d.help) |h| size += help_prefix + h.len;
        for (d.labels) |lbl| size += label_fixed + lbl.message.len;
    }
    return size;
}

pub fn serializeInto(tree: *const ast.Tree, buf: []u8) usize {
    std.debug.assert(buf.len >= bufferSize(tree));
    std.debug.assert(tree.root != .null);
    std.debug.assert(@intFromPtr(buf.ptr) % 4 == 0);

    const string_pool_len: u32 = @intCast(tree.strings.extra.items.len);
    const has_attached = tree.attached_comment_offsets.len != 0;
    const has_comments = tree.comments.len != 0;
    std.debug.assert(!has_attached or tree.attached_comment_offsets.len == tree.nodes.len + 1);

    var hdr_flags: u32 = 0;
    if (tree.isTs()) hdr_flags |= FLAG_TS;
    if (has_attached) hdr_flags |= FLAG_ATTACHED_COMMENTS;
    if (has_comments) hdr_flags |= FLAG_COMMENTS;

    const hdr = Header{
        .node_count = @intCast(tree.nodes.len),
        .extra_count = @intCast(tree.extras.items.len),
        .string_pool_len = string_pool_len,
        .source_len = @intCast(tree.source.len),
        .comment_count = @intCast(tree.comments.len),
        .attached_comment_count = @intCast(tree.attached_comments.len),
        .token_count = @intCast(tree.tokens.len),
        .diag_count = @intCast(tree.diagnostics.items.len),
        .program_index = @intFromEnum(tree.root),
        .flags = hdr_flags,
        .first_non_ascii = @intCast(firstNonAsciiOffset(tree.source)),
    };
    @memcpy(buf[0..HEADER_SIZE], std.mem.asBytes(&hdr));
    var pos: usize = HEADER_SIZE;

    const nodes_out: [*]PackedNode = @ptrCast(@alignCast(buf.ptr + pos));
    const data_items = tree.nodes.items(.data);
    const span_items = tree.nodes.items(.span);
    for (data_items, span_items, 0..) |*data, span, i| {
        nodes_out[i] = packNode(data, span);
    }
    pos += @as(usize, hdr.node_count) * NODE_SIZE;

    const extra_bytes = std.mem.sliceAsBytes(tree.extras.items);
    @memcpy(buf[pos..][0..extra_bytes.len], extra_bytes);
    pos += extra_bytes.len;

    @memcpy(buf[pos..][0..string_pool_len], tree.strings.extra.items);
    const pool_pad = alignPool(string_pool_len) - string_pool_len;
    @memset(buf[pos + string_pool_len ..][0..pool_pad], 0);
    pos += string_pool_len + pool_pad;

    const offsets_bytes = std.mem.sliceAsBytes(tree.attached_comment_offsets);
    @memcpy(buf[pos..][0..offsets_bytes.len], offsets_bytes);
    pos += offsets_bytes.len;

    const attached_out: [*]PackedAttachedComment = @ptrCast(@alignCast(buf.ptr + pos));
    for (tree.attached_comments, 0..) |c, i| {
        var flags: u8 = 0;
        if (c.type == .block) flags |= 1 << COMMENT_TYPE_BIT;
        flags |= @as(u8, @intFromEnum(c.position)) << ATTACHED_COMMENT_POSITION_SHIFT;
        if (c.same_line) flags |= 1 << ATTACHED_COMMENT_SAME_LINE_BIT;
        attached_out[i] = .{
            .flags = flags,
            .value_start = c.value.start,
            .value_end = c.value.end,
        };
    }
    pos += tree.attached_comments.len * ATTACHED_COMMENT_SIZE;

    const comments_out: [*]PackedComment = @ptrCast(@alignCast(buf.ptr + pos));
    for (tree.comments, 0..) |c, i| {
        comments_out[i] = .{
            .flags = if (c.type == .block) 1 << COMMENT_TYPE_BIT else 0,
            .value_start = c.value.start,
            .value_end = c.value.end,
            .span_start = c.span.start,
            .span_end = c.span.end,
        };
    }
    pos += tree.comments.len * COMMENT_SIZE;

    const token_bytes = std.mem.sliceAsBytes(tree.tokens);
    @memcpy(buf[pos..][0..token_bytes.len], token_bytes);
    pos += token_bytes.len;

    for (tree.diagnostics.items) |d| {
        buf[pos] = @intFromEnum(d.severity);
        pos += 1;
        w32(buf, pos, d.span.start);
        pos += 4;
        w32(buf, pos, d.span.end);
        pos += 4;
        w32(buf, pos, @intCast(d.message.len));
        pos += 4;
        @memcpy(buf[pos..][0..d.message.len], d.message);
        pos += d.message.len;
        if (d.help) |h| {
            buf[pos] = 1;
            pos += 1;
            w32(buf, pos, @intCast(h.len));
            pos += 4;
            @memcpy(buf[pos..][0..h.len], h);
            pos += h.len;
        } else {
            buf[pos] = 0;
            pos += 1;
        }
        w32(buf, pos, @intCast(d.labels.len));
        pos += 4;
        for (d.labels) |lbl| {
            w32(buf, pos, lbl.span.start);
            pos += 4;
            w32(buf, pos, lbl.span.end);
            pos += 4;
            w32(buf, pos, @intCast(lbl.message.len));
            pos += 4;
            @memcpy(buf[pos..][0..lbl.message.len], lbl.message);
            pos += lbl.message.len;
        }
    }

    std.debug.assert(pos == bufferSize(tree));
    return pos;
}

fn packNode(data: *const ast.NodeData, span: ast.Span) PackedNode {
    std.debug.assert(span.start <= span.end);
    var n: PackedNode = std.mem.zeroes(PackedNode);
    n.span_start = span.start;
    n.span_end = span.end;
    // captured by pointer to avoid copying the 44-byte union per node
    switch (data.*) {
        inline else => |*payload, tag| {
            n.tag = @intFromEnum(tag);
            packPayload(&n, payload);
        },
    }
    return n;
}

fn packPayload(n: *PackedNode, payload: anytype) void {
    const T = @typeInfo(@TypeOf(payload)).pointer.child;
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const val = @field(payload, f.name);
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            if (val) setFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            setSlot(n, slot, @intFromEnum(val));
        } else if (f.type == ast.IndexRange) {
            switch (comptime rangeIndexOf(T, i)) {
                0 => n.field0 = @intCast(val.len),
                1 => n.field0b = @intCast(val.len),
                else => setSlot(n, slot + 1, @intCast(val.len)),
            }
            setSlot(n, slot, val.start);
        } else if (f.type == ast.String) {
            setSlot(n, slot, val.start);
            setSlot(n, slot + 1, val.end);
        } else if (comptime isEnumType(f.type)) {
            setFlagBits(n, bit, @intFromEnum(val));
        } else if (f.type == ?ast.ImportPhase) {
            if (val) |v| {
                setFlagBit(n, bit);
                setFlagBits(n, bit + 1, @intFromEnum(v));
            }
        } else if (f.type == ?ast.Hashbang) {
            if (val) |h| {
                setFlagBit(n, bit);
                setSlot(n, slot, h.value.start);
                setSlot(n, slot + 1, h.value.end);
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++
                "' in " ++ @typeName(T));
        }
    }
}

inline fn setFlagBit(n: *PackedNode, comptime bit: u8) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), 1) << @intCast(bit);
}

inline fn setFlagBits(n: *PackedNode, comptime bit: u8, val: anytype) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), @intCast(val)) << @intCast(bit);
}

inline fn setSlot(n: *PackedNode, comptime slot: u8, val: u32) void {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    @as([*]u32, @ptrCast(&n.field1))[slot] = val;
}

inline fn w32(buf: []u8, pos: usize, val: u32) void {
    std.mem.writeInt(u32, buf[pos..][0..4], val, .little);
}

fn firstNonAsciiOffset(source: []const u8) usize {
    const Vec = @Vector(16, u8);
    const hi: Vec = @splat(0x80);
    var i: usize = 0;
    while (i + 16 <= source.len) : (i += 16) {
        if (@reduce(.Or, source[i..][0..16].* & hi) != 0) {
            for (source[i..][0..16], 0..) |c, k| if (c >= 0x80) return i + k;
            unreachable;
        }
    }
    for (source[i..], 0..) |c, k| if (c >= 0x80) return i + k;
    return source.len;
}

// reverses `serializeInto` except for diagnostics, which the codegen path never reads

pub const DeserializeError = error{ InvalidBuffer, OutOfMemory };

pub fn deserializeFromBuf(
    allocator: std.mem.Allocator,
    buf: []const u8,
    source: []const u8,
) DeserializeError!ast.Tree {
    if (buf.len < HEADER_SIZE) return error.InvalidBuffer;
    std.debug.assert(@intFromPtr(buf.ptr) % 4 == 0);

    var hdr: Header = undefined;
    @memcpy(std.mem.asBytes(&hdr), buf[0..HEADER_SIZE]);

    // an empty source means every `String` resolves through the pool
    std.debug.assert(source.len == 0 or source.len == hdr.source_len);
    std.debug.assert(hdr.program_index < hdr.node_count);

    var tree = ast.Tree.init(allocator, source);
    errdefer tree.deinit();

    if (hdr.flags & FLAG_TS != 0) tree.lang = .ts;

    var pos: usize = HEADER_SIZE;

    const nodes_bytes: usize = @as(usize, hdr.node_count) * NODE_SIZE;
    if (buf.len < pos + nodes_bytes) return error.InvalidBuffer;
    try tree.nodes.resize(tree.allocator(), hdr.node_count);
    const nodes_in: [*]const PackedNode = @ptrCast(@alignCast(buf.ptr + pos));
    for (0..hdr.node_count) |i| {
        const pn = nodes_in[i];
        tree.nodes.set(i, .{
            .data = unpackNode(pn),
            .span = .{ .start = pn.span_start, .end = pn.span_end },
        });
    }
    pos += nodes_bytes;

    const extras_bytes: usize = @as(usize, hdr.extra_count) * 4;
    if (buf.len < pos + extras_bytes) return error.InvalidBuffer;
    try tree.extras.resize(tree.allocator(), hdr.extra_count);
    @memcpy(std.mem.sliceAsBytes(tree.extras.items), buf[pos..][0..extras_bytes]);
    pos += extras_bytes;

    if (buf.len < pos + alignPool(hdr.string_pool_len)) return error.InvalidBuffer;
    try tree.strings.extra.resize(tree.allocator(), hdr.string_pool_len);
    @memcpy(tree.strings.extra.items, buf[pos..][0..hdr.string_pool_len]);
    pos += alignPool(hdr.string_pool_len);

    const has_attached = (hdr.flags & FLAG_ATTACHED_COMMENTS) != 0;
    if (has_attached) {
        const offsets_count: usize = @as(usize, hdr.node_count) + 1;
        const offsets_bytes = offsets_count * 4;
        if (buf.len < pos + offsets_bytes) return error.InvalidBuffer;
        const offsets = try tree.allocator().alloc(u32, offsets_count);
        @memcpy(std.mem.sliceAsBytes(offsets), buf[pos..][0..offsets_bytes]);
        tree.attached_comment_offsets = offsets;
        pos += offsets_bytes;
    }

    const attached_bytes: usize = @as(usize, hdr.attached_comment_count) * ATTACHED_COMMENT_SIZE;
    if (buf.len < pos + attached_bytes) return error.InvalidBuffer;
    if (hdr.attached_comment_count > 0) {
        const attached = try tree.allocator().alloc(ast.AttachedComment, hdr.attached_comment_count);
        const attached_in: [*]const PackedAttachedComment = @ptrCast(@alignCast(buf.ptr + pos));
        for (attached, 0..) |*out, i| {
            const ce = attached_in[i];
            const pos_bits = (ce.flags & ATTACHED_COMMENT_POSITION_MASK) >> ATTACHED_COMMENT_POSITION_SHIFT;
            out.* = .{
                .type = if ((ce.flags >> COMMENT_TYPE_BIT) & 1 == 0) .line else .block,
                .position = @enumFromInt(pos_bits),
                .same_line = (ce.flags >> ATTACHED_COMMENT_SAME_LINE_BIT) & 1 != 0,
                .value = .{ .start = ce.value_start, .end = ce.value_end },
            };
        }
        tree.attached_comments = attached;
    }
    pos += attached_bytes;

    const comments_bytes: usize = @as(usize, hdr.comment_count) * COMMENT_SIZE;
    if (buf.len < pos + comments_bytes) return error.InvalidBuffer;
    if (hdr.comment_count > 0) {
        const comments = try tree.allocator().alloc(ast.Comment, hdr.comment_count);
        const comments_in: [*]const PackedComment = @ptrCast(@alignCast(buf.ptr + pos));
        for (comments, 0..) |*out, i| {
            const ce = comments_in[i];
            out.* = .{
                .type = if ((ce.flags >> COMMENT_TYPE_BIT) & 1 == 0) .line else .block,
                .value = .{ .start = ce.value_start, .end = ce.value_end },
                .span = .{ .start = ce.span_start, .end = ce.span_end },
            };
        }
        tree.comments = comments;
    }
    pos += comments_bytes;

    pos += @as(usize, hdr.token_count) * TOKEN_SIZE;
    if (buf.len < pos) return error.InvalidBuffer;

    tree.root = @enumFromInt(hdr.program_index);
    std.debug.assert(tree.root != .null);
    return tree;
}

fn unpackNode(p: PackedNode) ast.NodeData {
    @setEvalBranchQuota(100_000);
    inline for (@typeInfo(ast.NodeData).@"union".fields, 0..) |field, tag| {
        if (p.tag == tag) {
            const T = field.type;
            var payload: T = std.mem.zeroes(T);
            unpackPayload(T, p, &payload);
            return @unionInit(ast.NodeData, field.name, payload);
        }
    }
    unreachable;
}

fn unpackPayload(comptime T: type, n: PackedNode, payload: *T) void {
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            @field(payload.*, f.name) = readFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            @field(payload.*, f.name) = @enumFromInt(readSlot(n, slot));
        } else if (f.type == ast.IndexRange) {
            const len: u32 = switch (comptime rangeIndexOf(T, i)) {
                0 => n.field0,
                1 => n.field0b,
                else => readSlot(n, slot + 1),
            };
            const start: u32 = if (len == 0) 0 else readSlot(n, slot);
            @field(payload.*, f.name) = .{ .start = start, .len = len };
        } else if (f.type == ast.String) {
            @field(payload.*, f.name) = .{
                .start = readSlot(n, slot),
                .end = readSlot(n, slot + 1),
            };
        } else if (comptime isEnumType(f.type)) {
            const bits = comptime enumBitWidth(f.type);
            const mask: u16 = (@as(u16, 1) << @intCast(bits)) - 1;
            const v: u16 = (n.flags >> @intCast(bit)) & mask;
            @field(payload.*, f.name) = @enumFromInt(v);
        } else if (f.type == ?ast.ImportPhase) {
            const present = ((n.flags >> @intCast(bit)) & 1) == 1;
            if (present) {
                const bits = comptime enumBitWidth(ast.ImportPhase);
                const mask: u16 = (@as(u16, 1) << @intCast(bits)) - 1;
                const v: u16 = (n.flags >> @intCast(bit + 1)) & mask;
                @field(payload.*, f.name) = @enumFromInt(v);
            } else {
                @field(payload.*, f.name) = null;
            }
        } else if (f.type == ?ast.Hashbang) {
            const present = ((n.flags >> @intCast(bit)) & 1) == 1;
            if (present) {
                @field(payload.*, f.name) = .{
                    .value = .{ .start = readSlot(n, slot), .end = readSlot(n, slot + 1) },
                };
            } else {
                @field(payload.*, f.name) = null;
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++
                "' in " ++ @typeName(T));
        }
    }
}

inline fn readFlagBit(n: PackedNode, comptime bit: u8) bool {
    return ((n.flags >> @intCast(bit)) & 1) == 1;
}

inline fn readSlot(n: PackedNode, comptime slot: u8) u32 {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    const ptr: [*]const u32 = @ptrCast(&n.field1);
    return ptr[slot];
}
