// Yuku AST transfer format v7.
//
// A compact, self-describing binary encoding of a parsed AST. It is the
// single wire format used in both directions across the FFI boundary:
//
//   encode (Zig -> JS)   `serializeInto` writes a tree into a buffer that
//                        the native NAPI binding returns to JS as an
//                        ArrayBuffer. JS decoders walk the buffer to build
//                        AST objects in any shape (ESTree, Babel, and so
//                        on) without copying the underlying bytes.
//   decode (JS -> Zig)   `deserializeFromBuf` reconstructs an `ast.Tree`
//                        from the same buffer. It is the exact inverse of
//                        the encoder for every section except diagnostics,
//                        which it skips (the codegen path that consumes it
//                        does not need them).
//
// All multi-byte integers are little endian. The format carries no version
// byte; producer and consumer are built from this file and must match.
//
// Layout ownership
//   The extern structs below (`Header`, `PackedNode`, `PackedComment`,
//   `PackedAttachedComment`) define the wire layout. Their `@sizeOf` and
//   `@offsetOf` values drive three consumers that therefore cannot drift:
//   the serializer and deserializer in this file, and the JS decoder
//   generated by `tools/estree/decoder.zig`.
//
// Buffer sections, in order. Each is present unconditionally unless a flag
// is noted; absent sections occupy zero bytes.
//
//   header             HEADER_SIZE bytes, fixed. Section counts and flags.
//   nodes              node_count * NODE_SIZE bytes. One PackedNode each.
//   extra              extra_count * 4 bytes. Flat u32 array backing
//                      IndexRange (see below).
//   strings            string_pool_len bytes of raw UTF-8 for pooled
//                      strings (see string pool below), zero-padded to the
//                      next 4-byte boundary. The header records the true
//                      length; consumers advance by alignPool(len) so every
//                      following section is 4-byte aligned.
//   attached_offsets   (node_count + 1) u32s when FLAG_ATTACHED_COMMENTS is
//                      set, absent otherwise. Prefix-sum offsets indexing
//                      attached_comments: node i owns entries
//                      [offsets[i], offsets[i + 1]).
//   attached_comments  attached_comment_count * ATTACHED_COMMENT_SIZE bytes.
//                      Present when FLAG_ATTACHED_COMMENTS is set.
//   comments           comment_count * COMMENT_SIZE bytes, in source order,
//                      each carrying its own span. Present when
//                      FLAG_COMMENTS is set.
//   tokens             Columnar token stream: token_count u32 span starts,
//                      then token_count u32 span ends, then token_count u8
//                      espree token type codes (`TokenType`), zero-padded
//                      to the next 4-byte boundary. Tokens are in source
//                      order and never overlap. Present when FLAG_TOKENS
//                      is set; FLAG_TOKENS may be set with a zero count
//                      (tokens were requested, none exist).
//   diagnostics        Variable length sequence (see diagnostics below).
//                      Written by the encoder; skipped by the decoder.
//
// Node packing
//   Every AST struct is packed into one PackedNode by iterating its fields
//   in declaration order and assigning each to flag bits and/or u32 data
//   slots. The mapping is derived at comptime by the layout helpers, so the
//   encoder, decoder, and JS codegen all agree. Per field type:
//
//   bool              1 flag bit, at the running sum of prior flag widths.
//   enum              ceil(log2(n)) flag bits, where n is the variant count.
//   NodeIndex         1 u32 slot. 0xFFFFFFFF marks null.
//   IndexRange        the first two such fields in a struct keep their
//                     u16 length in field0/field0b and take 1 u32 slot
//                     each for start; any later one takes 2 u32 slots,
//                     start then length.
//   String            2 u32 slots (start, end); see string handles below.
//   ?ImportPhase      1 flag bit for presence plus enum bits for the value.
//   ?Hashbang         1 flag bit for presence plus 2 u32 slots (start, end).
//
//   A PackedNode offers NODE_DATA_SLOTS u32 slots and NODE_FLAG_BITS flag
//   bits; `validateAllNodeLayouts` rejects at comptime any AST struct that
//   exceeds either budget.
//
// extra section
//   A flat u32 array of node indices. An IndexRange { start, len } denotes
//   the slice extra[start, start + len], used for variadic children (a
//   block's statements, a call's arguments, and so on).
//
// string handles
//   A String is a (start, end) pair of byte offsets resolved against one of
//   two backing buffers, distinguished by start:
//     start <  source_len   a slice of the original source buffer.
//     start >= source_len   a slice of the string pool, at offset
//                           (start - source_len).
//   The string pool holds strings that cannot be sliced directly from the
//   source (escaped or otherwise transformed values) and may contain WTF-8
//   encoded lone surrogates. On the wire it is zero-padded to a 4-byte
//   boundary, so every section is 4-byte aligned and both decoders read
//   whole u32 words. Only the variable-length diagnostics section has
//   unaligned interior fields.
//
// diagnostics
//   A sequence of diag_count entries, each variable length:
//
//     1 byte    severity (0 error, 1 warning, 2 hint, 3 info)
//     4 bytes   span_start
//     4 bytes   span_end
//     4 bytes   message_len
//     n bytes   message text (UTF-8)
//     1 byte    has_help flag
//     when has_help is 1:
//       4 bytes   help_len
//       n bytes   help text (UTF-8)
//     4 bytes   label_count
//     per label:
//       4 bytes   span_start
//       4 bytes   span_end
//       4 bytes   message_len
//       n bytes   message text (UTF-8)

const std = @import("std");
const ast = @import("parser").ast;

/// The analyzer's semantic sections, layered on this format. Exposed
/// here so the decoder generators reach both layouts through one module.
pub const semantic = @import("semantic.zig");

/// fixed size header prefixing the buffer. field order defines the wire
/// layout. the serializer writes this struct with `@memcpy` and the
/// decoder reads each field by the u32 index derived from `@offsetOf`.
const Header = extern struct {
    node_count: u32,
    extra_count: u32,
    string_pool_len: u32,
    source_len: u32,
    /// entries in the flat comments section.
    comment_count: u32,
    /// entries in the attached comments section.
    attached_comment_count: u32,
    /// entries in the tokens section.
    token_count: u32,
    diag_count: u32,
    program_index: u32,
    flags: u32,
    /// byte offset of the first non-ASCII byte in `source`, or
    /// `source_len` if the source is entirely ASCII. the decoder uses
    /// this as the boundary above which UTF-8 byte offsets need a
    /// `buildPosMap` walk. positions below it are an identity map.
    first_non_ascii: u32,
};

/// packed ast node entry. `tag` identifies the `ast.NodeData` variant,
/// `flags` holds packed booleans and small enums, and `field1..field7`
/// are u32 data slots assigned to struct fields by the packing rules.
///
/// the first IndexRange in a struct stores its u16 length in `field0`,
/// the second in `field0b`; each takes just one u32 slot for its start.
/// any further IndexRange uses two consecutive u32 slots, start then
/// length (no current node needs a third). the comptime validator
/// enforces the 7 slot and 16 flag bit budget regardless.
const PackedNode = extern struct {
    tag: u8,
    _pad0: u8 = 0,
    flags: u16,
    field0: u16,
    field0b: u16,
    field1: u32,
    field2: u32,
    field3: u32,
    field4: u32,
    field5: u32,
    field6: u32,
    field7: u32,
    span_start: u32,
    span_end: u32,
};

/// Comment entry on the wire, in source order. `flags` bit 0 is the type
/// (0 line, 1 block). `value_start`/`value_end` is a `String` handle into
/// source or pool, `span_start`/`span_end` is the full comment span.
const PackedComment = extern struct {
    flags: u8,
    _pad: [3]u8 = .{ 0, 0, 0 },
    value_start: u32,
    value_end: u32,
    span_start: u32,
    span_end: u32,
};

pub const COMMENT_TYPE_BIT: u8 = 0;

/// Attached comment entry on the wire. `flags` packs:
///   bit 0     type       (0 line, 1 block)
///   bits 1-2  position   (0 before, 1 after, 2 inside)
///   bit 3     same_line
/// `value_start`/`value_end` is a `String` handle into source or pool.
/// The host node is implicit from the entry's index and the offsets.
const PackedAttachedComment = extern struct {
    flags: u8,
    _pad: [3]u8 = .{ 0, 0, 0 },
    value_start: u32,
    value_end: u32,
};

pub const ATTACHED_COMMENT_POSITION_SHIFT: u8 = 1;
pub const ATTACHED_COMMENT_POSITION_MASK: u8 = 0b11 << ATTACHED_COMMENT_POSITION_SHIFT;
pub const ATTACHED_COMMENT_SAME_LINE_BIT: u8 = 3;

// section sizes.
pub const HEADER_SIZE: u32 = @sizeOf(Header);
pub const NODE_SIZE: u32 = @sizeOf(PackedNode);
pub const COMMENT_SIZE: u32 = @sizeOf(PackedComment);
pub const ATTACHED_COMMENT_SIZE: u32 = @sizeOf(PackedAttachedComment);

// `Header` field u32 indices for the decoder.
pub const HDR_NODE_COUNT_U32: u32 = @offsetOf(Header, "node_count") / 4;
pub const HDR_EXTRA_COUNT_U32: u32 = @offsetOf(Header, "extra_count") / 4;
pub const HDR_STRING_POOL_LEN_U32: u32 = @offsetOf(Header, "string_pool_len") / 4;
pub const HDR_SOURCE_LEN_U32: u32 = @offsetOf(Header, "source_len") / 4;
pub const HDR_COMMENT_COUNT_U32: u32 = @offsetOf(Header, "comment_count") / 4;
pub const HDR_ATTACHED_COMMENT_COUNT_U32: u32 = @offsetOf(Header, "attached_comment_count") / 4;
pub const HDR_TOKEN_COUNT_U32: u32 = @offsetOf(Header, "token_count") / 4;
pub const HDR_DIAG_COUNT_U32: u32 = @offsetOf(Header, "diag_count") / 4;
pub const HDR_PROGRAM_INDEX_U32: u32 = @offsetOf(Header, "program_index") / 4;
pub const HDR_FLAGS_U32: u32 = @offsetOf(Header, "flags") / 4;
pub const HDR_FIRST_NON_ASCII_U32: u32 = @offsetOf(Header, "first_non_ascii") / 4;

// `Header.flags` bit positions.
pub const FLAG_TS: u32 = 1 << 0;
pub const FLAG_ATTACHED_COMMENTS: u32 = 1 << 1;
pub const FLAG_COMMENTS: u32 = 1 << 2;
/// Semantic sections (scopes, symbols, references, module records)
/// follow the diagnostics section. Written by `semantic.zig`,
/// consumed only by the analyzer decoder. Other decoders never read
/// past diagnostics, so the bit is invisible to them.
pub const FLAG_SEMANTIC: u32 = 1 << 3;
/// Token collection was enabled, so the tokens section is present
/// (possibly with a zero count).
pub const FLAG_TOKENS: u32 = 1 << 4;

// `PackedNode` byte offsets and u32 indices.
pub const NODE_FLAGS_OFFSET: u8 = @offsetOf(PackedNode, "flags");
pub const NODE_FIELD0_OFFSET: u8 = @offsetOf(PackedNode, "field0");
pub const NODE_FIELD0B_OFFSET: u8 = @offsetOf(PackedNode, "field0b");
pub const NODE_HEADER_U32S: u8 = @offsetOf(PackedNode, "field1") / 4;
pub const NODE_SPAN_START_U32: u8 = @offsetOf(PackedNode, "span_start") / 4;
pub const NODE_SPAN_END_U32: u8 = @offsetOf(PackedNode, "span_end") / 4;

// `PackedNode` capacity. counts the u32 data slots and flag bits available
// per node. used by `validateAllNodeLayouts` to reject ast structs that do
// not fit. both values track the struct layout automatically.
pub const NODE_DATA_SLOTS: u8 = NODE_SPAN_START_U32 - NODE_HEADER_U32S;
pub const NODE_FLAG_BITS: u8 = @bitSizeOf(@FieldType(PackedNode, "flags"));

// `PackedComment` byte offsets for the decoder.
pub const COMMENT_FLAGS_OFFSET: u8 = @offsetOf(PackedComment, "flags");
pub const COMMENT_VALUE_START_OFFSET: u8 = @offsetOf(PackedComment, "value_start");
pub const COMMENT_VALUE_END_OFFSET: u8 = @offsetOf(PackedComment, "value_end");
pub const COMMENT_SPAN_START_OFFSET: u8 = @offsetOf(PackedComment, "span_start");
pub const COMMENT_SPAN_END_OFFSET: u8 = @offsetOf(PackedComment, "span_end");

// `PackedAttachedComment` byte offsets for the decoder.
pub const ATTACHED_COMMENT_FLAGS_OFFSET: u8 = @offsetOf(PackedAttachedComment, "flags");
pub const ATTACHED_COMMENT_VALUE_START_OFFSET: u8 = @offsetOf(PackedAttachedComment, "value_start");
pub const ATTACHED_COMMENT_VALUE_END_OFFSET: u8 = @offsetOf(PackedAttachedComment, "value_end");

comptime {
    validateAllNodeLayouts();
}

// layout helpers used by the serializer below and by the decoder
// generator at tools/estree/decoder.zig.

/// number of flag bits consumed by field `field_idx` in struct T.
pub fn flagBitCount(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == bool) return 1;
    if (f.type == ?ast.ImportPhase) return 1 + enumBitWidth(ast.ImportPhase);
    if (f.type == ?ast.Hashbang) return 1;
    if (comptime isEnumType(f.type)) return enumBitWidth(f.type);
    if (f.type == ast.NodeIndex or f.type == ast.IndexRange or f.type == ast.String) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// starting flag bit position for field `target` in struct T.
pub fn flagBitForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var bit: u8 = 0;
        for (0..target) |i| bit += flagBitCount(T, i);
        return bit;
    }
}

/// number of u32 slots consumed by field `field_idx` in struct T.
/// the first two IndexRanges keep their length in the packed u16
/// length fields (`field0`, `field0b`), so they take one slot each.
pub fn fieldU32Count(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == ast.NodeIndex) return 1;
    if (f.type == ast.IndexRange) return if (rangeIndexOf(T, field_idx) < 2) 1 else 2;
    if (f.type == ast.String) return 2;
    if (f.type == ?ast.Hashbang) return 2;
    if (f.type == bool or f.type == ?ast.ImportPhase or comptime isEnumType(f.type)) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// first u32 slot index for field `target` in struct T.
pub fn u32SlotForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var slot: u8 = 0;
        for (0..target) |i| slot += fieldU32Count(T, i);
        return slot;
    }
}

/// 0-based position of field `target` among struct T's IndexRange
/// fields. `target` must be an IndexRange field.
pub fn rangeIndexOf(comptime T: type, comptime target: usize) u8 {
    comptime {
        std.debug.assert(std.meta.fields(T)[target].type == ast.IndexRange);
        var idx: u8 = 0;
        for (std.meta.fields(T)[0..target]) |f| {
            if (f.type == ast.IndexRange) idx += 1;
        }
        return idx;
    }
}

/// ceil(log2(n)) where n is the number of enum variants.
pub fn enumBitWidth(comptime E: type) u8 {
    return std.math.log2_int_ceil(usize, @typeInfo(E).@"enum".fields.len);
}

pub fn isEnumType(comptime T: type) bool {
    return @typeInfo(T) == .@"enum";
}

/// total u32 slots used by struct T.
pub fn totalU32Slots(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += fieldU32Count(T, i);
        return total;
    }
}

/// total flag bits used by struct T.
pub fn totalFlagBits(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += flagBitCount(T, i);
        return total;
    }
}

fn validateAllNodeLayouts() void {
    @setEvalBranchQuota(10_000);
    for (@typeInfo(ast.NodeData).@"union".fields) |field| {
        const T = field.type;
        if (@typeInfo(T) != .@"struct") continue;
        if (totalU32Slots(T) > NODE_DATA_SLOTS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} u32 slots",
            .{ field.name, NODE_DATA_SLOTS },
        ));
        if (totalFlagBits(T) > NODE_FLAG_BITS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} flag bits",
            .{ field.name, NODE_FLAG_BITS },
        ));
    }
}

// serialization

/// string pool length rounded up to the 4-byte boundary it occupies on
/// the wire. keeps every section after the pool u32-aligned.
pub inline fn alignPool(len: usize) usize {
    return (len + 3) & ~@as(usize, 3);
}

/// wire size of the tokens section: two u32 columns plus the u8 type
/// column zero-padded to the next 4-byte boundary.
pub inline fn tokenSectionSize(count: usize) usize {
    return count * 8 + alignPool(count);
}

pub fn bufferSize(tree: *const ast.Tree) usize {
    std.debug.assert(tree.nodes.len <= std.math.maxInt(u32));
    std.debug.assert(tree.extras.items.len <= std.math.maxInt(u32));
    std.debug.assert(tree.source.len <= std.math.maxInt(u32));
    // fixed part of a diagnostic. severity, span_start, span_end,
    // message_len, has_help, label_count.
    const diag_fixed = 1 + 4 + 4 + 4 + 1 + 4;
    const help_prefix = 4; // help_len
    const label_fixed = 4 + 4 + 4; // start, end, message_len

    std.debug.assert(tree.tokens.len <= std.math.maxInt(u32));
    var size: usize = HEADER_SIZE +
        tree.nodes.len * NODE_SIZE +
        tree.extras.items.len * 4 +
        alignPool(tree.strings.extra.items.len) +
        tree.attached_comment_offsets.len * 4 +
        tree.attached_comments.len * ATTACHED_COMMENT_SIZE +
        tree.comments.len * COMMENT_SIZE +
        tokenSectionSize(tree.tokens.len);

    for (tree.diagnostics.items) |d| {
        size += diag_fixed + d.message.len;
        if (d.help) |h| size += help_prefix + h.len;
        for (d.labels) |lbl| size += label_fixed + lbl.message.len;
    }
    return size;
}

pub fn serializeInto(tree: *const ast.Tree, buf: []u8) usize {
    std.debug.assert(buf.len >= bufferSize(tree));
    std.debug.assert(tree.root != .null);
    // every section is written through 4-byte-aligned pointers
    std.debug.assert(@intFromPtr(buf.ptr) % 4 == 0);

    const string_pool_len: u32 = @intCast(tree.strings.extra.items.len);
    const has_attached = tree.attached_comment_offsets.len != 0;
    const has_comments = tree.comments.len != 0;
    // attached offsets table is sized `node_count + 1` when present
    std.debug.assert(!has_attached or tree.attached_comment_offsets.len == tree.nodes.len + 1);

    // tokens exist only when collection was on
    if (!tree.collected_tokens) std.debug.assert(tree.tokens.len == 0);

    // header
    var hdr_flags: u32 = 0;
    if (tree.isTs()) hdr_flags |= FLAG_TS;
    if (has_attached) hdr_flags |= FLAG_ATTACHED_COMMENTS;
    if (has_comments) hdr_flags |= FLAG_COMMENTS;
    if (tree.collected_tokens) hdr_flags |= FLAG_TOKENS;

    const hdr = Header{
        .node_count = @intCast(tree.nodes.len),
        .extra_count = @intCast(tree.extras.items.len),
        .string_pool_len = string_pool_len,
        .source_len = @intCast(tree.source.len),
        .comment_count = @intCast(tree.comments.len),
        .attached_comment_count = @intCast(tree.attached_comments.len),
        .token_count = @intCast(tree.tokens.len),
        .diag_count = @intCast(tree.diagnostics.items.len),
        .program_index = @intFromEnum(tree.root),
        .flags = hdr_flags,
        .first_non_ascii = @intCast(firstNonAsciiOffset(tree.source)),
    };
    @memcpy(buf[0..HEADER_SIZE], std.mem.asBytes(&hdr));
    var pos: usize = HEADER_SIZE;

    // nodes, packed straight into the destination buffer
    const nodes_out: [*]PackedNode = @ptrCast(@alignCast(buf.ptr + pos));
    const data_items = tree.nodes.items(.data);
    const span_items = tree.nodes.items(.span);
    for (data_items, span_items, 0..) |*data, span, i| {
        nodes_out[i] = packNode(data, span);
    }
    pos += @as(usize, hdr.node_count) * NODE_SIZE;

    // extra
    const extra_bytes = std.mem.sliceAsBytes(tree.extras.items);
    @memcpy(buf[pos..][0..extra_bytes.len], extra_bytes);
    pos += extra_bytes.len;

    // string pool, zero-padded to the next 4-byte boundary
    @memcpy(buf[pos..][0..string_pool_len], tree.strings.extra.items);
    const pool_pad = alignPool(string_pool_len) - string_pool_len;
    @memset(buf[pos + string_pool_len ..][0..pool_pad], 0);
    pos += string_pool_len + pool_pad;

    // attached comment offsets (present only when FLAG_ATTACHED_COMMENTS is set)
    const offsets_bytes = std.mem.sliceAsBytes(tree.attached_comment_offsets);
    @memcpy(buf[pos..][0..offsets_bytes.len], offsets_bytes);
    pos += offsets_bytes.len;

    // attached comments
    const attached_out: [*]PackedAttachedComment = @ptrCast(@alignCast(buf.ptr + pos));
    for (tree.attached_comments, 0..) |c, i| {
        var flags: u8 = 0;
        if (c.type == .block) flags |= 1 << COMMENT_TYPE_BIT;
        flags |= @as(u8, @intFromEnum(c.position)) << ATTACHED_COMMENT_POSITION_SHIFT;
        if (c.same_line) flags |= 1 << ATTACHED_COMMENT_SAME_LINE_BIT;
        attached_out[i] = .{
            .flags = flags,
            .value_start = c.value.start,
            .value_end = c.value.end,
        };
    }
    pos += tree.attached_comments.len * ATTACHED_COMMENT_SIZE;

    // comments
    const comments_out: [*]PackedComment = @ptrCast(@alignCast(buf.ptr + pos));
    for (tree.comments, 0..) |c, i| {
        comments_out[i] = .{
            .flags = if (c.type == .block) 1 << COMMENT_TYPE_BIT else 0,
            .value_start = c.value.start,
            .value_end = c.value.end,
            .span_start = c.span.start,
            .span_end = c.span.end,
        };
    }
    pos += tree.comments.len * COMMENT_SIZE;

    // tokens, columnar: span starts, span ends, then type codes padded
    // to the next 4-byte boundary
    if (tree.tokens.len > 0) {
        const starts_bytes = std.mem.sliceAsBytes(tree.tokens.items(.start));
        @memcpy(buf[pos..][0..starts_bytes.len], starts_bytes);
        pos += starts_bytes.len;

        const ends_bytes = std.mem.sliceAsBytes(tree.tokens.items(.end));
        @memcpy(buf[pos..][0..ends_bytes.len], ends_bytes);
        pos += ends_bytes.len;

        // `TokenType` is a u8 enum, so the column is raw bytes on the wire
        const types_bytes = std.mem.sliceAsBytes(tree.tokens.items(.type));
        std.debug.assert(types_bytes.len == tree.tokens.len);
        @memcpy(buf[pos..][0..types_bytes.len], types_bytes);
        const types_pad = alignPool(types_bytes.len) - types_bytes.len;
        @memset(buf[pos + types_bytes.len ..][0..types_pad], 0);
        pos += types_bytes.len + types_pad;
    }

    // diagnostics (variable length)
    for (tree.diagnostics.items) |d| {
        buf[pos] = @intFromEnum(d.severity);
        pos += 1;
        w32(buf, pos, d.span.start);
        pos += 4;
        w32(buf, pos, d.span.end);
        pos += 4;
        w32(buf, pos, @intCast(d.message.len));
        pos += 4;
        @memcpy(buf[pos..][0..d.message.len], d.message);
        pos += d.message.len;
        if (d.help) |h| {
            buf[pos] = 1;
            pos += 1;
            w32(buf, pos, @intCast(h.len));
            pos += 4;
            @memcpy(buf[pos..][0..h.len], h);
            pos += h.len;
        } else {
            buf[pos] = 0;
            pos += 1;
        }
        w32(buf, pos, @intCast(d.labels.len));
        pos += 4;
        for (d.labels) |lbl| {
            w32(buf, pos, lbl.span.start);
            pos += 4;
            w32(buf, pos, lbl.span.end);
            pos += 4;
            w32(buf, pos, @intCast(lbl.message.len));
            pos += 4;
            @memcpy(buf[pos..][0..lbl.message.len], lbl.message);
            pos += lbl.message.len;
        }
    }

    // serializer must have written exactly the size reported by `bufferSize`
    std.debug.assert(pos == bufferSize(tree));
    return pos;
}

fn packNode(data: *const ast.NodeData, span: ast.Span) PackedNode {
    std.debug.assert(span.start <= span.end);
    var n: PackedNode = std.mem.zeroes(PackedNode);
    n.span_start = span.start;
    n.span_end = span.end;
    // by pointer to avoid copying the 44-byte `ast.NodeData` union per node.
    switch (data.*) {
        inline else => |*payload, tag| {
            n.tag = @intFromEnum(tag);
            packPayload(&n, payload);
        },
    }
    return n;
}

fn packPayload(n: *PackedNode, payload: anytype) void {
    const T = @typeInfo(@TypeOf(payload)).pointer.child;
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const val = @field(payload, f.name);
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            if (val) setFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            setSlot(n, slot, @intFromEnum(val));
        } else if (f.type == ast.IndexRange) {
            switch (comptime rangeIndexOf(T, i)) {
                0 => n.field0 = @intCast(val.len),
                1 => n.field0b = @intCast(val.len),
                else => setSlot(n, slot + 1, @intCast(val.len)),
            }
            setSlot(n, slot, val.start);
        } else if (f.type == ast.String) {
            setSlot(n, slot, val.start);
            setSlot(n, slot + 1, val.end);
        } else if (comptime isEnumType(f.type)) {
            setFlagBits(n, bit, @intFromEnum(val));
        } else if (f.type == ?ast.ImportPhase) {
            if (val) |v| {
                setFlagBit(n, bit);
                setFlagBits(n, bit + 1, @intFromEnum(v));
            }
        } else if (f.type == ?ast.Hashbang) {
            if (val) |h| {
                setFlagBit(n, bit);
                setSlot(n, slot, h.value.start);
                setSlot(n, slot + 1, h.value.end);
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++
                "' in " ++ @typeName(T));
        }
    }
}

inline fn setFlagBit(n: *PackedNode, comptime bit: u8) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), 1) << @intCast(bit);
}

inline fn setFlagBits(n: *PackedNode, comptime bit: u8, val: anytype) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), @intCast(val)) << @intCast(bit);
}

inline fn setSlot(n: *PackedNode, comptime slot: u8, val: u32) void {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    @as([*]u32, @ptrCast(&n.field1))[slot] = val;
}

inline fn w32(buf: []u8, pos: usize, val: u32) void {
    std.mem.writeInt(u32, buf[pos..][0..4], val, .little);
}

/// returns the byte offset of the first non-ASCII byte in `source`, or
/// `source.len` if the source is entirely ASCII.
fn firstNonAsciiOffset(source: []const u8) usize {
    const Vec = @Vector(16, u8);
    const hi: Vec = @splat(0x80);
    var i: usize = 0;
    while (i + 16 <= source.len) : (i += 16) {
        if (@reduce(.Or, source[i..][0..16].* & hi) != 0) {
            // non-ASCII somewhere in this 16-byte block. find it.
            for (source[i..][0..16], 0..) |c, k| if (c >= 0x80) return i + k;
            unreachable;
        }
    }
    for (source[i..], 0..) |c, k| if (c >= 0x80) return i + k;
    return source.len;
}

// deserialization. reverses `serializeInto`, comptime-driven by the same
// layout helpers. ignores the diagnostics section, which the codegen path
// doesn't need. the caller passes in the source string, which may be
// empty when every `String` resolves through the pool.

pub const DeserializeError = error{ InvalidBuffer, OutOfMemory };

pub fn deserializeFromBuf(
    allocator: std.mem.Allocator,
    buf: []const u8,
    source: []const u8,
) DeserializeError!ast.Tree {
    if (buf.len < HEADER_SIZE) return error.InvalidBuffer;
    // sections are read through 4-byte-aligned pointers
    std.debug.assert(@intFromPtr(buf.ptr) % 4 == 0);

    var hdr: Header = undefined;
    @memcpy(std.mem.asBytes(&hdr), buf[0..HEADER_SIZE]);

    // header sanity: the program index must point inside the node array.
    // source may be empty (then every `String` resolves via the pool) or
    // match `hdr.source_len` for direct slicing.
    std.debug.assert(source.len == 0 or source.len == hdr.source_len);
    std.debug.assert(hdr.program_index < hdr.node_count);

    var tree = ast.Tree.init(allocator, source);
    errdefer tree.deinit();

    if (hdr.flags & FLAG_TS != 0) tree.lang = .ts;

    var pos: usize = HEADER_SIZE;

    // nodes
    const nodes_bytes: usize = @as(usize, hdr.node_count) * NODE_SIZE;
    if (buf.len < pos + nodes_bytes) return error.InvalidBuffer;
    try tree.nodes.resize(tree.allocator(), hdr.node_count);
    const nodes_in: [*]const PackedNode = @ptrCast(@alignCast(buf.ptr + pos));
    for (0..hdr.node_count) |i| {
        const pn = nodes_in[i];
        tree.nodes.set(i, .{
            .data = unpackNode(pn),
            .span = .{ .start = pn.span_start, .end = pn.span_end },
        });
    }
    pos += nodes_bytes;

    // extras
    const extras_bytes: usize = @as(usize, hdr.extra_count) * 4;
    if (buf.len < pos + extras_bytes) return error.InvalidBuffer;
    try tree.extras.resize(tree.allocator(), hdr.extra_count);
    @memcpy(std.mem.sliceAsBytes(tree.extras.items), buf[pos..][0..extras_bytes]);
    pos += extras_bytes;

    // string pool (padded to 4 bytes on the wire, true length in the header)
    if (buf.len < pos + alignPool(hdr.string_pool_len)) return error.InvalidBuffer;
    try tree.strings.extra.resize(tree.allocator(), hdr.string_pool_len);
    @memcpy(tree.strings.extra.items, buf[pos..][0..hdr.string_pool_len]);
    pos += alignPool(hdr.string_pool_len);

    // attached comment offsets (present only when FLAG_ATTACHED_COMMENTS is set)
    const has_attached = (hdr.flags & FLAG_ATTACHED_COMMENTS) != 0;
    if (has_attached) {
        const offsets_count: usize = @as(usize, hdr.node_count) + 1;
        const offsets_bytes = offsets_count * 4;
        if (buf.len < pos + offsets_bytes) return error.InvalidBuffer;
        const offsets = try tree.allocator().alloc(u32, offsets_count);
        @memcpy(std.mem.sliceAsBytes(offsets), buf[pos..][0..offsets_bytes]);
        tree.attached_comment_offsets = offsets;
        pos += offsets_bytes;
    }

    // attached comments
    const attached_bytes: usize = @as(usize, hdr.attached_comment_count) * ATTACHED_COMMENT_SIZE;
    if (buf.len < pos + attached_bytes) return error.InvalidBuffer;
    if (hdr.attached_comment_count > 0) {
        const attached = try tree.allocator().alloc(ast.AttachedComment, hdr.attached_comment_count);
        const attached_in: [*]const PackedAttachedComment = @ptrCast(@alignCast(buf.ptr + pos));
        for (attached, 0..) |*out, i| {
            const ce = attached_in[i];
            const pos_bits = (ce.flags & ATTACHED_COMMENT_POSITION_MASK) >> ATTACHED_COMMENT_POSITION_SHIFT;
            out.* = .{
                .type = if ((ce.flags >> COMMENT_TYPE_BIT) & 1 == 0) .line else .block,
                .position = @enumFromInt(pos_bits),
                .same_line = (ce.flags >> ATTACHED_COMMENT_SAME_LINE_BIT) & 1 != 0,
                .value = .{ .start = ce.value_start, .end = ce.value_end },
            };
        }
        tree.attached_comments = attached;
    }
    pos += attached_bytes;

    // comments
    const comments_bytes: usize = @as(usize, hdr.comment_count) * COMMENT_SIZE;
    if (buf.len < pos + comments_bytes) return error.InvalidBuffer;
    if (hdr.comment_count > 0) {
        const comments = try tree.allocator().alloc(ast.Comment, hdr.comment_count);
        const comments_in: [*]const PackedComment = @ptrCast(@alignCast(buf.ptr + pos));
        for (comments, 0..) |*out, i| {
            const ce = comments_in[i];
            out.* = .{
                .type = if ((ce.flags >> COMMENT_TYPE_BIT) & 1 == 0) .line else .block,
                .value = .{ .start = ce.value_start, .end = ce.value_end },
                .span = .{ .start = ce.span_start, .end = ce.span_end },
            };
        }
        tree.comments = comments;
    }
    pos += comments_bytes;

    // tokens
    const has_tokens = (hdr.flags & FLAG_TOKENS) != 0;
    if (!has_tokens) std.debug.assert(hdr.token_count == 0);
    tree.collected_tokens = has_tokens;
    const tokens_bytes = tokenSectionSize(hdr.token_count);
    if (buf.len < pos + tokens_bytes) return error.InvalidBuffer;
    if (hdr.token_count > 0) {
        try tree.tokens.resize(tree.allocator(), hdr.token_count);
        const column = @as(usize, hdr.token_count) * 4;
        @memcpy(std.mem.sliceAsBytes(tree.tokens.items(.start)), buf[pos..][0..column]);
        @memcpy(std.mem.sliceAsBytes(tree.tokens.items(.end)), buf[pos + column ..][0..column]);
        const types_bytes = std.mem.sliceAsBytes(tree.tokens.items(.type));
        @memcpy(types_bytes, buf[pos + 2 * column ..][0..hdr.token_count]);
    }
    pos += tokens_bytes;

    // skip diagnostics. codegen doesn't read them.

    tree.root = @enumFromInt(hdr.program_index);
    std.debug.assert(tree.root != .null);
    return tree;
}

fn unpackNode(p: PackedNode) ast.NodeData {
    @setEvalBranchQuota(100_000);
    inline for (@typeInfo(ast.NodeData).@"union".fields, 0..) |field, tag| {
        if (p.tag == tag) {
            const T = field.type;
            var payload: T = std.mem.zeroes(T);
            unpackPayload(T, p, &payload);
            return @unionInit(ast.NodeData, field.name, payload);
        }
    }
    unreachable;
}

fn unpackPayload(comptime T: type, n: PackedNode, payload: *T) void {
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            @field(payload.*, f.name) = readFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            @field(payload.*, f.name) = @enumFromInt(readSlot(n, slot));
        } else if (f.type == ast.IndexRange) {
            const len: u32 = switch (comptime rangeIndexOf(T, i)) {
                0 => n.field0,
                1 => n.field0b,
                else => readSlot(n, slot + 1),
            };
            const start: u32 = if (len == 0) 0 else readSlot(n, slot);
            @field(payload.*, f.name) = .{ .start = start, .len = len };
        } else if (f.type == ast.String) {
            @field(payload.*, f.name) = .{
                .start = readSlot(n, slot),
                .end = readSlot(n, slot + 1),
            };
        } else if (comptime isEnumType(f.type)) {
            const bits = comptime enumBitWidth(f.type);
            const mask: u16 = (@as(u16, 1) << @intCast(bits)) - 1;
            const v: u16 = (n.flags >> @intCast(bit)) & mask;
            @field(payload.*, f.name) = @enumFromInt(v);
        } else if (f.type == ?ast.ImportPhase) {
            const present = ((n.flags >> @intCast(bit)) & 1) == 1;
            if (present) {
                const bits = comptime enumBitWidth(ast.ImportPhase);
                const mask: u16 = (@as(u16, 1) << @intCast(bits)) - 1;
                const v: u16 = (n.flags >> @intCast(bit + 1)) & mask;
                @field(payload.*, f.name) = @enumFromInt(v);
            } else {
                @field(payload.*, f.name) = null;
            }
        } else if (f.type == ?ast.Hashbang) {
            const present = ((n.flags >> @intCast(bit)) & 1) == 1;
            if (present) {
                @field(payload.*, f.name) = .{
                    .value = .{ .start = readSlot(n, slot), .end = readSlot(n, slot + 1) },
                };
            } else {
                @field(payload.*, f.name) = null;
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++
                "' in " ++ @typeName(T));
        }
    }
}

inline fn readFlagBit(n: PackedNode, comptime bit: u8) bool {
    return ((n.flags >> @intCast(bit)) & 1) == 1;
}

inline fn readSlot(n: PackedNode, comptime slot: u8) u32 {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    const ptr: [*]const u32 = @ptrCast(&n.field1);
    return ptr[slot];
}
