// Yuku AST Transfer Format v1
//
// a compact binary encoding of the parsed AST. all integers are little endian.
// decoders for any AST shape (ESTree, Babel, etc) can be generated from this format.
// the JS ESTree decoder is generated by tools/gen_estree_decoder.zig.
//
//
// 1. buffer layout
//
//   offset  section
//   0       header      (40 bytes, fixed)
//   40      nodes       (node_count * 32 bytes)
//   ...     extra       (extra_count * 4 bytes)
//   ...     strings     (string_pool_len bytes, raw utf8)
//   ...     comments    (comment_count * 20 bytes)
//   ...     diagnostics (variable length)
//
//
// 2. header (40 bytes)
//
//   offset  size  field
//   0       4     magic               "YUKU" (0x59 0x55 0x4B 0x55)
//   4       4     version             format version (currently 1)
//   8       4     node_count          number of AST nodes
//   12      4     extra_count         number of u32 entries in the extra array
//   16      4     string_pool_len     byte length of the string pool
//   20      4     source_len          byte length of the original source (utf8)
//   24      4     comment_count       number of comments
//   28      4     diagnostic_count    number of diagnostics
//   32      4     program_index       node index of the root Program node
//   36      4     flags               bit 0: source is all ascii
//
//
// 3. nodes (32 bytes each)
//
//   offset  size  field
//   0       1     tag         node type (index into the NodeData union)
//   1       1     flags       packed booleans and small enums
//   2       2     field0      u16 value (first IndexRange length)
//   4       4     field1      u32 slot 0
//   8       4     field2      u32 slot 1
//   12      4     field3      u32 slot 2
//   16      4     field4      u32 slot 3
//   20      4     field5      u32 slot 4
//   24      4     span_start  byte offset in source
//   28      4     span_end    byte offset in source
//
//   fields are assigned to slots by iterating the AST struct's fields
//   in declaration order. for each field:
//
//     bool              1 bit in flags (bit position = sum of prior flag widths)
//     enum              ceil(log2(N)) bits in flags
//     NodeIndex         1 u32 slot (0xFFFFFFFF = null)
//     IndexRange        first:  len in field0 (u16), start in 1 u32 slot
//                       later:  start then len in 2 consecutive u32 slots
//     String            2 u32 slots (start, end). if start < source_len,
//                       references source text; otherwise references the
//                       string pool at offset (start - source_len)
//     ?OptionalEnum     1 flag bit (presence) + enum bits (value)
//     ?OptionalStruct   1 flag bit (presence) + u32 slots for inner fields
//
//
// 4. extra (u32 array)
//
//   flat array of node indices used by IndexRange fields.
//   an IndexRange { start, len } refers to extra[start .. start+len].
//
//
// 5. string pool (raw bytes)
//
//   flat utf8 byte buffer for strings not directly sliceable from source.
//   a String { start, end } with start >= source_len references
//   pool bytes at offset (start - source_len) .. (end - source_len).
//   may contain WTF8 encoded lone surrogates.
//
//
// 6. comments (20 bytes each)
//
//   offset  size  field
//   0       1     type          0 = line, 1 = block
//   1       3     (padding)
//   4       4     start         byte offset in source
//   8       4     end           byte offset in source
//   12      4     value_start   String start (comment content without delimiters)
//   16      4     value_end     String end
//
//
// 7. diagnostics (variable length, sequential)
//
//   each diagnostic:
//     1 byte    severity        0 = error, 1 = warning, 2 = hint, 3 = info
//     4 bytes   span_start      byte offset in source
//     4 bytes   span_end        byte offset in source
//     4 bytes   message_len
//     N bytes   message         utf8 text
//     1 byte    has_help        0 or 1
//     if has_help:
//       4 bytes   help_len
//       N bytes   help          utf8 text
//     4 bytes   label_count
//     for each label:
//       4 bytes   start         byte offset in source
//       4 bytes   end           byte offset in source
//       4 bytes   message_len
//       N bytes   message       utf8 text

const std = @import("std");
const ast = @import("parser").ast;

pub const VERSION: u32 = 1;
pub const HEADER_SIZE: u32 = 40;
pub const NODE_SIZE: u32 = 32;
pub const COMMENT_SIZE: u32 = 20;

const PackedNode = extern struct {
    tag: u8,
    flags: u8,
    field0: u16,
    field1: u32,
    field2: u32,
    field3: u32,
    field4: u32,
    field5: u32,
    span_start: u32,
    span_end: u32,
};

comptime {
    std.debug.assert(@sizeOf(PackedNode) == NODE_SIZE);
    validateAllNodeLayouts();
}

// comptime layout functions
// used by both the serializer (below) and the decoder generator (tools/gen_estree_decoder.zig).

/// number of flag bits consumed by field `field_idx` in struct T.
pub fn flagBitCount(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == bool) return 1;
    if (f.type == ?ast.ImportPhase) return 1 + enumBitWidth(ast.ImportPhase);
    if (f.type == ?ast.Hashbang) return 1;
    if (comptime isEnumType(f.type)) return enumBitWidth(f.type);
    if (f.type == ast.NodeIndex or f.type == ast.IndexRange or f.type == ast.String) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// starting flag bit position for field `target` in struct T.
pub fn flagBitForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var bit: u8 = 0;
        for (0..target) |i| bit += flagBitCount(T, i);
        return bit;
    }
}

/// number of u32 slots consumed by field `field_idx` in struct T.
pub fn fieldU32Count(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == ast.NodeIndex) return 1;
    if (f.type == ast.IndexRange) return if (isFirstRange(T, field_idx)) 1 else 2;
    if (f.type == ast.String) return 2;
    if (f.type == ?ast.Hashbang) return 2;
    if (f.type == bool or f.type == ?ast.ImportPhase or comptime isEnumType(f.type)) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// first u32 slot index for field `target` in struct T.
pub fn u32SlotForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var slot: u8 = 0;
        for (0..target) |i| slot += fieldU32Count(T, i);
        return slot;
    }
}

/// true if field `target` is the first IndexRange in struct T.
pub fn isFirstRange(comptime T: type, comptime target: usize) bool {
    comptime {
        for (std.meta.fields(T), 0..) |f, i| {
            if (f.type == ast.IndexRange) return i == target;
        }
        return false;
    }
}

/// ceil(log2(N)) where N is the number of enum variants.
pub fn enumBitWidth(comptime E: type) u8 {
    const n = @typeInfo(E).@"enum".fields.len;
    comptime {
        var bits: u8 = 0;
        var max: usize = 1;
        while (max < n) {
            bits += 1;
            max *= 2;
        }
        return bits;
    }
}

pub fn isEnumType(comptime T: type) bool {
    return @typeInfo(T) == .@"enum";
}

/// total u32 slots used by struct T.
pub fn totalU32Slots(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += fieldU32Count(T, i);
        return total;
    }
}

/// total flag bits used by struct T.
pub fn totalFlagBits(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += flagBitCount(T, i);
        return total;
    }
}

fn validateAllNodeLayouts() void {
    @setEvalBranchQuota(10_000);
    for (@typeInfo(ast.NodeData).@"union".fields) |field| {
        const T = field.type;
        if (@typeInfo(T) != .@"struct") continue;
        if (totalU32Slots(T) > 5)
            @compileError("node '" ++ field.name ++ "' needs more than 5 u32 slots");
        if (totalFlagBits(T) > 8)
            @compileError("node '" ++ field.name ++ "' needs more than 8 flag bits");
    }
}

// serialization

pub fn bufferSize(tree: *const ast.Tree) usize {
    var size: usize = HEADER_SIZE +
        tree.nodes.len * NODE_SIZE +
        tree.extra.items.len * 4 +
        tree.strings.extra.items.len +
        tree.comments.len * COMMENT_SIZE;

    for (tree.diagnostics.items) |d| {
        size += 18 + d.message.len;
        if (d.help) |h| size += 4 + h.len;
        for (d.labels) |lbl| size += 12 + lbl.message.len;
    }
    return size;
}

pub fn serializeInto(tree: *const ast.Tree, buf: []u8) usize {
    const node_count: u32 = @intCast(tree.nodes.len);
    const extra_count: u32 = @intCast(tree.extra.items.len);
    const source_len: u32 = @intCast(tree.source.len);
    const string_pool_len: u32 = @intCast(tree.strings.extra.items.len);
    const comment_count: u32 = @intCast(tree.comments.len);
    const diag_count: u32 = @intCast(tree.diagnostics.items.len);
    const program_index: u32 = @intFromEnum(tree.program);
    const flags: u32 = if (isAsciiOnly(tree.source)) 1 else 0;

    var pos: usize = 0;

    // header
    @memcpy(buf[0..4], "YUKU");
    w32(buf, 4, VERSION);
    w32(buf, 8, node_count);
    w32(buf, 12, extra_count);
    w32(buf, 16, string_pool_len);
    w32(buf, 20, source_len);
    w32(buf, 24, comment_count);
    w32(buf, 28, diag_count);
    w32(buf, 32, program_index);
    w32(buf, 36, flags);
    pos = HEADER_SIZE;

    // nodes
    const data_items = tree.nodes.items(.data);
    const span_items = tree.nodes.items(.span);
    for (0..node_count) |i| {
        const node: *const [NODE_SIZE]u8 = @ptrCast(&packNode(data_items[i], span_items[i]));
        @memcpy(buf[pos..][0..NODE_SIZE], node);
        pos += NODE_SIZE;
    }

    // extra
    const extra_bytes = std.mem.sliceAsBytes(tree.extra.items);
    @memcpy(buf[pos..][0..extra_bytes.len], extra_bytes);
    pos += extra_bytes.len;

    // string pool
    @memcpy(buf[pos..][0..string_pool_len], tree.strings.extra.items);
    pos += string_pool_len;

    // comments
    for (tree.comments) |c| {
        buf[pos] = @intFromEnum(c.type);
        @memset(buf[pos + 1 ..][0..3], 0);
        w32(buf, pos + 4, c.start);
        w32(buf, pos + 8, c.end);
        w32(buf, pos + 12, c.value.start);
        w32(buf, pos + 16, c.value.end);
        pos += COMMENT_SIZE;
    }

    // diagnostics
    for (tree.diagnostics.items) |d| {
        buf[pos] = @intFromEnum(d.severity);
        pos += 1;
        w32(buf, pos, d.span.start);
        pos += 4;
        w32(buf, pos, d.span.end);
        pos += 4;
        w32(buf, pos, @intCast(d.message.len));
        pos += 4;
        @memcpy(buf[pos..][0..d.message.len], d.message);
        pos += d.message.len;
        if (d.help) |h| {
            buf[pos] = 1;
            pos += 1;
            w32(buf, pos, @intCast(h.len));
            pos += 4;
            @memcpy(buf[pos..][0..h.len], h);
            pos += h.len;
        } else {
            buf[pos] = 0;
            pos += 1;
        }
        w32(buf, pos, @intCast(d.labels.len));
        pos += 4;
        for (d.labels) |lbl| {
            w32(buf, pos, lbl.span.start);
            pos += 4;
            w32(buf, pos, lbl.span.end);
            pos += 4;
            w32(buf, pos, @intCast(lbl.message.len));
            pos += 4;
            @memcpy(buf[pos..][0..lbl.message.len], lbl.message);
            pos += lbl.message.len;
        }
    }

    return pos;
}

fn packNode(data: ast.NodeData, span: ast.Span) PackedNode {
    var n = PackedNode{
        .tag = 0,
        .flags = 0,
        .field0 = 0,
        .field1 = 0,
        .field2 = 0,
        .field3 = 0,
        .field4 = 0,
        .field5 = 0,
        .span_start = span.start,
        .span_end = span.end,
    };
    switch (data) {
        inline else => |payload, tag| {
            n.tag = @intFromEnum(tag);
            packPayload(&n, payload);
        },
    }
    return n;
}

fn packPayload(n: *PackedNode, payload: anytype) void {
    const T = @TypeOf(payload);
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const val = @field(payload, f.name);

        if (f.type == bool) {
            if (val) n.flags |= @as(u8, 1) << @as(u3, @intCast(comptime flagBitForField(T, i)));
        } else if (f.type == ast.NodeIndex) {
            setSlot(n, comptime u32SlotForField(T, i), @intFromEnum(val));
        } else if (f.type == ast.IndexRange) {
            const slot = comptime u32SlotForField(T, i);
            if (comptime isFirstRange(T, i)) {
                n.field0 = @intCast(val.len);
                setSlot(n, slot, val.start);
            } else {
                setSlot(n, slot, val.start);
                setSlot(n, slot + 1, @intCast(val.len));
            }
        } else if (f.type == ast.String) {
            const slot = comptime u32SlotForField(T, i);
            setSlot(n, slot, val.start);
            setSlot(n, slot + 1, val.end);
        } else if (comptime isEnumType(f.type)) {
            n.flags |= @as(u8, @intFromEnum(val)) << @as(u3, @intCast(comptime flagBitForField(T, i)));
        } else if (f.type == ?ast.ImportPhase) {
            const bit = comptime flagBitForField(T, i);
            if (val) |v| {
                n.flags |= @as(u8, 1) << @as(u3, @intCast(bit));
                n.flags |= @as(u8, @intFromEnum(v)) << @as(u3, @intCast(bit + 1));
            }
        } else if (f.type == ?ast.Hashbang) {
            const slot = comptime u32SlotForField(T, i);
            if (val) |h| {
                n.flags |= @as(u8, 1) << @as(u3, @intCast(comptime flagBitForField(T, i)));
                setSlot(n, slot, h.value.start);
                setSlot(n, slot + 1, h.value.end);
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
        }
    }
}

fn setSlot(n: *PackedNode, comptime slot: u8, val: u32) void {
    switch (slot) {
        0 => n.field1 = val,
        1 => n.field2 = val,
        2 => n.field3 = val,
        3 => n.field4 = val,
        4 => n.field5 = val,
        else => @compileError("too many u32 slots"),
    }
}

inline fn w32(buf: []u8, pos: usize, val: u32) void {
    std.mem.writeInt(u32, buf[pos..][0..4], val, .little);
}

fn isAsciiOnly(source: []const u8) bool {
    const Vec = @Vector(16, u8);
    const hi: Vec = @splat(0x80);
    var i: usize = 0;
    while (i + 16 <= source.len) : (i += 16) {
        if (@reduce(.Or, source[i..][0..16].* & hi) != 0) return false;
    }
    for (source[i..]) |c| {
        if (c >= 0x80) return false;
    }
    return true;
}
