import type {
  ClassType,
  Declaration,
  Expression,
  FunctionType,
  MethodDefinitionType,
  ModuleDeclaration,
  NodeOfType,
  NodeType,
  Statement,
  TSType,
} from "@yuku-toolchain/types";

// every group member must be a real node type, and the union-backed
// groups must match their @yuku-toolchain/types union exactly, both
// directions checked below
export const ALIAS_GROUPS = {
  Expression: [
    "Identifier",
    "Literal",
    "ThisExpression",
    "Super",
    "ArrayExpression",
    "ObjectExpression",
    "FunctionExpression",
    "ArrowFunctionExpression",
    "ClassExpression",
    "TaggedTemplateExpression",
    "TemplateLiteral",
    "MemberExpression",
    "CallExpression",
    "NewExpression",
    "ChainExpression",
    "SequenceExpression",
    "ParenthesizedExpression",
    "BinaryExpression",
    "LogicalExpression",
    "ConditionalExpression",
    "UnaryExpression",
    "UpdateExpression",
    "AssignmentExpression",
    "YieldExpression",
    "AwaitExpression",
    "ImportExpression",
    "MetaProperty",
    "TSAsExpression",
    "TSSatisfiesExpression",
    "TSTypeAssertion",
    "TSNonNullExpression",
    "TSInstantiationExpression",
    "JSXElement",
    "JSXFragment",
  ],
  Statement: [
    "ExpressionStatement",
    "BlockStatement",
    "EmptyStatement",
    "DebuggerStatement",
    "ReturnStatement",
    "LabeledStatement",
    "BreakStatement",
    "ContinueStatement",
    "IfStatement",
    "SwitchStatement",
    "ThrowStatement",
    "TryStatement",
    "WhileStatement",
    "DoWhileStatement",
    "ForStatement",
    "ForInStatement",
    "ForOfStatement",
    "WithStatement",
    "FunctionDeclaration",
    "ClassDeclaration",
    "VariableDeclaration",
    "TSDeclareFunction",
    "TSTypeAliasDeclaration",
    "TSInterfaceDeclaration",
    "TSEnumDeclaration",
    "TSModuleDeclaration",
    "TSImportEqualsDeclaration",
  ],
  Declaration: [
    "FunctionDeclaration",
    "ClassDeclaration",
    "VariableDeclaration",
    "TSDeclareFunction",
    "TSTypeAliasDeclaration",
    "TSInterfaceDeclaration",
    "TSEnumDeclaration",
    "TSModuleDeclaration",
    "TSImportEqualsDeclaration",
  ],
  ModuleDeclaration: [
    "ImportDeclaration",
    "ExportNamedDeclaration",
    "ExportDefaultDeclaration",
    "ExportAllDeclaration",
    "TSExportAssignment",
    "TSNamespaceExportDeclaration",
  ],
  Function: [
    "FunctionDeclaration",
    "FunctionExpression",
    "TSDeclareFunction",
    "TSEmptyBodyFunctionExpression",
    "ArrowFunctionExpression",
  ],
  Class: ["ClassDeclaration", "ClassExpression"],
  Method: ["MethodDefinition", "TSAbstractMethodDefinition"],
  Loop: ["DoWhileStatement", "ForInStatement", "ForOfStatement", "ForStatement", "WhileStatement"],
  Pattern: ["ArrayPattern", "ObjectPattern", "AssignmentPattern", "RestElement"],
  JSX: [
    "JSXAttribute",
    "JSXClosingElement",
    "JSXClosingFragment",
    "JSXElement",
    "JSXEmptyExpression",
    "JSXExpressionContainer",
    "JSXFragment",
    "JSXIdentifier",
    "JSXMemberExpression",
    "JSXNamespacedName",
    "JSXOpeningElement",
    "JSXOpeningFragment",
    "JSXSpreadAttribute",
    "JSXSpreadChild",
    "JSXText",
  ],
  TSType: [
    "TSAnyKeyword",
    "TSUnknownKeyword",
    "TSNeverKeyword",
    "TSVoidKeyword",
    "TSNullKeyword",
    "TSUndefinedKeyword",
    "TSStringKeyword",
    "TSNumberKeyword",
    "TSBigIntKeyword",
    "TSBooleanKeyword",
    "TSSymbolKeyword",
    "TSObjectKeyword",
    "TSIntrinsicKeyword",
    "TSThisType",
    "TSTypeReference",
    "TSTypeQuery",
    "TSImportType",
    "TSLiteralType",
    "TSTemplateLiteralType",
    "TSArrayType",
    "TSIndexedAccessType",
    "TSTupleType",
    "TSNamedTupleMember",
    "TSJSDocNullableType",
    "TSJSDocNonNullableType",
    "TSJSDocUnknownType",
    "TSUnionType",
    "TSIntersectionType",
    "TSConditionalType",
    "TSInferType",
    "TSTypeOperator",
    "TSParenthesizedType",
    "TSFunctionType",
    "TSConstructorType",
    "TSTypePredicate",
    "TSTypeLiteral",
    "TSMappedType",
  ],
} as const satisfies Record<string, readonly NodeType[]>;

export type AliasName = keyof typeof ALIAS_GROUPS;

type GroupType<A extends AliasName> = (typeof ALIAS_GROUPS)[A][number];

/** The node union each alias covers, e.g. `AliasMap["Function"]`. */
export type AliasMap = { [A in AliasName]: NodeOfType<GroupType<A>> };

export const ALIAS_NAMES = Object.keys(ALIAS_GROUPS) as readonly AliasName[];

// exact two-way agreement with the @yuku-toolchain/types unions
type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Expect<T extends true> = T;
type _expression = Expect<Same<GroupType<"Expression">, Expression["type"]>>;
type _statement = Expect<Same<GroupType<"Statement">, Statement["type"]>>;
type _declaration = Expect<Same<GroupType<"Declaration">, Declaration["type"]>>;
type _module = Expect<Same<GroupType<"ModuleDeclaration">, ModuleDeclaration["type"]>>;
type _function = Expect<Same<GroupType<"Function">, FunctionType | "ArrowFunctionExpression">>;
type _class = Expect<Same<GroupType<"Class">, ClassType>>;
type _method = Expect<Same<GroupType<"Method">, MethodDefinitionType>>;
type _tstype = Expect<Same<GroupType<"TSType">, TSType["type"]>>;
