// generated by tools/estree/decoder.zig, do not edit
const KEYS: Record<string, string[]> = Object.create(null);
function ck(type: string, keys: string[]): void {
  const prev = KEYS[type];
  if (prev === undefined) KEYS[type] = keys;
  else for (const k of keys) if (!prev.includes(k)) prev.push(k);
}
ck("SequenceExpression", ["expressions"]);
ck("ParenthesizedExpression", ["expression"]);
ck("ArrowFunctionExpression", ["typeParameters", "params", "returnType", "body"]);
ck("FunctionDeclaration", ["id", "typeParameters", "params", "returnType", "body"]);
ck("FunctionExpression", ["id", "typeParameters", "params", "returnType", "body"]);
ck("TSDeclareFunction", ["id", "typeParameters", "params", "returnType", "body"]);
ck("TSEmptyBodyFunctionExpression", ["id", "typeParameters", "params", "returnType", "body"]);
ck("BlockStatement", ["body"]);
ck("BlockStatement", ["body"]);
ck("BinaryExpression", ["left", "right"]);
ck("LogicalExpression", ["left", "right"]);
ck("ConditionalExpression", ["test", "consequent", "alternate"]);
ck("UnaryExpression", ["argument"]);
ck("UpdateExpression", ["argument"]);
ck("AssignmentExpression", ["left", "right"]);
ck("ArrayExpression", ["elements"]);
ck("ObjectExpression", ["properties"]);
ck("SpreadElement", ["argument"]);
ck("Property", ["key", "value"]);
ck("MemberExpression", ["object", "property"]);
ck("CallExpression", ["callee", "typeArguments", "arguments"]);
ck("ChainExpression", ["expression"]);
ck("TaggedTemplateExpression", ["tag", "typeArguments", "quasi"]);
ck("NewExpression", ["callee", "typeArguments", "arguments"]);
ck("AwaitExpression", ["argument"]);
ck("YieldExpression", ["argument"]);
ck("MetaProperty", ["meta", "property"]);
ck("Decorator", ["expression"]);
ck("ClassDeclaration", ["decorators", "id", "typeParameters", "superClass", "superTypeArguments", "implements", "body"]);
ck("ClassExpression", ["decorators", "id", "typeParameters", "superClass", "superTypeArguments", "implements", "body"]);
ck("ClassBody", ["body"]);
ck("MethodDefinition", ["decorators", "key", "value"]);
ck("TSAbstractMethodDefinition", ["decorators", "key", "value"]);
ck("PropertyDefinition", ["decorators", "key", "typeAnnotation", "value"]);
ck("AccessorProperty", ["decorators", "key", "typeAnnotation", "value"]);
ck("TSAbstractPropertyDefinition", ["decorators", "key", "typeAnnotation", "value"]);
ck("TSAbstractAccessorProperty", ["decorators", "key", "typeAnnotation", "value"]);
ck("StaticBlock", ["body"]);
ck("Super", []);
ck("Literal", []);
ck("Literal", []);
ck("Literal", []);
ck("Literal", []);
ck("Literal", []);
ck("ThisExpression", []);
ck("Literal", []);
ck("TemplateLiteral", ["quasis", "expressions"]);
ck("TemplateElement", []);
ck("Identifier", []);
ck("PrivateIdentifier", []);
ck("Identifier", ["decorators", "typeAnnotation"]);
ck("Identifier", []);
ck("Identifier", []);
ck("ExpressionStatement", ["expression"]);
ck("IfStatement", ["test", "consequent", "alternate"]);
ck("SwitchStatement", ["discriminant", "cases"]);
ck("SwitchCase", ["test", "consequent"]);
ck("ForStatement", ["init", "test", "update", "body"]);
ck("ForInStatement", ["left", "right", "body"]);
ck("ForOfStatement", ["left", "right", "body"]);
ck("WhileStatement", ["test", "body"]);
ck("DoWhileStatement", ["body", "test"]);
ck("BreakStatement", ["label"]);
ck("ContinueStatement", ["label"]);
ck("LabeledStatement", ["label", "body"]);
ck("WithStatement", ["object", "body"]);
ck("ReturnStatement", ["argument"]);
ck("ThrowStatement", ["argument"]);
ck("TryStatement", ["block", "handler", "finalizer"]);
ck("CatchClause", ["param", "body"]);
ck("DebuggerStatement", []);
ck("EmptyStatement", []);
ck("VariableDeclaration", ["declarations"]);
ck("VariableDeclarator", ["id", "init"]);
ck("ExpressionStatement", ["expression"]);
ck("AssignmentPattern", ["decorators", "left", "typeAnnotation", "right"]);
ck("RestElement", ["decorators", "argument", "typeAnnotation"]);
ck("ArrayPattern", ["decorators", "elements", "typeAnnotation"]);
ck("ObjectPattern", ["decorators", "properties", "typeAnnotation"]);
ck("Property", ["key", "value"]);
ck("Program", ["hashbang", "body"]);
ck("ImportExpression", ["source", "options"]);
ck("ImportDeclaration", ["specifiers", "source", "attributes"]);
ck("ImportSpecifier", ["imported", "local"]);
ck("ImportDefaultSpecifier", ["local"]);
ck("ImportNamespaceSpecifier", ["local"]);
ck("ImportAttribute", ["key", "value"]);
ck("ExportNamedDeclaration", ["declaration", "specifiers", "source", "attributes"]);
ck("ExportDefaultDeclaration", ["declaration"]);
ck("ExportAllDeclaration", ["exported", "source", "attributes"]);
ck("ExportSpecifier", ["local", "exported"]);
ck("TSTypeAnnotation", ["typeAnnotation"]);
ck("TSAnyKeyword", []);
ck("TSUnknownKeyword", []);
ck("TSNeverKeyword", []);
ck("TSVoidKeyword", []);
ck("TSNullKeyword", []);
ck("TSUndefinedKeyword", []);
ck("TSStringKeyword", []);
ck("TSNumberKeyword", []);
ck("TSBigIntKeyword", []);
ck("TSBooleanKeyword", []);
ck("TSSymbolKeyword", []);
ck("TSObjectKeyword", []);
ck("TSIntrinsicKeyword", []);
ck("TSThisType", []);
ck("TSTypeReference", ["typeName", "typeArguments"]);
ck("TSQualifiedName", ["left", "right"]);
ck("TSTypeQuery", ["exprName", "typeArguments"]);
ck("TSImportType", ["source", "options", "qualifier", "typeArguments"]);
ck("TSTypeParameter", ["name", "constraint", "default"]);
ck("TSTypeParameterDeclaration", ["params"]);
ck("TSTypeParameterInstantiation", ["params"]);
ck("TSLiteralType", ["literal"]);
ck("TSTemplateLiteralType", ["quasis", "types"]);
ck("TSArrayType", ["elementType"]);
ck("TSIndexedAccessType", ["objectType", "indexType"]);
ck("TSTupleType", ["elementTypes"]);
ck("TSNamedTupleMember", ["label", "elementType"]);
ck("TSOptionalType", ["typeAnnotation"]);
ck("TSRestType", ["typeAnnotation"]);
ck("TSJSDocNullableType", ["typeAnnotation"]);
ck("TSJSDocNonNullableType", ["typeAnnotation"]);
ck("TSJSDocUnknownType", []);
ck("TSUnionType", ["types"]);
ck("TSIntersectionType", ["types"]);
ck("TSConditionalType", ["checkType", "extendsType", "trueType", "falseType"]);
ck("TSInferType", ["typeParameter"]);
ck("TSTypeOperator", ["typeAnnotation"]);
ck("TSParenthesizedType", ["typeAnnotation"]);
ck("TSFunctionType", ["typeParameters", "params", "returnType"]);
ck("TSConstructorType", ["typeParameters", "params", "returnType"]);
ck("TSTypePredicate", ["parameterName", "typeAnnotation"]);
ck("TSTypeLiteral", ["members"]);
ck("TSMappedType", ["key", "constraint", "nameType", "typeAnnotation"]);
ck("TSPropertySignature", ["key", "typeAnnotation"]);
ck("TSMethodSignature", ["key", "typeParameters", "params", "returnType"]);
ck("TSCallSignatureDeclaration", ["typeParameters", "params", "returnType"]);
ck("TSConstructSignatureDeclaration", ["typeParameters", "params", "returnType"]);
ck("TSIndexSignature", ["parameters", "typeAnnotation"]);
ck("TSTypeAliasDeclaration", ["id", "typeParameters", "typeAnnotation"]);
ck("TSInterfaceDeclaration", ["id", "typeParameters", "extends", "body"]);
ck("TSInterfaceBody", ["body"]);
ck("TSInterfaceHeritage", ["expression", "typeArguments"]);
ck("TSClassImplements", ["expression", "typeArguments"]);
ck("TSEnumDeclaration", ["id", "body"]);
ck("TSEnumBody", ["members"]);
ck("TSEnumMember", ["id", "initializer"]);
ck("TSModuleDeclaration", ["id", "body"]);
ck("TSModuleBlock", ["body"]);
ck("TSModuleDeclaration", ["id", "body"]);
ck("TSParameterProperty", ["decorators", "parameter"]);
ck("Identifier", ["typeAnnotation"]);
ck("TSAsExpression", ["expression", "typeAnnotation"]);
ck("TSSatisfiesExpression", ["expression", "typeAnnotation"]);
ck("TSTypeAssertion", ["typeAnnotation", "expression"]);
ck("TSNonNullExpression", ["expression"]);
ck("TSInstantiationExpression", ["expression", "typeArguments"]);
ck("TSExportAssignment", ["expression"]);
ck("TSNamespaceExportDeclaration", ["id"]);
ck("TSImportEqualsDeclaration", ["id", "moduleReference"]);
ck("TSExternalModuleReference", ["expression"]);
ck("JSXElement", ["openingElement", "children", "closingElement"]);
ck("JSXOpeningElement", ["name", "typeArguments", "attributes"]);
ck("JSXClosingElement", ["name"]);
ck("JSXFragment", ["openingFragment", "children", "closingFragment"]);
ck("JSXOpeningFragment", []);
ck("JSXClosingFragment", []);
ck("JSXIdentifier", []);
ck("JSXNamespacedName", ["namespace", "name"]);
ck("JSXMemberExpression", ["object", "property"]);
ck("JSXAttribute", ["name", "value"]);
ck("JSXSpreadAttribute", ["argument"]);
ck("JSXExpressionContainer", ["expression"]);
ck("JSXEmptyExpression", []);
ck("JSXText", []);
ck("JSXSpreadChild", ["expression"]);
ck("Hashbang", []);

export const CHILD_KEYS: Readonly<Record<string, readonly string[]>> = KEYS;

const TYPES = [
  "SequenceExpression",
  "ParenthesizedExpression",
  "ArrowFunctionExpression",
  "FunctionDeclaration",
  "FunctionExpression",
  "TSDeclareFunction",
  "TSEmptyBodyFunctionExpression",
  "BlockStatement",
  "BlockStatement",
  "BinaryExpression",
  "LogicalExpression",
  "ConditionalExpression",
  "UnaryExpression",
  "UpdateExpression",
  "AssignmentExpression",
  "ArrayExpression",
  "ObjectExpression",
  "SpreadElement",
  "Property",
  "MemberExpression",
  "CallExpression",
  "ChainExpression",
  "TaggedTemplateExpression",
  "NewExpression",
  "AwaitExpression",
  "YieldExpression",
  "MetaProperty",
  "Decorator",
  "ClassDeclaration",
  "ClassExpression",
  "ClassBody",
  "MethodDefinition",
  "TSAbstractMethodDefinition",
  "PropertyDefinition",
  "AccessorProperty",
  "TSAbstractPropertyDefinition",
  "TSAbstractAccessorProperty",
  "StaticBlock",
  "Super",
  "Literal",
  "Literal",
  "Literal",
  "Literal",
  "Literal",
  "ThisExpression",
  "Literal",
  "TemplateLiteral",
  "TemplateElement",
  "Identifier",
  "PrivateIdentifier",
  "Identifier",
  "Identifier",
  "Identifier",
  "ExpressionStatement",
  "IfStatement",
  "SwitchStatement",
  "SwitchCase",
  "ForStatement",
  "ForInStatement",
  "ForOfStatement",
  "WhileStatement",
  "DoWhileStatement",
  "BreakStatement",
  "ContinueStatement",
  "LabeledStatement",
  "WithStatement",
  "ReturnStatement",
  "ThrowStatement",
  "TryStatement",
  "CatchClause",
  "DebuggerStatement",
  "EmptyStatement",
  "VariableDeclaration",
  "VariableDeclarator",
  "ExpressionStatement",
  "AssignmentPattern",
  "RestElement",
  "ArrayPattern",
  "ObjectPattern",
  "Property",
  "Program",
  "ImportExpression",
  "ImportDeclaration",
  "ImportSpecifier",
  "ImportDefaultSpecifier",
  "ImportNamespaceSpecifier",
  "ImportAttribute",
  "ExportNamedDeclaration",
  "ExportDefaultDeclaration",
  "ExportAllDeclaration",
  "ExportSpecifier",
  "TSTypeAnnotation",
  "TSAnyKeyword",
  "TSUnknownKeyword",
  "TSNeverKeyword",
  "TSVoidKeyword",
  "TSNullKeyword",
  "TSUndefinedKeyword",
  "TSStringKeyword",
  "TSNumberKeyword",
  "TSBigIntKeyword",
  "TSBooleanKeyword",
  "TSSymbolKeyword",
  "TSObjectKeyword",
  "TSIntrinsicKeyword",
  "TSThisType",
  "TSTypeReference",
  "TSQualifiedName",
  "TSTypeQuery",
  "TSImportType",
  "TSTypeParameter",
  "TSTypeParameterDeclaration",
  "TSTypeParameterInstantiation",
  "TSLiteralType",
  "TSTemplateLiteralType",
  "TSArrayType",
  "TSIndexedAccessType",
  "TSTupleType",
  "TSNamedTupleMember",
  "TSOptionalType",
  "TSRestType",
  "TSJSDocNullableType",
  "TSJSDocNonNullableType",
  "TSJSDocUnknownType",
  "TSUnionType",
  "TSIntersectionType",
  "TSConditionalType",
  "TSInferType",
  "TSTypeOperator",
  "TSParenthesizedType",
  "TSFunctionType",
  "TSConstructorType",
  "TSTypePredicate",
  "TSTypeLiteral",
  "TSMappedType",
  "TSPropertySignature",
  "TSMethodSignature",
  "TSCallSignatureDeclaration",
  "TSConstructSignatureDeclaration",
  "TSIndexSignature",
  "TSTypeAliasDeclaration",
  "TSInterfaceDeclaration",
  "TSInterfaceBody",
  "TSInterfaceHeritage",
  "TSClassImplements",
  "TSEnumDeclaration",
  "TSEnumBody",
  "TSEnumMember",
  "TSModuleDeclaration",
  "TSModuleBlock",
  "TSModuleDeclaration",
  "TSParameterProperty",
  "Identifier",
  "TSAsExpression",
  "TSSatisfiesExpression",
  "TSTypeAssertion",
  "TSNonNullExpression",
  "TSInstantiationExpression",
  "TSExportAssignment",
  "TSNamespaceExportDeclaration",
  "TSImportEqualsDeclaration",
  "TSExternalModuleReference",
  "JSXElement",
  "JSXOpeningElement",
  "JSXClosingElement",
  "JSXFragment",
  "JSXOpeningFragment",
  "JSXClosingFragment",
  "JSXIdentifier",
  "JSXNamespacedName",
  "JSXMemberExpression",
  "JSXAttribute",
  "JSXSpreadAttribute",
  "JSXExpressionContainer",
  "JSXEmptyExpression",
  "JSXText",
  "JSXSpreadChild",
  "Hashbang",
] as const;

export type GeneratedNodeType = (typeof TYPES)[number];

export const NODE_TYPES: readonly GeneratedNodeType[] = [...new Set<GeneratedNodeType>(TYPES)];
