// Yuku AST Transfer Format v2
//
// serializes the parsed AST into a compact binary buffer for passing to JS.
// the buffer is returned as an ArrayBuffer from the native NAPI binding.
// JS side decoders walk this buffer to construct AST objects in any shape
// (ESTree, Babel, etc). all integers are little endian.
// the current ESTree decoder is generated by tools/gen_estree_decoder.zig.
//
//
// 1. buffer layout
//
//   offset  section
//   0       header      (sizeof(Header) bytes, fixed)
//   ...     nodes       (node_count * sizeof(PackedNode) bytes)
//   ...     extra       (extra_count * 4 bytes)
//   ...     strings     (string_pool_len bytes, raw utf8)
//   ...     comments    (comment_count * sizeof(CommentEntry) bytes)
//   ...     diagnostics (variable length)
//
//
// 2. fixed structures
//
//   `Header`, `PackedNode`, and `CommentEntry` below are `extern struct`s.
//   their `@sizeOf` and `@offsetOf` values are the single source of truth
//   for both the serializer and the JS decoder. changing a field in any of
//   these structs propagates to the generated decoder automatically via the
//   `pub const` offsets exported from this file.
//
//
// 3. node field packing
//
//   fields of an AST struct are assigned to `PackedNode` slots by iterating
//   the struct in declaration order. for each field:
//
//     bool              1 bit in flags (bit position = sum of prior flag widths)
//     enum              ceil(log2(N)) bits in flags
//     NodeIndex         1 u32 slot (0xFFFFFFFF = null)
//     IndexRange        first:  len in field0 (u16), start in 1 u32 slot
//                       later:  start then len in 2 consecutive u32 slots
//     String            2 u32 slots (start, end). if start < source_len,
//                       references source text; otherwise references the
//                       string pool at offset (start - source_len)
//     ?OptionalEnum     1 flag bit (presence) + enum bits (value)
//     ?OptionalStruct   1 flag bit (presence) + u32 slots for inner fields
//
//
// 4. extra (u32 array)
//
//   flat array of node indices used by IndexRange fields.
//   an IndexRange { start, len } refers to extra[start .. start+len].
//
//
// 5. string pool (raw bytes)
//
//   flat utf8 byte buffer for strings not directly sliceable from source.
//   a String { start, end } with start >= source_len references
//   pool bytes at offset (start - source_len) .. (end - source_len).
//   may contain WTF8 encoded lone surrogates.
//
//
// 6. diagnostics (variable length, sequential)
//
//   each diagnostic:
//     1 byte    severity        0 = error, 1 = warning, 2 = hint, 3 = info
//     4 bytes   span_start
//     4 bytes   span_end
//     4 bytes   message_len
//     N bytes   message         utf8 text
//     1 byte    has_help        0 or 1
//     if has_help:
//       4 bytes   help_len
//       N bytes   help          utf8 text
//     4 bytes   label_count
//     for each label:
//       4 bytes   start
//       4 bytes   end
//       4 bytes   message_len
//       N bytes   message       utf8 text

const std = @import("std");
const ast = @import("parser").ast;

pub const VERSION: u32 = 2;

/// fixed-size header prefixing the buffer. field order defines the on-wire
/// layout; the serializer writes this struct via `@memcpy` and the decoder
/// reads each field by the u32 index derived from `@offsetOf` below.
const Header = extern struct {
    magic: [4]u8,
    version: u32,
    node_count: u32,
    extra_count: u32,
    string_pool_len: u32,
    source_len: u32,
    comment_count: u32,
    diag_count: u32,
    program_index: u32,
    flags: u32,
};

/// packed AST node entry. the `tag` identifies the `ast.NodeData` variant;
/// `flags` holds packed booleans and small enums; `field1..field8` are u32
/// data slots assigned to struct fields by the rules in section 3.
const PackedNode = extern struct {
    tag: u8,
    _pad0: u8 = 0,
    flags: u16,
    /// first IndexRange's length (other IndexRanges use full u32 slots).
    field0: u16,
    _pad1: u16 = 0,
    field1: u32,
    field2: u32,
    field3: u32,
    field4: u32,
    field5: u32,
    field6: u32,
    field7: u32,
    field8: u32,
    span_start: u32,
    span_end: u32,
};

/// comment entry in the comments section.
const CommentEntry = extern struct {
    type: u8,
    _pad: [3]u8 = [_]u8{0} ** 3,
    start: u32,
    end: u32,
    value_start: u32,
    value_end: u32,
};

// section sizes
pub const HEADER_SIZE: u32 = @sizeOf(Header);
pub const NODE_SIZE: u32 = @sizeOf(PackedNode);
pub const COMMENT_SIZE: u32 = @sizeOf(CommentEntry);

// `Header` field u32 indices, for the decoder
pub const HDR_NODE_COUNT_U32: u32 = @offsetOf(Header, "node_count") / 4;
pub const HDR_EXTRA_COUNT_U32: u32 = @offsetOf(Header, "extra_count") / 4;
pub const HDR_STRING_POOL_LEN_U32: u32 = @offsetOf(Header, "string_pool_len") / 4;
pub const HDR_SOURCE_LEN_U32: u32 = @offsetOf(Header, "source_len") / 4;
pub const HDR_COMMENT_COUNT_U32: u32 = @offsetOf(Header, "comment_count") / 4;
pub const HDR_DIAG_COUNT_U32: u32 = @offsetOf(Header, "diag_count") / 4;
pub const HDR_PROGRAM_INDEX_U32: u32 = @offsetOf(Header, "program_index") / 4;
pub const HDR_FLAGS_U32: u32 = @offsetOf(Header, "flags") / 4;

// `Header.flags` bit positions
pub const FLAG_ASCII: u32 = 1;
pub const FLAG_TS: u32 = 2;

// `PackedNode` byte offsets and u32 indices
pub const NODE_FLAGS_OFFSET: u8 = @offsetOf(PackedNode, "flags");
pub const NODE_FIELD0_OFFSET: u8 = @offsetOf(PackedNode, "field0");
pub const NODE_HEADER_U32S: u8 = @offsetOf(PackedNode, "field1") / 4;
pub const NODE_SPAN_START_U32: u8 = @offsetOf(PackedNode, "span_start") / 4;
pub const NODE_SPAN_END_U32: u8 = @offsetOf(PackedNode, "span_end") / 4;

// `PackedNode` capacity, number of u32 data slots and flag bits available
// per node. used by `validateAllNodeLayouts` to reject AST structs that
// don't fit. both values track the struct layout automatically.
pub const NODE_DATA_SLOTS: u8 = NODE_SPAN_START_U32 - NODE_HEADER_U32S;
pub const NODE_FLAG_BITS: u8 = @bitSizeOf(@FieldType(PackedNode, "flags"));

// `CommentEntry` byte offsets, for the decoder
pub const COMMENT_START_OFFSET: u8 = @offsetOf(CommentEntry, "start");
pub const COMMENT_END_OFFSET: u8 = @offsetOf(CommentEntry, "end");
pub const COMMENT_VALUE_START_OFFSET: u8 = @offsetOf(CommentEntry, "value_start");
pub const COMMENT_VALUE_END_OFFSET: u8 = @offsetOf(CommentEntry, "value_end");

comptime {
    validateAllNodeLayouts();
}

// layout functions used by both the serializer (below) and the decoder generator (tools/gen_estree_decoder.zig).

/// number of flag bits consumed by field `field_idx` in struct T.
pub fn flagBitCount(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == bool) return 1;
    if (f.type == ?ast.ImportPhase) return 1 + enumBitWidth(ast.ImportPhase);
    if (f.type == ?ast.Hashbang) return 1;
    if (comptime isEnumType(f.type)) return enumBitWidth(f.type);
    if (f.type == ast.NodeIndex or f.type == ast.IndexRange or f.type == ast.String) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// starting flag bit position for field `target` in struct T.
pub fn flagBitForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var bit: u8 = 0;
        for (0..target) |i| bit += flagBitCount(T, i);
        return bit;
    }
}

/// number of u32 slots consumed by field `field_idx` in struct T.
pub fn fieldU32Count(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == ast.NodeIndex) return 1;
    if (f.type == ast.IndexRange) return if (isFirstRange(T, field_idx)) 1 else 2;
    if (f.type == ast.String) return 2;
    if (f.type == ?ast.Hashbang) return 2;
    if (f.type == bool or f.type == ?ast.ImportPhase or comptime isEnumType(f.type)) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// first u32 slot index for field `target` in struct T.
pub fn u32SlotForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var slot: u8 = 0;
        for (0..target) |i| slot += fieldU32Count(T, i);
        return slot;
    }
}

/// true if field `target` is the first IndexRange in struct T.
pub fn isFirstRange(comptime T: type, comptime target: usize) bool {
    comptime {
        for (std.meta.fields(T), 0..) |f, i| {
            if (f.type == ast.IndexRange) return i == target;
        }
        return false;
    }
}

/// ceil(log2(N)) where N is the number of enum variants.
pub fn enumBitWidth(comptime E: type) u8 {
    return std.math.log2_int_ceil(usize, @typeInfo(E).@"enum".fields.len);
}

pub fn isEnumType(comptime T: type) bool {
    return @typeInfo(T) == .@"enum";
}

/// total u32 slots used by struct T.
pub fn totalU32Slots(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += fieldU32Count(T, i);
        return total;
    }
}

/// total flag bits used by struct T.
pub fn totalFlagBits(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += flagBitCount(T, i);
        return total;
    }
}

fn validateAllNodeLayouts() void {
    @setEvalBranchQuota(10_000);
    for (@typeInfo(ast.NodeData).@"union".fields) |field| {
        const T = field.type;
        if (@typeInfo(T) != .@"struct") continue;
        if (totalU32Slots(T) > NODE_DATA_SLOTS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} u32 slots",
            .{ field.name, NODE_DATA_SLOTS },
        ));
        if (totalFlagBits(T) > NODE_FLAG_BITS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} flag bits",
            .{ field.name, NODE_FLAG_BITS },
        ));
    }
}

// serialization

pub fn bufferSize(tree: *const ast.Tree) usize {
    // fixed-size diagnostic prologue, severity + span_start + span_end +
    // message_len + has_help + label_count.
    const diag_fixed = 1 + 4 + 4 + 4 + 1 + 4;
    const help_prefix = 4; // help_len
    const label_fixed = 4 + 4 + 4; // start + end + message_len

    var size: usize = HEADER_SIZE +
        tree.nodes.len * NODE_SIZE +
        tree.extra.items.len * 4 +
        tree.strings.extra.items.len +
        tree.comments.len * COMMENT_SIZE;

    for (tree.diagnostics.items) |d| {
        size += diag_fixed + d.message.len;
        if (d.help) |h| size += help_prefix + h.len;
        for (d.labels) |lbl| size += label_fixed + lbl.message.len;
    }
    return size;
}

pub fn serializeInto(tree: *const ast.Tree, buf: []u8) usize {
    const string_pool_len: u32 = @intCast(tree.strings.extra.items.len);
    var hdr_flags: u32 = if (isAsciiOnly(tree.source)) FLAG_ASCII else 0;
    if (tree.isTs()) hdr_flags |= FLAG_TS;

    // header
    const hdr = Header{
        .magic = "YUKU".*,
        .version = VERSION,
        .node_count = @intCast(tree.nodes.len),
        .extra_count = @intCast(tree.extra.items.len),
        .string_pool_len = string_pool_len,
        .source_len = @intCast(tree.source.len),
        .comment_count = @intCast(tree.comments.len),
        .diag_count = @intCast(tree.diagnostics.items.len),
        .program_index = @intFromEnum(tree.program),
        .flags = hdr_flags,
    };
    @memcpy(buf[0..HEADER_SIZE], std.mem.asBytes(&hdr));
    var pos: usize = HEADER_SIZE;

    // nodes
    const data_items = tree.nodes.items(.data);
    const span_items = tree.nodes.items(.span);
    for (0..hdr.node_count) |i| {
        const n = packNode(data_items[i], span_items[i]);
        @memcpy(buf[pos..][0..NODE_SIZE], std.mem.asBytes(&n));
        pos += NODE_SIZE;
    }

    // extra
    const extra_bytes = std.mem.sliceAsBytes(tree.extra.items);
    @memcpy(buf[pos..][0..extra_bytes.len], extra_bytes);
    pos += extra_bytes.len;

    // string pool
    @memcpy(buf[pos..][0..string_pool_len], tree.strings.extra.items);
    pos += string_pool_len;

    // comments
    for (tree.comments) |c| {
        const entry = CommentEntry{
            .type = @intFromEnum(c.type),
            .start = c.start,
            .end = c.end,
            .value_start = c.value.start,
            .value_end = c.value.end,
        };
        @memcpy(buf[pos..][0..COMMENT_SIZE], std.mem.asBytes(&entry));
        pos += COMMENT_SIZE;
    }

    // diagnostics (variable length)
    for (tree.diagnostics.items) |d| {
        buf[pos] = @intFromEnum(d.severity);
        pos += 1;
        w32(buf, pos, d.span.start);
        pos += 4;
        w32(buf, pos, d.span.end);
        pos += 4;
        w32(buf, pos, @intCast(d.message.len));
        pos += 4;
        @memcpy(buf[pos..][0..d.message.len], d.message);
        pos += d.message.len;
        if (d.help) |h| {
            buf[pos] = 1;
            pos += 1;
            w32(buf, pos, @intCast(h.len));
            pos += 4;
            @memcpy(buf[pos..][0..h.len], h);
            pos += h.len;
        } else {
            buf[pos] = 0;
            pos += 1;
        }
        w32(buf, pos, @intCast(d.labels.len));
        pos += 4;
        for (d.labels) |lbl| {
            w32(buf, pos, lbl.span.start);
            pos += 4;
            w32(buf, pos, lbl.span.end);
            pos += 4;
            w32(buf, pos, @intCast(lbl.message.len));
            pos += 4;
            @memcpy(buf[pos..][0..lbl.message.len], lbl.message);
            pos += lbl.message.len;
        }
    }

    return pos;
}

fn packNode(data: ast.NodeData, span: ast.Span) PackedNode {
    var n: PackedNode = std.mem.zeroes(PackedNode);
    n.span_start = span.start;
    n.span_end = span.end;
    switch (data) {
        inline else => |payload, tag| {
            n.tag = @intFromEnum(tag);
            packPayload(&n, payload);
        },
    }
    return n;
}

fn packPayload(n: *PackedNode, payload: anytype) void {
    const T = @TypeOf(payload);
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const val = @field(payload, f.name);
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            if (val) setFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            setSlot(n, slot, @intFromEnum(val));
        } else if (f.type == ast.IndexRange) {
            if (comptime isFirstRange(T, i)) {
                n.field0 = @intCast(val.len);
                setSlot(n, slot, val.start);
            } else {
                setSlot(n, slot, val.start);
                setSlot(n, slot + 1, @intCast(val.len));
            }
        } else if (f.type == ast.String) {
            setSlot(n, slot, val.start);
            setSlot(n, slot + 1, val.end);
        } else if (comptime isEnumType(f.type)) {
            setFlagBits(n, bit, @intFromEnum(val));
        } else if (f.type == ?ast.ImportPhase) {
            if (val) |v| {
                setFlagBit(n, bit);
                setFlagBits(n, bit + 1, @intFromEnum(v));
            }
        } else if (f.type == ?ast.Hashbang) {
            if (val) |h| {
                setFlagBit(n, bit);
                setSlot(n, slot, h.value.start);
                setSlot(n, slot + 1, h.value.end);
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
        }
    }
}

inline fn setFlagBit(n: *PackedNode, comptime bit: u8) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), 1) << @intCast(bit);
}

inline fn setFlagBits(n: *PackedNode, comptime bit: u8, val: anytype) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), @intCast(val)) << @intCast(bit);
}

inline fn setSlot(n: *PackedNode, comptime slot: u8, val: u32) void {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    @as([*]u32, @ptrCast(&n.field1))[slot] = val;
}

inline fn w32(buf: []u8, pos: usize, val: u32) void {
    std.mem.writeInt(u32, buf[pos..][0..4], val, .little);
}

fn isAsciiOnly(source: []const u8) bool {
    const Vec = @Vector(16, u8);
    const hi: Vec = @splat(0x80);
    var i: usize = 0;
    while (i + 16 <= source.len) : (i += 16) {
        if (@reduce(.Or, source[i..][0..16].* & hi) != 0) return false;
    }
    for (source[i..]) |c| {
        if (c >= 0x80) return false;
    }
    return true;
}
