// yuku ast transfer format v6.
//
// serializes the parsed ast into a compact binary buffer for passing to js.
// the buffer is returned as an arraybuffer from the native napi binding.
// js decoders walk the buffer to construct ast objects in any shape
// (estree, babel, and so on). all integers are little endian.
//
// the extern structs below (Header, PackedNode, PackedComment) own the
// wire layout. their @sizeOf and @offsetOf values drive both the
// serializer below and the js decoder generated by
// tools/gen_estree_decoder.zig, so the two sides cannot drift.
//
// buffer sections
//   header             HEADER_SIZE bytes, fixed
//   nodes              node_count times NODE_SIZE bytes
//   extra              extra_count times 4 bytes, flat u32 array backing IndexRange
//   strings            string_pool_len bytes of raw utf8 for pooled strings
//   comment_offsets    (node_count+1) u32s when FLAG_ATTACH_COMMENTS is set,
//                      empty otherwise. prefix-sum index into `comments`.
//   comments           comment_count times COMMENT_SIZE bytes
//   line_starts        line_starts_count times 4 bytes, flat u32 array
//   diagnostics        variable length sequence
//
// each AST struct is packed into a PackedNode by iterating its fields in
// declaration order.
//
//   bool              1 flag bit, position is the sum of prior flag widths
//   enum              ceil(log2(n)) flag bits
//   NodeIndex         1 u32 slot, 0xFFFFFFFF marks null
//   IndexRange        the first such field takes field0 (u16 length) and 1
//                     u32 slot for start. later ones take 2 u32 slots for
//                     start then length
//   String            2 u32 slots (start, end). when start < source_len
//                     the range is a slice of the source buffer, otherwise
//                     it references the string pool at (start minus
//                     source_len)
//   ?OptionalEnum     1 flag bit for presence and enum bits for the value
//   ?OptionalStruct   1 flag bit for presence and u32 slots for inner fields
//
// the extra section is a flat u32 array of node indices. an
// IndexRange { start, len } refers to extra[start, start + len].
//
// the string pool is a flat utf8 buffer for strings that cannot be sliced
// directly from the source. it may contain wtf8 encoded lone surrogates.
// the pool length is arbitrary, so sections that follow may be at any
// byte offset; the js decoder uses DataView for reads against them.
//
// a diagnostic entry is variable length and laid out as
//
//   1 byte    severity (0 error, 1 warning, 2 hint, 3 info)
//   4 bytes   span_start
//   4 bytes   span_end
//   4 bytes   message_len
//   n bytes   message text
//   1 byte    has_help flag
//   when has_help is 1
//     4 bytes   help_len
//     n bytes   help text
//   4 bytes   label_count
//   per label
//     4 bytes   start
//     4 bytes   end
//     4 bytes   message_len
//     n bytes   message text

const std = @import("std");
const ast = @import("parser").ast;

/// fixed size header prefixing the buffer. field order defines the wire
/// layout. the serializer writes this struct with `@memcpy` and the
/// decoder reads each field by the u32 index derived from `@offsetOf`.
const Header = extern struct {
    node_count: u32,
    extra_count: u32,
    string_pool_len: u32,
    source_len: u32,
    comment_count: u32,
    line_starts_count: u32,
    diag_count: u32,
    program_index: u32,
    flags: u32,
    /// byte offset of the first non-ASCII byte in `source`, or
    /// `source_len` if the source is entirely ASCII. the decoder uses
    /// this as the boundary above which UTF-8 byte offsets need a
    /// `buildPosMap` walk. positions below it are an identity map.
    first_non_ascii: u32,
};

/// packed ast node entry. `tag` identifies the `ast.NodeData` variant,
/// `flags` holds packed booleans and small enums, and `field1..field8`
/// are u32 data slots assigned to struct fields by the packing rules.
///
/// the *first* IndexRange in a struct uses `field0` (u16 length) plus one
/// u32 slot for start, saving one full slot. every *later* IndexRange
/// uses two consecutive u32 slots for start then length. this only
/// affects structs with two or more IndexRange fields. the comptime
/// validator still enforces the 8 slot and 16 flag bit budget regardless.
/// when ordering fields for density, declare the first IndexRange first.
const PackedNode = extern struct {
    tag: u8,
    _pad0: u8 = 0,
    flags: u16,
    field0: u16,
    _pad1: u16 = 0,
    field1: u32,
    field2: u32,
    field3: u32,
    field4: u32,
    field5: u32,
    field6: u32,
    field7: u32,
    field8: u32,
    span_start: u32,
    span_end: u32,
};

/// Comment entry on the wire. `flags` packs:
///   bit 0     type       (0 line, 1 block)
///   bits 1-2  position   (0 before, 1 after, 2 inside)
///   bit 3     same_line
/// `value_start`/`value_end` is a `String` handle into source or pool.
/// The host node is implicit from the entry's index and the offsets.
const PackedComment = extern struct {
    flags: u8,
    _pad: [3]u8 = .{ 0, 0, 0 },
    value_start: u32,
    value_end: u32,
};

pub const COMMENT_TYPE_BIT: u8 = 0;
pub const COMMENT_POSITION_SHIFT: u8 = 1;
pub const COMMENT_POSITION_MASK: u8 = 0b11 << COMMENT_POSITION_SHIFT;
pub const COMMENT_SAME_LINE_BIT: u8 = 3;

// section sizes.
pub const HEADER_SIZE: u32 = @sizeOf(Header);
pub const NODE_SIZE: u32 = @sizeOf(PackedNode);
pub const COMMENT_SIZE: u32 = @sizeOf(PackedComment);

// `Header` field u32 indices for the decoder.
pub const HDR_NODE_COUNT_U32: u32 = @offsetOf(Header, "node_count") / 4;
pub const HDR_EXTRA_COUNT_U32: u32 = @offsetOf(Header, "extra_count") / 4;
pub const HDR_STRING_POOL_LEN_U32: u32 = @offsetOf(Header, "string_pool_len") / 4;
pub const HDR_SOURCE_LEN_U32: u32 = @offsetOf(Header, "source_len") / 4;
pub const HDR_COMMENT_COUNT_U32: u32 = @offsetOf(Header, "comment_count") / 4;
pub const HDR_LINE_STARTS_COUNT_U32: u32 = @offsetOf(Header, "line_starts_count") / 4;
pub const HDR_DIAG_COUNT_U32: u32 = @offsetOf(Header, "diag_count") / 4;
pub const HDR_PROGRAM_INDEX_U32: u32 = @offsetOf(Header, "program_index") / 4;
pub const HDR_FLAGS_U32: u32 = @offsetOf(Header, "flags") / 4;
pub const HDR_FIRST_NON_ASCII_U32: u32 = @offsetOf(Header, "first_non_ascii") / 4;

// `Header.flags` bit positions.
pub const FLAG_TS: u32 = 1 << 0;
pub const FLAG_ATTACH_COMMENTS: u32 = 1 << 1;

// `PackedNode` byte offsets and u32 indices.
pub const NODE_FLAGS_OFFSET: u8 = @offsetOf(PackedNode, "flags");
pub const NODE_FIELD0_OFFSET: u8 = @offsetOf(PackedNode, "field0");
pub const NODE_HEADER_U32S: u8 = @offsetOf(PackedNode, "field1") / 4;
pub const NODE_SPAN_START_U32: u8 = @offsetOf(PackedNode, "span_start") / 4;
pub const NODE_SPAN_END_U32: u8 = @offsetOf(PackedNode, "span_end") / 4;

// `PackedNode` capacity. counts the u32 data slots and flag bits available
// per node. used by `validateAllNodeLayouts` to reject ast structs that do
// not fit. both values track the struct layout automatically.
pub const NODE_DATA_SLOTS: u8 = NODE_SPAN_START_U32 - NODE_HEADER_U32S;
pub const NODE_FLAG_BITS: u8 = @bitSizeOf(@FieldType(PackedNode, "flags"));

// `PackedComment` byte offsets for the decoder.
pub const COMMENT_FLAGS_OFFSET: u8 = @offsetOf(PackedComment, "flags");
pub const COMMENT_VALUE_START_OFFSET: u8 = @offsetOf(PackedComment, "value_start");
pub const COMMENT_VALUE_END_OFFSET: u8 = @offsetOf(PackedComment, "value_end");

comptime {
    validateAllNodeLayouts();
}

// layout helpers used by the serializer below and by the decoder
// generator at tools/gen_estree_decoder.zig.

/// number of flag bits consumed by field `field_idx` in struct T.
pub fn flagBitCount(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == bool) return 1;
    if (f.type == ?ast.ImportPhase) return 1 + enumBitWidth(ast.ImportPhase);
    if (f.type == ?ast.Hashbang) return 1;
    if (comptime isEnumType(f.type)) return enumBitWidth(f.type);
    if (f.type == ast.NodeIndex or f.type == ast.IndexRange or f.type == ast.String) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// starting flag bit position for field `target` in struct T.
pub fn flagBitForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var bit: u8 = 0;
        for (0..target) |i| bit += flagBitCount(T, i);
        return bit;
    }
}

/// number of u32 slots consumed by field `field_idx` in struct T.
pub fn fieldU32Count(comptime T: type, comptime field_idx: usize) u8 {
    const f = std.meta.fields(T)[field_idx];
    if (f.type == ast.NodeIndex) return 1;
    if (f.type == ast.IndexRange) return if (isFirstRange(T, field_idx)) 1 else 2;
    if (f.type == ast.String) return 2;
    if (f.type == ?ast.Hashbang) return 2;
    if (f.type == bool or f.type == ?ast.ImportPhase or comptime isEnumType(f.type)) return 0;
    @compileError("unsupported field type '" ++ @typeName(f.type) ++ "' in " ++ @typeName(T));
}

/// first u32 slot index for field `target` in struct T.
pub fn u32SlotForField(comptime T: type, comptime target: usize) u8 {
    comptime {
        var slot: u8 = 0;
        for (0..target) |i| slot += fieldU32Count(T, i);
        return slot;
    }
}

/// true if field `target` is the first IndexRange in struct T.
pub fn isFirstRange(comptime T: type, comptime target: usize) bool {
    comptime {
        for (std.meta.fields(T), 0..) |f, i| {
            if (f.type == ast.IndexRange) return i == target;
        }
        return false;
    }
}

/// ceil(log2(n)) where n is the number of enum variants.
pub fn enumBitWidth(comptime E: type) u8 {
    return std.math.log2_int_ceil(usize, @typeInfo(E).@"enum".fields.len);
}

pub fn isEnumType(comptime T: type) bool {
    return @typeInfo(T) == .@"enum";
}

/// total u32 slots used by struct T.
pub fn totalU32Slots(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += fieldU32Count(T, i);
        return total;
    }
}

/// total flag bits used by struct T.
pub fn totalFlagBits(comptime T: type) u8 {
    comptime {
        var total: u8 = 0;
        for (0..std.meta.fields(T).len) |i| total += flagBitCount(T, i);
        return total;
    }
}

fn validateAllNodeLayouts() void {
    @setEvalBranchQuota(10_000);
    for (@typeInfo(ast.NodeData).@"union".fields) |field| {
        const T = field.type;
        if (@typeInfo(T) != .@"struct") continue;
        if (totalU32Slots(T) > NODE_DATA_SLOTS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} u32 slots",
            .{ field.name, NODE_DATA_SLOTS },
        ));
        if (totalFlagBits(T) > NODE_FLAG_BITS) @compileError(std.fmt.comptimePrint(
            "node '{s}' needs more than {d} flag bits",
            .{ field.name, NODE_FLAG_BITS },
        ));
    }
}

// serialization

pub fn bufferSize(tree: *const ast.Tree) usize {
    // fixed part of a diagnostic. severity, span_start, span_end,
    // message_len, has_help, label_count.
    const diag_fixed = 1 + 4 + 4 + 4 + 1 + 4;
    const help_prefix = 4; // help_len
    const label_fixed = 4 + 4 + 4; // start, end, message_len

    var size: usize = HEADER_SIZE +
        tree.nodes.len * NODE_SIZE +
        tree.extras.items.len * 4 +
        tree.strings.extra.items.len +
        tree.node_comment_offsets.len * 4 +
        tree.comments.len * COMMENT_SIZE +
        tree.line_starts.len * 4;

    for (tree.diagnostics.items) |d| {
        size += diag_fixed + d.message.len;
        if (d.help) |h| size += help_prefix + h.len;
        for (d.labels) |lbl| size += label_fixed + lbl.message.len;
    }
    return size;
}

pub fn serializeInto(tree: *const ast.Tree, buf: []u8) usize {
    const string_pool_len: u32 = @intCast(tree.strings.extra.items.len);
    const has_attach = tree.node_comment_offsets.len != 0;

    // header
    var hdr_flags: u32 = 0;
    if (tree.isTs()) hdr_flags |= FLAG_TS;
    if (has_attach) hdr_flags |= FLAG_ATTACH_COMMENTS;

    const hdr = Header{
        .node_count = @intCast(tree.nodes.len),
        .extra_count = @intCast(tree.extras.items.len),
        .string_pool_len = string_pool_len,
        .source_len = @intCast(tree.source.len),
        .comment_count = @intCast(tree.comments.len),
        .line_starts_count = @intCast(tree.line_starts.len),
        .diag_count = @intCast(tree.diagnostics.items.len),
        .program_index = @intFromEnum(tree.root),
        .flags = hdr_flags,
        .first_non_ascii = @intCast(firstNonAsciiOffset(tree.source)),
    };
    @memcpy(buf[0..HEADER_SIZE], std.mem.asBytes(&hdr));
    var pos: usize = HEADER_SIZE;

    // nodes
    const data_items = tree.nodes.items(.data);
    const span_items = tree.nodes.items(.span);
    for (0..hdr.node_count) |i| {
        const n = packNode(data_items[i], span_items[i]);
        @memcpy(buf[pos..][0..NODE_SIZE], std.mem.asBytes(&n));
        pos += NODE_SIZE;
    }

    // extra
    const extra_bytes = std.mem.sliceAsBytes(tree.extras.items);
    @memcpy(buf[pos..][0..extra_bytes.len], extra_bytes);
    pos += extra_bytes.len;

    // string pool
    @memcpy(buf[pos..][0..string_pool_len], tree.strings.extra.items);
    pos += string_pool_len;

    // comment offsets (present only when FLAG_ATTACH_COMMENTS is set)
    const offsets_bytes = std.mem.sliceAsBytes(tree.node_comment_offsets);
    @memcpy(buf[pos..][0..offsets_bytes.len], offsets_bytes);
    pos += offsets_bytes.len;

    // comments
    for (tree.comments) |c| {
        var flags: u8 = 0;
        if (c.type == .block) flags |= 1 << COMMENT_TYPE_BIT;
        flags |= @as(u8, @intFromEnum(c.position)) << COMMENT_POSITION_SHIFT;
        if (c.same_line) flags |= 1 << COMMENT_SAME_LINE_BIT;
        const entry = PackedComment{
            .flags = flags,
            .value_start = c.value.start,
            .value_end = c.value.end,
        };
        @memcpy(buf[pos..][0..COMMENT_SIZE], std.mem.asBytes(&entry));
        pos += COMMENT_SIZE;
    }

    // line starts
    const ls_bytes = std.mem.sliceAsBytes(tree.line_starts);
    @memcpy(buf[pos..][0..ls_bytes.len], ls_bytes);
    pos += ls_bytes.len;

    // diagnostics (variable length)
    for (tree.diagnostics.items) |d| {
        buf[pos] = @intFromEnum(d.severity);
        pos += 1;
        w32(buf, pos, d.span.start);
        pos += 4;
        w32(buf, pos, d.span.end);
        pos += 4;
        w32(buf, pos, @intCast(d.message.len));
        pos += 4;
        @memcpy(buf[pos..][0..d.message.len], d.message);
        pos += d.message.len;
        if (d.help) |h| {
            buf[pos] = 1;
            pos += 1;
            w32(buf, pos, @intCast(h.len));
            pos += 4;
            @memcpy(buf[pos..][0..h.len], h);
            pos += h.len;
        } else {
            buf[pos] = 0;
            pos += 1;
        }
        w32(buf, pos, @intCast(d.labels.len));
        pos += 4;
        for (d.labels) |lbl| {
            w32(buf, pos, lbl.span.start);
            pos += 4;
            w32(buf, pos, lbl.span.end);
            pos += 4;
            w32(buf, pos, @intCast(lbl.message.len));
            pos += 4;
            @memcpy(buf[pos..][0..lbl.message.len], lbl.message);
            pos += lbl.message.len;
        }
    }

    return pos;
}

fn packNode(data: ast.NodeData, span: ast.Span) PackedNode {
    var n: PackedNode = std.mem.zeroes(PackedNode);
    n.span_start = span.start;
    n.span_end = span.end;
    switch (data) {
        inline else => |payload, tag| {
            n.tag = @intFromEnum(tag);
            packPayload(&n, payload);
        },
    }
    return n;
}

fn packPayload(n: *PackedNode, payload: anytype) void {
    const T = @TypeOf(payload);
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const val = @field(payload, f.name);
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            if (val) setFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            setSlot(n, slot, @intFromEnum(val));
        } else if (f.type == ast.IndexRange) {
            if (comptime isFirstRange(T, i)) {
                n.field0 = @intCast(val.len);
                setSlot(n, slot, val.start);
            } else {
                setSlot(n, slot, val.start);
                setSlot(n, slot + 1, @intCast(val.len));
            }
        } else if (f.type == ast.String) {
            setSlot(n, slot, val.start);
            setSlot(n, slot + 1, val.end);
        } else if (comptime isEnumType(f.type)) {
            setFlagBits(n, bit, @intFromEnum(val));
        } else if (f.type == ?ast.ImportPhase) {
            if (val) |v| {
                setFlagBit(n, bit);
                setFlagBits(n, bit + 1, @intFromEnum(v));
            }
        } else if (f.type == ?ast.Hashbang) {
            if (val) |h| {
                setFlagBit(n, bit);
                setSlot(n, slot, h.value.start);
                setSlot(n, slot + 1, h.value.end);
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++
                "' in " ++ @typeName(T));
        }
    }
}

inline fn setFlagBit(n: *PackedNode, comptime bit: u8) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), 1) << @intCast(bit);
}

inline fn setFlagBits(n: *PackedNode, comptime bit: u8, val: anytype) void {
    n.flags |= @as(@FieldType(PackedNode, "flags"), @intCast(val)) << @intCast(bit);
}

inline fn setSlot(n: *PackedNode, comptime slot: u8, val: u32) void {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    @as([*]u32, @ptrCast(&n.field1))[slot] = val;
}

inline fn w32(buf: []u8, pos: usize, val: u32) void {
    std.mem.writeInt(u32, buf[pos..][0..4], val, .little);
}

/// returns the byte offset of the first non-ASCII byte in `source`, or
/// `source.len` if the source is entirely ASCII.
fn firstNonAsciiOffset(source: []const u8) usize {
    const Vec = @Vector(16, u8);
    const hi: Vec = @splat(0x80);
    var i: usize = 0;
    while (i + 16 <= source.len) : (i += 16) {
        if (@reduce(.Or, source[i..][0..16].* & hi) != 0) {
            // non-ASCII somewhere in this 16-byte block. find it.
            for (source[i..][0..16], 0..) |c, k| if (c >= 0x80) return i + k;
            unreachable;
        }
    }
    for (source[i..], 0..) |c, k| if (c >= 0x80) return i + k;
    return source.len;
}

// deserialization. reverses `serializeInto`, comptime-driven by the same
// layout helpers. ignores the diagnostics section, which the codegen path
// doesn't need. the caller passes in the source string, which may be
// empty when every `String` resolves through the pool.

pub const DeserializeError = error{ InvalidBuffer, OutOfMemory };

pub fn deserializeFromBuf(
    allocator: std.mem.Allocator,
    buf: []const u8,
    source: []const u8,
) DeserializeError!ast.Tree {
    if (buf.len < HEADER_SIZE) return error.InvalidBuffer;

    var hdr: Header = undefined;
    @memcpy(std.mem.asBytes(&hdr), buf[0..HEADER_SIZE]);

    var tree = ast.Tree.init(allocator, source);
    errdefer tree.deinit();

    if (hdr.flags & FLAG_TS != 0) tree.lang = .ts;

    var pos: usize = HEADER_SIZE;

    // nodes
    const nodes_bytes: usize = @as(usize, hdr.node_count) * NODE_SIZE;
    if (buf.len < pos + nodes_bytes) return error.InvalidBuffer;
    try tree.nodes.resize(tree.allocator(), hdr.node_count);
    for (0..hdr.node_count) |i| {
        var pn: PackedNode = undefined;
        @memcpy(std.mem.asBytes(&pn), buf[pos..][0..NODE_SIZE]);
        pos += NODE_SIZE;
        tree.nodes.set(i, .{
            .data = unpackNode(pn),
            .span = .{ .start = pn.span_start, .end = pn.span_end },
        });
    }

    // extras
    const extras_bytes: usize = @as(usize, hdr.extra_count) * 4;
    if (buf.len < pos + extras_bytes) return error.InvalidBuffer;
    try tree.extras.resize(tree.allocator(), hdr.extra_count);
    @memcpy(std.mem.sliceAsBytes(tree.extras.items), buf[pos..][0..extras_bytes]);
    pos += extras_bytes;

    // string pool
    if (buf.len < pos + hdr.string_pool_len) return error.InvalidBuffer;
    try tree.strings.extra.resize(tree.allocator(), hdr.string_pool_len);
    @memcpy(tree.strings.extra.items, buf[pos..][0..hdr.string_pool_len]);
    pos += hdr.string_pool_len;

    // comment offsets (present only when FLAG_ATTACH_COMMENTS is set)
    const has_attach = (hdr.flags & FLAG_ATTACH_COMMENTS) != 0;
    if (has_attach) {
        const offsets_count: usize = @as(usize, hdr.node_count) + 1;
        const offsets_bytes = offsets_count * 4;
        if (buf.len < pos + offsets_bytes) return error.InvalidBuffer;
        const offsets = try tree.allocator().alloc(u32, offsets_count);
        @memcpy(std.mem.sliceAsBytes(offsets), buf[pos..][0..offsets_bytes]);
        tree.node_comment_offsets = offsets;
        pos += offsets_bytes;
    }

    // comments
    const comments_bytes: usize = @as(usize, hdr.comment_count) * COMMENT_SIZE;
    if (buf.len < pos + comments_bytes) return error.InvalidBuffer;
    if (hdr.comment_count > 0) {
        const comments = try tree.allocator().alloc(ast.Comment, hdr.comment_count);
        for (0..hdr.comment_count) |i| {
            var ce: PackedComment = undefined;
            @memcpy(std.mem.asBytes(&ce), buf[pos..][0..COMMENT_SIZE]);
            pos += COMMENT_SIZE;
            const pos_bits = (ce.flags & COMMENT_POSITION_MASK) >> COMMENT_POSITION_SHIFT;
            comments[i] = .{
                .type = if ((ce.flags >> COMMENT_TYPE_BIT) & 1 == 0) .line else .block,
                .position = @enumFromInt(pos_bits),
                .same_line = (ce.flags >> COMMENT_SAME_LINE_BIT) & 1 != 0,
                .value = .{ .start = ce.value_start, .end = ce.value_end },
            };
        }
        tree.comments = comments;
    }

    // line starts
    const ls_bytes: usize = @as(usize, hdr.line_starts_count) * 4;
    if (buf.len < pos + ls_bytes) return error.InvalidBuffer;
    if (hdr.line_starts_count > 0) {
        const starts = try tree.allocator().alloc(u32, hdr.line_starts_count);
        @memcpy(std.mem.sliceAsBytes(starts), buf[pos..][0..ls_bytes]);
        tree.line_starts = starts;
        pos += ls_bytes;
    }

    // skip diagnostics. codegen doesn't read them.

    tree.root = @enumFromInt(hdr.program_index);
    return tree;
}

fn unpackNode(p: PackedNode) ast.NodeData {
    @setEvalBranchQuota(100_000);
    inline for (@typeInfo(ast.NodeData).@"union".fields, 0..) |field, tag| {
        if (p.tag == tag) {
            const T = field.type;
            var payload: T = std.mem.zeroes(T);
            unpackPayload(T, p, &payload);
            return @unionInit(ast.NodeData, field.name, payload);
        }
    }
    unreachable;
}

fn unpackPayload(comptime T: type, n: PackedNode, payload: *T) void {
    if (@typeInfo(T) != .@"struct") return;
    if (@typeInfo(T).@"struct".fields.len == 0) return;

    inline for (std.meta.fields(T), 0..) |f, i| {
        const bit = comptime flagBitForField(T, i);
        const slot = comptime u32SlotForField(T, i);

        if (f.type == bool) {
            @field(payload.*, f.name) = readFlagBit(n, bit);
        } else if (f.type == ast.NodeIndex) {
            @field(payload.*, f.name) = @enumFromInt(readSlot(n, slot));
        } else if (f.type == ast.IndexRange) {
            const len: u32 = if (comptime isFirstRange(T, i)) n.field0 else readSlot(n, slot + 1);
            const start: u32 = if (len == 0) 0 else readSlot(n, slot);
            @field(payload.*, f.name) = .{ .start = start, .len = len };
        } else if (f.type == ast.String) {
            @field(payload.*, f.name) = .{
                .start = readSlot(n, slot),
                .end = readSlot(n, slot + 1),
            };
        } else if (comptime isEnumType(f.type)) {
            const bits = comptime enumBitWidth(f.type);
            const mask: u16 = (@as(u16, 1) << @intCast(bits)) - 1;
            const v: u16 = (n.flags >> @intCast(bit)) & mask;
            @field(payload.*, f.name) = @enumFromInt(v);
        } else if (f.type == ?ast.ImportPhase) {
            const present = ((n.flags >> @intCast(bit)) & 1) == 1;
            if (present) {
                const bits = comptime enumBitWidth(ast.ImportPhase);
                const mask: u16 = (@as(u16, 1) << @intCast(bits)) - 1;
                const v: u16 = (n.flags >> @intCast(bit + 1)) & mask;
                @field(payload.*, f.name) = @enumFromInt(v);
            } else {
                @field(payload.*, f.name) = null;
            }
        } else if (f.type == ?ast.Hashbang) {
            const present = ((n.flags >> @intCast(bit)) & 1) == 1;
            if (present) {
                @field(payload.*, f.name) = .{
                    .value = .{ .start = readSlot(n, slot), .end = readSlot(n, slot + 1) },
                };
            } else {
                @field(payload.*, f.name) = null;
            }
        } else {
            @compileError("unsupported field type '" ++ @typeName(f.type) ++
                "' in " ++ @typeName(T));
        }
    }
}

inline fn readFlagBit(n: PackedNode, comptime bit: u8) bool {
    return ((n.flags >> @intCast(bit)) & 1) == 1;
}

inline fn readSlot(n: PackedNode, comptime slot: u8) u32 {
    if (comptime slot >= NODE_DATA_SLOTS) @compileError("slot index out of range");
    const ptr: [*]const u32 = @ptrCast(&n.field1);
    return ptr[slot];
}
