// generates decode.js, a decoder that reads the binary ast buffer passed
// from zig and constructs an estree js object. uses the same comptime layout
// helpers as the serializer in transfer.zig, so the decoder can never drift
// from the format.
//
// two output modes share this file:
//   .parser    the lean decoder shipped with yuku-parser.
//   .analyzer  the yuku-analyzer decoder. nodes are memoized by index
//              (semantic queries and the walked AST share object
//              identity), spans are readable without materializing
//              nodes, and the semantic sections written by
//              transfer/semantic.zig are exposed as generated per-field
//              accessors, so the wire layout never leaks into
//              hand-written js.

const std = @import("std");
const parser = @import("parser");
const ast = parser.ast;
const rt = @import("transfer");
const sem_rt = rt.semantic;

const Symbol = parser.traverser.semantic.Symbol;

const Writer = std.Io.Writer;

pub const Mode = enum { parser, analyzer };

pub fn generate(w: *Writer, mode: Mode) !void {
    try w.writeAll(
        \\// generated by tools/estree/decoder.zig, do not edit
        \\const NULL = -1;
        \\const _td = new TextDecoder("utf-8", { ignoreBOM: true });
        \\
    );
    try writeLookupTables(w);
    if (mode == .analyzer) try writeSemanticConstants(w);
    try writeBuildPosMap(w);
    try writeDecodeOpen(w);
    try writeNodeFunction(w, mode);
    try writeDecodeBody(w, mode);
    switch (mode) {
        .parser => try w.writeAll("export { decode };\n"),
        .analyzer => try w.writeAll("export { decode, SymbolFlags };\n"),
    }
}

// js names for the `Symbol.Flags` bits, TS-checker style. every flag
// field must appear here: the comptime loop below fails the build when
// a new flag is added to the binder without a js name.
const symbol_flag_names = [_]struct { zig: []const u8, js: []const u8 }{
    .{ .zig = "function_scoped_var", .js = "FunctionScopedVariable" },
    .{ .zig = "block_scoped_var", .js = "BlockScopedVariable" },
    .{ .zig = "function", .js = "Function" },
    .{ .zig = "class", .js = "Class" },
    .{ .zig = "regular_enum", .js = "RegularEnum" },
    .{ .zig = "const_enum", .js = "ConstEnum" },
    .{ .zig = "value_module", .js = "ValueModule" },
    .{ .zig = "interface", .js = "Interface" },
    .{ .zig = "type_alias", .js = "TypeAlias" },
    .{ .zig = "type_parameter", .js = "TypeParameter" },
    .{ .zig = "namespace_module", .js = "NamespaceModule" },
    .{ .zig = "import", .js = "Import" },
    .{ .zig = "type_import", .js = "TypeImport" },
    .{ .zig = "const_var", .js = "Const" },
    .{ .zig = "ambient", .js = "Ambient" },
    .{ .zig = "parameter", .js = "Parameter" },
    .{ .zig = "catch_var", .js = "CatchVariable" },
    .{ .zig = "exported", .js = "Exported" },
    .{ .zig = "is_default", .js = "Default" },
};

fn jsFlagName(comptime zig_name: []const u8) []const u8 {
    inline for (symbol_flag_names) |entry| {
        if (comptime std.mem.eql(u8, entry.zig, zig_name)) return entry.js;
    }
    @compileError("Symbol.Flags field '" ++ zig_name ++
        "' has no js name in symbol_flag_names");
}

/// `view[i * stride + column]` js expression for one field of a packed
/// semantic wire struct, rendered at comptime. stride and column come
/// from `@sizeOf`/`@offsetOf`, so the generated index can never drift
/// from the format.
fn cell(
    comptime view: []const u8,
    comptime Packed: type,
    comptime field: []const u8,
) []const u8 {
    return std.fmt.comptimePrint("{s}[i * {d} + {d}]", .{
        view, @sizeOf(Packed) / 4, @offsetOf(Packed, field) / 4,
    });
}

/// `str(start, end)` js expression for a wire string handle stored as
/// adjacent (start, end) columns.
fn strCell(
    comptime view: []const u8,
    comptime Packed: type,
    comptime start_field: []const u8,
    comptime end_field: []const u8,
) []const u8 {
    if (@offsetOf(Packed, end_field) != @offsetOf(Packed, start_field) + 4) {
        @compileError("string handle columns must be adjacent: " ++ start_field);
    }
    return std.fmt.comptimePrint("str({s}, {s})", .{
        cell(view, Packed, start_field), cell(view, Packed, end_field),
    });
}

// emits the shared wire constants for the semantic sections: enum name
// tables and the SymbolFlags bitset, all reflected from the zig types,
// so they cannot drift.
fn writeSemanticConstants(w: *Writer) !void {
    try writeArray(w, "SCOPE_KINDS", &.{
        "global", "module",      "function",       "block",
        "class",  "staticBlock", "expressionName", "tsModule",
    });
    try writeArray(w, "NAME_KINDS", &.{ "named", "star", "none" });
    try writeArray(w, "IMPORT_PHASES", &.{ "source", "defer" });

    try w.writeAll("const SymbolFlags = Object.freeze({\n");
    inline for (@typeInfo(Symbol.Flags).@"struct".fields) |field| {
        if (comptime std.mem.eql(u8, field.name, "_")) continue;
        try w.print("  {s}: 1 << {d},\n", .{
            comptime jsFlagName(field.name),
            @bitOffsetOf(Symbol.Flags, field.name),
        });
    }
    try w.writeAll("});\n");
}

/// the decoder is wrapped in one `decode(buffer, source)` function, so
/// every piece of per call state (u8 and u32 views, srcLen, nodesOff, and
/// so on) lives as a local const. inner helpers (`node`, `nodeArr`,
/// `fnParams`, `_poolDecode`) close over those locals. the decoder is
/// reentrant, owns no module state, and needs no cleanup on exit.
fn writeBuildPosMap(w: *Writer) !void {
    try w.writeAll(
        \\function buildPosMap(src, byteLen, startByte) {
        \\  const m = new Uint32Array(byteLen - startByte + 1);
        \\  const len = src.length;
        \\  let bp = 0, u16p = startByte, i = startByte;
        \\  while (i < len) {
        \\    if (i + 16 <= len) {
        \\      let allAscii = true;
        \\      for (let k = 0; k < 16; k++) {
        \\        if (src.charCodeAt(i + k) >= 0x80) { allAscii = false; break; }
        \\      }
        \\      if (allAscii) {
        \\        for (let k = 0; k < 16; k++) m[bp + k] = u16p + k;
        \\        bp += 16; u16p += 16; i += 16;
        \\        continue;
        \\      }
        \\    }
        \\    const cu = src.charCodeAt(i);
        \\    m[bp] = u16p;
        \\    if (cu < 0x80) { bp++; u16p++; i++; }
        \\    else if (cu < 0x800) { m[bp + 1] = u16p + 1; bp += 2; u16p++; i++; }
        \\    else if (cu < 0xD800 || cu >= 0xE000) {
        \\      m[bp + 1] = u16p + 1; m[bp + 2] = u16p + 1;
        \\      bp += 3; u16p++; i++;
        \\    }
        \\    else {
        \\      m[bp + 1] = u16p + 1; m[bp + 2] = u16p + 2; m[bp + 3] = u16p + 2;
        \\      bp += 4; u16p += 2; i += 2;
        \\    }
        \\  }
        \\  m[byteLen - startByte] = u16p;
        \\  return m;
        \\}
        \\
    );
}

fn writeDecodeOpen(w: *Writer) !void {
    try w.print(
        \\function decode(buffer, source) {{
        \\  const _u8 = new Uint8Array(buffer);
        \\  const aLen = (buffer.byteLength >> 2) << 2;
        \\  const _u32 = new Int32Array(buffer, 0, aLen >> 2);
        \\  const _src = source;
        \\  const _srcLen = _u32[{[u_src]d}];
        \\  const nodeCount = _u32[{[u_nc]d}],
        \\        extraCount = _u32[{[u_ec]d}],
        \\        spLen = _u32[{[u_sp]d}];
        \\  const commentCount = _u32[{[u_cc]d}],
        \\        lineStartsCount = _u32[{[u_ls]d}],
        \\        diagCount = _u32[{[u_dc]d}],
        \\        progIdx = _u32[{[u_pi]d}];
        \\  const attachedCommentCount = _u32[{[u_acc]d}];
        \\  const _flags = _u32[{[u_fl]d}];
        \\  const _isTs = !!(_flags & {[ts]d});
        \\  const _attached = !!(_flags & {[ac]d});
        \\  const _firstNa = _u32[{[u_fna]d}];
        \\  const _nodesOff = {[hdr]d};
        \\  const eOff = _nodesOff + nodeCount * {[size]d};
        \\  const _extraBase = eOff >> 2;
        \\  const _spOff = eOff + extraCount * 4;
        \\  const dv = new DataView(buffer);
        \\  const _aoOff = _spOff + spLen;
        \\  const _acOff = _attached ? _aoOff + (nodeCount + 1) * 4 : _aoOff;
        \\  const _cOff = _acOff + attachedCommentCount * {[acsize]d};
        \\  function _poolDecode(s, e) {{
        \\    const a = _spOff + s - _srcLen, b = _spOff + e - _srcLen;
        \\    let hasEd = false;
        \\    for (let i = a; i < b; i++) if (_u8[i] === 0xED) {{ hasEd = true; break; }}
        \\    if (!hasEd) return _td.decode(_u8.subarray(a, b));
        \\    let r = "";
        \\    for (let i = a; i < b; ) {{
        \\      const c = _u8[i];
        \\      if (c < 0x80) {{ r += String.fromCharCode(c); i++; }}
        \\      else if (c < 0xE0) {{
        \\        r += String.fromCharCode(((c & 0x1F) << 6) | (_u8[i+1] & 0x3F));
        \\        i += 2;
        \\      }}
        \\      else if (c < 0xF0) {{
        \\        r += String.fromCharCode(
        \\          ((c & 0x0F) << 12) | ((_u8[i+1] & 0x3F) << 6) | (_u8[i+2] & 0x3F)
        \\        );
        \\        i += 3;
        \\      }}
        \\      else {{
        \\        r += String.fromCodePoint(
        \\          ((c & 0x07) << 18) | ((_u8[i+1] & 0x3F) << 12) |
        \\            ((_u8[i+2] & 0x3F) << 6) | (_u8[i+3] & 0x3F)
        \\        );
        \\        i += 4;
        \\      }}
        \\    }}
        \\    return r;
        \\  }}
        \\  const pm = _firstNa < _srcLen ? buildPosMap(_src, _srcLen, _firstNa) : null;
        \\  const _p = v => v <= _firstNa ? v : pm[v - _firstNa];
        \\  const str = (s, e) => {{
        \\    if (s === e) return "";
        \\    if (s >= _srcLen) return _poolDecode(s, e);
        \\    if (e <= _firstNa) return _src.slice(s, e);
        \\    const ss = s < _firstNa ? s : pm[s - _firstNa];
        \\    return _src.slice(ss, pm[e - _firstNa]);
        \\  }};
        \\  function nodeArr(s, len) {{
        \\    const r = Array.from({{ length: len }});
        \\    for (let j = 0; j < len; j++) r[j] = node(_u32[_extraBase + s + j]);
        \\    return r;
        \\  }}
        \\  function nodeArrHoles(s, len) {{
        \\    const r = Array.from({{ length: len }});
        \\    for (let j = 0; j < len; j++) {{
        \\      const x = _u32[_extraBase + s + j];
        \\      r[j] = x !== NULL ? node(x) : null;
        \\    }}
        \\    return r;
        \\  }}
        \\  function fnParams(idx) {{
        \\    const po = _nodesOff + idx * {[size]d};
        \\    const len = _u8[po + {[f0]d}] | (_u8[po + {[f01]d}] << 8);
        \\    const pb = po >> 2;
        \\    const iStart = _u32[pb + {[items]d}], rest = _u32[pb + {[rest]d}];
        \\    const p = [];
        \\    for (let j = 0; j < len; j++) p.push(node(_u32[_extraBase + iStart + j]));
        \\    if (rest !== NULL) p.push(node(rest));
        \\    return p;
        \\  }}
        \\
    , .{
        .u_src = rt.HDR_SOURCE_LEN_U32,
        .u_nc = rt.HDR_NODE_COUNT_U32,
        .u_ec = rt.HDR_EXTRA_COUNT_U32,
        .u_sp = rt.HDR_STRING_POOL_LEN_U32,
        .u_cc = rt.HDR_COMMENT_COUNT_U32,
        .u_ls = rt.HDR_LINE_STARTS_COUNT_U32,
        .u_dc = rt.HDR_DIAG_COUNT_U32,
        .u_pi = rt.HDR_PROGRAM_INDEX_U32,
        .u_acc = rt.HDR_ATTACHED_COMMENT_COUNT_U32,
        .u_fl = rt.HDR_FLAGS_U32,
        .u_fna = rt.HDR_FIRST_NON_ASCII_U32,
        .ts = rt.FLAG_TS,
        .ac = rt.FLAG_ATTACHED_COMMENTS,
        .hdr = rt.HEADER_SIZE,
        .size = rt.NODE_SIZE,
        .acsize = rt.ATTACHED_COMMENT_SIZE,
        .f0 = rt.NODE_FIELD0_OFFSET,
        .f01 = rt.NODE_FIELD0_OFFSET + 1,
        .items = comptime u32IndexOf(ast.FormalParameters, "items"),
        .rest = comptime u32IndexOf(ast.FormalParameters, "rest"),
    });
}

fn writeNodeFunction(w: *Writer, mode: Mode) !void {
    try w.print(
        \\  function _attachedCommentsOf(a, e) {{
        \\    const out = Array.from({{ length: e - a }});
        \\    for (let j = a; j < e; j++) {{
        \\      const o = _acOff + j * {[acsize]d};
        \\      const cf = _u8[o + {[ac_fl]d}];
        \\      const vs = dv.getUint32(o + {[ac_vs]d}, true),
        \\            ve = dv.getUint32(o + {[ac_ve]d}, true);
        \\      out[j - a] = {{
        \\        type: (cf & 1) ? "Block" : "Line",
        \\        position: ["before", "after", "inside"][(cf >> 1) & 3],
        \\        sameLine: (cf & 8) !== 0,
        \\        value: str(vs, ve),
        \\      }};
        \\    }}
        \\    return out;
        \\  }}
        \\  function nodeWithComments(i) {{
        \\    const r = _decode(i);
        \\    if (r && r.type !== undefined && r.comments === undefined) {{
        \\      const off = _aoOff + i * 4;
        \\      const a = dv.getUint32(off, true), e = dv.getUint32(off + 4, true);
        \\      if (a !== e) r.comments = _attachedCommentsOf(a, e);
        \\    }}
        \\    return r;
        \\  }}
        \\  function _decode(i) {{
        \\    const o = _nodesOff + i * {[size]d};
        \\    const tag = _u8[o];
        \\    const flags = _u8[o + {[fl]d}] | (_u8[o + {[fl1]d}] << 8);
        \\    const f0 = _u8[o + {[f0]d}] | (_u8[o + {[f01]d}] << 8);
        \\    const b = o >> 2;
        \\    const f1 = _u32[b + {[d0]d}], f2 = _u32[b + {[d1]d}],
        \\          f3 = _u32[b + {[d2]d}], f4 = _u32[b + {[d3]d}],
        \\          f5 = _u32[b + {[d4]d}], f6 = _u32[b + {[d5]d}],
        \\          f7 = _u32[b + {[d6]d}], f8 = _u32[b + {[d7]d}];
        \\    const _ss = _u32[b + {[ss]d}], _se = _u32[b + {[se]d}];
        \\    const start = _ss <= _firstNa ? _ss : pm[_ss - _firstNa];
        \\    const end = _se <= _firstNa ? _se : pm[_se - _firstNa];
        \\    switch (tag) {{
        \\
    , .{
        .size = rt.NODE_SIZE,
        .acsize = rt.ATTACHED_COMMENT_SIZE,
        .ac_fl = rt.ATTACHED_COMMENT_FLAGS_OFFSET,
        .ac_vs = rt.ATTACHED_COMMENT_VALUE_START_OFFSET,
        .ac_ve = rt.ATTACHED_COMMENT_VALUE_END_OFFSET,
        .fl = rt.NODE_FLAGS_OFFSET,
        .fl1 = rt.NODE_FLAGS_OFFSET + 1,
        .f0 = rt.NODE_FIELD0_OFFSET,
        .f01 = rt.NODE_FIELD0_OFFSET + 1,
        .d0 = rt.NODE_HEADER_U32S,
        .d1 = rt.NODE_HEADER_U32S + 1,
        .d2 = rt.NODE_HEADER_U32S + 2,
        .d3 = rt.NODE_HEADER_U32S + 3,
        .d4 = rt.NODE_HEADER_U32S + 4,
        .d5 = rt.NODE_HEADER_U32S + 5,
        .d6 = rt.NODE_HEADER_U32S + 6,
        .d7 = rt.NODE_HEADER_U32S + 7,
        .ss = rt.NODE_SPAN_START_U32,
        .se = rt.NODE_SPAN_END_U32,
    });
    try writeNodeCases(w);
    switch (mode) {
        .parser => try w.writeAll(
            \\    }
            \\  }
            \\  const node = _attached ? nodeWithComments : _decode;
            \\
        ),
        // memoize by node index: a node reached through the AST and the
        // same node handed back by a semantic query are one object. the
        // WeakMap is the reverse direction (node object -> index).
        .analyzer => try w.writeAll(
            \\    }
            \\  }
            \\  const _inner = _attached ? nodeWithComments : _decode;
            \\  const _nodes = Array.from({ length: nodeCount });
            \\  const _nodeIndexes = new WeakMap();
            \\  function node(i) {
            \\    const m = _nodes[i];
            \\    if (m !== undefined) return m;
            \\    const r = _inner(i);
            \\    _nodes[i] = r;
            \\    if (r !== null && typeof r === "object") _nodeIndexes.set(r, i);
            \\    return r;
            \\  }
            \\
        ),
    }
}

// lookup tables

fn writeLookupTables(w: *Writer) !void {
    try writeArray(w, "BINARY_OPS", &.{
        "==", "!=", "===", "!==", "<",  "<=",         ">", ">=",
        "+",  "-",  "*",   "/",   "%",  "**",         "|", "^",
        "&",  "<<", ">>",  ">>>", "in", "instanceof",
    });
    try writeArray(w, "LOGICAL_OPS", &.{ "&&", "||", "??" });
    try writeArray(w, "UNARY_OPS", &.{ "-", "+", "!", "~", "typeof", "void", "delete" });
    try writeArray(w, "UPDATE_OPS", &.{ "++", "--" });
    try writeArray(w, "ASSIGNMENT_OPS", &.{
        "=",   "+=",   "-=", "*=", "/=", "%=",  "**=", "<<=",
        ">>=", ">>>=", "|=", "^=", "&=", "||=", "&&=", "??=",
    });
    try writeArray(w, "VAR_KINDS", &.{ "var", "let", "const", "using", "await using" });
    try writeArray(w, "PROPERTY_KINDS", &.{ "init", "get", "set" });
    try writeArray(w, "METHOD_KINDS", &.{ "constructor", "method", "get", "set" });
    try writeArray(w, "FUNCTION_TYPES", &.{
        "FunctionDeclaration",
        "FunctionExpression",
        "TSDeclareFunction",
        "TSEmptyBodyFunctionExpression",
    });
    try writeArray(w, "CLASS_TYPES", &.{ "ClassDeclaration", "ClassExpression" });
    try writeArray(w, "SEVERITY", &.{ "error", "warning", "hint", "info" });
    try writeArrayRaw(w, "IMPORT_EXPORT_KINDS", &.{ "\"value\"", "\"type\"" });
    try writeArrayRaw(w, "ACCESSIBILITY", &.{
        "null",        "\"public\"",
        "\"private\"", "\"protected\"",
    });
    try writeArrayRaw(w, "TS_TYPE_OPERATORS", &.{
        "\"keyof\"", "\"unique\"", "\"readonly\"",
    });
    try writeArrayRaw(w, "TS_METHOD_SIGNATURE_KINDS", &.{
        "\"method\"", "\"get\"", "\"set\"",
    });
    try writeArrayRaw(w, "TS_MODULE_KINDS", &.{ "\"namespace\"", "\"module\"" });
    // mapped type `?` modifier: absent decodes to `false`.
    try writeArrayRaw(w, "TS_MAPPED_OPTIONAL", &.{ "false", "true", "\"+\"", "\"-\"" });
    // mapped type `readonly` modifier: absent decodes to `null`.
    try writeArrayRaw(w, "TS_MAPPED_READONLY", &.{ "null", "true", "\"+\"", "\"-\"" });
}

fn writeArray(w: *Writer, name: []const u8, items: []const []const u8) !void {
    try w.print("const {s} = [", .{name});
    for (items, 0..) |item, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("\"{s}\"", .{item});
    }
    try w.writeAll("];\n");
}

/// elements written raw (pre quoted strings, or literals such as `null`).
fn writeArrayRaw(w: *Writer, name: []const u8, items: []const []const u8) !void {
    try w.print("const {s} = [", .{name});
    for (items, 0..) |item, i| {
        if (i > 0) try w.writeAll(", ");
        try w.writeAll(item);
    }
    try w.writeAll("];\n");
}

// node cases. for each union variant the generator emits a `case` body.
// custom shapes live in `writeSpecialCase`, everything else goes through
// `writeGenericCase`, a comptime struct to object mapper.

fn writeNodeCases(w: *Writer) !void {
    @setEvalBranchQuota(100_000);
    inline for (@typeInfo(ast.NodeData).@"union".fields, 0..) |field, tag| {
        if (comptime isSpecial(field.name)) {
            try writeSpecialCase(w, field.name, tag);
        } else {
            try writeGenericCase(w, field.name, tag, field.type);
        }
    }
}

fn writeGenericCase(
    w: *Writer,
    comptime name: []const u8,
    comptime tag: usize,
    comptime T: type,
) !void {
    const etype = comptime estreeType(name);
    const has_ts = comptime hasAnyTsField(name, T) or tsExtrasOf(name).len > 0;
    if (!has_ts) {
        try w.print("    case {d}: return {{ type: \"{s}\", start, end", .{ tag, etype });
        try writeStructFields(w, name, T, .all);
        try w.writeAll(" };\n");
        return;
    }
    try w.print("    case {d}: {{ const r = {{ type: \"{s}\", start, end", .{ tag, etype });
    try writeStructFields(w, name, T, .non_ts);
    try w.writeAll(" }; if (_isTs) { ");
    try writeStructFields(w, name, T, .ts_only);
    try writeTsExtras(w, name);
    try w.writeAll("} return r; }\n");
}

const FieldSelection = enum { all, non_ts, ts_only };

fn writeStructFields(
    w: *Writer,
    comptime tag_name: []const u8,
    comptime T: type,
    comptime sel: FieldSelection,
) !void {
    if (@typeInfo(T) != .@"struct") return;
    inline for (std.meta.fields(T), 0..) |f, i| {
        const is_ts = comptime isTsField(tag_name, f.name);
        const include = switch (sel) {
            .all => true,
            .non_ts => !is_ts,
            .ts_only => is_ts,
        };
        if (!include) continue;
        const js = comptime estreeField(tag_name, f.name);
        if (sel == .ts_only) try w.print("r.{s} = ", .{js}) else try w.print(", {s}: ", .{js});
        try writeFieldExpr(w, tag_name, f.name, T, i, f.type);
        if (sel == .ts_only) try w.writeAll("; ");
    }
}

fn writeFieldExpr(
    w: *Writer,
    comptime tag_name: []const u8,
    comptime field_name: []const u8,
    comptime T: type,
    comptime i: usize,
    comptime F: type,
) !void {
    const s = comptime rt.u32SlotForField(T, i) + 1;
    if (F == ast.NodeIndex) {
        try w.print("f{d} !== NULL ? node(f{d}) : null", .{ s, s });
    } else if (F == ast.IndexRange) {
        const fn_name = comptime if (isHoley(tag_name, field_name)) "nodeArrHoles" else "nodeArr";
        if (comptime rt.isFirstRange(T, i)) {
            try w.print("{s}(f{d}, f0)", .{ fn_name, s });
        } else {
            try w.print("{s}(f{d}, f{d})", .{ fn_name, s, s + 1 });
        }
    } else if (F == ast.String) {
        try w.print("str(f{d}, f{d})", .{ s, s + 1 });
    } else if (F == bool) {
        try w.print("!!(flags & {d})", .{comptime flagMaskAt(T, i)});
    } else if (comptime rt.isEnumType(F)) {
        const bit = comptime rt.flagBitForField(T, i);
        const mask = comptime enumMask(F);
        const table = comptime enumTable(F);
        if (bit == 0) {
            try w.print("{s}[flags & {d}]", .{ table, mask });
        } else {
            try w.print("{s}[(flags >> {d}) & {d}]", .{ table, bit, mask });
        }
    } else if (F == ?ast.ImportPhase) {
        const bit = comptime rt.flagBitForField(T, i);
        try w.print(
            "(flags & {d}) ? [\"source\", \"defer\"][(flags >> {d}) & 1] : null",
            .{ @as(u32, 1) << @intCast(bit), bit + 1 },
        );
    } else if (F == ?ast.Hashbang) {
        const bit = comptime rt.flagBitForField(T, i);
        try w.print(
            "(flags & {d}) ? str(f{d}, f{d}) : null",
            .{ @as(u32, 1) << @intCast(bit), s, s + 1 },
        );
    } else {
        @compileError("unsupported field type in decoder: " ++ @typeName(F));
    }
}

// special cases. nodes whose estree shape does not reduce to a struct
// to object mapping. each branch emits a single js `case` line.

fn isSpecial(comptime name: []const u8) bool {
    inline for ([_][]const u8{
        "formal_parameter",
        "formal_parameters",
        "function",
        "arrow_function_expression",
        "program",
        "directive",
        "string_literal",
        "numeric_literal",
        "bigint_literal",
        "boolean_literal",
        "null_literal",
        "regexp_literal",
        "template_element",
        "class",
        "method_definition",
        "property_definition",
        "unary_expression",
        "binding_property",
        "array_pattern",
        "object_pattern",
        "jsx_text",
        "ts_function_type",
        "ts_constructor_type",
        "ts_method_signature",
        "ts_call_signature_declaration",
        "ts_construct_signature_declaration",
        "ts_mapped_type",
        "ts_module_declaration",
        "ts_global_declaration",
        "ts_this_parameter",
    }) |s| if (std.mem.eql(u8, s, name)) return true;
    return false;
}

fn writeSpecialCase(w: *Writer, comptime name: []const u8, comptime tag: usize) !void {
    const eql = std.mem.eql;
    if (comptime eql(u8, name, "formal_parameter")) {
        const sp = comptime slotOf(ast.FormalParameter, "pattern");
        try emit(w, "    case {d}: return node(f{d});", .{ tag, sp });
    } else if (comptime eql(u8, name, "formal_parameters")) {
        try emit(w, "    case {d}: return {{ params: fnParams(i) }};", .{tag});
    } else if (comptime eql(u8, name, "function")) {
        const sid = comptime slotOf(ast.Function, "id");
        const sp = comptime slotOf(ast.Function, "params");
        const sb = comptime slotOf(ast.Function, "body");
        const stp = comptime slotOf(ast.Function, "type_parameters");
        const srt = comptime slotOf(ast.Function, "return_type");
        const bg = comptime flagMask(ast.Function, "generator");
        const ba = comptime flagMask(ast.Function, "async");
        const bd = comptime flagMask(ast.Function, "declare");
        try emit(w,
            \\    case {d}: {{
            \\      const ft = flags & {d};
            \\      const r = {{
            \\        type: FUNCTION_TYPES[ft], start, end,
            \\        id: f{d} !== NULL ? node(f{d}) : null,
            \\        generator: !!(flags & {d}), async: !!(flags & {d}),
            \\        params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\        body: f{d} !== NULL ? node(f{d}) : null,
            \\        expression: false,
            \\      }};
            \\      if (_isTs) {{
            \\        r.typeParameters = f{d} !== NULL ? node(f{d}) : null;
            \\        r.returnType = f{d} !== NULL ? node(f{d}) : null;
            \\        r.declare = !!(flags & {d});
            \\      }}
            \\      return r;
            \\    }}
        , .{
            tag, comptime enumMask(ast.FunctionType),
            sid, sid,
            bg,  ba,
            sp,  sp,
            sb,  sb,
            stp, stp,
            srt, srt,
            bd,
        });
    } else if (comptime eql(u8, name, "arrow_function_expression")) {
        const sp = comptime slotOf(ast.ArrowFunctionExpression, "params");
        const sb = comptime slotOf(ast.ArrowFunctionExpression, "body");
        const stp = comptime slotOf(ast.ArrowFunctionExpression, "type_parameters");
        const srt = comptime slotOf(ast.ArrowFunctionExpression, "return_type");
        const be = comptime flagMask(ast.ArrowFunctionExpression, "expression");
        const ba = comptime flagMask(ast.ArrowFunctionExpression, "async");
        try emit(w,
            \\    case {d}: {{
            \\      const r = {{
            \\        type: "ArrowFunctionExpression", start, end,
            \\        id: null, generator: false, async: !!(flags & {d}),
            \\        params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\        body: node(f{d}), expression: !!(flags & {d}),
            \\      }};
            \\      if (_isTs) {{
            \\        r.typeParameters = f{d} !== NULL ? node(f{d}) : null;
            \\        r.returnType = f{d} !== NULL ? node(f{d}) : null;
            \\      }}
            \\      return r;
            \\    }}
        , .{ tag, ba, sp, sp, sb, be, stp, stp, srt, srt });
    } else if (comptime eql(u8, name, "program")) {
        const sb = comptime slotOf(ast.Program, "body");
        const hs = comptime slotOf(ast.Program, "hashbang");
        // hashbang span includes the leading `#!`. value.start points to the
        // first byte after `#!`, so the node's start is value.start - 2.
        try emit(w,
            \\    case {d}: return {{
            \\      type: "Program", start, end,
            \\      sourceType: (flags & 1) ? "module" : "script",
            \\      hashbang: (flags & {d}) ? {{
            \\        type: "Hashbang",
            \\        start: _p(f{d} - 2), end: _p(f{d}),
            \\        value: str(f{d}, f{d}),
            \\      }} : null,
            \\      body: nodeArr(f{d}, f0),
            \\    }};
        , .{ tag, comptime flagMask(ast.Program, "hashbang"), hs, hs + 1, hs, hs + 1, sb });
    } else if (comptime eql(u8, name, "directive")) {
        const se = comptime slotOf(ast.Directive, "expression");
        const sv = comptime slotOf(ast.Directive, "value");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "ExpressionStatement", start, end,
            \\      expression: node(f{d}), directive: str(f{d}, f{d}),
            \\    }};
        , .{ tag, se, sv, sv + 1 });
    } else if (comptime eql(u8, name, "string_literal")) {
        const sv = comptime slotOf(ast.StringLiteral, "value");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "Literal", start, end,
            \\      value: str(f{d}, f{d}), raw: _src.slice(start, end),
            \\    }};
        , .{ tag, sv, sv + 1 });
    } else if (comptime eql(u8, name, "numeric_literal")) {
        try emit(w,
            \\    case {d}: {{
            \\      const r = _src.slice(start, end);
            \\      const s = r.indexOf("_") === -1 ? r : r.replace(/_/g, "");
            \\      const v = (flags & {d}) === 2 && s[1] !== "o" && s[1] !== "O"
            \\        ? parseInt(s.slice(1), 8)
            \\        : +s;
            \\      return {{
            \\        type: "Literal", start, end,
            \\        value: v === v && isFinite(v) ? v : null,
            \\        raw: r,
            \\      }};
            \\    }}
        , .{ tag, comptime enumMask(ast.NumericLiteral.Kind) });
    } else if (comptime eql(u8, name, "bigint_literal")) {
        const sr = comptime slotOf(ast.BigIntLiteral, "raw");
        try emit(w,
            \\    case {d}: {{
            \\      const r = _src.slice(start, end);
            \\      const d = str(f{d}, f{d}).replace(/_/g, "");
            \\      const v = BigInt(d);
            \\      return {{
            \\        type: "Literal", start, end,
            \\        value: v, raw: r, bigint: v.toString(),
            \\      }};
            \\    }}
        , .{ tag, sr, sr + 1 });
    } else if (comptime eql(u8, name, "boolean_literal")) {
        try emit(w,
            \\    case {d}: {{
            \\      const v = !!(flags & {d});
            \\      return {{
            \\        type: "Literal", start, end,
            \\        value: v, raw: v ? "true" : "false",
            \\      }};
            \\    }}
        , .{ tag, comptime flagMaskAt(ast.BooleanLiteral, 0) });
    } else if (comptime eql(u8, name, "null_literal")) {
        try emit(w,
            \\    case {d}: return {{ type: "Literal", start, end, value: null, raw: "null" }};
        , .{tag});
    } else if (comptime eql(u8, name, "regexp_literal")) {
        const sp = comptime slotOf(ast.RegExpLiteral, "pattern");
        const sf = comptime slotOf(ast.RegExpLiteral, "flags");
        try emit(w,
            \\    case {d}: {{
            \\      const p = str(f{d}, f{d}), fl = str(f{d}, f{d});
            \\      let v = null;
            \\      try {{ v = new RegExp(p, fl); }} catch {{}}
            \\      return {{
            \\        type: "Literal", start, end,
            \\        value: v, raw: "/" + p + "/" + fl,
            \\        regex: {{ pattern: p, flags: fl.split("").sort().join("") }},
            \\      }};
            \\    }}
        , .{ tag, sp, sp + 1, sf, sf + 1 });
    } else if (comptime eql(u8, name, "template_element")) {
        const sc = comptime slotOf(ast.TemplateElement, "cooked");
        try emit(w,
            \\    case {d}: {{
            \\      const raw = _src.slice(start, end).replace(/\r\n?/g, "\n");
            \\      const tl = !!(flags & {d});
            \\      const s = _isTs ? start - 1 : start;
            \\      const e = _isTs ? (tl ? end + 1 : end + 2) : end;
            \\      return {{
            \\        type: "TemplateElement", start: s, end: e,
            \\        value: {{
            \\          raw,
            \\          cooked: (flags & {d}) ? null : str(f{d}, f{d}),
            \\        }},
            \\        tail: tl,
            \\      }};
            \\    }}
        , .{
            tag,
            comptime flagMask(ast.TemplateElement, "tail"),
            comptime flagMask(ast.TemplateElement, "is_cooked_undefined"),
            sc,
            sc + 1,
        });
    } else if (comptime eql(u8, name, "class")) {
        const sd = comptime slotOf(ast.Class, "decorators");
        const si = comptime slotOf(ast.Class, "id");
        const ss = comptime slotOf(ast.Class, "super_class");
        const sb = comptime slotOf(ast.Class, "body");
        const stp = comptime slotOf(ast.Class, "type_parameters");
        const ssta = comptime slotOf(ast.Class, "super_type_arguments");
        const simp = comptime slotOf(ast.Class, "implements");
        try emit(w,
            \\    case {d}: {{
            \\      const r = {{
            \\        type: CLASS_TYPES[flags & {d}], start, end,
            \\        decorators: nodeArr(f{d}, f0),
            \\        id: f{d} !== NULL ? node(f{d}) : null,
            \\        superClass: f{d} !== NULL ? node(f{d}) : null,
            \\        body: node(f{d}),
            \\      }};
            \\      if (_isTs) {{
            \\        r.typeParameters = f{d} !== NULL ? node(f{d}) : null;
            \\        r.superTypeArguments = f{d} !== NULL ? node(f{d}) : null;
            \\        r.implements = nodeArr(f{d}, f{d});
            \\        r.abstract = !!(flags & {d});
            \\        r.declare = !!(flags & {d});
            \\      }}
            \\      return r;
            \\    }}
        , .{
            tag,                                      comptime enumMask(ast.ClassType),
            sd,                                       si,
            si,                                       ss,
            ss,                                       sb,
            stp,                                      stp,
            ssta,                                     ssta,
            simp,                                     simp + 1,
            comptime flagMask(ast.Class, "abstract"), comptime flagMask(ast.Class, "declare"),
        });
    } else if (comptime eql(u8, name, "method_definition")) {
        const M = ast.MethodDefinition;
        const sd = comptime slotOf(M, "decorators");
        const sk = comptime slotOf(M, "key");
        const sv = comptime slotOf(M, "value");
        try emit(w,
            \\    case {d}: {{
            \\      const r = {{
            \\        type: "MethodDefinition", start, end,
            \\        decorators: nodeArr(f{d}, f0),
            \\        key: node(f{d}), value: node(f{d}),
            \\        kind: METHOD_KINDS[flags & {d}],
            \\        computed: !!(flags & {d}), static: !!(flags & {d}),
            \\      }};
            \\      if (_isTs) {{
            \\        r.override = !!(flags & {d});
            \\        r.optional = !!(flags & {d});
            \\        const _abs = !!(flags & {d});
            \\        r.accessibility = ACCESSIBILITY[(flags >> {d}) & {d}];
            \\        if (_abs) r.type = "TSAbstractMethodDefinition";
            \\      }}
            \\      return r;
            \\    }}
        , .{
            tag,
            sd,
            sk,
            sv,
            comptime enumMask(ast.MethodDefinitionKind),
            comptime flagMask(M, "computed"),
            comptime flagMask(M, "static"),
            comptime flagMask(M, "override"),
            comptime flagMask(M, "optional"),
            comptime flagMask(M, "abstract"),
            comptime flagBit(M, "accessibility"),
            comptime enumMask(ast.Accessibility),
        });
    } else if (comptime eql(u8, name, "property_definition")) {
        const P = ast.PropertyDefinition;
        const sd = comptime slotOf(P, "decorators");
        const sk = comptime slotOf(P, "key");
        const sv = comptime slotOf(P, "value");
        const sta = comptime slotOf(P, "type_annotation");
        try emit(w,
            \\    case {d}: {{
            \\      const _acc = !!(flags & {d});
            \\      const r = {{
            \\        type: _acc ? "AccessorProperty" : "PropertyDefinition",
            \\        start, end,
            \\        decorators: nodeArr(f{d}, f0),
            \\        key: node(f{d}),
            \\        value: f{d} !== NULL ? node(f{d}) : null,
            \\        computed: !!(flags & {d}), static: !!(flags & {d}),
            \\      }};
            \\      if (_isTs) {{
            \\        r.typeAnnotation = f{d} !== NULL ? node(f{d}) : null;
            \\        r.declare = !!(flags & {d});
            \\        r.override = !!(flags & {d});
            \\        r.optional = !!(flags & {d});
            \\        r.definite = !!(flags & {d});
            \\        r.readonly = !!(flags & {d});
            \\        const _abs = !!(flags & {d});
            \\        r.accessibility = ACCESSIBILITY[(flags >> {d}) & {d}];
            \\        if (_abs)
            \\          r.type = _acc
            \\            ? "TSAbstractAccessorProperty"
            \\            : "TSAbstractPropertyDefinition";
            \\      }}
            \\      return r;
            \\    }}
        , .{
            tag,
            comptime flagMask(P, "accessor"),
            sd,
            sk,
            sv,
            sv,
            comptime flagMask(P, "computed"),
            comptime flagMask(P, "static"),
            sta,
            sta,
            comptime flagMask(P, "declare"),
            comptime flagMask(P, "override"),
            comptime flagMask(P, "optional"),
            comptime flagMask(P, "definite"),
            comptime flagMask(P, "readonly"),
            comptime flagMask(P, "abstract"),
            comptime flagBit(P, "accessibility"),
            comptime enumMask(ast.Accessibility),
        });
    } else if (comptime eql(u8, name, "unary_expression")) {
        const sa = comptime slotOf(ast.UnaryExpression, "argument");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "UnaryExpression", start, end,
            \\      operator: UNARY_OPS[flags & {d}], prefix: true,
            \\      argument: f{d} !== NULL ? node(f{d}) : null,
            \\    }};
        , .{ tag, comptime enumMask(ast.UnaryOperator), sa, sa });
    } else if (comptime eql(u8, name, "binding_property")) {
        const sk = comptime slotOf(ast.BindingProperty, "key");
        const sv = comptime slotOf(ast.BindingProperty, "value");
        try w.print(
            \\    case {d}: {{
            \\      const r = {{
            \\        type: "Property", start, end,
            \\        kind: "init",
            \\        key: node(f{d}), value: node(f{d}),
            \\        method: false,
            \\        shorthand: !!(flags & {d}),
            \\        computed: !!(flags & {d}),
            \\      }};
        , .{
            tag,
            sk,
            sv,
            comptime flagMask(ast.BindingProperty, "shorthand"),
            comptime flagMask(ast.BindingProperty, "computed"),
        });
        try w.writeAll(" if (_isTs) { ");
        try writeTsExtras(w, "binding_property");
        try w.writeAll("} return r; }\n");
    } else if (comptime eql(u8, name, "array_pattern")) {
        const se = comptime slotOf(ast.ArrayPattern, "elements");
        const sr = comptime slotOf(ast.ArrayPattern, "rest");
        const sdec = comptime slotOf(ast.ArrayPattern, "decorators");
        const sta = comptime slotOf(ast.ArrayPattern, "type_annotation");
        try emit(w,
            \\    case {d}: {{
            \\      const el = nodeArrHoles(f{d}, f0);
            \\      if (f{d} !== NULL) el.push(node(f{d}));
            \\      const r = {{ type: "ArrayPattern", start, end, elements: el }};
            \\      if (_isTs) {{
            \\        r.decorators = nodeArr(f{d}, f{d});
            \\        r.optional = !!(flags & {d});
            \\        r.typeAnnotation = f{d} !== NULL ? node(f{d}) : null;
            \\      }}
            \\      return r;
            \\    }}
        , .{
            tag,  se,       sr,                                              sr,
            sdec, sdec + 1, comptime flagMask(ast.ArrayPattern, "optional"), sta,
            sta,
        });
    } else if (comptime eql(u8, name, "object_pattern")) {
        const sp = comptime slotOf(ast.ObjectPattern, "properties");
        const sr = comptime slotOf(ast.ObjectPattern, "rest");
        const sdec = comptime slotOf(ast.ObjectPattern, "decorators");
        const sta = comptime slotOf(ast.ObjectPattern, "type_annotation");
        try emit(w,
            \\    case {d}: {{
            \\      const pr = nodeArr(f{d}, f0);
            \\      if (f{d} !== NULL) pr.push(node(f{d}));
            \\      const r = {{ type: "ObjectPattern", start, end, properties: pr }};
            \\      if (_isTs) {{
            \\        r.decorators = nodeArr(f{d}, f{d});
            \\        r.optional = !!(flags & {d});
            \\        r.typeAnnotation = f{d} !== NULL ? node(f{d}) : null;
            \\      }}
            \\      return r;
            \\    }}
        , .{
            tag,  sp,       sr,                                               sr,
            sdec, sdec + 1, comptime flagMask(ast.ObjectPattern, "optional"), sta,
            sta,
        });
    } else if (comptime eql(u8, name, "jsx_text")) {
        const sv = comptime slotOf(ast.JSXText, "value");
        try emit(w,
            \\    case {d}: {{
            \\      const t = str(f{d}, f{d});
            \\      return {{ type: "JSXText", start, end, value: t, raw: t }};
            \\    }}
        , .{ tag, sv, sv + 1 });
    } else if (comptime eql(u8, name, "ts_function_type")) {
        const stp = comptime slotOf(ast.TSFunctionType, "type_parameters");
        const sp = comptime slotOf(ast.TSFunctionType, "params");
        const srt = comptime slotOf(ast.TSFunctionType, "return_type");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSFunctionType", start, end,
            \\      typeParameters: f{d} !== NULL ? node(f{d}) : null,
            \\      params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\      returnType: f{d} !== NULL ? node(f{d}) : null,
            \\    }};
        , .{ tag, stp, stp, sp, sp, srt, srt });
    } else if (comptime eql(u8, name, "ts_constructor_type")) {
        const stp = comptime slotOf(ast.TSConstructorType, "type_parameters");
        const sp = comptime slotOf(ast.TSConstructorType, "params");
        const srt = comptime slotOf(ast.TSConstructorType, "return_type");
        const ba = comptime flagMask(ast.TSConstructorType, "abstract");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSConstructorType", start, end,
            \\      abstract: !!(flags & {d}),
            \\      typeParameters: f{d} !== NULL ? node(f{d}) : null,
            \\      params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\      returnType: f{d} !== NULL ? node(f{d}) : null,
            \\    }};
        , .{ tag, ba, stp, stp, sp, sp, srt, srt });
    } else if (comptime eql(u8, name, "ts_method_signature")) {
        const sk = comptime slotOf(ast.TSMethodSignature, "key");
        const stp = comptime slotOf(ast.TSMethodSignature, "type_parameters");
        const sp = comptime slotOf(ast.TSMethodSignature, "params");
        const srt = comptime slotOf(ast.TSMethodSignature, "return_type");
        const kbit = comptime rt.flagBitForField(
            ast.TSMethodSignature,
            fieldIdx(ast.TSMethodSignature, "kind"),
        );
        const kmask = comptime enumMask(ast.TSMethodSignatureKind);
        const bc = comptime flagMask(ast.TSMethodSignature, "computed");
        const bo = comptime flagMask(ast.TSMethodSignature, "optional");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSMethodSignature", start, end,
            \\      key: node(f{d}),
            \\      computed: !!(flags & {d}),
            \\      optional: !!(flags & {d}),
            \\      kind: TS_METHOD_SIGNATURE_KINDS[(flags >> {d}) & {d}],
            \\      typeParameters: f{d} !== NULL ? node(f{d}) : null,
            \\      params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\      returnType: f{d} !== NULL ? node(f{d}) : null,
            \\      accessibility: null, readonly: false, static: false,
            \\    }};
        , .{ tag, sk, bc, bo, kbit, kmask, stp, stp, sp, sp, srt, srt });
    } else if (comptime eql(u8, name, "ts_call_signature_declaration")) {
        const stp = comptime slotOf(ast.TSCallSignatureDeclaration, "type_parameters");
        const sp = comptime slotOf(ast.TSCallSignatureDeclaration, "params");
        const srt = comptime slotOf(ast.TSCallSignatureDeclaration, "return_type");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSCallSignatureDeclaration", start, end,
            \\      typeParameters: f{d} !== NULL ? node(f{d}) : null,
            \\      params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\      returnType: f{d} !== NULL ? node(f{d}) : null,
            \\    }};
        , .{ tag, stp, stp, sp, sp, srt, srt });
    } else if (comptime eql(u8, name, "ts_mapped_type")) {
        const sk = comptime slotOf(ast.TSMappedType, "key");
        const sc = comptime slotOf(ast.TSMappedType, "constraint");
        const snt = comptime slotOf(ast.TSMappedType, "name_type");
        const sta = comptime slotOf(ast.TSMappedType, "type_annotation");
        const bo = comptime flagBit(ast.TSMappedType, "optional");
        const br = comptime flagBit(ast.TSMappedType, "readonly");
        const mo = comptime enumMask(ast.TSMappedTypeModifier);
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSMappedType", start, end,
            \\      key: node(f{d}),
            \\      constraint: node(f{d}),
            \\      nameType: f{d} !== NULL ? node(f{d}) : null,
            \\      typeAnnotation: f{d} !== NULL ? node(f{d}) : null,
            \\      optional: TS_MAPPED_OPTIONAL[(flags >> {d}) & {d}],
            \\      readonly: TS_MAPPED_READONLY[(flags >> {d}) & {d}],
            \\    }};
        , .{ tag, sk, sc, snt, snt, sta, sta, bo, mo, br, mo });
    } else if (comptime eql(u8, name, "ts_construct_signature_declaration")) {
        const stp = comptime slotOf(ast.TSConstructSignatureDeclaration, "type_parameters");
        const sp = comptime slotOf(ast.TSConstructSignatureDeclaration, "params");
        const srt = comptime slotOf(ast.TSConstructSignatureDeclaration, "return_type");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSConstructSignatureDeclaration", start, end,
            \\      typeParameters: f{d} !== NULL ? node(f{d}) : null,
            \\      params: f{d} !== NULL ? fnParams(f{d}) : [],
            \\      returnType: f{d} !== NULL ? node(f{d}) : null,
            \\    }};
        , .{ tag, stp, stp, sp, sp, srt, srt });
    } else if (comptime eql(u8, name, "ts_module_declaration")) {
        const sid = comptime slotOf(ast.TSModuleDeclaration, "id");
        const sb = comptime slotOf(ast.TSModuleDeclaration, "body");
        const kbit = comptime flagBit(ast.TSModuleDeclaration, "kind");
        const kmask = comptime enumMask(ast.TSModuleDeclarationKind);
        const db = comptime flagMask(ast.TSModuleDeclaration, "declare");
        // bodyless forms (`declare module "foo";`) omit the `body` field
        // entirely. this matches the de-facto ESTree convention: oxc,
        // babel, and @typescript-eslint/typescript-estree all drop the
        // key instead of emitting `body: null`.
        try emit(w,
            \\    case {d}: {{
            \\      const r = {{
            \\        type: "TSModuleDeclaration", start, end,
            \\        id: node(f{d}),
            \\        kind: TS_MODULE_KINDS[(flags >> {d}) & {d}],
            \\        declare: !!(flags & {d}),
            \\        global: false,
            \\      }};
            \\      if (f{d} !== NULL) r.body = node(f{d});
            \\      return r;
            \\    }}
        , .{ tag, sid, kbit, kmask, db, sb, sb });
    } else if (comptime eql(u8, name, "ts_global_declaration")) {
        const sid = comptime slotOf(ast.TSGlobalDeclaration, "id");
        const sb = comptime slotOf(ast.TSGlobalDeclaration, "body");
        const db = comptime flagMask(ast.TSGlobalDeclaration, "declare");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "TSModuleDeclaration", start, end,
            \\      id: node(f{d}), body: node(f{d}),
            \\      kind: "global",
            \\      declare: !!(flags & {d}),
            \\      global: true,
            \\    }};
        , .{ tag, sid, sb, db });
    } else if (comptime eql(u8, name, "ts_this_parameter")) {
        // renders as an `Identifier` with the fixed name `this`, matching
        // the @typescript-eslint/typescript-estree convention and the target
        // AST reference. The fixed `name: "this"` is what the encoder keys on
        // to tell a `this`-parameter Identifier apart from a regular one.
        const sta = comptime slotOf(ast.TSThisParameter, "type_annotation");
        try emit(w,
            \\    case {d}: return {{
            \\      type: "Identifier", start, end,
            \\      decorators: [],
            \\      name: "this", optional: false,
            \\      typeAnnotation: f{d} !== NULL ? node(f{d}) : null,
            \\    }};
        , .{ tag, sta, sta });
    }
}

// emits the lazy diagnostics decoder and the returned object
fn writeDecodeBody(w: *Writer, mode: Mode) !void {
    try w.print(
        \\  const lsOff = _cOff + commentCount * {[csize]d};
        \\  const dOff = lsOff + lineStartsCount * 4;
        \\  function _decodeComments() {{
        \\    const out = Array.from({{ length: commentCount }});
        \\    for (let j = 0; j < commentCount; j++) {{
        \\      const o = _cOff + j * {[csize]d};
        \\      const cf = _u8[o + {[c_fl]d}];
        \\      const vs = dv.getUint32(o + {[c_vs]d}, true),
        \\            ve = dv.getUint32(o + {[c_ve]d}, true);
        \\      const ss = dv.getUint32(o + {[c_ss]d}, true),
        \\            se = dv.getUint32(o + {[c_se]d}, true);
        \\      out[j] = {{
        \\        type: (cf & 1) ? "Block" : "Line",
        \\        value: str(vs, ve),
        \\        start: _p(ss),
        \\        end: _p(se),
        \\      }};
        \\    }}
        \\    return out;
        \\  }}
        \\  function _decodeLineStarts() {{
        \\    const out = Array.from({{ length: lineStartsCount }});
        \\    if (_firstNa >= _srcLen) {{
        \\      for (let j = 0; j < lineStartsCount; j++) {{
        \\        out[j] = dv.getUint32(lsOff + j * 4, true);
        \\      }}
        \\      return out;
        \\    }}
        \\    for (let j = 0; j < lineStartsCount; j++) {{
        \\      const v = dv.getUint32(lsOff + j * 4, true);
        \\      out[j] = v < _firstNa ? v : (v >= _srcLen ? pm[pm.length - 1] : pm[v - _firstNa]);
        \\    }}
        \\    return out;
        \\  }}
        \\  function _decodeDiagnostics() {{
        \\    const out = Array.from({{ length: diagCount }});
        \\    let dp = dOff;
        \\    for (let j = 0; j < diagCount; j++) {{
        \\      const sev = SEVERITY[_u8[dp]]; dp++;
        \\      const ds = _p(dv.getUint32(dp, true)); dp += 4;
        \\      const de = _p(dv.getUint32(dp, true)); dp += 4;
        \\      const ml = dv.getUint32(dp, true); dp += 4;
        \\      const msg = _td.decode(_u8.subarray(dp, dp + ml)); dp += ml;
        \\      const hh = _u8[dp]; dp++;
        \\      let help = null;
        \\      if (hh) {{
        \\        const hl = dv.getUint32(dp, true); dp += 4;
        \\        help = _td.decode(_u8.subarray(dp, dp + hl)); dp += hl;
        \\      }}
        \\      const lc = dv.getUint32(dp, true); dp += 4;
        \\      const labels = Array.from({{ length: lc }});
        \\      for (let k = 0; k < lc; k++) {{
        \\        const ls = _p(dv.getUint32(dp, true)); dp += 4;
        \\        const le = _p(dv.getUint32(dp, true)); dp += 4;
        \\        const lml = dv.getUint32(dp, true); dp += 4;
        \\        labels[k] = {{
        \\          start: ls,
        \\          end: le,
        \\          message: _td.decode(_u8.subarray(dp, dp + lml)),
        \\        }};
        \\        dp += lml;
        \\      }}
        \\      out[j] = {{ severity: sev, message: msg, start: ds, end: de, help, labels }};
        \\    }}
        \\    return out;
        \\  }}
        \\
    , .{
        .csize = rt.COMMENT_SIZE,
        .c_fl = rt.COMMENT_FLAGS_OFFSET,
        .c_vs = rt.COMMENT_VALUE_START_OFFSET,
        .c_ve = rt.COMMENT_VALUE_END_OFFSET,
        .c_ss = rt.COMMENT_SPAN_START_OFFSET,
        .c_se = rt.COMMENT_SPAN_END_OFFSET,
    });

    if (mode == .analyzer) try writeSemanticBody(w);

    try w.writeAll(
        \\  let _program, _lineStarts, _diagnostics, _comments;
        \\  function _getLineStarts() {
        \\    if (_lineStarts === undefined) _lineStarts = _decodeLineStarts();
        \\    return _lineStarts;
        \\  }
        \\  return {
        \\    get program() {
        \\      return _program !== undefined ? _program : (_program = node(progIdx));
        \\    },
        \\    get comments() {
        \\      return _comments !== undefined
        \\        ? _comments
        \\        : (_comments = _decodeComments());
        \\    },
        \\    get diagnostics() {
        \\      return _diagnostics !== undefined
        \\        ? _diagnostics
        \\        : (_diagnostics = _decodeDiagnostics());
        \\    },
        \\    get lineStarts() { return _getLineStarts(); },
        \\    locOf(offset) {
        \\      const ls = _getLineStarts();
        \\      let lo = 0, hi = ls.length;
        \\      while (lo < hi) {
        \\        const mid = (lo + hi) >>> 1;
        \\        if (ls[mid] <= offset) lo = mid + 1; else hi = mid;
        \\      }
        \\      return { line: lo, column: offset - ls[lo - 1] };
        \\    },
        \\    locNear(offset, hintLine) {
        \\      const ls = _getLineStarts();
        \\      let i = hintLine - 1;
        \\      if (i < 0) i = 0;
        \\      if (i >= ls.length) i = ls.length - 1;
        \\      if (ls[i] <= offset) {
        \\        while (i + 1 < ls.length && ls[i + 1] <= offset) i++;
        \\      } else {
        \\        while (i > 0 && ls[i] > offset) i--;
        \\      }
        \\      return { line: i + 1, column: offset - ls[i] };
        \\    },
        \\
    );

    if (mode == .analyzer) try w.writeAll(
        \\    nodeOf: node,
        \\    indexOf: (n) => _nodeIndexes.get(n),
        \\    startOf, endOf, str,
        \\    get semantic() { return _semantic(); },
        \\
    );

    try w.writeAll(
        \\  };
        \\}
        \\
    );
}

// emits the analyzer-only decode internals: direct span reads (no node
// materialization) and the lazy `_semantic()` accessor object. the
// section offset is found by skipping the variable-length diagnostics,
// then rounding up to the 4-byte alignment the serializer padded to.
fn writeSemanticBody(w: *Writer) !void {
    try w.print(
        \\  const _nodesU32 = _nodesOff >> 2;
        \\  function startOf(i) {{ return _p(_u32[_nodesU32 + i * {[stride]d} + {[ss]d}]); }}
        \\  function endOf(i) {{ return _p(_u32[_nodesU32 + i * {[stride]d} + {[se]d}]); }}
        \\  let _semView;
        \\  function _semantic() {{
        \\    if (_semView !== undefined) return _semView;
        \\    if (!(_flags & {[flag]d})) return (_semView = null);
        \\    let dp = dOff;
        \\    for (let j = 0; j < diagCount; j++) {{
        \\      dp += 9;
        \\      const ml = dv.getUint32(dp, true); dp += 4 + ml;
        \\      if (_u8[dp++]) {{ const hl = dv.getUint32(dp, true); dp += 4 + hl; }}
        \\      const lc = dv.getUint32(dp, true); dp += 4;
        \\      for (let k = 0; k < lc; k++) {{
        \\        dp += 8;
        \\        const lml = dv.getUint32(dp, true); dp += 4 + lml;
        \\      }}
        \\    }}
        \\    let o = ((dp + 3) & ~3) >> 2;
        \\    const scopeCount = _u32[o], symbolCount = _u32[o + 1],
        \\          referenceCount = _u32[o + 2], declNodeCount = _u32[o + 3],
        \\          importCount = _u32[o + 4], exportCount = _u32[o + 5];
        \\    o += {[sub]d};
        \\    const scopes = _u32.subarray(o, o + scopeCount * {[scope]d});
        \\    o += scopeCount * {[scope]d};
        \\    const symbols = _u32.subarray(o, o + symbolCount * {[symbol]d});
        \\    o += symbolCount * {[symbol]d};
        \\    const declNodes = _u32.subarray(o, o + declNodeCount);
        \\    o += declNodeCount;
        \\    const references = _u32.subarray(o, o + referenceCount * {[reference]d});
        \\    o += referenceCount * {[reference]d};
        \\    const imports = _u32.subarray(o, o + importCount * {[import]d});
        \\    o += importCount * {[import]d};
        \\    const exports = _u32.subarray(o, o + exportCount * {[expt]d});
        \\    o += exportCount * {[expt]d};
        \\
    , .{
        .stride = rt.NODE_SIZE / 4,
        .ss = rt.NODE_SPAN_START_U32,
        .se = rt.NODE_SPAN_END_U32,
        .flag = rt.FLAG_SEMANTIC,
        .sub = sem_rt.SUBHEADER_SIZE / 4,
        .scope = sem_rt.SCOPE_SIZE / 4,
        .symbol = sem_rt.SYMBOL_SIZE / 4,
        .reference = sem_rt.REFERENCE_SIZE / 4,
        .import = sem_rt.IMPORT_SIZE / 4,
        .expt = sem_rt.EXPORT_SIZE / 4,
    });
    try writeSemanticAccessors(w);
    try w.writeAll(
        \\  }
        \\
    );
}

// emits the accessor groups returned by `_semantic()`: one function per
// wire field, every stride, column, and bit position folded in from the
// packed structs at generation time. the hand-written js layer reads
// semantics exclusively through these, so it never sees the layout.
// `*Id` accessors return row ids with the none sentinel mapped to null.
fn writeSemanticAccessors(w: *Writer) !void {
    const Scope = sem_rt.PackedScope;
    const Sym = sem_rt.PackedSymbol;
    const Ref = sem_rt.PackedReference;
    const Imp = sem_rt.PackedImport;
    const Exp = sem_rt.PackedExport;
    try w.writeAll(
        \\    const _id = (v) => v === NULL ? null : v;
        \\    return (_semView = {
        \\
    );
    try w.print(
        \\      scope: {{
        \\        count: scopeCount,
        \\        kind: (i) => SCOPE_KINDS[{[bits]s} & {[kmask]d}],
        \\        strict: (i) => (({[bits]s} >> {[strict]d}) & 1) !== 0,
        \\        node: (i) => node({[n]s}),
        \\        nodeIndex: (i) => {[n]s},
        \\        parentId: (i) => _id({[p]s}),
        \\        hoistTargetId: (i) => {[h]s},
        \\        start: (i) => startOf({[n]s}),
        \\        end: (i) => endOf({[n]s}),
        \\      }},
        \\
    , .{
        .bits = comptime cell("scopes", Scope, "bits"),
        .kmask = sem_rt.SCOPE_KIND_MASK,
        .strict = sem_rt.SCOPE_STRICT_BIT,
        .n = comptime cell("scopes", Scope, "node"),
        .p = comptime cell("scopes", Scope, "parent"),
        .h = comptime cell("scopes", Scope, "hoist_target"),
    });
    try w.print(
        \\      symbol: {{
        \\        count: symbolCount,
        \\        name: (i) => {[name]s},
        \\        flags: (i) => {[flags]s},
        \\        scopeId: (i) => {[scope]s},
        \\        declCount: (i) => {[dlen]s},
        \\        declNode: (i, j) => node(declNodes[{[dstart]s} + j]),
        \\        declNodeIndex: (i, j) => declNodes[{[dstart]s} + j],
        \\      }},
        \\
    , .{
        .name = comptime strCell("symbols", Sym, "name_start", "name_end"),
        .flags = comptime cell("symbols", Sym, "flags"),
        .scope = comptime cell("symbols", Sym, "scope"),
        .dlen = comptime cell("symbols", Sym, "decls_len"),
        .dstart = comptime cell("symbols", Sym, "decls_start"),
    });
    try w.print(
        \\      reference: {{
        \\        count: referenceCount,
        \\        name: (i) => {[name]s},
        \\        scopeId: (i) => {[scope]s},
        \\        node: (i) => node({[n]s}),
        \\        nodeIndex: (i) => {[n]s},
        \\        kind: (i) => IMPORT_EXPORT_KINDS[({[bits]s} >> {[tbit]d}) & 1],
        \\        isWrite: (i) => (({[bits]s} >> {[wbit]d}) & 1) !== 0,
        \\        symbolId: (i) => _id({[sym]s}),
        \\        start: (i) => startOf({[n]s}),
        \\        end: (i) => endOf({[n]s}),
        \\      }},
        \\
    , .{
        .name = comptime strCell("references", Ref, "name_start", "name_end"),
        .scope = comptime cell("references", Ref, "scope"),
        .n = comptime cell("references", Ref, "node"),
        .bits = comptime cell("references", Ref, "bits"),
        .tbit = sem_rt.REFERENCE_TYPE_BIT,
        .wbit = sem_rt.REFERENCE_WRITE_BIT,
        .sym = comptime cell("references", Ref, "symbol"),
    });
    try w.print(
        \\      import: {{
        \\        count: importCount,
        \\        symbolId: (i) => _id({[sym]s}),
        \\        nameKind: (i) => NAME_KINDS[{[bits]s} & {[nkmask]d}],
        \\        name: (i) => {[name]s},
        \\        specifier: (i) => {[spec]s},
        \\        typeOnly: (i) => (({[bits]s} >> {[tbit]d}) & 1) !== 0,
        \\        phase: (i) =>
        \\          ({[bits]s} >> {[hpbit]d}) & 1
        \\            ? IMPORT_PHASES[({[bits]s} >> {[pbit]d}) & 1]
        \\            : null,
        \\        node: (i) => node({[n]s}),
        \\      }},
        \\
    , .{
        .sym = comptime cell("imports", Imp, "symbol"),
        .bits = comptime cell("imports", Imp, "bits"),
        .nkmask = sem_rt.IMPORT_NAME_KIND_MASK,
        .name = comptime strCell("imports", Imp, "name_start", "name_end"),
        .spec = comptime strCell("imports", Imp, "specifier_start", "specifier_end"),
        .tbit = sem_rt.IMPORT_TYPE_BIT,
        .hpbit = sem_rt.IMPORT_HAS_PHASE_BIT,
        .pbit = sem_rt.IMPORT_PHASE_BIT,
        .n = comptime cell("imports", Imp, "node"),
    });
    try w.print(
        \\      export: {{
        \\        count: exportCount,
        \\        nameKind: (i) => NAME_KINDS[{[bits]s} & {[nkmask]d}],
        \\        fromKind: (i) => NAME_KINDS[({[bits]s} >> {[fkshift]d}) & {[nkmask]d}],
        \\        typeOnly: (i) => (({[bits]s} >> {[tbit]d}) & 1) !== 0,
        \\        name: (i) => {[name]s},
        \\        fromName: (i) => {[fname]s},
        \\        specifier: (i) => {[spec]s},
        \\        symbolId: (i) => _id({[sym]s}),
        \\        node: (i) => node({[n]s}),
        \\      }},
        \\    }});
        \\
    , .{
        .bits = comptime cell("exports", Exp, "bits"),
        .nkmask = sem_rt.EXPORT_NAME_KIND_MASK,
        .fkshift = sem_rt.EXPORT_FROM_KIND_SHIFT,
        .tbit = sem_rt.EXPORT_TYPE_BIT,
        .name = comptime strCell("exports", Exp, "name_start", "name_end"),
        .fname = comptime strCell("exports", Exp, "from_name_start", "from_name_end"),
        .spec = comptime strCell("exports", Exp, "specifier_start", "specifier_end"),
        .sym = comptime cell("exports", Exp, "symbol"),
        .n = comptime cell("exports", Exp, "node"),
    });
}

// per node metadata.

/// typescript only fields, grouped by node. emitted only when the source
/// language is typescript.
const TS_FIELDS = [_]struct { node: []const u8, fields: []const []const u8 }{
    .{ .node = "variable_declaration", .fields = &.{"declare"} },
    .{ .node = "variable_declarator", .fields = &.{"definite"} },
    .{ .node = "function", .fields = &.{ "type_parameters", "return_type" } },
    .{ .node = "arrow_function_expression", .fields = &.{ "type_parameters", "return_type" } },
    .{ .node = "class", .fields = &.{
        "type_parameters",
        "super_type_arguments",
        "implements",
        "abstract",
        "declare",
    } },
    .{ .node = "method_definition", .fields = &.{
        "override",
        "optional",
        "abstract",
        "accessibility",
    } },
    .{ .node = "property_definition", .fields = &.{
        "type_annotation",
        "declare",
        "override",
        "optional",
        "definite",
        "readonly",
        "abstract",
        "accessibility",
    } },
    .{ .node = "call_expression", .fields = &.{"type_arguments"} },
    .{ .node = "new_expression", .fields = &.{"type_arguments"} },
    .{ .node = "tagged_template_expression", .fields = &.{"type_arguments"} },
    .{ .node = "jsx_opening_element", .fields = &.{"type_arguments"} },
    .{ .node = "import_declaration", .fields = &.{"import_kind"} },
    .{ .node = "import_specifier", .fields = &.{"import_kind"} },
    .{ .node = "export_named_declaration", .fields = &.{"export_kind"} },
    .{ .node = "export_all_declaration", .fields = &.{"export_kind"} },
    .{ .node = "export_specifier", .fields = &.{"export_kind"} },
    .{ .node = "binding_rest_element", .fields = &.{
        "decorators",
        "optional",
        "type_annotation",
    } },
    .{ .node = "binding_identifier", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "assignment_pattern", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "object_pattern", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "array_pattern", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "ts_index_signature", .fields = &.{"static"} },
};

fn isTsField(comptime tag: []const u8, comptime field: []const u8) bool {
    for (TS_FIELDS) |e| {
        if (!std.mem.eql(u8, e.node, tag)) continue;
        for (e.fields) |f| if (std.mem.eql(u8, f, field)) return true;
    }
    return false;
}

fn hasAnyTsField(comptime tag: []const u8, comptime T: type) bool {
    if (@typeInfo(T) != .@"struct") return false;
    inline for (std.meta.fields(T)) |f| if (comptime isTsField(tag, f.name)) return true;
    return false;
}

/// ts estree constant fields with no zig ast counterpart. emitted
/// alongside any struct backed ts fields inside the `if (_isTs) { ... }`
/// branch. values are raw js expressions such as `"null"`, `"false"`, `"[]"`.
const Extra = struct { field: []const u8, value: []const u8 };

const IDENT_EXTRAS = [_]Extra{
    .{ .field = "decorators", .value = "[]" },
    .{ .field = "optional", .value = "false" },
    .{ .field = "typeAnnotation", .value = "null" },
};

const TS_EXTRAS = [_]struct { node: []const u8, extras: []const Extra }{
    // identifier like nodes carry no backing decorators, optional, or typeAnnotation.
    .{ .node = "identifier_reference", .extras = &IDENT_EXTRAS },
    .{ .node = "identifier_name", .extras = &IDENT_EXTRAS },
    .{ .node = "label_identifier", .extras = &IDENT_EXTRAS },
    // `optional` is always false on properties, no syntax sets it to true.
    .{ .node = "binding_property", .extras = &.{.{ .field = "optional", .value = "false" }} },
    .{ .node = "object_property", .extras = &.{.{ .field = "optional", .value = "false" }} },
    .{ .node = "expression_statement", .extras = &.{.{ .field = "directive", .value = "null" }} },
    .{ .node = "binding_rest_element", .extras = &.{.{ .field = "value", .value = "null" }} },
    .{ .node = "export_default_declaration", .extras = &.{
        .{ .field = "exportKind", .value = "\"value\"" },
    } },
    // ts signature nodes carry constant estree fields with no backing zig storage.
    .{ .node = "ts_property_signature", .extras = &.{
        .{ .field = "accessibility", .value = "null" },
        .{ .field = "static", .value = "false" },
    } },
    .{ .node = "ts_index_signature", .extras = &.{.{ .field = "accessibility", .value = "null" }} },
    // constructor parameter properties cannot be static; the field is a
    // fixed estree convention with no backing zig storage.
    .{ .node = "ts_parameter_property", .extras = &.{
        .{ .field = "static", .value = "false" },
    } },
};

fn tsExtrasOf(comptime name: []const u8) []const Extra {
    inline for (TS_EXTRAS) |e| {
        if (comptime std.mem.eql(u8, e.node, name)) return e.extras;
    }
    return &.{};
}

fn writeTsExtras(w: *Writer, comptime name: []const u8) !void {
    inline for (comptime tsExtrasOf(name)) |e| {
        try w.print("r.{s} = {s}; ", .{ e.field, e.value });
    }
}

fn estreeType(comptime name: []const u8) []const u8 {
    const overrides = .{
        .{ "function_body", "BlockStatement" },
        .{ "binding_rest_element", "RestElement" },
        .{ "object_property", "Property" },
        .{ "identifier_reference", "Identifier" },
        .{ "binding_identifier", "Identifier" },
        .{ "identifier_name", "Identifier" },
        .{ "label_identifier", "Identifier" },
        // snake to pascal would produce "Bigint", typescript uses "BigInt".
        .{ "ts_bigint_keyword", "TSBigIntKeyword" },
        // snake to pascal would produce "Jsdoc...", typescript uses "JSDoc...".
        .{ "ts_jsdoc_nullable_type", "TSJSDocNullableType" },
        .{ "ts_jsdoc_non_nullable_type", "TSJSDocNonNullableType" },
        .{ "ts_jsdoc_unknown_type", "TSJSDocUnknownType" },
    };
    inline for (overrides) |o| if (comptime std.mem.eql(u8, name, o[0])) return o[1];
    if (comptime std.mem.startsWith(u8, name, "jsx_")) {
        return "JSX" ++ snakeConvert(name[4..], true);
    }
    if (comptime std.mem.startsWith(u8, name, "ts_")) return "TS" ++ snakeConvert(name[3..], true);
    return snakeConvert(name, true);
}

fn estreeField(comptime tag: []const u8, comptime field: []const u8) []const u8 {
    if (comptime std.mem.eql(u8, tag, "variable_declaration") and
        std.mem.eql(u8, field, "declarators")) return "declarations";
    // `const` is a zig keyword, so the TSEnumDeclaration field is named
    // `is_const` in the ast. estree renders it as the bare `const` key.
    if (comptime std.mem.eql(u8, tag, "ts_enum_declaration") and
        std.mem.eql(u8, field, "is_const")) return "const";
    return snakeConvert(field, false);
}

/// array fields that allow holes. sparse elements become `null` in estree.
fn isHoley(comptime tag: []const u8, comptime field: []const u8) bool {
    return std.mem.eql(u8, tag, "array_expression") and std.mem.eql(u8, field, "elements");
}

// comptime utilities

fn emit(w: *Writer, comptime fmt: []const u8, args: anytype) !void {
    try w.print(fmt, args);
    try w.writeByte('\n');
}

fn fieldIdx(comptime T: type, comptime name: []const u8) comptime_int {
    return std.meta.fieldIndex(T, name) orelse
        @compileError("field '" ++ name ++ "' not found in " ++ @typeName(T));
}

/// u32 slot number for use as `f{N}` in the generated js. slot 0 is the
/// header `f0`. slots 1 and up come from `_u32[b + 2..]`, hence the `+ 1`.
fn slotOf(comptime T: type, comptime field: []const u8) u32 {
    return rt.u32SlotForField(T, fieldIdx(T, field)) + 1;
}

/// raw u32 index, already includes the header offset. use in `_u32[pb + N]`.
fn u32IndexOf(comptime T: type, comptime field: []const u8) u32 {
    return rt.u32SlotForField(T, fieldIdx(T, field)) + rt.NODE_HEADER_U32S;
}

fn flagBit(comptime T: type, comptime field: []const u8) u32 {
    return rt.flagBitForField(T, fieldIdx(T, field));
}

fn flagMask(comptime T: type, comptime field: []const u8) u32 {
    return flagMaskAt(T, fieldIdx(T, field));
}

fn flagMaskAt(comptime T: type, comptime i: usize) u32 {
    return @as(u32, 1) << @intCast(rt.flagBitForField(T, i));
}

fn enumMask(comptime E: type) u32 {
    return (@as(u32, 1) << @intCast(rt.enumBitWidth(E))) - 1;
}

fn enumTable(comptime E: type) []const u8 {
    if (E == ast.BinaryOperator) return "BINARY_OPS";
    if (E == ast.LogicalOperator) return "LOGICAL_OPS";
    if (E == ast.UnaryOperator) return "UNARY_OPS";
    if (E == ast.UpdateOperator) return "UPDATE_OPS";
    if (E == ast.AssignmentOperator) return "ASSIGNMENT_OPS";
    if (E == ast.VariableKind) return "VAR_KINDS";
    if (E == ast.PropertyKind) return "PROPERTY_KINDS";
    if (E == ast.MethodDefinitionKind) return "METHOD_KINDS";
    if (E == ast.FunctionType) return "FUNCTION_TYPES";
    if (E == ast.ClassType) return "CLASS_TYPES";
    if (E == ast.ImportOrExportKind) return "IMPORT_EXPORT_KINDS";
    if (E == ast.Accessibility) return "ACCESSIBILITY";
    if (E == ast.TSTypeOperatorKind) return "TS_TYPE_OPERATORS";
    if (E == ast.TSMethodSignatureKind) return "TS_METHOD_SIGNATURE_KINDS";
    if (E == ast.TSModuleDeclarationKind) return "TS_MODULE_KINDS";
    @compileError("no lookup table for enum");
}

fn snakeConvert(comptime name: []const u8, comptime pascal: bool) []const u8 {
    comptime {
        var result: [name.len]u8 = undefined;
        var len: usize = 0;
        var cap = pascal;
        for (name) |c| {
            if (c == '_') {
                cap = true;
            } else {
                result[len] = if (cap) std.ascii.toUpper(c) else c;
                cap = false;
                len += 1;
            }
        }
        const final = result[0..len].*;
        return &final;
    }
}
