// generated by tools/estree/decoder.zig, do not edit
const NULL = -1;
const _td = new TextDecoder("utf-8", { ignoreBOM: true });
const BINARY_OPS = ["==", "!=", "===", "!==", "<", "<=", ">", ">=", "+", "-", "*", "/", "%", "**", "|", "^", "&", "<<", ">>", ">>>", "in", "instanceof"];
const LOGICAL_OPS = ["&&", "||", "??"];
const UNARY_OPS = ["-", "+", "!", "~", "typeof", "void", "delete"];
const UPDATE_OPS = ["++", "--"];
const ASSIGNMENT_OPS = ["=", "+=", "-=", "*=", "/=", "%=", "**=", "<<=", ">>=", ">>>=", "|=", "^=", "&=", "||=", "&&=", "??="];
const VAR_KINDS = ["var", "let", "const", "using", "await using"];
const PROPERTY_KINDS = ["init", "get", "set"];
const METHOD_KINDS = ["constructor", "method", "get", "set"];
const FUNCTION_TYPES = ["FunctionDeclaration", "FunctionExpression", "TSDeclareFunction", "TSEmptyBodyFunctionExpression"];
const CLASS_TYPES = ["ClassDeclaration", "ClassExpression"];
const SEVERITY = ["error", "warning", "hint", "info"];
const IMPORT_EXPORT_KINDS = ["value", "type"];
const ACCESSIBILITY = [null, "public", "private", "protected"];
const TS_TYPE_OPERATORS = ["keyof", "unique", "readonly"];
const TS_METHOD_SIGNATURE_KINDS = ["method", "get", "set"];
const TS_MODULE_KINDS = ["namespace", "module"];
const TS_MAPPED_OPTIONAL = [false, true, "+", "-"];
const TS_MAPPED_READONLY = [null, true, "+", "-"];
const CHILD_KEYS = Object.create(null);
function _ck(type, keys) {
  const prev = CHILD_KEYS[type];
  if (prev === undefined) CHILD_KEYS[type] = keys;
  else for (const k of keys) if (!prev.includes(k)) prev.push(k);
}
_ck("SequenceExpression", ["expressions"]);
_ck("ParenthesizedExpression", ["expression"]);
_ck("ArrowFunctionExpression", ["params", "body", "typeParameters", "returnType"]);
_ck("FunctionDeclaration", ["id", "params", "body", "typeParameters", "returnType"]);
_ck("FunctionExpression", ["id", "params", "body", "typeParameters", "returnType"]);
_ck("TSDeclareFunction", ["id", "params", "body", "typeParameters", "returnType"]);
_ck("TSEmptyBodyFunctionExpression", ["id", "params", "body", "typeParameters", "returnType"]);
_ck("BlockStatement", ["body"]);
_ck("BlockStatement", ["body"]);
_ck("BinaryExpression", ["left", "right"]);
_ck("LogicalExpression", ["left", "right"]);
_ck("ConditionalExpression", ["test", "consequent", "alternate"]);
_ck("UnaryExpression", ["argument"]);
_ck("UpdateExpression", ["argument"]);
_ck("AssignmentExpression", ["left", "right"]);
_ck("ArrayExpression", ["elements"]);
_ck("ObjectExpression", ["properties"]);
_ck("SpreadElement", ["argument"]);
_ck("Property", ["key", "value"]);
_ck("MemberExpression", ["object", "property"]);
_ck("CallExpression", ["callee", "arguments", "typeArguments"]);
_ck("ChainExpression", ["expression"]);
_ck("TaggedTemplateExpression", ["tag", "quasi", "typeArguments"]);
_ck("NewExpression", ["callee", "arguments", "typeArguments"]);
_ck("AwaitExpression", ["argument"]);
_ck("YieldExpression", ["argument"]);
_ck("MetaProperty", ["meta", "property"]);
_ck("Decorator", ["expression"]);
_ck("ClassDeclaration", ["decorators", "id", "superClass", "body", "typeParameters", "superTypeArguments", "implements"]);
_ck("ClassExpression", ["decorators", "id", "superClass", "body", "typeParameters", "superTypeArguments", "implements"]);
_ck("ClassBody", ["body"]);
_ck("MethodDefinition", ["decorators", "key", "value"]);
_ck("TSAbstractMethodDefinition", ["decorators", "key", "value"]);
_ck("PropertyDefinition", ["decorators", "key", "value", "typeAnnotation"]);
_ck("AccessorProperty", ["decorators", "key", "value", "typeAnnotation"]);
_ck("TSAbstractPropertyDefinition", ["decorators", "key", "value", "typeAnnotation"]);
_ck("TSAbstractAccessorProperty", ["decorators", "key", "value", "typeAnnotation"]);
_ck("StaticBlock", ["body"]);
_ck("Super", []);
_ck("Literal", []);
_ck("Literal", []);
_ck("Literal", []);
_ck("Literal", []);
_ck("Literal", []);
_ck("ThisExpression", []);
_ck("Literal", []);
_ck("TemplateLiteral", ["quasis", "expressions"]);
_ck("TemplateElement", []);
_ck("Identifier", []);
_ck("PrivateIdentifier", []);
_ck("Identifier", ["decorators", "typeAnnotation"]);
_ck("Identifier", []);
_ck("Identifier", []);
_ck("ExpressionStatement", ["expression"]);
_ck("IfStatement", ["test", "consequent", "alternate"]);
_ck("SwitchStatement", ["discriminant", "cases"]);
_ck("SwitchCase", ["test", "consequent"]);
_ck("ForStatement", ["init", "test", "update", "body"]);
_ck("ForInStatement", ["left", "right", "body"]);
_ck("ForOfStatement", ["left", "right", "body"]);
_ck("WhileStatement", ["test", "body"]);
_ck("DoWhileStatement", ["body", "test"]);
_ck("BreakStatement", ["label"]);
_ck("ContinueStatement", ["label"]);
_ck("LabeledStatement", ["label", "body"]);
_ck("WithStatement", ["object", "body"]);
_ck("ReturnStatement", ["argument"]);
_ck("ThrowStatement", ["argument"]);
_ck("TryStatement", ["block", "handler", "finalizer"]);
_ck("CatchClause", ["param", "body"]);
_ck("DebuggerStatement", []);
_ck("EmptyStatement", []);
_ck("VariableDeclaration", ["declarations"]);
_ck("VariableDeclarator", ["id", "init"]);
_ck("ExpressionStatement", ["expression"]);
_ck("AssignmentPattern", ["left", "right", "decorators", "typeAnnotation"]);
_ck("RestElement", ["argument", "decorators", "typeAnnotation"]);
_ck("ArrayPattern", ["decorators", "elements", "typeAnnotation"]);
_ck("ObjectPattern", ["decorators", "properties", "typeAnnotation"]);
_ck("Property", ["key", "value"]);
_ck("Program", ["hashbang", "body"]);
_ck("ImportExpression", ["source", "options"]);
_ck("ImportDeclaration", ["specifiers", "source", "attributes"]);
_ck("ImportSpecifier", ["imported", "local"]);
_ck("ImportDefaultSpecifier", ["local"]);
_ck("ImportNamespaceSpecifier", ["local"]);
_ck("ImportAttribute", ["key", "value"]);
_ck("ExportNamedDeclaration", ["declaration", "specifiers", "source", "attributes"]);
_ck("ExportDefaultDeclaration", ["declaration"]);
_ck("ExportAllDeclaration", ["exported", "source", "attributes"]);
_ck("ExportSpecifier", ["local", "exported"]);
_ck("TSTypeAnnotation", ["typeAnnotation"]);
_ck("TSAnyKeyword", []);
_ck("TSUnknownKeyword", []);
_ck("TSNeverKeyword", []);
_ck("TSVoidKeyword", []);
_ck("TSNullKeyword", []);
_ck("TSUndefinedKeyword", []);
_ck("TSStringKeyword", []);
_ck("TSNumberKeyword", []);
_ck("TSBigIntKeyword", []);
_ck("TSBooleanKeyword", []);
_ck("TSSymbolKeyword", []);
_ck("TSObjectKeyword", []);
_ck("TSIntrinsicKeyword", []);
_ck("TSThisType", []);
_ck("TSTypeReference", ["typeName", "typeArguments"]);
_ck("TSQualifiedName", ["left", "right"]);
_ck("TSTypeQuery", ["exprName", "typeArguments"]);
_ck("TSImportType", ["source", "options", "qualifier", "typeArguments"]);
_ck("TSTypeParameter", ["name", "constraint", "default"]);
_ck("TSTypeParameterDeclaration", ["params"]);
_ck("TSTypeParameterInstantiation", ["params"]);
_ck("TSLiteralType", ["literal"]);
_ck("TSTemplateLiteralType", ["quasis", "types"]);
_ck("TSArrayType", ["elementType"]);
_ck("TSIndexedAccessType", ["objectType", "indexType"]);
_ck("TSTupleType", ["elementTypes"]);
_ck("TSNamedTupleMember", ["label", "elementType"]);
_ck("TSOptionalType", ["typeAnnotation"]);
_ck("TSRestType", ["typeAnnotation"]);
_ck("TSJSDocNullableType", ["typeAnnotation"]);
_ck("TSJSDocNonNullableType", ["typeAnnotation"]);
_ck("TSJSDocUnknownType", []);
_ck("TSUnionType", ["types"]);
_ck("TSIntersectionType", ["types"]);
_ck("TSConditionalType", ["checkType", "extendsType", "trueType", "falseType"]);
_ck("TSInferType", ["typeParameter"]);
_ck("TSTypeOperator", ["typeAnnotation"]);
_ck("TSParenthesizedType", ["typeAnnotation"]);
_ck("TSFunctionType", ["typeParameters", "params", "returnType"]);
_ck("TSConstructorType", ["typeParameters", "params", "returnType"]);
_ck("TSTypePredicate", ["parameterName", "typeAnnotation"]);
_ck("TSTypeLiteral", ["members"]);
_ck("TSMappedType", ["key", "constraint", "nameType", "typeAnnotation"]);
_ck("TSPropertySignature", ["key", "typeAnnotation"]);
_ck("TSMethodSignature", ["key", "typeParameters", "params", "returnType"]);
_ck("TSCallSignatureDeclaration", ["typeParameters", "params", "returnType"]);
_ck("TSConstructSignatureDeclaration", ["typeParameters", "params", "returnType"]);
_ck("TSIndexSignature", ["parameters", "typeAnnotation"]);
_ck("TSTypeAliasDeclaration", ["id", "typeParameters", "typeAnnotation"]);
_ck("TSInterfaceDeclaration", ["id", "typeParameters", "extends", "body"]);
_ck("TSInterfaceBody", ["body"]);
_ck("TSInterfaceHeritage", ["expression", "typeArguments"]);
_ck("TSClassImplements", ["expression", "typeArguments"]);
_ck("TSEnumDeclaration", ["id", "body"]);
_ck("TSEnumBody", ["members"]);
_ck("TSEnumMember", ["id", "initializer"]);
_ck("TSModuleDeclaration", ["id", "body"]);
_ck("TSModuleBlock", ["body"]);
_ck("TSModuleDeclaration", ["id", "body"]);
_ck("TSParameterProperty", ["decorators", "parameter"]);
_ck("Identifier", ["typeAnnotation"]);
_ck("TSAsExpression", ["expression", "typeAnnotation"]);
_ck("TSSatisfiesExpression", ["expression", "typeAnnotation"]);
_ck("TSTypeAssertion", ["typeAnnotation", "expression"]);
_ck("TSNonNullExpression", ["expression"]);
_ck("TSInstantiationExpression", ["expression", "typeArguments"]);
_ck("TSExportAssignment", ["expression"]);
_ck("TSNamespaceExportDeclaration", ["id"]);
_ck("TSImportEqualsDeclaration", ["id", "moduleReference"]);
_ck("TSExternalModuleReference", ["expression"]);
_ck("JSXElement", ["openingElement", "children", "closingElement"]);
_ck("JSXOpeningElement", ["name", "attributes", "typeArguments"]);
_ck("JSXClosingElement", ["name"]);
_ck("JSXFragment", ["openingFragment", "children", "closingFragment"]);
_ck("JSXOpeningFragment", []);
_ck("JSXClosingFragment", []);
_ck("JSXIdentifier", []);
_ck("JSXNamespacedName", ["namespace", "name"]);
_ck("JSXMemberExpression", ["object", "property"]);
_ck("JSXAttribute", ["name", "value"]);
_ck("JSXSpreadAttribute", ["argument"]);
_ck("JSXExpressionContainer", ["expression"]);
_ck("JSXEmptyExpression", []);
_ck("JSXText", []);
_ck("JSXSpreadChild", ["expression"]);
_ck("Hashbang", []);
const SCOPE_KINDS = ["global", "module", "function", "block", "class", "staticBlock", "expressionName", "tsModule"];
const NAME_KINDS = ["named", "star", "none", "equals", "global"];
const IMPORT_PHASES = ["source", "defer"];
const SymbolFlags = Object.freeze({
  FunctionScopedVariable: 1 << 0,
  BlockScopedVariable: 1 << 1,
  Function: 1 << 2,
  Class: 1 << 3,
  RegularEnum: 1 << 4,
  ConstEnum: 1 << 5,
  ValueModule: 1 << 6,
  Interface: 1 << 7,
  TypeAlias: 1 << 8,
  TypeParameter: 1 << 9,
  NamespaceModule: 1 << 10,
  ValueImport: 1 << 11,
  TypeImport: 1 << 12,
  Const: 1 << 13,
  Ambient: 1 << 14,
  Parameter: 1 << 15,
  CatchVariable: 1 << 16,
  Exported: 1 << 17,
  Default: 1 << 18,
  Variable: 3,
  Import: 6144,
  ValueSpace: 127,
  TypeSpace: 952,
});
const SCAN_CHILDREN = [
  [2, 2],
  [0, 2],
  [0, 2, 0, 3, 0, 4, 0, 5],
  [0, 2, 0, 3, 0, 4, 0, 5, 0, 6],
  [2, 2],
  [2, 2],
  [2, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3, 0, 4],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3],
  [2, 2],
  [2, 2],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 2, 3, 0, 4],
  [0, 2],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 2, 3, 0, 4],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2],
  [2, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 1, 8],
  [2, 2],
  [2, 2, 0, 3, 0, 4],
  [2, 2, 0, 3, 0, 4, 0, 5],
  [2, 2],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [2, 2, 1, 3],
  [],
  [],
  [],
  [2, 4, 0, 5],
  [],
  [],
  [0, 2],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 2, 3],
  [0, 2, 2, 3],
  [0, 2, 0, 3, 0, 4, 0, 5],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3],
  [],
  [],
  [2, 2],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2, 0, 3, 2, 4, 0, 5],
  [0, 2, 2, 3, 0, 4],
  [2, 2, 0, 3, 1, 4, 0, 6],
  [2, 2, 0, 3, 1, 4, 0, 6],
  [0, 2, 0, 3],
  [2, 2],
  [0, 2, 0, 3],
  [2, 2, 0, 3, 1, 4],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2, 2, 3, 0, 4, 1, 5],
  [0, 2],
  [0, 2, 0, 3, 2, 4],
  [0, 2, 0, 3],
  [0, 2],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3, 0, 4, 0, 5],
  [0, 2, 0, 3, 0, 4],
  [2, 2],
  [2, 2],
  [0, 2],
  [2, 2, 1, 3],
  [0, 2],
  [0, 2, 0, 3],
  [2, 2],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2],
  [0, 2],
  [0, 2],
  [],
  [2, 2],
  [2, 2],
  [0, 2, 0, 3, 0, 4, 0, 5],
  [0, 2],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3],
  [2, 2],
  [0, 2, 0, 3, 0, 4, 0, 5],
  [0, 2, 0, 3],
  [0, 2, 0, 3, 0, 4, 0, 5],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3, 0, 4],
  [2, 2, 0, 3],
  [0, 2, 0, 3, 0, 4],
  [0, 2, 0, 3, 2, 4, 0, 5],
  [2, 2],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [2, 2],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [2, 2],
  [0, 2, 0, 3],
  [2, 2, 0, 3],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2, 2, 3, 0, 4],
  [0, 2, 2, 3, 0, 4],
  [0, 2],
  [0, 2, 2, 3, 0, 4],
  [],
  [],
  [],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2, 0, 3],
  [0, 2],
  [0, 2],
  [],
  [],
  [0, 2],
];
const TAG_TYPES = [
  "SequenceExpression",
  "ParenthesizedExpression",
  "ArrowFunctionExpression",
  0,
  "BlockStatement",
  "BlockStatement",
  null,
  "BinaryExpression",
  "LogicalExpression",
  "ConditionalExpression",
  "UnaryExpression",
  "UpdateExpression",
  "AssignmentExpression",
  "ArrayExpression",
  "ObjectExpression",
  "SpreadElement",
  "Property",
  "MemberExpression",
  "CallExpression",
  "ChainExpression",
  "TaggedTemplateExpression",
  "NewExpression",
  "AwaitExpression",
  "YieldExpression",
  "MetaProperty",
  "Decorator",
  0,
  "ClassBody",
  0,
  0,
  "StaticBlock",
  "Super",
  "Literal",
  "Literal",
  "Literal",
  "Literal",
  "Literal",
  "ThisExpression",
  "Literal",
  "TemplateLiteral",
  "TemplateElement",
  "Identifier",
  "PrivateIdentifier",
  "Identifier",
  "Identifier",
  "Identifier",
  "ExpressionStatement",
  "IfStatement",
  "SwitchStatement",
  "SwitchCase",
  "ForStatement",
  "ForInStatement",
  "ForOfStatement",
  "WhileStatement",
  "DoWhileStatement",
  "BreakStatement",
  "ContinueStatement",
  "LabeledStatement",
  "WithStatement",
  "ReturnStatement",
  "ThrowStatement",
  "TryStatement",
  "CatchClause",
  "DebuggerStatement",
  "EmptyStatement",
  "VariableDeclaration",
  "VariableDeclarator",
  "ExpressionStatement",
  "AssignmentPattern",
  "RestElement",
  "ArrayPattern",
  "ObjectPattern",
  "Property",
  "Program",
  "ImportExpression",
  "ImportDeclaration",
  "ImportSpecifier",
  "ImportDefaultSpecifier",
  "ImportNamespaceSpecifier",
  "ImportAttribute",
  "ExportNamedDeclaration",
  "ExportDefaultDeclaration",
  "ExportAllDeclaration",
  "ExportSpecifier",
  "TSTypeAnnotation",
  "TSAnyKeyword",
  "TSUnknownKeyword",
  "TSNeverKeyword",
  "TSVoidKeyword",
  "TSNullKeyword",
  "TSUndefinedKeyword",
  "TSStringKeyword",
  "TSNumberKeyword",
  "TSBigIntKeyword",
  "TSBooleanKeyword",
  "TSSymbolKeyword",
  "TSObjectKeyword",
  "TSIntrinsicKeyword",
  "TSThisType",
  "TSTypeReference",
  "TSQualifiedName",
  "TSTypeQuery",
  "TSImportType",
  "TSTypeParameter",
  "TSTypeParameterDeclaration",
  "TSTypeParameterInstantiation",
  "TSLiteralType",
  "TSTemplateLiteralType",
  "TSArrayType",
  "TSIndexedAccessType",
  "TSTupleType",
  "TSNamedTupleMember",
  "TSOptionalType",
  "TSRestType",
  "TSJSDocNullableType",
  "TSJSDocNonNullableType",
  "TSJSDocUnknownType",
  "TSUnionType",
  "TSIntersectionType",
  "TSConditionalType",
  "TSInferType",
  "TSTypeOperator",
  "TSParenthesizedType",
  "TSFunctionType",
  "TSConstructorType",
  "TSTypePredicate",
  "TSTypeLiteral",
  "TSMappedType",
  "TSPropertySignature",
  "TSMethodSignature",
  "TSCallSignatureDeclaration",
  "TSConstructSignatureDeclaration",
  "TSIndexSignature",
  "TSTypeAliasDeclaration",
  "TSInterfaceDeclaration",
  "TSInterfaceBody",
  "TSInterfaceHeritage",
  "TSClassImplements",
  "TSEnumDeclaration",
  "TSEnumBody",
  "TSEnumMember",
  "TSModuleDeclaration",
  "TSModuleBlock",
  "TSModuleDeclaration",
  "TSParameterProperty",
  "Identifier",
  "TSAsExpression",
  "TSSatisfiesExpression",
  "TSTypeAssertion",
  "TSNonNullExpression",
  "TSInstantiationExpression",
  "TSExportAssignment",
  "TSNamespaceExportDeclaration",
  "TSImportEqualsDeclaration",
  "TSExternalModuleReference",
  "JSXElement",
  "JSXOpeningElement",
  "JSXClosingElement",
  "JSXFragment",
  "JSXOpeningFragment",
  "JSXClosingFragment",
  "JSXIdentifier",
  "JSXNamespacedName",
  "JSXMemberExpression",
  "JSXAttribute",
  "JSXSpreadAttribute",
  "JSXExpressionContainer",
  "JSXEmptyExpression",
  "JSXText",
  "JSXSpreadChild",
];
const TAG_CHOICES = new Map([
  [3, ["FunctionDeclaration", "FunctionExpression", "TSDeclareFunction", "TSEmptyBodyFunctionExpression"]],
  [26, ["ClassDeclaration", "ClassExpression"]],
  [28, ["MethodDefinition", "TSAbstractMethodDefinition"]],
  [29, ["PropertyDefinition", "AccessorProperty", "TSAbstractPropertyDefinition", "TSAbstractAccessorProperty"]],
]);
function buildPosMap(src, byteLen, startByte) {
  const m = new Uint32Array(byteLen - startByte + 1);
  const len = src.length;
  let bp = 0, u16p = startByte, i = startByte;
  while (i < len) {
    if (i + 16 <= len) {
      let allAscii = true;
      for (let k = 0; k < 16; k++) {
        if (src.charCodeAt(i + k) >= 0x80) { allAscii = false; break; }
      }
      if (allAscii) {
        for (let k = 0; k < 16; k++) m[bp + k] = u16p + k;
        bp += 16; u16p += 16; i += 16;
        continue;
      }
    }
    const cu = src.charCodeAt(i);
    m[bp] = u16p;
    if (cu < 0x80) { bp++; u16p++; i++; }
    else if (cu < 0x800) { m[bp + 1] = u16p + 1; bp += 2; u16p++; i++; }
    else if (cu < 0xD800 || cu >= 0xE000) {
      m[bp + 1] = u16p + 1; m[bp + 2] = u16p + 1;
      bp += 3; u16p++; i++;
    }
    else {
      m[bp + 1] = u16p + 1; m[bp + 2] = u16p + 2; m[bp + 3] = u16p + 2;
      bp += 4; u16p += 2; i += 2;
    }
  }
  m[byteLen - startByte] = u16p;
  return m;
}
function decode(buffer, source) {
  const _u8 = new Uint8Array(buffer);
  const aLen = (buffer.byteLength >> 2) << 2;
  const _u32 = new Int32Array(buffer, 0, aLen >> 2);
  const _src = source;
  const _srcLen = _u32[3];
  const nodeCount = _u32[0],
        extraCount = _u32[1],
        spLen = _u32[2];
  const commentCount = _u32[4],
        lineStartsCount = _u32[6],
        diagCount = _u32[7],
        progIdx = _u32[8];
  const attachedCommentCount = _u32[5];
  const _flags = _u32[9];
  const _isTs = !!(_flags & 1);
  const _attached = !!(_flags & 2);
  const _firstNa = _u32[10];
  const _nodesOff = 44;
  const eOff = _nodesOff + nodeCount * 48;
  const _extraBase = eOff >> 2;
  const _spOff = eOff + extraCount * 4;
  const dv = new DataView(buffer);
  const _aoOff = _spOff + spLen;
  const _acOff = _attached ? _aoOff + (nodeCount + 1) * 4 : _aoOff;
  const _cOff = _acOff + attachedCommentCount * 12;
  function _poolDecode(s, e) {
    const a = _spOff + s - _srcLen, b = _spOff + e - _srcLen;
    let hasEd = false;
    for (let i = a; i < b; i++) if (_u8[i] === 0xED) { hasEd = true; break; }
    if (!hasEd) return _td.decode(_u8.subarray(a, b));
    let r = "";
    for (let i = a; i < b; ) {
      const c = _u8[i];
      if (c < 0x80) { r += String.fromCharCode(c); i++; }
      else if (c < 0xE0) {
        r += String.fromCharCode(((c & 0x1F) << 6) | (_u8[i+1] & 0x3F));
        i += 2;
      }
      else if (c < 0xF0) {
        r += String.fromCharCode(
          ((c & 0x0F) << 12) | ((_u8[i+1] & 0x3F) << 6) | (_u8[i+2] & 0x3F)
        );
        i += 3;
      }
      else {
        r += String.fromCodePoint(
          ((c & 0x07) << 18) | ((_u8[i+1] & 0x3F) << 12) |
            ((_u8[i+2] & 0x3F) << 6) | (_u8[i+3] & 0x3F)
        );
        i += 4;
      }
    }
    return r;
  }
  const pm = _firstNa < _srcLen ? buildPosMap(_src, _srcLen, _firstNa) : null;
  const _p = v => v <= _firstNa ? v : pm[v - _firstNa];
  const str = (s, e) => {
    if (s === e) return "";
    if (s >= _srcLen) return _poolDecode(s, e);
    if (e <= _firstNa) return _src.slice(s, e);
    const ss = s < _firstNa ? s : pm[s - _firstNa];
    return _src.slice(ss, pm[e - _firstNa]);
  };
  function nodeArr(s, len) {
    const r = Array.from({ length: len });
    for (let j = 0; j < len; j++) r[j] = node(_u32[_extraBase + s + j]);
    return r;
  }
  function nodeArrHoles(s, len) {
    const r = Array.from({ length: len });
    for (let j = 0; j < len; j++) {
      const x = _u32[_extraBase + s + j];
      r[j] = x !== NULL ? node(x) : null;
    }
    return r;
  }
  function fnParams(idx) {
    const po = _nodesOff + idx * 48;
    const len = _u8[po + 4] | (_u8[po + 5] << 8);
    const pb = po >> 2;
    const iStart = _u32[pb + 2], rest = _u32[pb + 3];
    const p = [];
    for (let j = 0; j < len; j++) p.push(node(_u32[_extraBase + iStart + j]));
    if (rest !== NULL) p.push(node(rest));
    return p;
  }
  function _attachedCommentsOf(a, e) {
    const out = Array.from({ length: e - a });
    for (let j = a; j < e; j++) {
      const o = _acOff + j * 12;
      const cf = _u8[o + 0];
      const vs = dv.getUint32(o + 4, true),
            ve = dv.getUint32(o + 8, true);
      out[j - a] = {
        type: (cf & 1) ? "Block" : "Line",
        position: ["before", "after", "inside"][(cf >> 1) & 3],
        sameLine: (cf & 8) !== 0,
        value: str(vs, ve),
      };
    }
    return out;
  }
  function nodeWithComments(i) {
    const r = _decode(i);
    if (r && r.type !== undefined && r.comments === undefined) {
      const off = _aoOff + i * 4;
      const a = dv.getUint32(off, true), e = dv.getUint32(off + 4, true);
      if (a !== e) r.comments = _attachedCommentsOf(a, e);
    }
    return r;
  }
  function _decode(i) {
    const o = _nodesOff + i * 48;
    const tag = _u8[o];
    const flags = _u8[o + 2] | (_u8[o + 3] << 8);
    const f0 = _u8[o + 4] | (_u8[o + 5] << 8);
    const b = o >> 2;
    const f1 = _u32[b + 2], f2 = _u32[b + 3],
          f3 = _u32[b + 4], f4 = _u32[b + 5],
          f5 = _u32[b + 6], f6 = _u32[b + 7],
          f7 = _u32[b + 8], f8 = _u32[b + 9];
    const _ss = _u32[b + 10], _se = _u32[b + 11];
    const start = _ss <= _firstNa ? _ss : pm[_ss - _firstNa];
    const end = _se <= _firstNa ? _se : pm[_se - _firstNa];
    switch (tag) {
    case 0: return { type: "SequenceExpression", start, end, expressions: nodeArr(f1, f0) };
    case 1: return { type: "ParenthesizedExpression", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 2: {
      const r = {
        type: "ArrowFunctionExpression", start, end,
        id: null, generator: false, async: !!(flags & 2),
        params: f1 !== NULL ? fnParams(f1) : [],
        body: node(f2), expression: !!(flags & 1),
      };
      if (_isTs) {
        r.typeParameters = f3 !== NULL ? node(f3) : null;
        r.returnType = f4 !== NULL ? node(f4) : null;
      }
      return r;
    }
    case 3: {
      const ft = flags & 3;
      const r = {
        type: FUNCTION_TYPES[ft], start, end,
        id: f1 !== NULL ? node(f1) : null,
        generator: !!(flags & 4), async: !!(flags & 8),
        params: f2 !== NULL ? fnParams(f2) : [],
        body: f3 !== NULL ? node(f3) : null,
        expression: false,
      };
      if (_isTs) {
        r.typeParameters = f4 !== NULL ? node(f4) : null;
        r.returnType = f5 !== NULL ? node(f5) : null;
        r.declare = !!(flags & 16);
      }
      return r;
    }
    case 4: return { type: "BlockStatement", start, end, body: nodeArr(f1, f0) };
    case 5: return { type: "BlockStatement", start, end, body: nodeArr(f1, f0) };
    case 6: return { params: fnParams(i) };
    case 7: return { type: "BinaryExpression", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null, operator: BINARY_OPS[flags & 31] };
    case 8: return { type: "LogicalExpression", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null, operator: LOGICAL_OPS[flags & 3] };
    case 9: return { type: "ConditionalExpression", start, end, test: f1 !== NULL ? node(f1) : null, consequent: f2 !== NULL ? node(f2) : null, alternate: f3 !== NULL ? node(f3) : null };
    case 10: return {
      type: "UnaryExpression", start, end,
      operator: UNARY_OPS[flags & 7], prefix: true,
      argument: f1 !== NULL ? node(f1) : null,
    };
    case 11: return { type: "UpdateExpression", start, end, argument: f1 !== NULL ? node(f1) : null, operator: UPDATE_OPS[flags & 1], prefix: !!(flags & 2) };
    case 12: return { type: "AssignmentExpression", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null, operator: ASSIGNMENT_OPS[flags & 15] };
    case 13: return { type: "ArrayExpression", start, end, elements: nodeArrHoles(f1, f0) };
    case 14: return { type: "ObjectExpression", start, end, properties: nodeArr(f1, f0) };
    case 15: return { type: "SpreadElement", start, end, argument: f1 !== NULL ? node(f1) : null };
    case 16: { const r = { type: "Property", start, end, key: f1 !== NULL ? node(f1) : null, value: f2 !== NULL ? node(f2) : null, kind: PROPERTY_KINDS[flags & 3], method: !!(flags & 4), shorthand: !!(flags & 8), computed: !!(flags & 16) }; if (_isTs) { r.optional = false; } return r; }
    case 17: return { type: "MemberExpression", start, end, object: f1 !== NULL ? node(f1) : null, property: f2 !== NULL ? node(f2) : null, computed: !!(flags & 1), optional: !!(flags & 2) };
    case 18: { const r = { type: "CallExpression", start, end, callee: f1 !== NULL ? node(f1) : null, arguments: nodeArr(f2, f0), optional: !!(flags & 1) }; if (_isTs) { r.typeArguments = f3 !== NULL ? node(f3) : null; } return r; }
    case 19: return { type: "ChainExpression", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 20: { const r = { type: "TaggedTemplateExpression", start, end, tag: f1 !== NULL ? node(f1) : null, quasi: f2 !== NULL ? node(f2) : null }; if (_isTs) { r.typeArguments = f3 !== NULL ? node(f3) : null; } return r; }
    case 21: { const r = { type: "NewExpression", start, end, callee: f1 !== NULL ? node(f1) : null, arguments: nodeArr(f2, f0) }; if (_isTs) { r.typeArguments = f3 !== NULL ? node(f3) : null; } return r; }
    case 22: return { type: "AwaitExpression", start, end, argument: f1 !== NULL ? node(f1) : null };
    case 23: return { type: "YieldExpression", start, end, argument: f1 !== NULL ? node(f1) : null, delegate: !!(flags & 1) };
    case 24: return { type: "MetaProperty", start, end, meta: f1 !== NULL ? node(f1) : null, property: f2 !== NULL ? node(f2) : null };
    case 25: return { type: "Decorator", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 26: {
      const r = {
        type: CLASS_TYPES[flags & 1], start, end,
        decorators: nodeArr(f1, f0),
        id: f2 !== NULL ? node(f2) : null,
        superClass: f3 !== NULL ? node(f3) : null,
        body: node(f4),
      };
      if (_isTs) {
        r.typeParameters = f5 !== NULL ? node(f5) : null;
        r.superTypeArguments = f6 !== NULL ? node(f6) : null;
        r.implements = nodeArr(f7, f8);
        r.abstract = !!(flags & 2);
        r.declare = !!(flags & 4);
      }
      return r;
    }
    case 27: return { type: "ClassBody", start, end, body: nodeArr(f1, f0) };
    case 28: {
      const r = {
        type: "MethodDefinition", start, end,
        decorators: nodeArr(f1, f0),
        key: node(f2), value: node(f3),
        kind: METHOD_KINDS[flags & 3],
        computed: !!(flags & 4), static: !!(flags & 8),
      };
      if (_isTs) {
        r.override = !!(flags & 16);
        r.optional = !!(flags & 32);
        const _abs = !!(flags & 64);
        r.accessibility = ACCESSIBILITY[(flags >> 7) & 3];
        if (_abs) r.type = "TSAbstractMethodDefinition";
      }
      return r;
    }
    case 29: {
      const _acc = !!(flags & 4);
      const r = {
        type: _acc ? "AccessorProperty" : "PropertyDefinition",
        start, end,
        decorators: nodeArr(f1, f0),
        key: node(f2),
        value: f3 !== NULL ? node(f3) : null,
        computed: !!(flags & 1), static: !!(flags & 2),
      };
      if (_isTs) {
        r.typeAnnotation = f4 !== NULL ? node(f4) : null;
        r.declare = !!(flags & 8);
        r.override = !!(flags & 16);
        r.optional = !!(flags & 32);
        r.definite = !!(flags & 64);
        r.readonly = !!(flags & 128);
        const _abs = !!(flags & 256);
        r.accessibility = ACCESSIBILITY[(flags >> 9) & 3];
        if (_abs)
          r.type = _acc
            ? "TSAbstractAccessorProperty"
            : "TSAbstractPropertyDefinition";
      }
      return r;
    }
    case 30: return { type: "StaticBlock", start, end, body: nodeArr(f1, f0) };
    case 31: return { type: "Super", start, end };
    case 32: return {
      type: "Literal", start, end,
      value: str(f1, f2), raw: _src.slice(start, end),
    };
    case 33: {
      const r = _src.slice(start, end);
      const s = r.indexOf("_") === -1 ? r : r.replace(/_/g, "");
      const v = (flags & 3) === 2 && s[1] !== "o" && s[1] !== "O"
        ? parseInt(s.slice(1), 8)
        : +s;
      return {
        type: "Literal", start, end,
        value: v === v && isFinite(v) ? v : null,
        raw: r,
      };
    }
    case 34: {
      const r = _src.slice(start, end);
      const d = str(f1, f2).replace(/_/g, "");
      const v = BigInt(d);
      return {
        type: "Literal", start, end,
        value: v, raw: r, bigint: v.toString(),
      };
    }
    case 35: {
      const v = !!(flags & 1);
      return {
        type: "Literal", start, end,
        value: v, raw: v ? "true" : "false",
      };
    }
    case 36: return { type: "Literal", start, end, value: null, raw: "null" };
    case 37: return { type: "ThisExpression", start, end };
    case 38: {
      const p = str(f1, f2), fl = str(f3, f4);
      let v = null;
      try { v = new RegExp(p, fl); } catch {}
      return {
        type: "Literal", start, end,
        value: v, raw: "/" + p + "/" + fl,
        regex: { pattern: p, flags: fl.split("").sort().join("") },
      };
    }
    case 39: return { type: "TemplateLiteral", start, end, quasis: nodeArr(f1, f0), expressions: nodeArr(f2, f3) };
    case 40: {
      const raw = _src.slice(start, end).replace(/\r\n?/g, "\n");
      const tl = !!(flags & 1);
      const s = _isTs ? start - 1 : start;
      const e = _isTs ? (tl ? end + 1 : end + 2) : end;
      return {
        type: "TemplateElement", start: s, end: e,
        value: {
          raw,
          cooked: (flags & 2) ? null : str(f1, f2),
        },
        tail: tl,
      };
    }
    case 41: { const r = { type: "Identifier", start, end, name: str(f1, f2) }; if (_isTs) { r.decorators = []; r.optional = false; r.typeAnnotation = null; } return r; }
    case 42: return { type: "PrivateIdentifier", start, end, name: str(f1, f2) };
    case 43: { const r = { type: "Identifier", start, end, name: str(f1, f2) }; if (_isTs) { r.decorators = nodeArr(f3, f0); r.typeAnnotation = f4 !== NULL ? node(f4) : null; r.optional = !!(flags & 1); } return r; }
    case 44: { const r = { type: "Identifier", start, end, name: str(f1, f2) }; if (_isTs) { r.decorators = []; r.optional = false; r.typeAnnotation = null; } return r; }
    case 45: { const r = { type: "Identifier", start, end, name: str(f1, f2) }; if (_isTs) { r.decorators = []; r.optional = false; r.typeAnnotation = null; } return r; }
    case 46: { const r = { type: "ExpressionStatement", start, end, expression: f1 !== NULL ? node(f1) : null }; if (_isTs) { r.directive = null; } return r; }
    case 47: return { type: "IfStatement", start, end, test: f1 !== NULL ? node(f1) : null, consequent: f2 !== NULL ? node(f2) : null, alternate: f3 !== NULL ? node(f3) : null };
    case 48: return { type: "SwitchStatement", start, end, discriminant: f1 !== NULL ? node(f1) : null, cases: nodeArr(f2, f0) };
    case 49: return { type: "SwitchCase", start, end, test: f1 !== NULL ? node(f1) : null, consequent: nodeArr(f2, f0) };
    case 50: return { type: "ForStatement", start, end, init: f1 !== NULL ? node(f1) : null, test: f2 !== NULL ? node(f2) : null, update: f3 !== NULL ? node(f3) : null, body: f4 !== NULL ? node(f4) : null };
    case 51: return { type: "ForInStatement", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null, body: f3 !== NULL ? node(f3) : null };
    case 52: return { type: "ForOfStatement", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null, body: f3 !== NULL ? node(f3) : null, await: !!(flags & 1) };
    case 53: return { type: "WhileStatement", start, end, test: f1 !== NULL ? node(f1) : null, body: f2 !== NULL ? node(f2) : null };
    case 54: return { type: "DoWhileStatement", start, end, body: f1 !== NULL ? node(f1) : null, test: f2 !== NULL ? node(f2) : null };
    case 55: return { type: "BreakStatement", start, end, label: f1 !== NULL ? node(f1) : null };
    case 56: return { type: "ContinueStatement", start, end, label: f1 !== NULL ? node(f1) : null };
    case 57: return { type: "LabeledStatement", start, end, label: f1 !== NULL ? node(f1) : null, body: f2 !== NULL ? node(f2) : null };
    case 58: return { type: "WithStatement", start, end, object: f1 !== NULL ? node(f1) : null, body: f2 !== NULL ? node(f2) : null };
    case 59: return { type: "ReturnStatement", start, end, argument: f1 !== NULL ? node(f1) : null };
    case 60: return { type: "ThrowStatement", start, end, argument: f1 !== NULL ? node(f1) : null };
    case 61: return { type: "TryStatement", start, end, block: f1 !== NULL ? node(f1) : null, handler: f2 !== NULL ? node(f2) : null, finalizer: f3 !== NULL ? node(f3) : null };
    case 62: return { type: "CatchClause", start, end, param: f1 !== NULL ? node(f1) : null, body: f2 !== NULL ? node(f2) : null };
    case 63: return { type: "DebuggerStatement", start, end };
    case 64: return { type: "EmptyStatement", start, end };
    case 65: { const r = { type: "VariableDeclaration", start, end, kind: VAR_KINDS[flags & 7], declarations: nodeArr(f1, f0) }; if (_isTs) { r.declare = !!(flags & 8); } return r; }
    case 66: { const r = { type: "VariableDeclarator", start, end, id: f1 !== NULL ? node(f1) : null, init: f2 !== NULL ? node(f2) : null }; if (_isTs) { r.definite = !!(flags & 1); } return r; }
    case 67: return {
      type: "ExpressionStatement", start, end,
      expression: node(f1), directive: str(f2, f3),
    };
    case 68: { const r = { type: "AssignmentPattern", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null }; if (_isTs) { r.decorators = nodeArr(f3, f0); r.typeAnnotation = f4 !== NULL ? node(f4) : null; r.optional = !!(flags & 1); } return r; }
    case 69: { const r = { type: "RestElement", start, end, argument: f1 !== NULL ? node(f1) : null }; if (_isTs) { r.decorators = nodeArr(f2, f0); r.typeAnnotation = f3 !== NULL ? node(f3) : null; r.optional = !!(flags & 1); r.value = null; } return r; }
    case 70: {
      const el = nodeArrHoles(f1, f0);
      if (f2 !== NULL) el.push(node(f2));
      const r = { type: "ArrayPattern", start, end, elements: el };
      if (_isTs) {
        r.decorators = nodeArr(f3, f4);
        r.optional = !!(flags & 1);
        r.typeAnnotation = f5 !== NULL ? node(f5) : null;
      }
      return r;
    }
    case 71: {
      const pr = nodeArr(f1, f0);
      if (f2 !== NULL) pr.push(node(f2));
      const r = { type: "ObjectPattern", start, end, properties: pr };
      if (_isTs) {
        r.decorators = nodeArr(f3, f4);
        r.optional = !!(flags & 1);
        r.typeAnnotation = f5 !== NULL ? node(f5) : null;
      }
      return r;
    }
    case 72: {
      const r = {
        type: "Property", start, end,
        kind: "init",
        key: node(f1), value: node(f2),
        method: false,
        shorthand: !!(flags & 1),
        computed: !!(flags & 2),
      }; if (_isTs) { r.optional = false; } return r; }
    case 73: return {
      type: "Program", start, end,
      sourceType: (flags & 1) ? "module" : "script",
      hashbang: (flags & 2) ? {
        type: "Hashbang",
        start: _p(f2 - 2), end: _p(f3),
        value: str(f2, f3),
      } : null,
      body: nodeArr(f1, f0),
    };
    case 74: return { type: "ImportExpression", start, end, source: f1 !== NULL ? node(f1) : null, options: f2 !== NULL ? node(f2) : null, phase: (flags & 1) ? ["source", "defer"][(flags >> 1) & 1] : null };
    case 75: { const r = { type: "ImportDeclaration", start, end, specifiers: nodeArr(f1, f0), source: f2 !== NULL ? node(f2) : null, attributes: nodeArr(f3, f4), phase: (flags & 1) ? ["source", "defer"][(flags >> 1) & 1] : null }; if (_isTs) { r.importKind = IMPORT_EXPORT_KINDS[(flags >> 2) & 1]; } return r; }
    case 76: { const r = { type: "ImportSpecifier", start, end, imported: f1 !== NULL ? node(f1) : null, local: f2 !== NULL ? node(f2) : null }; if (_isTs) { r.importKind = IMPORT_EXPORT_KINDS[flags & 1]; } return r; }
    case 77: return { type: "ImportDefaultSpecifier", start, end, local: f1 !== NULL ? node(f1) : null };
    case 78: return { type: "ImportNamespaceSpecifier", start, end, local: f1 !== NULL ? node(f1) : null };
    case 79: return { type: "ImportAttribute", start, end, key: f1 !== NULL ? node(f1) : null, value: f2 !== NULL ? node(f2) : null };
    case 80: { const r = { type: "ExportNamedDeclaration", start, end, declaration: f1 !== NULL ? node(f1) : null, specifiers: nodeArr(f2, f0), source: f3 !== NULL ? node(f3) : null, attributes: nodeArr(f4, f5) }; if (_isTs) { r.exportKind = IMPORT_EXPORT_KINDS[flags & 1]; } return r; }
    case 81: { const r = { type: "ExportDefaultDeclaration", start, end, declaration: f1 !== NULL ? node(f1) : null }; if (_isTs) { r.exportKind = "value"; } return r; }
    case 82: { const r = { type: "ExportAllDeclaration", start, end, exported: f1 !== NULL ? node(f1) : null, source: f2 !== NULL ? node(f2) : null, attributes: nodeArr(f3, f0) }; if (_isTs) { r.exportKind = IMPORT_EXPORT_KINDS[flags & 1]; } return r; }
    case 83: { const r = { type: "ExportSpecifier", start, end, local: f1 !== NULL ? node(f1) : null, exported: f2 !== NULL ? node(f2) : null }; if (_isTs) { r.exportKind = IMPORT_EXPORT_KINDS[flags & 1]; } return r; }
    case 84: return { type: "TSTypeAnnotation", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null };
    case 85: return { type: "TSAnyKeyword", start, end };
    case 86: return { type: "TSUnknownKeyword", start, end };
    case 87: return { type: "TSNeverKeyword", start, end };
    case 88: return { type: "TSVoidKeyword", start, end };
    case 89: return { type: "TSNullKeyword", start, end };
    case 90: return { type: "TSUndefinedKeyword", start, end };
    case 91: return { type: "TSStringKeyword", start, end };
    case 92: return { type: "TSNumberKeyword", start, end };
    case 93: return { type: "TSBigIntKeyword", start, end };
    case 94: return { type: "TSBooleanKeyword", start, end };
    case 95: return { type: "TSSymbolKeyword", start, end };
    case 96: return { type: "TSObjectKeyword", start, end };
    case 97: return { type: "TSIntrinsicKeyword", start, end };
    case 98: return { type: "TSThisType", start, end };
    case 99: return { type: "TSTypeReference", start, end, typeName: f1 !== NULL ? node(f1) : null, typeArguments: f2 !== NULL ? node(f2) : null };
    case 100: return { type: "TSQualifiedName", start, end, left: f1 !== NULL ? node(f1) : null, right: f2 !== NULL ? node(f2) : null };
    case 101: return { type: "TSTypeQuery", start, end, exprName: f1 !== NULL ? node(f1) : null, typeArguments: f2 !== NULL ? node(f2) : null };
    case 102: return { type: "TSImportType", start, end, source: f1 !== NULL ? node(f1) : null, options: f2 !== NULL ? node(f2) : null, qualifier: f3 !== NULL ? node(f3) : null, typeArguments: f4 !== NULL ? node(f4) : null };
    case 103: return { type: "TSTypeParameter", start, end, name: f1 !== NULL ? node(f1) : null, constraint: f2 !== NULL ? node(f2) : null, default: f3 !== NULL ? node(f3) : null, in: !!(flags & 1), out: !!(flags & 2), const: !!(flags & 4) };
    case 104: return { type: "TSTypeParameterDeclaration", start, end, params: nodeArr(f1, f0) };
    case 105: return { type: "TSTypeParameterInstantiation", start, end, params: nodeArr(f1, f0) };
    case 106: return { type: "TSLiteralType", start, end, literal: f1 !== NULL ? node(f1) : null };
    case 107: return { type: "TSTemplateLiteralType", start, end, quasis: nodeArr(f1, f0), types: nodeArr(f2, f3) };
    case 108: return { type: "TSArrayType", start, end, elementType: f1 !== NULL ? node(f1) : null };
    case 109: return { type: "TSIndexedAccessType", start, end, objectType: f1 !== NULL ? node(f1) : null, indexType: f2 !== NULL ? node(f2) : null };
    case 110: return { type: "TSTupleType", start, end, elementTypes: nodeArr(f1, f0) };
    case 111: return { type: "TSNamedTupleMember", start, end, label: f1 !== NULL ? node(f1) : null, elementType: f2 !== NULL ? node(f2) : null, optional: !!(flags & 1) };
    case 112: return { type: "TSOptionalType", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null };
    case 113: return { type: "TSRestType", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null };
    case 114: return { type: "TSJSDocNullableType", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null, postfix: !!(flags & 1) };
    case 115: return { type: "TSJSDocNonNullableType", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null, postfix: !!(flags & 1) };
    case 116: return { type: "TSJSDocUnknownType", start, end };
    case 117: return { type: "TSUnionType", start, end, types: nodeArr(f1, f0) };
    case 118: return { type: "TSIntersectionType", start, end, types: nodeArr(f1, f0) };
    case 119: return { type: "TSConditionalType", start, end, checkType: f1 !== NULL ? node(f1) : null, extendsType: f2 !== NULL ? node(f2) : null, trueType: f3 !== NULL ? node(f3) : null, falseType: f4 !== NULL ? node(f4) : null };
    case 120: return { type: "TSInferType", start, end, typeParameter: f1 !== NULL ? node(f1) : null };
    case 121: return { type: "TSTypeOperator", start, end, operator: TS_TYPE_OPERATORS[flags & 3], typeAnnotation: f1 !== NULL ? node(f1) : null };
    case 122: return { type: "TSParenthesizedType", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null };
    case 123: return {
      type: "TSFunctionType", start, end,
      typeParameters: f1 !== NULL ? node(f1) : null,
      params: f2 !== NULL ? fnParams(f2) : [],
      returnType: f3 !== NULL ? node(f3) : null,
    };
    case 124: return {
      type: "TSConstructorType", start, end,
      abstract: !!(flags & 1),
      typeParameters: f1 !== NULL ? node(f1) : null,
      params: f2 !== NULL ? fnParams(f2) : [],
      returnType: f3 !== NULL ? node(f3) : null,
    };
    case 125: return { type: "TSTypePredicate", start, end, parameterName: f1 !== NULL ? node(f1) : null, typeAnnotation: f2 !== NULL ? node(f2) : null, asserts: !!(flags & 1) };
    case 126: return { type: "TSTypeLiteral", start, end, members: nodeArr(f1, f0) };
    case 127: return {
      type: "TSMappedType", start, end,
      key: node(f1),
      constraint: node(f2),
      nameType: f3 !== NULL ? node(f3) : null,
      typeAnnotation: f4 !== NULL ? node(f4) : null,
      optional: TS_MAPPED_OPTIONAL[(flags >> 0) & 3],
      readonly: TS_MAPPED_READONLY[(flags >> 2) & 3],
    };
    case 128: { const r = { type: "TSPropertySignature", start, end, key: f1 !== NULL ? node(f1) : null, typeAnnotation: f2 !== NULL ? node(f2) : null, computed: !!(flags & 1), optional: !!(flags & 2), readonly: !!(flags & 4) }; if (_isTs) { r.accessibility = null; r.static = false; } return r; }
    case 129: return {
      type: "TSMethodSignature", start, end,
      key: node(f1),
      computed: !!(flags & 4),
      optional: !!(flags & 8),
      kind: TS_METHOD_SIGNATURE_KINDS[(flags >> 0) & 3],
      typeParameters: f2 !== NULL ? node(f2) : null,
      params: f3 !== NULL ? fnParams(f3) : [],
      returnType: f4 !== NULL ? node(f4) : null,
      accessibility: null, readonly: false, static: false,
    };
    case 130: return {
      type: "TSCallSignatureDeclaration", start, end,
      typeParameters: f1 !== NULL ? node(f1) : null,
      params: f2 !== NULL ? fnParams(f2) : [],
      returnType: f3 !== NULL ? node(f3) : null,
    };
    case 131: return {
      type: "TSConstructSignatureDeclaration", start, end,
      typeParameters: f1 !== NULL ? node(f1) : null,
      params: f2 !== NULL ? fnParams(f2) : [],
      returnType: f3 !== NULL ? node(f3) : null,
    };
    case 132: { const r = { type: "TSIndexSignature", start, end, parameters: nodeArr(f1, f0), typeAnnotation: f2 !== NULL ? node(f2) : null, readonly: !!(flags & 1) }; if (_isTs) { r.static = !!(flags & 2); r.accessibility = null; } return r; }
    case 133: return { type: "TSTypeAliasDeclaration", start, end, id: f1 !== NULL ? node(f1) : null, typeParameters: f2 !== NULL ? node(f2) : null, typeAnnotation: f3 !== NULL ? node(f3) : null, declare: !!(flags & 1) };
    case 134: return { type: "TSInterfaceDeclaration", start, end, id: f1 !== NULL ? node(f1) : null, typeParameters: f2 !== NULL ? node(f2) : null, extends: nodeArr(f3, f0), body: f4 !== NULL ? node(f4) : null, declare: !!(flags & 1) };
    case 135: return { type: "TSInterfaceBody", start, end, body: nodeArr(f1, f0) };
    case 136: return { type: "TSInterfaceHeritage", start, end, expression: f1 !== NULL ? node(f1) : null, typeArguments: f2 !== NULL ? node(f2) : null };
    case 137: return { type: "TSClassImplements", start, end, expression: f1 !== NULL ? node(f1) : null, typeArguments: f2 !== NULL ? node(f2) : null };
    case 138: return { type: "TSEnumDeclaration", start, end, id: f1 !== NULL ? node(f1) : null, body: f2 !== NULL ? node(f2) : null, const: !!(flags & 1), declare: !!(flags & 2) };
    case 139: return { type: "TSEnumBody", start, end, members: nodeArr(f1, f0) };
    case 140: return { type: "TSEnumMember", start, end, id: f1 !== NULL ? node(f1) : null, initializer: f2 !== NULL ? node(f2) : null, computed: !!(flags & 1) };
    case 141: {
      const r = {
        type: "TSModuleDeclaration", start, end,
        id: node(f1),
        kind: TS_MODULE_KINDS[(flags >> 0) & 1],
        declare: !!(flags & 2),
        global: false,
      };
      if (f2 !== NULL) r.body = node(f2);
      return r;
    }
    case 142: return { type: "TSModuleBlock", start, end, body: nodeArr(f1, f0) };
    case 143: return {
      type: "TSModuleDeclaration", start, end,
      id: node(f1), body: node(f2),
      kind: "global",
      declare: !!(flags & 1),
      global: true,
    };
    case 144: { const r = { type: "TSParameterProperty", start, end, decorators: nodeArr(f1, f0), parameter: f2 !== NULL ? node(f2) : null, override: !!(flags & 1), readonly: !!(flags & 2), accessibility: ACCESSIBILITY[(flags >> 2) & 3] }; if (_isTs) { r.static = false; } return r; }
    case 145: return {
      type: "Identifier", start, end,
      decorators: [],
      name: "this", optional: false,
      typeAnnotation: f1 !== NULL ? node(f1) : null,
    };
    case 146: return { type: "TSAsExpression", start, end, expression: f1 !== NULL ? node(f1) : null, typeAnnotation: f2 !== NULL ? node(f2) : null };
    case 147: return { type: "TSSatisfiesExpression", start, end, expression: f1 !== NULL ? node(f1) : null, typeAnnotation: f2 !== NULL ? node(f2) : null };
    case 148: return { type: "TSTypeAssertion", start, end, typeAnnotation: f1 !== NULL ? node(f1) : null, expression: f2 !== NULL ? node(f2) : null };
    case 149: return { type: "TSNonNullExpression", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 150: return { type: "TSInstantiationExpression", start, end, expression: f1 !== NULL ? node(f1) : null, typeArguments: f2 !== NULL ? node(f2) : null };
    case 151: return { type: "TSExportAssignment", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 152: return { type: "TSNamespaceExportDeclaration", start, end, id: f1 !== NULL ? node(f1) : null };
    case 153: return { type: "TSImportEqualsDeclaration", start, end, id: f1 !== NULL ? node(f1) : null, moduleReference: f2 !== NULL ? node(f2) : null, importKind: IMPORT_EXPORT_KINDS[flags & 1] };
    case 154: return { type: "TSExternalModuleReference", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 155: return { type: "JSXElement", start, end, openingElement: f1 !== NULL ? node(f1) : null, children: nodeArr(f2, f0), closingElement: f3 !== NULL ? node(f3) : null };
    case 156: { const r = { type: "JSXOpeningElement", start, end, name: f1 !== NULL ? node(f1) : null, attributes: nodeArr(f2, f0), selfClosing: !!(flags & 1) }; if (_isTs) { r.typeArguments = f3 !== NULL ? node(f3) : null; } return r; }
    case 157: return { type: "JSXClosingElement", start, end, name: f1 !== NULL ? node(f1) : null };
    case 158: return { type: "JSXFragment", start, end, openingFragment: f1 !== NULL ? node(f1) : null, children: nodeArr(f2, f0), closingFragment: f3 !== NULL ? node(f3) : null };
    case 159: return { type: "JSXOpeningFragment", start, end };
    case 160: return { type: "JSXClosingFragment", start, end };
    case 161: return { type: "JSXIdentifier", start, end, name: str(f1, f2) };
    case 162: return { type: "JSXNamespacedName", start, end, namespace: f1 !== NULL ? node(f1) : null, name: f2 !== NULL ? node(f2) : null };
    case 163: return { type: "JSXMemberExpression", start, end, object: f1 !== NULL ? node(f1) : null, property: f2 !== NULL ? node(f2) : null };
    case 164: return { type: "JSXAttribute", start, end, name: f1 !== NULL ? node(f1) : null, value: f2 !== NULL ? node(f2) : null };
    case 165: return { type: "JSXSpreadAttribute", start, end, argument: f1 !== NULL ? node(f1) : null };
    case 166: return { type: "JSXExpressionContainer", start, end, expression: f1 !== NULL ? node(f1) : null };
    case 167: return { type: "JSXEmptyExpression", start, end };
    case 168: {
      const t = str(f1, f2);
      return { type: "JSXText", start, end, value: t, raw: t };
    }
    case 169: return { type: "JSXSpreadChild", start, end, expression: f1 !== NULL ? node(f1) : null };
    }
  }
  const _inner = _attached ? nodeWithComments : _decode;
  const _nodes = Array.from({ length: nodeCount });
  const _nodeIndexes = new WeakMap();
  function node(i) {
    const m = _nodes[i];
    if (m !== undefined) return m;
    const r = _inner(i);
    _nodes[i] = r;
    if (r !== null && typeof r === "object") _nodeIndexes.set(r, i);
    return r;
  }
  const _nodesU32 = _nodesOff >> 2;
  function startOf(i) { return _p(_u32[_nodesU32 + i * 12 + 10]); }
  function endOf(i) { return _p(_u32[_nodesU32 + i * 12 + 11]); }
  const lsOff = _cOff + commentCount * 20;
  const dOff = lsOff + lineStartsCount * 4;
  function _decodeComments() {
    const out = Array.from({ length: commentCount });
    for (let j = 0; j < commentCount; j++) {
      const o = _cOff + j * 20;
      const cf = _u8[o + 0];
      const vs = dv.getUint32(o + 4, true),
            ve = dv.getUint32(o + 8, true);
      const ss = dv.getUint32(o + 12, true),
            se = dv.getUint32(o + 16, true);
      out[j] = {
        type: (cf & 1) ? "Block" : "Line",
        value: str(vs, ve),
        start: _p(ss),
        end: _p(se),
      };
    }
    return out;
  }
  function _decodeLineStarts() {
    const out = Array.from({ length: lineStartsCount });
    if (_firstNa >= _srcLen) {
      for (let j = 0; j < lineStartsCount; j++) {
        out[j] = dv.getUint32(lsOff + j * 4, true);
      }
      return out;
    }
    for (let j = 0; j < lineStartsCount; j++) {
      const v = dv.getUint32(lsOff + j * 4, true);
      out[j] = v < _firstNa ? v : (v >= _srcLen ? pm[pm.length - 1] : pm[v - _firstNa]);
    }
    return out;
  }
  function _decodeDiagnostics() {
    const out = Array.from({ length: diagCount });
    let dp = dOff;
    for (let j = 0; j < diagCount; j++) {
      const sev = SEVERITY[_u8[dp]]; dp++;
      const ds = _p(dv.getUint32(dp, true)); dp += 4;
      const de = _p(dv.getUint32(dp, true)); dp += 4;
      const ml = dv.getUint32(dp, true); dp += 4;
      const msg = _td.decode(_u8.subarray(dp, dp + ml)); dp += ml;
      const hh = _u8[dp]; dp++;
      let help = null;
      if (hh) {
        const hl = dv.getUint32(dp, true); dp += 4;
        help = _td.decode(_u8.subarray(dp, dp + hl)); dp += hl;
      }
      const lc = dv.getUint32(dp, true); dp += 4;
      const labels = Array.from({ length: lc });
      for (let k = 0; k < lc; k++) {
        const ls = _p(dv.getUint32(dp, true)); dp += 4;
        const le = _p(dv.getUint32(dp, true)); dp += 4;
        const lml = dv.getUint32(dp, true); dp += 4;
        labels[k] = {
          start: ls,
          end: le,
          message: _td.decode(_u8.subarray(dp, dp + lml)),
        };
        dp += lml;
      }
      out[j] = { severity: sev, message: msg, start: ds, end: de, help, labels };
    }
    return out;
  }
  function _scanType(tag, flags) {
    switch (tag) {
      case 3: return FUNCTION_TYPES[flags & 3];
      case 26: return CLASS_TYPES[flags & 1];
      case 28:
        return _isTs && (flags & 64)
          ? "TSAbstractMethodDefinition"
          : "MethodDefinition";
      default: {
        const acc = (flags & 4) !== 0;
        if (_isTs && (flags & 256)) {
          return acc ? "TSAbstractAccessorProperty" : "TSAbstractPropertyDefinition";
        }
        return acc ? "AccessorProperty" : "PropertyDefinition";
      }
    }
  }
  function scan(visitors) {
    const handlers = new Map();
    let every = null;
    for (const k of Object.keys(visitors)) {
      const v = visitors[k];
      if (typeof v !== "function") continue;
      if (k === "enter") every = v;
      else handlers.set(k, v);
    }
    const wanted = new Array(TAG_TYPES.length).fill(null);
    for (let t = 0; t < TAG_TYPES.length; t++) {
      const tt = TAG_TYPES[t];
      if (tt === null) continue;
      if (tt === 0) {
        for (const c of TAG_CHOICES.get(t)) {
          if (handlers.has(c)) { wanted[t] = 0; break; }
        }
      } else {
        const h = handlers.get(tt);
        if (h !== undefined) wanted[t] = h;
      }
    }
    let stopFlag = false, skipFlag = false;
    let curIndex = 0, curO = 0, curTag = 0;
    const cursor = {
      get index() { return curIndex; },
      get type() {
        const t = TAG_TYPES[curTag];
        return t !== 0 ? t : _scanType(curTag, _u8[curO + 2] | (_u8[curO + 3] << 8));
      },
      get start() { return startOf(curIndex); },
      get end() { return endOf(curIndex); },
      node() { return node(curIndex); },
      skip() { skipFlag = true; },
      stop() { stopFlag = true; },
    };
    (function visit(i) {
      const o = _nodesOff + i * 48;
      const tag = _u8[o];
      let h = wanted[tag];
      if (h !== null || every !== null) {
        curIndex = i; curO = o; curTag = tag;
        if (h === 0) {
          h = handlers.get(_scanType(tag, _u8[o + 2] | (_u8[o + 3] << 8))) ?? null;
        }
        if (every !== null && TAG_TYPES[tag] !== null) {
          every(cursor);
          if (stopFlag) return;
        }
        if (h !== null) {
          h(cursor);
          if (stopFlag) return;
        }
        if (skipFlag) { skipFlag = false; return; }
      }
      const ops = SCAN_CHILDREN[tag];
      const b = o >> 2;
      for (let p = 0; p < ops.length; p += 2) {
        const slot = ops[p + 1];
        if (ops[p] === 0) {
          const c = _u32[b + slot];
          if (c !== NULL) {
            visit(c);
            if (stopFlag) return;
          }
        } else {
          const s = _u32[b + slot];
          const len = ops[p] === 1
            ? _u32[b + slot + 1]
            : _u8[o + 4] | (_u8[o + 5] << 8);
          for (let j = 0; j < len; j++) {
            const c = _u32[_extraBase + s + j];
            if (c !== NULL) {
              visit(c);
              if (stopFlag) return;
            }
          }
        }
      }
    })(progIdx);
  }
  let _semView;
  function _semantic() {
    if (_semView !== undefined) return _semView;
    if (!(_flags & 8)) return (_semView = null);
    let dp = dOff;
    for (let j = 0; j < diagCount; j++) {
      dp += 9;
      const ml = dv.getUint32(dp, true); dp += 4 + ml;
      if (_u8[dp++]) { const hl = dv.getUint32(dp, true); dp += 4 + hl; }
      const lc = dv.getUint32(dp, true); dp += 4;
      for (let k = 0; k < lc; k++) {
        dp += 8;
        const lml = dv.getUint32(dp, true); dp += 4 + lml;
      }
    }
    let o = ((dp + 3) & ~3) >> 2;
    const scopeCount = _u32[o], symbolCount = _u32[o + 1],
          referenceCount = _u32[o + 2], declNodeCount = _u32[o + 3],
          importCount = _u32[o + 4], exportCount = _u32[o + 5],
          nodeScopeCount = _u32[o + 6];
    o += 8;
    const scopes = _u32.subarray(o, o + scopeCount * 4);
    o += scopeCount * 4;
    const symbols = _u32.subarray(o, o + symbolCount * 6);
    o += symbolCount * 6;
    const declNodes = _u32.subarray(o, o + declNodeCount);
    o += declNodeCount;
    const references = _u32.subarray(o, o + referenceCount * 6);
    o += referenceCount * 6;
    const imports = _u32.subarray(o, o + importCount * 8);
    o += importCount * 8;
    const exports = _u32.subarray(o, o + exportCount * 10);
    o += exportCount * 10;
    const nodeScopes = _u32.subarray(o, o + nodeScopeCount);
    o += nodeScopeCount;
    const _id = (v) => v === NULL ? null : v;
    return (_semView = {
      scope: {
        count: scopeCount,
        kind: (i) => SCOPE_KINDS[scopes[i * 4 + 3] & 255],
        strict: (i) => ((scopes[i * 4 + 3] >> 8) & 1) !== 0,
        node: (i) => node(scopes[i * 4 + 0]),
        nodeIndex: (i) => scopes[i * 4 + 0],
        parentId: (i) => _id(scopes[i * 4 + 1]),
        hoistTargetId: (i) => scopes[i * 4 + 2],
        start: (i) => startOf(scopes[i * 4 + 0]),
        end: (i) => endOf(scopes[i * 4 + 0]),
      },
      symbol: {
        count: symbolCount,
        name: (i) => str(symbols[i * 6 + 0], symbols[i * 6 + 1]),
        flags: (i) => symbols[i * 6 + 2],
        scopeId: (i) => symbols[i * 6 + 3],
        declCount: (i) => symbols[i * 6 + 5],
        declNode: (i, j) => node(declNodes[symbols[i * 6 + 4] + j]),
        declNodeIndex: (i, j) => declNodes[symbols[i * 6 + 4] + j],
      },
      reference: {
        count: referenceCount,
        name: (i) => str(references[i * 6 + 0], references[i * 6 + 1]),
        scopeId: (i) => references[i * 6 + 2],
        node: (i) => node(references[i * 6 + 3]),
        nodeIndex: (i) => references[i * 6 + 3],
        kind: (i) => IMPORT_EXPORT_KINDS[(references[i * 6 + 4] >> 0) & 1],
        isWrite: (i) => ((references[i * 6 + 4] >> 1) & 1) !== 0,
        symbolId: (i) => _id(references[i * 6 + 5]),
        start: (i) => startOf(references[i * 6 + 3]),
        end: (i) => endOf(references[i * 6 + 3]),
      },
      import: {
        count: importCount,
        symbolId: (i) => _id(imports[i * 8 + 0]),
        nameKind: (i) => NAME_KINDS[imports[i * 8 + 1] & 7],
        name: (i) => str(imports[i * 8 + 2], imports[i * 8 + 3]),
        specifier: (i) => str(imports[i * 8 + 4], imports[i * 8 + 5]),
        typeOnly: (i) => ((imports[i * 8 + 1] >> 3) & 1) !== 0,
        phase: (i) =>
          (imports[i * 8 + 1] >> 4) & 1
            ? IMPORT_PHASES[(imports[i * 8 + 1] >> 5) & 1]
            : null,
        node: (i) => node(imports[i * 8 + 6]),
      },
      export: {
        count: exportCount,
        nameKind: (i) => NAME_KINDS[exports[i * 10 + 0] & 7],
        fromKind: (i) => NAME_KINDS[(exports[i * 10 + 0] >> 3) & 7],
        typeOnly: (i) => ((exports[i * 10 + 0] >> 6) & 1) !== 0,
        name: (i) => str(exports[i * 10 + 1], exports[i * 10 + 2]),
        fromName: (i) => str(exports[i * 10 + 4], exports[i * 10 + 5]),
        specifier: (i) => str(exports[i * 10 + 6], exports[i * 10 + 7]),
        symbolId: (i) => _id(exports[i * 10 + 3]),
        node: (i) => node(exports[i * 10 + 8]),
      },
      nodeScope: (i) => nodeScopes[i],
    });
  }
  let _program, _lineStarts, _diagnostics, _comments;
  function _getLineStarts() {
    if (_lineStarts === undefined) _lineStarts = _decodeLineStarts();
    return _lineStarts;
  }
  return {
    get program() {
      return _program !== undefined ? _program : (_program = node(progIdx));
    },
    get comments() {
      return _comments !== undefined
        ? _comments
        : (_comments = _decodeComments());
    },
    get diagnostics() {
      return _diagnostics !== undefined
        ? _diagnostics
        : (_diagnostics = _decodeDiagnostics());
    },
    get lineStarts() { return _getLineStarts(); },
    locOf(offset) {
      const ls = _getLineStarts();
      let lo = 0, hi = ls.length;
      while (lo < hi) {
        const mid = (lo + hi) >>> 1;
        if (ls[mid] <= offset) lo = mid + 1; else hi = mid;
      }
      return { line: lo, column: offset - ls[lo - 1] };
    },
    scan,
    nodeOf: node,
    indexOf: (n) => _nodeIndexes.get(n),
    startOf, endOf, str,
    get semantic() { return _semantic(); },
  };
}
export { decode, SymbolFlags, CHILD_KEYS };
