// generates decode.js, a decoder that reads the binary AST buffer from Zig
// and constructs an ESTree JS object. uses the same comptime layout functions
// as the serializer (transfer.zig), guaranteeing the decoder matches the format.

const std = @import("std");
const parser = @import("parser");
const ast = parser.ast;
const rt = @import("transfer");

const Writer = std.Io.Writer;

pub fn main(init: std.process.Init) !void {
    const stdout = std.Io.File.stdout();
    var buf: [64 * 1024]u8 = undefined;
    var fw = stdout.writer(init.io, &buf);
    try generate(&fw.interface);
    try fw.flush();
}

fn generate(w: *Writer) !void {
    try w.writeAll(
        \\// generated by tools/gen_estree_decoder.zig, do not edit
        \\const NULL = 0xFFFFFFFF;
        \\
    );
    try writeLookupTables(w);
    try w.writeAll(
        \\const _td = new TextDecoder("utf-8");
        \\let _u8, _u32, _src, _srcLen, _nodesOff, _extraBase, _spOff, _pm;
        \\function _p(v) { return _pm ? _pm[v] : v; }
        \\function str(s, e) {
        \\  if (s === e) return "";
        \\  if (s < _srcLen) return _pm ? _src.slice(_pm[s], _pm[e]) : _src.slice(s, e);
        \\  return _td.decode(_u8.subarray(_spOff + s - _srcLen, _spOff + e - _srcLen));
        \\}
        \\function node(i) {
        \\  const o = _nodesOff + i * 32;
        \\  const tag = _u8[o];
        \\  const flags = _u8[o + 1];
        \\  const f0 = _u8[o + 2] | (_u8[o + 3] << 8);
        \\  const b = o >> 2;
        \\  const f1 = _u32[b + 1], f2 = _u32[b + 2], f3 = _u32[b + 3], f4 = _u32[b + 4], f5 = _u32[b + 5];
        \\  const start = _p(_u32[b + 6]), end = _p(_u32[b + 7]);
        \\  switch (tag) {
        \\
    );
    try writeNodeCases(w);
    try w.writeAll(
        \\  }
        \\}
        \\
    );
    try writeHelpers(w);
    try writeDecodeFunction(w);
    try w.writeAll("export { decode };\n");
}

// lookup tables

fn writeLookupTables(w: *Writer) !void {
    try writeArray(w, "BINARY_OPS", &.{ "==", "!=", "===", "!==", "<", "<=", ">", ">=", "+", "-", "*", "/", "%", "**", "|", "^", "&", "<<", ">>", ">>>", "in", "instanceof" });
    try writeArray(w, "LOGICAL_OPS", &.{ "&&", "||", "??" });
    try writeArray(w, "UNARY_OPS", &.{ "-", "+", "!", "~", "typeof", "void", "delete" });
    try writeArray(w, "UPDATE_OPS", &.{ "++", "--" });
    try writeArray(w, "ASSIGNMENT_OPS", &.{ "=", "+=", "-=", "*=", "/=", "%=", "**=", "<<=", ">>=", ">>>=", "|=", "^=", "&=", "||=", "&&=", "??=" });
    try writeArray(w, "VAR_KINDS", &.{ "var", "let", "const", "using", "await using" });
    try writeArray(w, "PROPERTY_KINDS", &.{ "init", "get", "set" });
    try writeArray(w, "METHOD_KINDS", &.{ "constructor", "method", "get", "set" });
    try writeArray(w, "FUNCTION_TYPES", &.{ "FunctionDeclaration", "FunctionExpression", "TSDeclareFunction", "TSEmptyBodyFunctionExpression" });
    try writeArray(w, "CLASS_TYPES", &.{ "ClassDeclaration", "ClassExpression" });
    try writeArray(w, "COMMENT_TYPES", &.{ "Line", "Block" });
    try writeArray(w, "SEVERITY", &.{ "error", "warning", "hint", "info" });
}

fn writeArray(w: *Writer, name: []const u8, items: []const []const u8) !void {
    try w.print("const {s} = [", .{name});
    for (items, 0..) |item, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("\"{s}\"", .{item});
    }
    try w.writeAll("];\n");
}

// node cases

fn writeNodeCases(w: *Writer) !void {
    @setEvalBranchQuota(100_000);
    const fields = @typeInfo(ast.NodeData).@"union".fields;
    inline for (fields, 0..) |field, tag| {
        try writeNodeCase(w, field.name, tag, field.type);
    }
}

fn writeNodeCase(w: *Writer, comptime name: []const u8, comptime tag: usize, comptime T: type) !void {
    // special cases first
    if (comptime isSpecial(name)) {
        try writeSpecialCase(w, name, tag, T);
        return;
    }
    // generic case
    const etype = comptime estreeType(name);
    try w.print("    case {d}: return {{ type: \"{s}\", start, end", .{ tag, etype });
    try writeStructFields(w, name, T);
    try w.writeAll(" };\n");
}

fn writeStructFields(w: *Writer, comptime tag_name: []const u8, comptime T: type) !void {
    if (@typeInfo(T) != .@"struct") return;
    inline for (std.meta.fields(T), 0..) |f, i| {
        const js = comptime estreeField(tag_name, f.name);
        try w.print(", {s}: ", .{js});
        try writeFieldExpr(w, tag_name, f.name, T, i, f.type);
    }
}

fn writeFieldExpr(w: *Writer, comptime tag_name: []const u8, comptime field_name: []const u8, comptime T: type, comptime i: usize, comptime F: type) !void {
    if (F == ast.NodeIndex) {
        const s = comptime rt.u32SlotForField(T, i) + 1;
        try w.print("f{d} !== NULL ? node(f{d}) : null", .{ s, s });
    } else if (F == ast.IndexRange) {
        const s = comptime rt.u32SlotForField(T, i) + 1;
        const fn_name = comptime if (isHoley(tag_name, field_name)) "nodeArrHoles" else "nodeArr";
        if (comptime rt.isFirstRange(T, i)) {
            try w.print("{s}(f{d}, f0)", .{ fn_name, s });
        } else {
            try w.print("{s}(f{d}, f{d})", .{ fn_name, s, s + 1 });
        }
    } else if (F == ast.String) {
        const s = comptime rt.u32SlotForField(T, i) + 1;
        try w.print("str(f{d}, f{d})", .{ s, s + 1 });
    } else if (F == bool) {
        const m = comptime @as(u32, 1) << @intCast(rt.flagBitForField(T, i));
        try w.print("!!(flags & {d})", .{m});
    } else if (comptime rt.isEnumType(F)) {
        const bit = comptime rt.flagBitForField(T, i);
        const width = comptime rt.enumBitWidth(F);
        const mask = comptime (@as(u32, 1) << @intCast(width)) - 1;
        const table = comptime enumTable(F);
        if (bit == 0) {
            try w.print("{s}[flags & {d}]", .{ table, mask });
        } else {
            try w.print("{s}[(flags >> {d}) & {d}]", .{ table, bit, mask });
        }
    } else if (F == ?ast.ImportPhase) {
        const bit = comptime rt.flagBitForField(T, i);
        try w.print("(flags & {d}) ? [\"source\", \"defer\"][(flags >> {d}) & 1] : null", .{ @as(u32, 1) << @intCast(bit), bit + 1 });
    } else if (F == ?ast.Hashbang) {
        const bit = comptime rt.flagBitForField(T, i);
        const s = comptime rt.u32SlotForField(T, i) + 1;
        try w.print("(flags & {d}) ? str(f{d}, f{d}) : null", .{ @as(u32, 1) << @intCast(bit), s, s + 1 });
    }
}

// special cases

fn isSpecial(comptime name: []const u8) bool {
    return isOneOf(name, &.{
        "parenthesized_expression", "formal_parameter",          "formal_parameters",
        "function",                 "arrow_function_expression", "program",
        "directive",                "string_literal",            "numeric_literal",
        "bigint_literal",           "boolean_literal",           "null_literal",
        "regexp_literal",           "template_element",          "class",
        "property_definition",      "unary_expression",          "binding_property",
        "array_pattern",            "object_pattern",            "jsx_opening_fragment",
        "jsx_text",
    });
}

fn writeSpecialCase(w: *Writer, comptime name: []const u8, comptime tag: usize, comptime T: type) !void {
    const eql = std.mem.eql;
    _ = T;

    if (comptime eql(u8, name, "parenthesized_expression")) {
        const s = comptime slotOf("parenthesized_expression", ast.ParenthesizedExpression, "expression");
        try w.print("    case {d}: return node(f{d});\n", .{ tag, s });
        //
    } else if (comptime eql(u8, name, "formal_parameter")) {
        const s = comptime slotOf("formal_parameter", ast.FormalParameter, "pattern");
        try w.print("    case {d}: return node(f{d});\n", .{ tag, s });
        //
    } else if (comptime eql(u8, name, "formal_parameters")) {
        try w.print("    case {d}: return {{ params: fnParams(i) }};\n", .{tag});
        //
    } else if (comptime eql(u8, name, "function")) {
        const sid = comptime slotOf("function", ast.Function, "id");
        const sp = comptime slotOf("function", ast.Function, "params");
        const sb = comptime slotOf("function", ast.Function, "body");
        const bit_gen = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.Function, fieldIdx(ast.Function, "generator")));
        const bit_async = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.Function, fieldIdx(ast.Function, "async")));
        const mask_type = comptime (@as(u32, 1) << @intCast(rt.enumBitWidth(ast.FunctionType))) - 1;
        try w.print(
            \\    case {d}: {{ const ft = flags & {d}; const r = {{ type: FUNCTION_TYPES[ft], start, end, id: f{d} !== NULL ? node(f{d}) : null, generator: !!(flags & {d}), async: !!(flags & {d}), params: f{d} !== NULL ? fnParams(f{d}) : [], body: f{d} !== NULL ? node(f{d}) : null, expression: false }}; if (ft === 2) r.declare = true; return r; }}
        , .{ tag, mask_type, sid, sid, bit_gen, bit_async, sp, sp, sb, sb });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "arrow_function_expression")) {
        const sp = comptime slotOf("arrow_function_expression", ast.ArrowFunctionExpression, "params");
        const sb = comptime slotOf("arrow_function_expression", ast.ArrowFunctionExpression, "body");
        const bit_expr = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.ArrowFunctionExpression, fieldIdx(ast.ArrowFunctionExpression, "expression")));
        const bit_async = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.ArrowFunctionExpression, fieldIdx(ast.ArrowFunctionExpression, "async")));
        try w.print(
            \\    case {d}: return {{ type: "ArrowFunctionExpression", start, end, id: null, generator: false, async: !!(flags & {d}), params: f{d} !== NULL ? fnParams(f{d}) : [], body: node(f{d}), expression: !!(flags & {d}) }};
        , .{ tag, bit_async, sp, sp, sb, bit_expr });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "program")) {
        // program has: source_type(enum), body(range), hashbang(?Hashbang)
        const body_slot = comptime slotOf("program", ast.Program, "body");
        const hb_bit = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.Program, fieldIdx(ast.Program, "hashbang")));
        const hb_slot = comptime rt.u32SlotForField(ast.Program, fieldIdx(ast.Program, "hashbang")) + 1;
        try w.print(
            \\    case {d}: return {{ type: "Program", start, end, sourceType: (flags & 1) ? "module" : "script", hashbang: (flags & {d}) ? str(f{d}, f{d}) : null, body: nodeArr(f{d}, f0) }};
        , .{ tag, hb_bit, hb_slot, hb_slot + 1, body_slot });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "directive")) {
        const se = comptime slotOf("directive", ast.Directive, "expression");
        const sv = comptime rt.u32SlotForField(ast.Directive, fieldIdx(ast.Directive, "value")) + 1;
        try w.print(
            \\    case {d}: return {{ type: "ExpressionStatement", start, end, expression: node(f{d}), directive: str(f{d}, f{d}) }};
        , .{ tag, se, sv, sv + 1 });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "string_literal")) {
        const s = comptime rt.u32SlotForField(ast.StringLiteral, fieldIdx(ast.StringLiteral, "value")) + 1;
        try w.print(
            \\    case {d}: return {{ type: "Literal", start, end, value: str(f{d}, f{d}), raw: _src.slice(start, end) }};
        , .{ tag, s, s + 1 });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "numeric_literal")) {
        try w.print(
            \\    case {d}: {{ const r = _src.slice(start, end); const v = +r; return {{ type: "Literal", start, end, value: v === v && isFinite(v) ? v : null, raw: r }}; }}
        , .{tag});
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "bigint_literal")) {
        const s = comptime rt.u32SlotForField(ast.BigIntLiteral, fieldIdx(ast.BigIntLiteral, "raw")) + 1;
        try w.print(
            \\    case {d}: {{ const r = _src.slice(start, end); return {{ type: "Literal", start, end, value: "(BigInt) " + r, raw: r, bigint: str(f{d}, f{d}).replace(/_/g, "") }}; }}
        , .{ tag, s, s + 1 });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "boolean_literal")) {
        const bit = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.BooleanLiteral, 0));
        try w.print(
            \\    case {d}: {{ const v = !!(flags & {d}); return {{ type: "Literal", start, end, value: v, raw: v ? "true" : "false" }}; }}
        , .{ tag, bit });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "null_literal")) {
        try w.print(
            \\    case {d}: return {{ type: "Literal", start, end, value: null, raw: "null" }};
        , .{tag});
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "regexp_literal")) {
        const sp = comptime rt.u32SlotForField(ast.RegExpLiteral, fieldIdx(ast.RegExpLiteral, "pattern")) + 1;
        const sf = comptime rt.u32SlotForField(ast.RegExpLiteral, fieldIdx(ast.RegExpLiteral, "flags")) + 1;
        try w.print(
            \\    case {d}: {{ const p = str(f{d}, f{d}), fl = str(f{d}, f{d}); return {{ type: "Literal", start, end, value: "(RegExp) /" + p + "/" + fl, raw: "/" + p + "/" + fl, regex: {{ pattern: p, flags: fl.split("").sort().join("") }} }}; }}
        , .{ tag, sp, sp + 1, sf, sf + 1 });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "template_element")) {
        const bit_tail = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.TemplateElement, fieldIdx(ast.TemplateElement, "tail")));
        const bit_undef = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.TemplateElement, fieldIdx(ast.TemplateElement, "is_cooked_undefined")));
        const sc = comptime rt.u32SlotForField(ast.TemplateElement, fieldIdx(ast.TemplateElement, "cooked")) + 1;
        try w.print(
            \\    case {d}: {{ const r = _src.slice(start, end).replace(/\r\n?/g, "\n"); return {{ type: "TemplateElement", start, end, value: {{ raw: r, cooked: (flags & {d}) ? null : str(f{d}, f{d}) }}, tail: !!(flags & {d}) }}; }}
        , .{ tag, bit_undef, sc, sc + 1, bit_tail });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "class")) {
        const mask = comptime (@as(u32, 1) << @intCast(rt.enumBitWidth(ast.ClassType))) - 1;
        const sd = comptime slotOfRange("class", ast.Class, "decorators");
        const si = comptime slotOf("class", ast.Class, "id");
        const ss = comptime slotOf("class", ast.Class, "super_class");
        const sb = comptime slotOf("class", ast.Class, "body");
        try w.print(
            \\    case {d}: return {{ type: CLASS_TYPES[flags & {d}], start, end, decorators: nodeArr(f{d}, f0), id: f{d} !== NULL ? node(f{d}) : null, superClass: f{d} !== NULL ? node(f{d}) : null, body: node(f{d}) }};
        , .{ tag, mask, sd, si, si, ss, ss, sb });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "property_definition")) {
        const bit_comp = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.PropertyDefinition, fieldIdx(ast.PropertyDefinition, "computed")));
        const bit_stat = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.PropertyDefinition, fieldIdx(ast.PropertyDefinition, "static")));
        const bit_acc = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.PropertyDefinition, fieldIdx(ast.PropertyDefinition, "accessor")));
        const sd = comptime slotOfRange("property_definition", ast.PropertyDefinition, "decorators");
        const sk = comptime slotOf("property_definition", ast.PropertyDefinition, "key");
        const sv = comptime slotOf("property_definition", ast.PropertyDefinition, "value");
        try w.print(
            \\    case {d}: return {{ type: (flags & {d}) ? "AccessorProperty" : "PropertyDefinition", start, end, decorators: nodeArr(f{d}, f0), key: node(f{d}), value: f{d} !== NULL ? node(f{d}) : null, computed: !!(flags & {d}), static: !!(flags & {d}) }};
        , .{ tag, bit_acc, sd, sk, sv, sv, bit_comp, bit_stat });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "unary_expression")) {
        const sa = comptime slotOf("unary_expression", ast.UnaryExpression, "argument");
        const mask = comptime (@as(u32, 1) << @intCast(rt.enumBitWidth(ast.UnaryOperator))) - 1;
        try w.print(
            \\    case {d}: return {{ type: "UnaryExpression", start, end, operator: UNARY_OPS[flags & {d}], prefix: true, argument: f{d} !== NULL ? node(f{d}) : null }};
        , .{ tag, mask, sa, sa });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "binding_property")) {
        const sk = comptime slotOf("binding_property", ast.BindingProperty, "key");
        const sv = comptime slotOf("binding_property", ast.BindingProperty, "value");
        const bit_sh = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.BindingProperty, fieldIdx(ast.BindingProperty, "shorthand")));
        const bit_comp = comptime @as(u32, 1) << @intCast(rt.flagBitForField(ast.BindingProperty, fieldIdx(ast.BindingProperty, "computed")));
        try w.print(
            \\    case {d}: return {{ type: "Property", start, end, kind: "init", key: node(f{d}), value: node(f{d}), method: false, shorthand: !!(flags & {d}), computed: !!(flags & {d}) }};
        , .{ tag, sk, sv, bit_sh, bit_comp });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "array_pattern")) {
        const se = comptime slotOfRange("array_pattern", ast.ArrayPattern, "elements");
        const sr = comptime slotOf("array_pattern", ast.ArrayPattern, "rest");
        try w.print(
            \\    case {d}: {{ const el = nodeArrHoles(f{d}, f0); if (f{d} !== NULL) el.push(node(f{d})); return {{ type: "ArrayPattern", start, end, elements: el }}; }}
        , .{ tag, se, sr, sr });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "object_pattern")) {
        const sp = comptime slotOfRange("object_pattern", ast.ObjectPattern, "properties");
        const sr = comptime slotOf("object_pattern", ast.ObjectPattern, "rest");
        try w.print(
            \\    case {d}: {{ const pr = nodeArr(f{d}, f0); if (f{d} !== NULL) pr.push(node(f{d})); return {{ type: "ObjectPattern", start, end, properties: pr }}; }}
        , .{ tag, sp, sr, sr });
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "jsx_opening_fragment")) {
        try w.print(
            \\    case {d}: return {{ type: "JSXOpeningFragment", start, end, attributes: [], selfClosing: false }};
        , .{tag});
        try w.writeByte('\n');
        //
    } else if (comptime eql(u8, name, "jsx_text")) {
        const s = comptime rt.u32SlotForField(ast.JSXText, fieldIdx(ast.JSXText, "value")) + 1;
        try w.print(
            \\    case {d}: {{ const t = str(f{d}, f{d}); return {{ type: "JSXText", start, end, value: t, raw: t }}; }}
        , .{ tag, s, s + 1 });
        try w.writeByte('\n');
    }
}

// helpers and decode function

fn writeHelpers(w: *Writer) !void {
    // fnParams: uses comptime-computed offsets for FormalParameters and FormalParameter
    const fp_items_slot = comptime rt.u32SlotForField(ast.FormalParameters, fieldIdx(ast.FormalParameters, "items")) + 1;
    const fp_rest_slot = comptime rt.u32SlotForField(ast.FormalParameters, fieldIdx(ast.FormalParameters, "rest")) + 1;
    const fparam_pattern_slot = comptime rt.u32SlotForField(ast.FormalParameter, fieldIdx(ast.FormalParameter, "pattern")) + 1;

    try w.print(
        \\function nodeArr(s, len) {{
        \\  const r = new Array(len);
        \\  for (let j = 0; j < len; j++) r[j] = node(_u32[_extraBase + s + j]);
        \\  return r;
        \\}}
        \\function nodeArrHoles(s, len) {{
        \\  const r = new Array(len);
        \\  for (let j = 0; j < len; j++) {{ const x = _u32[_extraBase + s + j]; r[j] = x !== NULL ? node(x) : null; }}
        \\  return r;
        \\}}
        \\function fnParams(idx) {{
        \\  const po = _nodesOff + idx * 32;
        \\  const len = _u8[po + 2] | (_u8[po + 3] << 8);
        \\  const pb = po >> 2;
        \\  const iStart = _u32[pb + {d}], rest = _u32[pb + {d}];
        \\  const p = [];
        \\  for (let j = 0; j < len; j++) {{
        \\    const fi = _u32[_extraBase + iStart + j];
        \\    p.push(node(_u32[(_nodesOff + fi * 32 >> 2) + {d}]));
        \\  }}
        \\  if (rest !== NULL) p.push(node(rest));
        \\  return p;
        \\}}
        \\
    , .{ fp_items_slot, fp_rest_slot, fparam_pattern_slot });
}

fn writeDecodeFunction(w: *Writer) !void {
    try w.print(
        \\function buildPosMap(src, byteLen) {{
        \\  const m = new Uint32Array(byteLen + 1);
        \\  let bp = 0, u16p = 0;
        \\  for (let i = 0; i < src.length; i++) {{
        \\    m[bp] = u16p;
        \\    const cp = src.codePointAt(i);
        \\    let bytes = 1;
        \\    if (cp > 0x7F) {{ if (cp > 0x7FF) {{ bytes = cp > 0xFFFF ? 4 : 3; }} else {{ bytes = 2; }} }}
        \\    const units = bytes === 4 ? 2 : 1;
        \\    u16p += units;
        \\    for (let k = 1; k < bytes; k++) m[bp + k] = u16p;
        \\    bp += bytes;
        \\    if (bytes === 4) i++;
        \\  }}
        \\  m[byteLen] = u16p;
        \\  return m;
        \\}}
        \\function decode(buffer, source) {{
        \\  _u8 = new Uint8Array(buffer);
        \\  const aLen = (buffer.byteLength >> 2) << 2;
        \\  _u32 = new Uint32Array(buffer, 0, aLen >> 2);
        \\  _src = source;
        \\  _srcLen = _u32[5];
        \\  const nodeCount = _u32[2], extraCount = _u32[3], spLen = _u32[4];
        \\  const commentCount = _u32[6], diagCount = _u32[7], progIdx = _u32[8];
        \\  _pm = (_u32[9] & 1) ? null : buildPosMap(source, _srcLen);
        \\  _nodesOff = {d};
        \\  const eOff = _nodesOff + nodeCount * 32;
        \\  _extraBase = eOff >> 2;
        \\  _spOff = eOff + extraCount * 4;
        \\  const cOff = _spOff + spLen, dOff = cOff + commentCount * 20;
        \\  const dv = new DataView(buffer);
        \\  const comments = new Array(commentCount);
        \\  for (let j = 0; j < commentCount; j++) {{
        \\    const o = cOff + j * 20;
        \\    comments[j] = {{ type: COMMENT_TYPES[_u8[o]], value: str(dv.getUint32(o + 12, true), dv.getUint32(o + 16, true)), start: _p(dv.getUint32(o + 4, true)), end: _p(dv.getUint32(o + 8, true)) }};
        \\  }}
        \\  const diagnostics = new Array(diagCount);
        \\  let dp = dOff;
        \\  for (let j = 0; j < diagCount; j++) {{
        \\    const sev = SEVERITY[_u8[dp]]; dp++;
        \\    const ds = _p(dv.getUint32(dp, true)); dp += 4;
        \\    const de = _p(dv.getUint32(dp, true)); dp += 4;
        \\    const ml = dv.getUint32(dp, true); dp += 4;
        \\    const msg = _td.decode(_u8.subarray(dp, dp + ml)); dp += ml;
        \\    const hh = _u8[dp]; dp++;
        \\    let help = null;
        \\    if (hh) {{ const hl = dv.getUint32(dp, true); dp += 4; help = _td.decode(_u8.subarray(dp, dp + hl)); dp += hl; }}
        \\    const lc = dv.getUint32(dp, true); dp += 4;
        \\    const labels = new Array(lc);
        \\    for (let k = 0; k < lc; k++) {{
        \\      const ls = _p(dv.getUint32(dp, true)); dp += 4;
        \\      const le = _p(dv.getUint32(dp, true)); dp += 4;
        \\      const lml = dv.getUint32(dp, true); dp += 4;
        \\      labels[k] = {{ start: ls, end: le, message: _td.decode(_u8.subarray(dp, dp + lml)) }}; dp += lml;
        \\    }}
        \\    diagnostics[j] = {{ severity: sev, message: msg, start: ds, end: de, help, labels }};
        \\  }}
        \\  const program = node(progIdx);
        \\  _u8 = _u32 = _src = _pm = null;
        \\  return {{ program, comments, diagnostics }};
        \\}}
        \\
    , .{rt.HEADER_SIZE});
}

// comptime naming helpers

fn estreeType(comptime name: []const u8) []const u8 {
    const overrides = .{
        .{ "function_body", "BlockStatement" },
        .{ "binding_rest_element", "RestElement" },
        .{ "object_property", "Property" },
        .{ "identifier_reference", "Identifier" },
        .{ "binding_identifier", "Identifier" },
        .{ "identifier_name", "Identifier" },
        .{ "label_identifier", "Identifier" },
    };
    inline for (overrides) |o| {
        if (comptime std.mem.eql(u8, name, o[0])) return o[1];
    }
    // jsx/ts prefixes need caps
    if (comptime std.mem.startsWith(u8, name, "jsx_")) return "JSX" ++ snakeToPascal(name[4..]);
    if (comptime std.mem.startsWith(u8, name, "ts_")) return "TS" ++ snakeToPascal(name[3..]);
    return snakeToPascal(name);
}

fn estreeField(comptime tag_name: []const u8, comptime field_name: []const u8) []const u8 {
    if (comptime std.mem.eql(u8, tag_name, "variable_declaration") and std.mem.eql(u8, field_name, "declarators"))
        return "declarations";
    return snakeToCamel(field_name);
}

fn snakeToPascal(comptime name: []const u8) []const u8 {
    return comptime snakeConvert(name, true);
}

fn snakeToCamel(comptime name: []const u8) []const u8 {
    return comptime snakeConvert(name, false);
}

fn snakeConvert(comptime name: []const u8, comptime pascal: bool) []const u8 {
    comptime {
        var result: [name.len]u8 = undefined;
        var len: usize = 0;
        var cap = pascal;
        for (name) |c| {
            if (c == '_') {
                cap = true;
            } else {
                result[len] = if (cap) std.ascii.toUpper(c) else c;
                cap = false;
                len += 1;
            }
        }
        const final = result[0..len].*;
        return &final;
    }
}

fn enumTable(comptime E: type) []const u8 {
    if (E == ast.BinaryOperator) return "BINARY_OPS";
    if (E == ast.LogicalOperator) return "LOGICAL_OPS";
    if (E == ast.UnaryOperator) return "UNARY_OPS";
    if (E == ast.UpdateOperator) return "UPDATE_OPS";
    if (E == ast.AssignmentOperator) return "ASSIGNMENT_OPS";
    if (E == ast.VariableKind) return "VAR_KINDS";
    if (E == ast.PropertyKind) return "PROPERTY_KINDS";
    if (E == ast.MethodDefinitionKind) return "METHOD_KINDS";
    if (E == ast.FunctionType) return "FUNCTION_TYPES";
    if (E == ast.ClassType) return "CLASS_TYPES";
    @compileError("no lookup table for enum");
}

fn isHoley(comptime tag: []const u8, comptime field: []const u8) bool {
    return (std.mem.eql(u8, tag, "array_expression") and std.mem.eql(u8, field, "elements"));
}

fn isOneOf(comptime name: []const u8, comptime list: []const []const u8) bool {
    for (list) |item| {
        if (std.mem.eql(u8, name, item)) return true;
    }
    return false;
}

/// helper: get the u32 slot + 1 (JS field name) for a named NodeIndex field
fn slotOf(comptime tag_name: []const u8, comptime T: type, comptime field_name: []const u8) u32 {
    _ = tag_name;
    return rt.u32SlotForField(T, fieldIdx(T, field_name)) + 1;
}

/// helper: get the u32 slot + 1 for the start of a named IndexRange field (first range only)
fn slotOfRange(comptime tag_name: []const u8, comptime T: type, comptime field_name: []const u8) u32 {
    _ = tag_name;
    return rt.u32SlotForField(T, fieldIdx(T, field_name)) + 1;
}

/// find field index by name
fn fieldIdx(comptime T: type, comptime name: []const u8) usize {
    for (std.meta.fields(T), 0..) |f, i| {
        if (std.mem.eql(u8, f.name, name)) return i;
    }
    @compileError("field '" ++ name ++ "' not found");
}
