// generates tokens.d.ts for @yuku-toolchain/types, the TokenKind map the decoder exports

const std = @import("std");
const parser = @import("parser");
const decoder = @import("estree/decoder.zig");

pub fn main(init: std.process.Init) !void {
    @setEvalBranchQuota(50_000);
    const stdout = std.Io.File.stdout();
    var buf: [64 * 1024]u8 = undefined;
    var fw = stdout.writer(init.io, &buf);
    const w = &fw.interface;

    try w.writeAll(
        \\// generated by tools/gen_token_types.zig, do not edit
        \\
        \\/** Every token kind by name. Values may change between versions, compare by name. */
        \\export interface TokenKindMap {
        \\
    );
    inline for (@typeInfo(parser.ast.TokenTag).@"enum".fields) |field| {
        try w.print("  readonly {s}: {d};\n", .{ comptime decoder.tokenName(field.name), field.value });
    }
    try w.writeAll("}\n");
    try fw.flush();
}
