// generates decode.js, a decoder that reads the binary AST buffer passed from Zig
// and constructs an ESTree JS object. uses the same comptime layout functions
// as the serializer (transfer.zig), guaranteeing the decoder matches the format.

const std = @import("std");
const parser = @import("parser");
const ast = parser.ast;
const rt = @import("transfer");

const Writer = std.Io.Writer;

pub fn main(init: std.process.Init) !void {
    const stdout = std.Io.File.stdout();
    var buf: [64 * 1024]u8 = undefined;
    var fw = stdout.writer(init.io, &buf);
    try generate(&fw.interface);
    try fw.flush();
}

fn generate(w: *Writer) !void {
    try w.writeAll(
        \\// generated by tools/gen_estree_decoder.zig, do not edit
        \\const NULL = 0xFFFFFFFF;
        \\
    );
    try writeLookupTables(w);
    try writeRuntime(w);
    try writeNodeCases(w);
    try w.writeAll(
        \\  }
        \\}
        \\
    );
    try writeHelpers(w);
    try writeDecodeFunction(w);
    try w.writeAll("export { decode };\n");
}

/// emits the fixed JS runtime: `_poolDecode` and the `node(i)` switch prelude.
/// all PackedNode layout values are substituted from `transfer.zig` so the
/// decoder stays in sync with the binary format automatically.
fn writeRuntime(w: *Writer) !void {
    try w.print(
        \\const _td = new TextDecoder("utf-8", {{ ignoreBOM: true }});
        \\let _u8, _u32, _src, _srcLen, _nodesOff, _extraBase, _spOff, _p, _isTs, str;
        \\function _poolDecode(s, e) {{
        \\  const a = _spOff + s - _srcLen, b = _spOff + e - _srcLen;
        \\  let hasEd = false;
        \\  for (let i = a; i < b; i++) if (_u8[i] === 0xED) {{ hasEd = true; break; }}
        \\  if (!hasEd) return _td.decode(_u8.subarray(a, b));
        \\  let r = "";
        \\  for (let i = a; i < b; ) {{
        \\    const c = _u8[i];
        \\    if (c < 0x80) {{ r += String.fromCharCode(c); i++; }}
        \\    else if (c < 0xE0) {{ r += String.fromCharCode(((c & 0x1F) << 6) | (_u8[i+1] & 0x3F)); i += 2; }}
        \\    else if (c < 0xF0) {{ r += String.fromCharCode(((c & 0x0F) << 12) | ((_u8[i+1] & 0x3F) << 6) | (_u8[i+2] & 0x3F)); i += 3; }}
        \\    else {{ r += String.fromCodePoint(((c & 0x07) << 18) | ((_u8[i+1] & 0x3F) << 12) | ((_u8[i+2] & 0x3F) << 6) | (_u8[i+3] & 0x3F)); i += 4; }}
        \\  }}
        \\  return r;
        \\}}
        \\function node(i) {{
        \\  const o = _nodesOff + i * {[size]d};
        \\  const tag = _u8[o];
        \\  const flags = _u8[o + {[fl]d}] | (_u8[o + {[fl1]d}] << 8);
        \\  const f0 = _u8[o + {[f0]d}] | (_u8[o + {[f01]d}] << 8);
        \\  const b = o >> 2;
        \\  const f1 = _u32[b + {[d0]d}], f2 = _u32[b + {[d1]d}], f3 = _u32[b + {[d2]d}], f4 = _u32[b + {[d3]d}], f5 = _u32[b + {[d4]d}], f6 = _u32[b + {[d5]d}], f7 = _u32[b + {[d6]d}], f8 = _u32[b + {[d7]d}];
        \\  const start = _p(_u32[b + {[ss]d}]), end = _p(_u32[b + {[se]d}]);
        \\  switch (tag) {{
        \\
    , .{
        .size = rt.NODE_SIZE,
        .fl = rt.NODE_FLAGS_OFFSET,
        .fl1 = rt.NODE_FLAGS_OFFSET + 1,
        .f0 = rt.NODE_FIELD0_OFFSET,
        .f01 = rt.NODE_FIELD0_OFFSET + 1,
        .d0 = rt.NODE_HEADER_U32S,
        .d1 = rt.NODE_HEADER_U32S + 1,
        .d2 = rt.NODE_HEADER_U32S + 2,
        .d3 = rt.NODE_HEADER_U32S + 3,
        .d4 = rt.NODE_HEADER_U32S + 4,
        .d5 = rt.NODE_HEADER_U32S + 5,
        .d6 = rt.NODE_HEADER_U32S + 6,
        .d7 = rt.NODE_HEADER_U32S + 7,
        .ss = rt.NODE_SPAN_START_U32,
        .se = rt.NODE_SPAN_END_U32,
    });
}

// lookup tables

fn writeLookupTables(w: *Writer) !void {
    try writeArray(w, "BINARY_OPS", &.{ "==", "!=", "===", "!==", "<", "<=", ">", ">=", "+", "-", "*", "/", "%", "**", "|", "^", "&", "<<", ">>", ">>>", "in", "instanceof" });
    try writeArray(w, "LOGICAL_OPS", &.{ "&&", "||", "??" });
    try writeArray(w, "UNARY_OPS", &.{ "-", "+", "!", "~", "typeof", "void", "delete" });
    try writeArray(w, "UPDATE_OPS", &.{ "++", "--" });
    try writeArray(w, "ASSIGNMENT_OPS", &.{ "=", "+=", "-=", "*=", "/=", "%=", "**=", "<<=", ">>=", ">>>=", "|=", "^=", "&=", "||=", "&&=", "??=" });
    try writeArray(w, "VAR_KINDS", &.{ "var", "let", "const", "using", "await using" });
    try writeArray(w, "PROPERTY_KINDS", &.{ "init", "get", "set" });
    try writeArray(w, "METHOD_KINDS", &.{ "constructor", "method", "get", "set" });
    try writeArray(w, "FUNCTION_TYPES", &.{ "FunctionDeclaration", "FunctionExpression", "TSDeclareFunction", "TSEmptyBodyFunctionExpression" });
    try writeArray(w, "CLASS_TYPES", &.{ "ClassDeclaration", "ClassExpression" });
    try writeArray(w, "COMMENT_TYPES", &.{ "Line", "Block" });
    try writeArray(w, "SEVERITY", &.{ "error", "warning", "hint", "info" });
    try writeArrayRaw(w, "IMPORT_EXPORT_KINDS", &.{ "\"value\"", "\"type\"" });
    try writeArrayRaw(w, "ACCESSIBILITY", &.{ "null", "\"public\"", "\"private\"", "\"protected\"" });
}

fn writeArray(w: *Writer, name: []const u8, items: []const []const u8) !void {
    try w.print("const {s} = [", .{name});
    for (items, 0..) |item, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("\"{s}\"", .{item});
    }
    try w.writeAll("];\n");
}

/// elements written raw (pre-quoted strings, or literals like `null`).
fn writeArrayRaw(w: *Writer, name: []const u8, items: []const []const u8) !void {
    try w.print("const {s} = [", .{name});
    for (items, 0..) |item, i| {
        if (i > 0) try w.writeAll(", ");
        try w.writeAll(item);
    }
    try w.writeAll("];\n");
}

// node cases: for each union variant, emit a `case N:` body.
// custom shapes live in `writeSpecialCase`; everything else goes through
// `writeGenericCase`, a comptime struct->object mapper.

fn writeNodeCases(w: *Writer) !void {
    @setEvalBranchQuota(100_000);
    inline for (@typeInfo(ast.NodeData).@"union".fields, 0..) |field, tag| {
        if (comptime isSpecial(field.name)) {
            try writeSpecialCase(w, field.name, tag);
        } else {
            try writeGenericCase(w, field.name, tag, field.type);
        }
    }
}

fn writeGenericCase(w: *Writer, comptime name: []const u8, comptime tag: usize, comptime T: type) !void {
    const etype = comptime estreeType(name);
    const has_ts = comptime hasAnyTsField(name, T) or tsExtrasOf(name).len > 0;
    if (!has_ts) {
        try w.print("    case {d}: return {{ type: \"{s}\", start, end", .{ tag, etype });
        try writeStructFields(w, name, T, .all);
        try w.writeAll(" };\n");
        return;
    }
    try w.print("    case {d}: {{ const r = {{ type: \"{s}\", start, end", .{ tag, etype });
    try writeStructFields(w, name, T, .non_ts);
    try w.writeAll(" }; if (_isTs) { ");
    try writeStructFields(w, name, T, .ts_only);
    try writeTsExtras(w, name);
    try w.writeAll("} return r; }\n");
}

const FieldSelection = enum { all, non_ts, ts_only };

fn writeStructFields(w: *Writer, comptime tag_name: []const u8, comptime T: type, comptime sel: FieldSelection) !void {
    if (@typeInfo(T) != .@"struct") return;
    inline for (std.meta.fields(T), 0..) |f, i| {
        const is_ts = comptime isTsField(tag_name, f.name);
        const include = switch (sel) {
            .all => true,
            .non_ts => !is_ts,
            .ts_only => is_ts,
        };
        if (!include) continue;
        const js = comptime estreeField(tag_name, f.name);
        if (sel == .ts_only) try w.print("r.{s} = ", .{js}) else try w.print(", {s}: ", .{js});
        try writeFieldExpr(w, tag_name, f.name, T, i, f.type);
        if (sel == .ts_only) try w.writeAll("; ");
    }
}

fn writeFieldExpr(w: *Writer, comptime tag_name: []const u8, comptime field_name: []const u8, comptime T: type, comptime i: usize, comptime F: type) !void {
    const s = comptime rt.u32SlotForField(T, i) + 1;
    if (F == ast.NodeIndex) {
        try w.print("f{d} !== NULL ? node(f{d}) : null", .{ s, s });
    } else if (F == ast.IndexRange) {
        const fn_name = comptime if (isHoley(tag_name, field_name)) "nodeArrHoles" else "nodeArr";
        if (comptime rt.isFirstRange(T, i)) {
            try w.print("{s}(f{d}, f0)", .{ fn_name, s });
        } else {
            try w.print("{s}(f{d}, f{d})", .{ fn_name, s, s + 1 });
        }
    } else if (F == ast.String) {
        try w.print("str(f{d}, f{d})", .{ s, s + 1 });
    } else if (F == bool) {
        try w.print("!!(flags & {d})", .{comptime flagMaskAt(T, i)});
    } else if (comptime rt.isEnumType(F)) {
        const bit = comptime rt.flagBitForField(T, i);
        const mask = comptime enumMask(F);
        const table = comptime enumTable(F);
        if (bit == 0) {
            try w.print("{s}[flags & {d}]", .{ table, mask });
        } else {
            try w.print("{s}[(flags >> {d}) & {d}]", .{ table, bit, mask });
        }
    } else if (F == ?ast.ImportPhase) {
        const bit = comptime rt.flagBitForField(T, i);
        try w.print("(flags & {d}) ? [\"source\", \"defer\"][(flags >> {d}) & 1] : null", .{ @as(u32, 1) << @intCast(bit), bit + 1 });
    } else if (F == ?ast.Hashbang) {
        const bit = comptime rt.flagBitForField(T, i);
        try w.print("(flags & {d}) ? str(f{d}, f{d}) : null", .{ @as(u32, 1) << @intCast(bit), s, s + 1 });
    } else {
        @compileError("unsupported field type in decoder: " ++ @typeName(F));
    }
}

// special cases, nodes whose ESTree shape doesn't reduce to a struct -> object
// mapping. each branch emits a single JS `case N: ...` line.

fn isSpecial(comptime name: []const u8) bool {
    inline for ([_][]const u8{
        "formal_parameter", "formal_parameters", "function",            "arrow_function_expression",
        "program",          "directive",         "string_literal",      "numeric_literal",
        "bigint_literal",   "boolean_literal",   "null_literal",        "regexp_literal",
        "template_element", "class",             "property_definition", "unary_expression",
        "binding_property", "array_pattern",     "object_pattern",      "jsx_text",
    }) |s| if (std.mem.eql(u8, s, name)) return true;
    return false;
}

fn writeSpecialCase(w: *Writer, comptime name: []const u8, comptime tag: usize) !void {
    const eql = std.mem.eql;
    if (comptime eql(u8, name, "formal_parameter")) {
        const sp = comptime slotOf(ast.FormalParameter, "pattern");
        try emit(w, "    case {d}: return node(f{d});", .{ tag, sp });
    } else if (comptime eql(u8, name, "formal_parameters")) {
        try emit(w, "    case {d}: return {{ params: fnParams(i) }};", .{tag});
    } else if (comptime eql(u8, name, "function")) {
        const sid = comptime slotOf(ast.Function, "id");
        const sp = comptime slotOf(ast.Function, "params");
        const sb = comptime slotOf(ast.Function, "body");
        const stp = comptime slotOf(ast.Function, "type_parameters");
        const srt = comptime slotOf(ast.Function, "return_type");
        const bg = comptime flagMask(ast.Function, "generator");
        const ba = comptime flagMask(ast.Function, "async");
        try emit(w,
            \\    case {d}: {{ const ft = flags & {d}; const r = {{ type: FUNCTION_TYPES[ft], start, end, id: f{d} !== NULL ? node(f{d}) : null, generator: !!(flags & {d}), async: !!(flags & {d}), params: f{d} !== NULL ? fnParams(f{d}) : [], body: f{d} !== NULL ? node(f{d}) : null, expression: false }}; if (_isTs) {{ r.typeParameters = f{d} !== NULL ? node(f{d}) : null; r.returnType = f{d} !== NULL ? node(f{d}) : null; r.declare = ft === 2; }} return r; }}
        , .{ tag, comptime enumMask(ast.FunctionType), sid, sid, bg, ba, sp, sp, sb, sb, stp, stp, srt, srt });
    } else if (comptime eql(u8, name, "arrow_function_expression")) {
        const sp = comptime slotOf(ast.ArrowFunctionExpression, "params");
        const sb = comptime slotOf(ast.ArrowFunctionExpression, "body");
        const stp = comptime slotOf(ast.ArrowFunctionExpression, "type_parameters");
        const srt = comptime slotOf(ast.ArrowFunctionExpression, "return_type");
        const be = comptime flagMask(ast.ArrowFunctionExpression, "expression");
        const ba = comptime flagMask(ast.ArrowFunctionExpression, "async");
        try emit(w,
            \\    case {d}: {{ const r = {{ type: "ArrowFunctionExpression", start, end, id: null, generator: false, async: !!(flags & {d}), params: f{d} !== NULL ? fnParams(f{d}) : [], body: node(f{d}), expression: !!(flags & {d}) }}; if (_isTs) {{ r.typeParameters = f{d} !== NULL ? node(f{d}) : null; r.returnType = f{d} !== NULL ? node(f{d}) : null; }} return r; }}
        , .{ tag, ba, sp, sp, sb, be, stp, stp, srt, srt });
    } else if (comptime eql(u8, name, "program")) {
        const sb = comptime slotOf(ast.Program, "body");
        const hs = comptime slotOf(ast.Program, "hashbang");
        try emit(w,
            \\    case {d}: return {{ type: "Program", start, end, sourceType: (flags & 1) ? "module" : "script", hashbang: (flags & {d}) ? str(f{d}, f{d}) : null, body: nodeArr(f{d}, f0) }};
        , .{ tag, comptime flagMask(ast.Program, "hashbang"), hs, hs + 1, sb });
    } else if (comptime eql(u8, name, "directive")) {
        const se = comptime slotOf(ast.Directive, "expression");
        const sv = comptime slotOf(ast.Directive, "value");
        try emit(w,
            \\    case {d}: return {{ type: "ExpressionStatement", start, end, expression: node(f{d}), directive: str(f{d}, f{d}) }};
        , .{ tag, se, sv, sv + 1 });
    } else if (comptime eql(u8, name, "string_literal")) {
        const sv = comptime slotOf(ast.StringLiteral, "value");
        try emit(w,
            \\    case {d}: return {{ type: "Literal", start, end, value: str(f{d}, f{d}), raw: _src.slice(start, end) }};
        , .{ tag, sv, sv + 1 });
    } else if (comptime eql(u8, name, "numeric_literal")) {
        try emit(w,
            \\    case {d}: {{ const r = _src.slice(start, end); const s = r.indexOf("_") === -1 ? r : r.replace(/_/g, ""); const v = (flags & {d}) === 2 && s[1] !== "o" && s[1] !== "O" ? parseInt(s.slice(1), 8) : +s; return {{ type: "Literal", start, end, value: v === v && isFinite(v) ? v : null, raw: r }}; }}
        , .{ tag, comptime enumMask(ast.NumericLiteral.Kind) });
    } else if (comptime eql(u8, name, "bigint_literal")) {
        const sr = comptime slotOf(ast.BigIntLiteral, "raw");
        try emit(w,
            \\    case {d}: {{ const r = _src.slice(start, end); const d = str(f{d}, f{d}).replace(/_/g, ""); const v = BigInt(d); return {{ type: "Literal", start, end, value: v, raw: r, bigint: v.toString() }}; }}
        , .{ tag, sr, sr + 1 });
    } else if (comptime eql(u8, name, "boolean_literal")) {
        try emit(w,
            \\    case {d}: {{ const v = !!(flags & {d}); return {{ type: "Literal", start, end, value: v, raw: v ? "true" : "false" }}; }}
        , .{ tag, comptime flagMaskAt(ast.BooleanLiteral, 0) });
    } else if (comptime eql(u8, name, "null_literal")) {
        try emit(w,
            \\    case {d}: return {{ type: "Literal", start, end, value: null, raw: "null" }};
        , .{tag});
    } else if (comptime eql(u8, name, "regexp_literal")) {
        const sp = comptime slotOf(ast.RegExpLiteral, "pattern");
        const sf = comptime slotOf(ast.RegExpLiteral, "flags");
        try emit(w,
            \\    case {d}: {{ const p = str(f{d}, f{d}), fl = str(f{d}, f{d}); let v = null; try {{ v = new RegExp(p, fl); }} catch {{}} return {{ type: "Literal", start, end, value: v, raw: "/" + p + "/" + fl, regex: {{ pattern: p, flags: fl.split("").sort().join("") }} }}; }}
        , .{ tag, sp, sp + 1, sf, sf + 1 });
    } else if (comptime eql(u8, name, "template_element")) {
        const sc = comptime slotOf(ast.TemplateElement, "cooked");
        try emit(w,
            \\    case {d}: {{ const raw = _src.slice(start, end).replace(/\r\n?/g, "\n"); const tl = !!(flags & {d}); const s = _isTs ? start - 1 : start; const e = _isTs ? (tl ? end + 1 : end + 2) : end; return {{ type: "TemplateElement", start: s, end: e, value: {{ raw, cooked: (flags & {d}) ? null : str(f{d}, f{d}) }}, tail: tl }}; }}
        , .{ tag, comptime flagMask(ast.TemplateElement, "tail"), comptime flagMask(ast.TemplateElement, "is_cooked_undefined"), sc, sc + 1 });
    } else if (comptime eql(u8, name, "class")) {
        const sd = comptime slotOf(ast.Class, "decorators");
        const si = comptime slotOf(ast.Class, "id");
        const ss = comptime slotOf(ast.Class, "super_class");
        const sb = comptime slotOf(ast.Class, "body");
        const stp = comptime slotOf(ast.Class, "type_parameters");
        const ssta = comptime slotOf(ast.Class, "super_type_arguments");
        const simp = comptime slotOf(ast.Class, "implements");
        try emit(w,
            \\    case {d}: {{ const r = {{ type: CLASS_TYPES[flags & {d}], start, end, decorators: nodeArr(f{d}, f0), id: f{d} !== NULL ? node(f{d}) : null, superClass: f{d} !== NULL ? node(f{d}) : null, body: node(f{d}) }}; if (_isTs) {{ r.typeParameters = f{d} !== NULL ? node(f{d}) : null; r.superTypeArguments = f{d} !== NULL ? node(f{d}) : null; r.implements = nodeArr(f{d}, f{d}); r.abstract = !!(flags & {d}); r.declare = !!(flags & {d}); }} return r; }}
        , .{ tag, comptime enumMask(ast.ClassType), sd, si, si, ss, ss, sb, stp, stp, ssta, ssta, simp, simp + 1, comptime flagMask(ast.Class, "abstract"), comptime flagMask(ast.Class, "declare") });
    } else if (comptime eql(u8, name, "property_definition")) {
        const P = ast.PropertyDefinition;
        const sd = comptime slotOf(P, "decorators");
        const sk = comptime slotOf(P, "key");
        const sv = comptime slotOf(P, "value");
        const sta = comptime slotOf(P, "type_annotation");
        try emit(w,
            \\    case {d}: {{ const r = {{ type: (flags & {d}) ? "AccessorProperty" : "PropertyDefinition", start, end, decorators: nodeArr(f{d}, f0), key: node(f{d}), value: f{d} !== NULL ? node(f{d}) : null, computed: !!(flags & {d}), static: !!(flags & {d}) }}; if (_isTs) {{ r.typeAnnotation = f{d} !== NULL ? node(f{d}) : null; r.declare = !!(flags & {d}); r.override = !!(flags & {d}); r.optional = !!(flags & {d}); r.definite = !!(flags & {d}); r.readonly = !!(flags & {d}); r.accessibility = ACCESSIBILITY[(flags >> {d}) & {d}]; }} return r; }}
        , .{
            tag,
            comptime flagMask(P, "accessor"),
            sd,
            sk,
            sv,
            sv,
            comptime flagMask(P, "computed"),
            comptime flagMask(P, "static"),
            sta,
            sta,
            comptime flagMask(P, "declare"),
            comptime flagMask(P, "override"),
            comptime flagMask(P, "optional"),
            comptime flagMask(P, "definite"),
            comptime flagMask(P, "readonly"),
            comptime flagBit(P, "accessibility"),
            comptime enumMask(ast.Accessibility),
        });
    } else if (comptime eql(u8, name, "unary_expression")) {
        const sa = comptime slotOf(ast.UnaryExpression, "argument");
        try emit(w,
            \\    case {d}: return {{ type: "UnaryExpression", start, end, operator: UNARY_OPS[flags & {d}], prefix: true, argument: f{d} !== NULL ? node(f{d}) : null }};
        , .{ tag, comptime enumMask(ast.UnaryOperator), sa, sa });
    } else if (comptime eql(u8, name, "binding_property")) {
        const sk = comptime slotOf(ast.BindingProperty, "key");
        const sv = comptime slotOf(ast.BindingProperty, "value");
        try w.print(
            \\    case {d}: {{ const r = {{ type: "Property", start, end, kind: "init", key: node(f{d}), value: node(f{d}), method: false, shorthand: !!(flags & {d}), computed: !!(flags & {d}) }};
        , .{ tag, sk, sv, comptime flagMask(ast.BindingProperty, "shorthand"), comptime flagMask(ast.BindingProperty, "computed") });
        try w.writeAll(" if (_isTs) { ");
        try writeTsExtras(w, "binding_property");
        try w.writeAll("} return r; }\n");
    } else if (comptime eql(u8, name, "array_pattern")) {
        const se = comptime slotOf(ast.ArrayPattern, "elements");
        const sr = comptime slotOf(ast.ArrayPattern, "rest");
        const sdec = comptime slotOf(ast.ArrayPattern, "decorators");
        const sta = comptime slotOf(ast.ArrayPattern, "type_annotation");
        try emit(w,
            \\    case {d}: {{ const el = nodeArrHoles(f{d}, f0); if (f{d} !== NULL) el.push(node(f{d})); const r = {{ type: "ArrayPattern", start, end, elements: el }}; if (_isTs) {{ r.decorators = nodeArr(f{d}, f{d}); r.optional = !!(flags & {d}); r.typeAnnotation = f{d} !== NULL ? node(f{d}) : null; }} return r; }}
        , .{ tag, se, sr, sr, sdec, sdec + 1, comptime flagMask(ast.ArrayPattern, "optional"), sta, sta });
    } else if (comptime eql(u8, name, "object_pattern")) {
        const sp = comptime slotOf(ast.ObjectPattern, "properties");
        const sr = comptime slotOf(ast.ObjectPattern, "rest");
        const sdec = comptime slotOf(ast.ObjectPattern, "decorators");
        const sta = comptime slotOf(ast.ObjectPattern, "type_annotation");
        try emit(w,
            \\    case {d}: {{ const pr = nodeArr(f{d}, f0); if (f{d} !== NULL) pr.push(node(f{d})); const r = {{ type: "ObjectPattern", start, end, properties: pr }}; if (_isTs) {{ r.decorators = nodeArr(f{d}, f{d}); r.optional = !!(flags & {d}); r.typeAnnotation = f{d} !== NULL ? node(f{d}) : null; }} return r; }}
        , .{ tag, sp, sr, sr, sdec, sdec + 1, comptime flagMask(ast.ObjectPattern, "optional"), sta, sta });
    } else if (comptime eql(u8, name, "jsx_text")) {
        const sv = comptime slotOf(ast.JSXText, "value");
        try emit(w,
            \\    case {d}: {{ const t = str(f{d}, f{d}); return {{ type: "JSXText", start, end, value: t, raw: t }}; }}
        , .{ tag, sv, sv + 1 });
    }
}

// helpers and decode function

fn writeHelpers(w: *Writer) !void {
    try w.print(
        \\function nodeArr(s, len) {{
        \\  const r = new Array(len);
        \\  for (let j = 0; j < len; j++) r[j] = node(_u32[_extraBase + s + j]);
        \\  return r;
        \\}}
        \\function nodeArrHoles(s, len) {{
        \\  const r = new Array(len);
        \\  for (let j = 0; j < len; j++) {{ const x = _u32[_extraBase + s + j]; r[j] = x !== NULL ? node(x) : null; }}
        \\  return r;
        \\}}
        \\function fnParams(idx) {{
        \\  const po = _nodesOff + idx * {[size]d};
        \\  const len = _u8[po + {[f0]d}] | (_u8[po + {[f01]d}] << 8);
        \\  const pb = po >> 2;
        \\  const iStart = _u32[pb + {[items]d}], rest = _u32[pb + {[rest]d}];
        \\  const p = [];
        \\  for (let j = 0; j < len; j++) {{
        \\    const fi = _u32[_extraBase + iStart + j];
        \\    p.push(node(_u32[(_nodesOff + fi * {[size]d} >> 2) + {[pat]d}]));
        \\  }}
        \\  if (rest !== NULL) p.push(node(rest));
        \\  return p;
        \\}}
        \\
    , .{
        .size = rt.NODE_SIZE,
        .f0 = rt.NODE_FIELD0_OFFSET,
        .f01 = rt.NODE_FIELD0_OFFSET + 1,
        .items = comptime u32IndexOf(ast.FormalParameters, "items"),
        .rest = comptime u32IndexOf(ast.FormalParameters, "rest"),
        .pat = comptime u32IndexOf(ast.FormalParameter, "pattern"),
    });
}

fn writeDecodeFunction(w: *Writer) !void {
    try w.print(
        \\function buildPosMap(src, byteLen) {{
        \\  const m = new Uint32Array(byteLen + 1);
        \\  let bp = 0, u16p = 0;
        \\  for (let i = 0; i < src.length; i++) {{
        \\    m[bp] = u16p;
        \\    const cp = src.codePointAt(i);
        \\    let bytes = 1;
        \\    if (cp > 0x7F) {{ if (cp > 0x7FF) {{ bytes = cp > 0xFFFF ? 4 : 3; }} else {{ bytes = 2; }} }}
        \\    const units = bytes === 4 ? 2 : 1;
        \\    u16p += units;
        \\    for (let k = 1; k < bytes; k++) m[bp + k] = u16p;
        \\    bp += bytes;
        \\    if (bytes === 4) i++;
        \\  }}
        \\  m[byteLen] = u16p;
        \\  return m;
        \\}}
        \\function decode(buffer, source) {{
        \\  _u8 = new Uint8Array(buffer);
        \\  const aLen = (buffer.byteLength >> 2) << 2;
        \\  _u32 = new Uint32Array(buffer, 0, aLen >> 2);
        \\  _src = source;
        \\  _srcLen = _u32[{[u_src]d}];
        \\  const nodeCount = _u32[{[u_nc]d}], extraCount = _u32[{[u_ec]d}], spLen = _u32[{[u_sp]d}];
        \\  const commentCount = _u32[{[u_cc]d}], diagCount = _u32[{[u_dc]d}], progIdx = _u32[{[u_pi]d}];
        \\  _isTs = !!(_u32[{[u_fl]d}] & {[ts]d});
        \\  const pm = (_u32[{[u_fl]d}] & {[ascii]d}) ? null : buildPosMap(source, _srcLen);
        \\  if (pm) {{
        \\    _p = function(v) {{ return pm[v]; }};
        \\    str = function(s, e) {{ if (s === e) return ""; if (s < _srcLen) return _src.slice(pm[s], pm[e]); return _poolDecode(s, e); }};
        \\  }} else {{
        \\    _p = function(v) {{ return v; }};
        \\    str = function(s, e) {{ if (s === e) return ""; if (s < _srcLen) return _src.slice(s, e); return _poolDecode(s, e); }};
        \\  }}
        \\  _nodesOff = {[hdr]d};
        \\  const eOff = _nodesOff + nodeCount * {[size]d};
        \\  _extraBase = eOff >> 2;
        \\  _spOff = eOff + extraCount * 4;
        \\  const cOff = _spOff + spLen, dOff = cOff + commentCount * {[csize]d};
        \\  const dv = new DataView(buffer);
        \\  const comments = new Array(commentCount);
        \\  for (let j = 0; j < commentCount; j++) {{
        \\    const o = cOff + j * {[csize]d};
        \\    comments[j] = {{ type: COMMENT_TYPES[_u8[o]], value: str(dv.getUint32(o + {[c_vs]d}, true), dv.getUint32(o + {[c_ve]d}, true)), start: _p(dv.getUint32(o + {[c_s]d}, true)), end: _p(dv.getUint32(o + {[c_e]d}, true)) }};
        \\  }}
        \\  const diagnostics = new Array(diagCount);
        \\  let dp = dOff;
        \\  for (let j = 0; j < diagCount; j++) {{
        \\    const sev = SEVERITY[_u8[dp]]; dp++;
        \\    const ds = _p(dv.getUint32(dp, true)); dp += 4;
        \\    const de = _p(dv.getUint32(dp, true)); dp += 4;
        \\    const ml = dv.getUint32(dp, true); dp += 4;
        \\    const msg = _td.decode(_u8.subarray(dp, dp + ml)); dp += ml;
        \\    const hh = _u8[dp]; dp++;
        \\    let help = null;
        \\    if (hh) {{ const hl = dv.getUint32(dp, true); dp += 4; help = _td.decode(_u8.subarray(dp, dp + hl)); dp += hl; }}
        \\    const lc = dv.getUint32(dp, true); dp += 4;
        \\    const labels = new Array(lc);
        \\    for (let k = 0; k < lc; k++) {{
        \\      const ls = _p(dv.getUint32(dp, true)); dp += 4;
        \\      const le = _p(dv.getUint32(dp, true)); dp += 4;
        \\      const lml = dv.getUint32(dp, true); dp += 4;
        \\      labels[k] = {{ start: ls, end: le, message: _td.decode(_u8.subarray(dp, dp + lml)) }}; dp += lml;
        \\    }}
        \\    diagnostics[j] = {{ severity: sev, message: msg, start: ds, end: de, help, labels }};
        \\  }}
        \\  const program = node(progIdx);
        \\  _u8 = _u32 = _src = null;
        \\  _isTs = false;
        \\  return {{ program, comments, diagnostics }};
        \\}}
        \\
    , .{
        .u_src = rt.HDR_SOURCE_LEN_U32,
        .u_nc = rt.HDR_NODE_COUNT_U32,
        .u_ec = rt.HDR_EXTRA_COUNT_U32,
        .u_sp = rt.HDR_STRING_POOL_LEN_U32,
        .u_cc = rt.HDR_COMMENT_COUNT_U32,
        .u_dc = rt.HDR_DIAG_COUNT_U32,
        .u_pi = rt.HDR_PROGRAM_INDEX_U32,
        .u_fl = rt.HDR_FLAGS_U32,
        .ts = rt.FLAG_TS,
        .ascii = rt.FLAG_ASCII,
        .hdr = rt.HEADER_SIZE,
        .size = rt.NODE_SIZE,
        .csize = rt.COMMENT_SIZE,
        .c_s = rt.COMMENT_START_OFFSET,
        .c_e = rt.COMMENT_END_OFFSET,
        .c_vs = rt.COMMENT_VALUE_START_OFFSET,
        .c_ve = rt.COMMENT_VALUE_END_OFFSET,
    });
}

// per-node metadata

/// typescript-only fields, grouped by node. emitted only when the source
/// language is TypeScript.
const TS_FIELDS = [_]struct { node: []const u8, fields: []const []const u8 }{
    .{ .node = "variable_declaration", .fields = &.{"declare"} },
    .{ .node = "variable_declarator", .fields = &.{"definite"} },
    .{ .node = "function", .fields = &.{ "type_parameters", "return_type" } },
    .{ .node = "arrow_function_expression", .fields = &.{ "type_parameters", "return_type" } },
    .{ .node = "class", .fields = &.{ "type_parameters", "super_type_arguments", "implements", "abstract", "declare" } },
    .{ .node = "method_definition", .fields = &.{ "override", "optional", "accessibility" } },
    .{ .node = "property_definition", .fields = &.{ "type_annotation", "declare", "override", "optional", "definite", "readonly", "accessibility" } },
    .{ .node = "call_expression", .fields = &.{"type_arguments"} },
    .{ .node = "new_expression", .fields = &.{"type_arguments"} },
    .{ .node = "tagged_template_expression", .fields = &.{"type_arguments"} },
    .{ .node = "jsx_opening_element", .fields = &.{"type_arguments"} },
    .{ .node = "import_declaration", .fields = &.{"import_kind"} },
    .{ .node = "import_specifier", .fields = &.{"import_kind"} },
    .{ .node = "export_named_declaration", .fields = &.{"export_kind"} },
    .{ .node = "export_all_declaration", .fields = &.{"export_kind"} },
    .{ .node = "export_specifier", .fields = &.{"export_kind"} },
    .{ .node = "binding_rest_element", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "binding_identifier", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "assignment_pattern", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "object_pattern", .fields = &.{ "decorators", "optional", "type_annotation" } },
    .{ .node = "array_pattern", .fields = &.{ "decorators", "optional", "type_annotation" } },
};

fn isTsField(comptime tag: []const u8, comptime field: []const u8) bool {
    for (TS_FIELDS) |e| {
        if (!std.mem.eql(u8, e.node, tag)) continue;
        for (e.fields) |f| if (std.mem.eql(u8, f, field)) return true;
    }
    return false;
}

fn hasAnyTsField(comptime tag: []const u8, comptime T: type) bool {
    if (@typeInfo(T) != .@"struct") return false;
    inline for (std.meta.fields(T)) |f| if (comptime isTsField(tag, f.name)) return true;
    return false;
}

/// TS-ESTree-only constant fields with no Zig AST counterpart. emitted
/// alongside any struct-backed TS fields inside the `if (_isTs) { ... }`
/// branch. values are raw JS expressions (e.g. `"null"`, `"false"`, `"[]"`).
const Extra = struct { field: []const u8, value: []const u8 };

const IDENT_EXTRAS = [_]Extra{
    .{ .field = "decorators", .value = "[]" },
    .{ .field = "optional", .value = "false" },
    .{ .field = "typeAnnotation", .value = "null" },
};

const TS_EXTRAS = [_]struct { node: []const u8, extras: []const Extra }{
    // identifier-like nodes have no backing decorators/optional/typeAnnotation.
    .{ .node = "identifier_reference", .extras = &IDENT_EXTRAS },
    .{ .node = "identifier_name", .extras = &IDENT_EXTRAS },
    .{ .node = "label_identifier", .extras = &IDENT_EXTRAS },
    // `optional` is always false on properties, no syntax sets it to true.
    .{ .node = "binding_property", .extras = &.{.{ .field = "optional", .value = "false" }} },
    .{ .node = "object_property", .extras = &.{.{ .field = "optional", .value = "false" }} },
    .{ .node = "expression_statement", .extras = &.{.{ .field = "directive", .value = "null" }} },
    .{ .node = "binding_rest_element", .extras = &.{.{ .field = "value", .value = "null" }} },
    .{ .node = "export_default_declaration", .extras = &.{.{ .field = "exportKind", .value = "\"value\"" }} },
};

fn tsExtrasOf(comptime name: []const u8) []const Extra {
    inline for (TS_EXTRAS) |e| {
        if (comptime std.mem.eql(u8, e.node, name)) return e.extras;
    }
    return &.{};
}

fn writeTsExtras(w: *Writer, comptime name: []const u8) !void {
    inline for (comptime tsExtrasOf(name)) |e| {
        try w.print("r.{s} = {s}; ", .{ e.field, e.value });
    }
}

fn estreeType(comptime name: []const u8) []const u8 {
    const overrides = .{
        .{ "function_body", "BlockStatement" },
        .{ "binding_rest_element", "RestElement" },
        .{ "object_property", "Property" },
        .{ "identifier_reference", "Identifier" },
        .{ "binding_identifier", "Identifier" },
        .{ "identifier_name", "Identifier" },
        .{ "label_identifier", "Identifier" },
        // snake->pascal would produce "Bigint"; typescript uses "BigInt".
        .{ "ts_bigint_keyword", "TSBigIntKeyword" },
    };
    inline for (overrides) |o| if (comptime std.mem.eql(u8, name, o[0])) return o[1];
    if (comptime std.mem.startsWith(u8, name, "jsx_")) return "JSX" ++ snakeConvert(name[4..], true);
    if (comptime std.mem.startsWith(u8, name, "ts_")) return "TS" ++ snakeConvert(name[3..], true);
    return snakeConvert(name, true);
}

fn estreeField(comptime tag: []const u8, comptime field: []const u8) []const u8 {
    if (comptime std.mem.eql(u8, tag, "variable_declaration") and std.mem.eql(u8, field, "declarators")) return "declarations";
    return snakeConvert(field, false);
}

/// array fields that allow holes (sparse elements -> `null` in ESTree).
fn isHoley(comptime tag: []const u8, comptime field: []const u8) bool {
    return std.mem.eql(u8, tag, "array_expression") and std.mem.eql(u8, field, "elements");
}

// comptime utilities

fn emit(w: *Writer, comptime fmt: []const u8, args: anytype) !void {
    try w.print(fmt, args);
    try w.writeByte('\n');
}

fn fieldIdx(comptime T: type, comptime name: []const u8) usize {
    for (std.meta.fields(T), 0..) |f, i| if (std.mem.eql(u8, f.name, name)) return i;
    @compileError("field '" ++ name ++ "' not found");
}

/// u32 slot number to use as `f{N}` in generated JS. slot 0 is the header's
/// `f0`; slots 1.. come from `_u32[b + 2..]`, hence the `+ 1`.
fn slotOf(comptime T: type, comptime field: []const u8) u32 {
    return rt.u32SlotForField(T, fieldIdx(T, field)) + 1;
}

/// raw u32 index (already includes the header offset) — use in `_u32[pb + N]`.
fn u32IndexOf(comptime T: type, comptime field: []const u8) u32 {
    return rt.u32SlotForField(T, fieldIdx(T, field)) + rt.NODE_HEADER_U32S;
}

fn flagBit(comptime T: type, comptime field: []const u8) u32 {
    return rt.flagBitForField(T, fieldIdx(T, field));
}

fn flagMask(comptime T: type, comptime field: []const u8) u32 {
    return flagMaskAt(T, fieldIdx(T, field));
}

fn flagMaskAt(comptime T: type, comptime i: usize) u32 {
    return @as(u32, 1) << @intCast(rt.flagBitForField(T, i));
}

fn enumMask(comptime E: type) u32 {
    return (@as(u32, 1) << @intCast(rt.enumBitWidth(E))) - 1;
}

fn enumTable(comptime E: type) []const u8 {
    if (E == ast.BinaryOperator) return "BINARY_OPS";
    if (E == ast.LogicalOperator) return "LOGICAL_OPS";
    if (E == ast.UnaryOperator) return "UNARY_OPS";
    if (E == ast.UpdateOperator) return "UPDATE_OPS";
    if (E == ast.AssignmentOperator) return "ASSIGNMENT_OPS";
    if (E == ast.VariableKind) return "VAR_KINDS";
    if (E == ast.PropertyKind) return "PROPERTY_KINDS";
    if (E == ast.MethodDefinitionKind) return "METHOD_KINDS";
    if (E == ast.FunctionType) return "FUNCTION_TYPES";
    if (E == ast.ClassType) return "CLASS_TYPES";
    if (E == ast.ImportOrExportKind) return "IMPORT_EXPORT_KINDS";
    if (E == ast.Accessibility) return "ACCESSIBILITY";
    @compileError("no lookup table for enum");
}

fn snakeConvert(comptime name: []const u8, comptime pascal: bool) []const u8 {
    comptime {
        var result: [name.len]u8 = undefined;
        var len: usize = 0;
        var cap = pascal;
        for (name) |c| {
            if (c == '_') {
                cap = true;
            } else {
                result[len] = if (cap) std.ascii.toUpper(c) else c;
                cap = false;
                len += 1;
            }
        }
        const final = result[0..len].*;
        return &final;
    }
}
