// generates encode.js, the inverse of decode.js: walks an ESTree object
// and writes a binary AST buffer in the v6 wire format that
// `transfer.deserializeFromBuf` reads back into an `ast.Tree`.
const std = @import("std");
const parser = @import("parser");
const ast = parser.ast;
const rt = @import("transfer");
const meta = @import("estree_meta");

const Writer = std.Io.Writer;

pub fn main(init: std.process.Init) !void {
    const stdout = std.Io.File.stdout();
    var buf: [128 * 1024]u8 = undefined;
    var fw = stdout.writer(init.io, &buf);
    try generate(&fw.interface);
    try fw.flush();
}

fn generate(w: *Writer) !void {
    @setEvalBranchQuota(500_000);
    try writePrologue(w);
    try writeInverseMaps(w);
    try writeRuntime(w);
    try writeIdentifierHelpers(w);
    try writeNodeEncoders(w);
    try writeDispatcher(w);
    try writeAssemble(w);
    try w.writeAll("export { encode };\n");
}

// Prologue + constants

fn writePrologue(w: *Writer) !void {
    try w.print(
        \\// generated by tools/gen_estree_encoder.zig, do not edit
        \\//
        \\// Encodes an ESTree object into the Yuku transfer-format buffer.
        \\const NULL = 0xFFFFFFFF;
        \\const _enc = new TextEncoder();
        \\const NODE_SIZE = {[node_size]d};
        \\const HEADER_SIZE = {[hdr_size]d};
        \\const NODE_FLAGS_OFFSET = {[flags_off]d};
        \\const NODE_FIELD0_OFFSET = {[f0_off]d};
        \\const NODE_HEADER_U32S = {[hdr_u32s]d};
        \\const NODE_SPAN_START_U32 = {[ss_u32]d};
        \\const NODE_SPAN_END_U32 = {[se_u32]d};
        \\const COMMENT_SIZE = {[c_size]d};
        \\const COMMENT_FLAGS_OFFSET = {[c_fl]d};
        \\const COMMENT_VALUE_START_OFFSET = {[c_vs]d};
        \\const COMMENT_VALUE_END_OFFSET = {[c_ve]d};
        \\const FLAG_ATTACH_COMMENTS = {[ac]d};
        \\
    , .{
        .node_size = rt.NODE_SIZE,
        .hdr_size = rt.HEADER_SIZE,
        .flags_off = rt.NODE_FLAGS_OFFSET,
        .f0_off = rt.NODE_FIELD0_OFFSET,
        .hdr_u32s = rt.NODE_HEADER_U32S,
        .ss_u32 = rt.NODE_SPAN_START_U32,
        .se_u32 = rt.NODE_SPAN_END_U32,
        .c_size = rt.COMMENT_SIZE,
        .c_fl = rt.COMMENT_FLAGS_OFFSET,
        .c_vs = rt.COMMENT_VALUE_START_OFFSET,
        .c_ve = rt.COMMENT_VALUE_END_OFFSET,
        .ac = rt.FLAG_ATTACH_COMMENTS,
    });
}

// Inverse lookup tables

fn writeInverseMaps(w: *Writer) !void {
    try writeInverseObject(w, "BINARY_OPS_INV", &meta.BINARY_OPS);
    try writeInverseObject(w, "LOGICAL_OPS_INV", &meta.LOGICAL_OPS);
    try writeInverseObject(w, "UNARY_OPS_INV", &meta.UNARY_OPS);
    try writeInverseObject(w, "UPDATE_OPS_INV", &meta.UPDATE_OPS);
    try writeInverseObject(w, "ASSIGNMENT_OPS_INV", &meta.ASSIGNMENT_OPS);
    try writeInverseObject(w, "VAR_KINDS_INV", &meta.VAR_KINDS);
    try writeInverseObject(w, "PROPERTY_KINDS_INV", &meta.PROPERTY_KINDS);
    try writeInverseObject(w, "METHOD_KINDS_INV", &meta.METHOD_KINDS);
    try writeInverseObject(w, "IMPORT_EXPORT_KINDS_INV", &.{ "value", "type" });
    try writeInverseObject(w, "TS_TYPE_OPERATORS_INV", &.{ "keyof", "unique", "readonly" });
    try writeInverseObject(w, "TS_METHOD_SIGNATURE_KINDS_INV", &.{ "method", "get", "set" });
    try writeInverseObject(w, "TS_MODULE_KINDS_INV", &.{ "namespace", "module" });
    try writeInverseObject(w, "IMPORT_PHASE_INV", &.{ "source", "defer" });

    // Mixed-typed enums need inverse functions, not object maps.
    try w.writeAll(
        \\const ACCESSIBILITY_INV = (v) => v == null ? 0 : v === "public" ? 1 : v === "private" ? 2 : 3;
        \\const TS_MAPPED_OPTIONAL_INV = (v) => v === true ? 1 : v === "+" ? 2 : v === "-" ? 3 : 0;
        \\const TS_MAPPED_READONLY_INV = (v) => v === true ? 1 : v === "+" ? 2 : v === "-" ? 3 : 0;
        \\
    );
}

fn writeInverseObject(w: *Writer, name: []const u8, items: []const []const u8) !void {
    try w.print("const {s} = {{", .{name});
    for (items, 0..) |item, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("\"{s}\": {d}", .{ item, i });
    }
    try w.writeAll("};\n");
}

// Runtime: growable buffers, alloc, encStr, encArr

fn writeRuntime(w: *Writer) !void {
    try w.writeAll(
        \\function encode(result) {
        \\  const root = result.program;
        \\  const lineStarts = result.lineStarts;
        \\  let nodeCap = 512;
        \\  let nodeAB = new ArrayBuffer(nodeCap * NODE_SIZE);
        \\  let nU8 = new Uint8Array(nodeAB);
        \\  let nU32 = new Uint32Array(nodeAB);
        \\  let nodeCount = 0;
        \\  let extraCap = 512;
        \\  let extras = new Uint32Array(extraCap);
        \\  let extraCount = 0;
        \\  let poolCap = 4096;
        \\  let pool = new Uint8Array(poolCap);
        \\  let poolLen = 0;
        \\  const strMap = new Map();
        \\  function alloc() {
        \\    if (nodeCount >= nodeCap) {
        \\      nodeCap *= 2;
        \\      const nb = new ArrayBuffer(nodeCap * NODE_SIZE);
        \\      new Uint8Array(nb).set(nU8);
        \\      nodeAB = nb; nU8 = new Uint8Array(nb); nU32 = new Uint32Array(nb);
        \\    }
        \\    const idx = nodeCount++;
        \\    const b = (idx * NODE_SIZE) >>> 2;
        \\    nU32[b + NODE_HEADER_U32S + 0] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 1] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 2] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 3] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 4] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 5] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 6] = NULL;
        \\    nU32[b + NODE_HEADER_U32S + 7] = NULL;
        \\    return idx;
        \\  }
        \\  function tagAt(idx, tag) { nU8[idx * NODE_SIZE] = tag; }
        \\  function flagsAt(idx, v) {
        \\    const o = idx * NODE_SIZE + NODE_FLAGS_OFFSET;
        \\    nU8[o] = v & 0xFF; nU8[o + 1] = (v >>> 8) & 0xFF;
        \\  }
        \\  function f0At(idx, v) {
        \\    const o = idx * NODE_SIZE + NODE_FIELD0_OFFSET;
        \\    nU8[o] = v & 0xFF; nU8[o + 1] = (v >>> 8) & 0xFF;
        \\  }
        \\  function slotAt(idx, slot, v) {
        \\    nU32[((idx * NODE_SIZE) >>> 2) + NODE_HEADER_U32S + slot] = v >>> 0;
        \\  }
        \\  function spanAt(idx, s, e) {
        \\    const b = (idx * NODE_SIZE) >>> 2;
        \\    nU32[b + NODE_SPAN_START_U32] = (s >>> 0);
        \\    nU32[b + NODE_SPAN_END_U32] = (e >>> 0);
        \\  }
        \\  function pushExtra(idx) {
        \\    if (extraCount >= extraCap) {
        \\      extraCap *= 2;
        \\      const ne = new Uint32Array(extraCap);
        \\      ne.set(extras); extras = ne;
        \\    }
        \\    extras[extraCount++] = idx >>> 0;
        \\  }
        \\  function encArr(arr, encEach) {
        \\    if (!arr || arr.length === 0) return { start: 0, len: 0 };
        \\    const len = arr.length;
        \\    const ids = new Array(len);
        \\    for (let i = 0; i < len; i++) ids[i] = encEach(arr[i]);
        \\    const start = extraCount;
        \\    for (let i = 0; i < len; i++) pushExtra(ids[i]);
        \\    return { start, len };
        \\  }
        \\  function encArrHoles(arr, encEach) {
        \\    if (!arr || arr.length === 0) return { start: 0, len: 0 };
        \\    const len = arr.length;
        \\    const ids = new Array(len);
        \\    for (let i = 0; i < len; i++) { const e = arr[i]; ids[i] = e == null ? NULL : encEach(e); }
        \\    const start = extraCount;
        \\    for (let i = 0; i < len; i++) pushExtra(ids[i]);
        \\    return { start, len };
        \\  }
        \\  function encStr(s) {
        \\    if (s == null || s === "") return { start: 0, end: 0 };
        \\    const hit = strMap.get(s);
        \\    if (hit !== undefined) return hit;
        \\    const bytes = _enc.encode(s);
        \\    while (poolLen + bytes.length > poolCap) {
        \\      poolCap *= 2;
        \\      const np = new Uint8Array(poolCap);
        \\      np.set(pool); pool = np;
        \\    }
        \\    pool.set(bytes, poolLen);
        \\    const r = { start: poolLen, end: poolLen + bytes.length };
        \\    poolLen += bytes.length;
        \\    strMap.set(s, r);
        \\    return r;
        \\  }
        \\  function asStart(n) { return (n && typeof n.start === "number") ? n.start : 0; }
        \\  function asEnd(n) { return (n && typeof n.end === "number") ? n.end : 0; }
        \\  // called by every enc_* to register the node's `.comments` array
        \\  function recordComments(n, idx) {
        \\    if (idx !== NULL && n && Array.isArray(n.comments) && n.comments.length > 0) {
        \\      commentsByIdx.set(idx, n.comments);
        \\    }
        \\  }
        \\
    );
}

// Contextual Identifier dispatch helpers

fn writeIdentifierHelpers(w: *Writer) !void {
    try w.writeAll(
        \\  function encBindingTarget(n) {
        \\    if (n == null) return NULL;
        \\    if (n.type === "Identifier") return enc_binding_identifier(n);
        \\    return encNode(n);
        \\  }
        \\  function encLabel(n) {
        \\    if (n == null) return NULL;
        \\    return enc_label_identifier(n);
        \\  }
        \\  function encPropertyKey(n) {
        \\    if (n == null) return NULL;
        \\    if (n.type === "Identifier") return enc_identifier_name(n);
        \\    return encNode(n);
        \\  }
        \\
    );
}

// Per-tag encoders

fn writeNodeEncoders(w: *Writer) !void {
    inline for (@typeInfo(ast.NodeData).@"union".fields, 0..) |field, tag| {
        if (comptime skipGeneration(field.name)) continue;
        if (comptime meta.isSpecial(field.name)) {
            try writeSpecialEncoder(w, field.name, tag);
        } else {
            try writeGenericEncoder(w, field.name, tag, field.type);
        }
    }
}

/// Yuku-internal node tags that the JS encoder never produces (so we don't
/// emit a dead `enc_*` function for them).
fn skipGeneration(comptime name: []const u8) bool {
    @setEvalBranchQuota(20_000);
    // `function_body` (tag 5) is interchangeable with `block_statement` (tag 4):
    // both decode to ESTree `BlockStatement` and the printer treats them
    // identically. The encoder always uses `block_statement`.
    return std.mem.eql(u8, name, "function_body");
}

fn writeGenericEncoder(w: *Writer, comptime name: []const u8, comptime tag: usize, comptime T: type) !void {
    try w.print("  function enc_{s}(n) {{\n", .{name});

    if (@typeInfo(T) != .@"struct" or @typeInfo(T).@"struct".fields.len == 0) {
        try w.print(
            \\    const idx = alloc();
            \\    tagAt(idx, {d});
            \\    spanAt(idx, asStart(n), asEnd(n));
            \\    recordComments(n, idx);
            \\    return idx;
            \\  }}
            \\
        , .{tag});
        return;
    }

    // Phase 1: encode children into locals (so realloc during recursion
    // never affects pointers we hold).
    inline for (std.meta.fields(T)) |f| {
        const jsf = comptime meta.estreeField(name, f.name);
        if (f.type == ast.NodeIndex) {
            const role = comptime meta.fieldRole(name, f.name);
            const helper = switch (role) {
                .binding => "encBindingTarget",
                .label => "encLabel",
                .auto => "encNode",
            };
            try w.print("    const c_{s} = n.{s} == null ? NULL : {s}(n.{s});\n", .{ f.name, jsf, helper, jsf });
        } else if (f.type == ast.IndexRange) {
            const fn_name = if (comptime meta.isHoleyArray(name, f.name)) "encArrHoles" else "encArr";
            try w.print("    const c_{s} = {s}(n.{s}, encNode);\n", .{ f.name, fn_name, jsf });
        } else if (f.type == ast.String) {
            try w.print("    const c_{s} = encStr(n.{s});\n", .{ f.name, jsf });
        }
    }

    // Phase 2: allocate + write tag.
    try w.print("    const idx = alloc();\n    tagAt(idx, {d});\n", .{tag});

    // Phase 3: write slots.
    inline for (std.meta.fields(T), 0..) |f, i| {
        const slot = comptime rt.u32SlotForField(T, i);
        const jsf = comptime meta.estreeField(name, f.name);
        if (f.type == ast.NodeIndex) {
            try w.print("    slotAt(idx, {d}, c_{s});\n", .{ slot, f.name });
        } else if (f.type == ast.IndexRange) {
            if (comptime rt.isFirstRange(T, i)) {
                try w.print("    f0At(idx, c_{s}.len);\n    slotAt(idx, {d}, c_{s}.start);\n", .{ f.name, slot, f.name });
            } else {
                try w.print("    slotAt(idx, {d}, c_{s}.start);\n    slotAt(idx, {d}, c_{s}.len);\n", .{ slot, f.name, slot + 1, f.name });
            }
        } else if (f.type == ast.String) {
            try w.print("    slotAt(idx, {d}, c_{s}.start);\n    slotAt(idx, {d}, c_{s}.end);\n", .{ slot, f.name, slot + 1, f.name });
        } else if (f.type == ?ast.Hashbang) {
            try w.print("    if (n.{s} != null) {{ const _hb = encStr(n.{s}.value); slotAt(idx, {d}, _hb.start); slotAt(idx, {d}, _hb.end); }}\n", .{ jsf, jsf, slot, slot + 1 });
        }
    }

    // Phase 4: write flags (bools, enums, ?ImportPhase, ?Hashbang presence).
    const any_flag = comptime blk: {
        for (std.meta.fields(T)) |f| {
            if (isFlagField(f.type)) break :blk true;
        }
        break :blk false;
    };
    if (any_flag) {
        try w.writeAll("    flagsAt(idx, 0");
        inline for (std.meta.fields(T), 0..) |f, i| {
            _ = i;
            const bit = comptime rt.flagBitForField(T, std.meta.fieldIndex(T, f.name).?);
            const jsf = comptime meta.estreeField(name, f.name);
            if (f.type == bool) {
                const mask: u32 = @as(u32, 1) << @intCast(bit);
                try w.print(" | (n.{s} ? {d} : 0)", .{ jsf, mask });
            } else if (comptime isEnumFlag(f.type)) {
                const table_inv = comptime meta.enumTableName(f.type) ++ "_INV";
                const needs_fn = comptime meta.enumNeedsInverseFn(f.type);
                if (needs_fn) {
                    if (bit == 0) {
                        try w.print(" | {s}(n.{s})", .{ table_inv, jsf });
                    } else {
                        try w.print(" | ({s}(n.{s}) << {d})", .{ table_inv, jsf, bit });
                    }
                } else {
                    if (bit == 0) {
                        try w.print(" | ({s}[n.{s}] | 0)", .{ table_inv, jsf });
                    } else {
                        try w.print(" | (({s}[n.{s}] | 0) << {d})", .{ table_inv, jsf, bit });
                    }
                }
            } else if (f.type == ?ast.ImportPhase) {
                const pres_mask: u32 = @as(u32, 1) << @intCast(bit);
                try w.print(" | (n.{s} != null ? {d} | ((IMPORT_PHASE_INV[n.{s}] | 0) << {d}) : 0)", .{ jsf, pres_mask, jsf, bit + 1 });
            } else if (f.type == ?ast.Hashbang) {
                const mask: u32 = @as(u32, 1) << @intCast(bit);
                try w.print(" | (n.{s} != null ? {d} : 0)", .{ jsf, mask });
            }
        }
        try w.writeAll(");\n");
    }

    try w.writeAll("    spanAt(idx, asStart(n), asEnd(n));\n    recordComments(n, idx);\n    return idx;\n  }\n");
}

fn writeSpecialEncoder(w: *Writer, comptime name: []const u8, comptime tag: usize) !void {
    const eql = std.mem.eql;
    if (comptime eql(u8, name, "program")) try writeSpecialProgram(w, tag) //
    else if (comptime eql(u8, name, "directive")) try writeSpecialDirective(w, tag) //
    else if (comptime eql(u8, name, "string_literal")) try writeSpecialStringLit(w, tag) //
    else if (comptime eql(u8, name, "numeric_literal")) try writeSpecialNumericLit(w, tag) //
    else if (comptime eql(u8, name, "bigint_literal")) try writeSpecialBigIntLit(w, tag) //
    else if (comptime eql(u8, name, "boolean_literal")) try writeSpecialBoolLit(w, tag) //
    else if (comptime eql(u8, name, "null_literal")) try writeSpecialNullLit(w, tag) //
    else if (comptime eql(u8, name, "regexp_literal")) try writeSpecialRegExpLit(w, tag) //
    else if (comptime eql(u8, name, "template_element")) try writeSpecialTemplateElement(w, tag) //
    else if (comptime eql(u8, name, "unary_expression")) try writeSpecialUnaryExpr(w, tag) //
    else if (comptime eql(u8, name, "member_expression")) try writeSpecialMemberExpr(w, tag) //
    else if (comptime eql(u8, name, "function")) try writeSpecialFunction(w, tag) //
    else if (comptime eql(u8, name, "arrow_function_expression")) try writeSpecialArrowFn(w, tag) //
    else if (comptime eql(u8, name, "formal_parameter")) try writeSpecialFormalParameter(w, tag) //
    else if (comptime eql(u8, name, "formal_parameters")) try writeSpecialFormalParameters(w, tag) //
    else if (comptime eql(u8, name, "class")) try writeSpecialClass(w, tag) //
    else if (comptime eql(u8, name, "method_definition")) try writeSpecialMethodDef(w, tag) //
    else if (comptime eql(u8, name, "property_definition")) try writeSpecialPropertyDef(w, tag) //
    else if (comptime eql(u8, name, "object_property")) try writeSpecialObjectProperty(w, tag) //
    else if (comptime eql(u8, name, "binding_property")) try writeSpecialBindingProperty(w, tag) //
    else if (comptime eql(u8, name, "array_pattern")) try writeSpecialArrayPattern(w, tag) //
    else if (comptime eql(u8, name, "object_pattern")) try writeSpecialObjectPattern(w, tag) //
    else if (comptime eql(u8, name, "jsx_text")) try writeSpecialJSXText(w, tag) //
    else if (comptime eql(u8, name, "ts_function_type")) try writeSpecialTSFunctionType(w, tag) //
    else if (comptime eql(u8, name, "ts_constructor_type")) try writeSpecialTSConstructorType(w, tag) //
    else if (comptime eql(u8, name, "ts_method_signature")) try writeSpecialTSMethodSig(w, tag) //
    else if (comptime eql(u8, name, "ts_call_signature_declaration")) try writeSpecialTSCallSig(w, tag) //
    else if (comptime eql(u8, name, "ts_construct_signature_declaration")) try writeSpecialTSConstructSig(w, tag) //
    else if (comptime eql(u8, name, "ts_mapped_type")) try writeSpecialTSMappedType(w, tag) //
    else if (comptime eql(u8, name, "ts_module_declaration")) try writeSpecialTSModuleDecl(w, tag) //
    else if (comptime eql(u8, name, "ts_global_declaration")) try writeSpecialTSGlobalDecl(w, tag) //
    else if (comptime eql(u8, name, "ts_this_parameter")) try writeSpecialTSThisParam(w, tag) //
    else if (comptime eql(u8, name, "ts_property_signature")) try writeSpecialTSPropertySig(w, tag) //
    else if (comptime eql(u8, name, "ts_enum_member")) try writeSpecialTSEnumMember(w, tag) //
    else if (comptime eql(u8, name, "ts_index_signature")) try writeSpecialTSIndexSig(w, tag) //
    else @compileError("missing special encoder for: " ++ name);
}

// helpers used inside generic + special encoders
/// true when the field type contributes flag bits (and only flag bits) to the node.
fn isFlagField(comptime F: type) bool {
    if (F == bool) return true;
    if (F == ?ast.ImportPhase) return true;
    if (F == ?ast.Hashbang) return true;
    if (F == ast.NodeIndex or F == ast.IndexRange or F == ast.String) return false;
    return @typeInfo(F) == .@"enum";
}

/// true when the field is a plain enum (no presence bit), which the
/// generic encoder maps through `<TABLE>_INV`. `ast.NodeIndex` is also
/// an enum at the type level (it's `enum(u32)`), so we exclude it.
fn isEnumFlag(comptime F: type) bool {
    if (F == ast.NodeIndex or F == ast.IndexRange or F == ast.String) return false;
    return @typeInfo(F) == .@"enum";
}

fn slotOf(comptime T: type, comptime field: []const u8) u32 {
    return rt.u32SlotForField(T, std.meta.fieldIndex(T, field) orelse @compileError("no field " ++ field));
}
fn flagBit(comptime T: type, comptime field: []const u8) u32 {
    return rt.flagBitForField(T, std.meta.fieldIndex(T, field) orelse @compileError("no field " ++ field));
}
fn flagMask(comptime T: type, comptime field: []const u8) u32 {
    return @as(u32, 1) << @intCast(flagBit(T, field));
}
fn enumMask(comptime E: type) u32 {
    return (@as(u32, 1) << @intCast(rt.enumBitWidth(E))) - 1;
}

fn writeSpecialStringLit(w: *Writer, comptime tag: usize) !void {
    const sv = comptime slotOf(ast.StringLiteral, "value");
    try w.print(
        \\  function enc_string_literal(n) {{
        \\    const s = encStr(typeof n.value === "string" ? n.value : "");
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, s.start); slotAt(idx, {d}, s.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sv, sv + 1 });
}

fn writeSpecialNumericLit(w: *Writer, comptime tag: usize) !void {
    const sr = comptime slotOf(ast.NumericLiteral, "raw");
    try w.print(
        \\  function enc_numeric_literal(n) {{
        \\    const raw = typeof n.raw === "string" ? n.raw : String(n.value);
        \\    let kind = 0;
        \\    if (raw.length > 1 && raw.charCodeAt(0) === 48) {{
        \\      const c = raw.charCodeAt(1);
        \\      if (c === 120 || c === 88) kind = 1;
        \\      else if (c === 111 || c === 79) kind = 2;
        \\      else if (c === 98 || c === 66) kind = 3;
        \\    }}
        \\    const r = encStr(raw);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    flagsAt(idx, kind);
        \\    slotAt(idx, {d}, r.start); slotAt(idx, {d}, r.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sr, sr + 1 });
}

fn writeSpecialBigIntLit(w: *Writer, comptime tag: usize) !void {
    const sr = comptime slotOf(ast.BigIntLiteral, "raw");
    try w.print(
        \\  function enc_bigint_literal(n) {{
        \\    const raw = typeof n.bigint === "string" ? n.bigint : String(n.value);
        \\    const r = encStr(raw);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, r.start); slotAt(idx, {d}, r.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sr, sr + 1 });
}

fn writeSpecialBoolLit(w: *Writer, comptime tag: usize) !void {
    const mv = comptime flagMask(ast.BooleanLiteral, "value");
    try w.print(
        \\  function enc_boolean_literal(n) {{
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    flagsAt(idx, n.value ? {d} : 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, mv });
}

fn writeSpecialNullLit(w: *Writer, comptime tag: usize) !void {
    try w.print(
        \\  function enc_null_literal(n) {{
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{tag});
}

fn writeSpecialRegExpLit(w: *Writer, comptime tag: usize) !void {
    const sp = comptime slotOf(ast.RegExpLiteral, "pattern");
    const sf = comptime slotOf(ast.RegExpLiteral, "flags");
    try w.print(
        \\  function enc_regexp_literal(n) {{
        \\    const p = encStr(n.regex && n.regex.pattern || "");
        \\    const fl = encStr(n.regex && n.regex.flags || "");
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, p.start); slotAt(idx, {d}, p.end);
        \\    slotAt(idx, {d}, fl.start); slotAt(idx, {d}, fl.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sp, sp + 1, sf, sf + 1 });
}

fn writeSpecialTemplateElement(w: *Writer, comptime tag: usize) !void {
    const sc = comptime slotOf(ast.TemplateElement, "cooked");
    const mt = comptime flagMask(ast.TemplateElement, "tail");
    const mu = comptime flagMask(ast.TemplateElement, "is_cooked_undefined");
    try w.print(
        \\  function enc_template_element(n) {{
        \\    const v = (n.value || {{}});
        \\    const undef = v.cooked == null;
        \\    const c = encStr(undef ? "" : v.cooked);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    flagsAt(idx, (n.tail ? {d} : 0) | (undef ? {d} : 0));
        \\    slotAt(idx, {d}, c.start); slotAt(idx, {d}, c.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, mt, mu, sc, sc + 1 });
}

fn writeSpecialUnaryExpr(w: *Writer, comptime tag: usize) !void {
    const sa = comptime slotOf(ast.UnaryExpression, "argument");
    try w.print(
        \\  function enc_unary_expression(n) {{
        \\    const a = n.argument == null ? NULL : encNode(n.argument);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, a);
        \\    flagsAt(idx, UNARY_OPS_INV[n.operator] | 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sa });
}

fn writeSpecialMemberExpr(w: *Writer, comptime tag: usize) !void {
    const so = comptime slotOf(ast.MemberExpression, "object");
    const sp = comptime slotOf(ast.MemberExpression, "property");
    const mc = comptime flagMask(ast.MemberExpression, "computed");
    const mo = comptime flagMask(ast.MemberExpression, "optional");
    try w.print(
        \\  function enc_member_expression(n) {{
        \\    const o = n.object == null ? NULL : encNode(n.object);
        \\    const p = n.property == null ? NULL : (n.computed ? encNode(n.property) : encPropertyKey(n.property));
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, o); slotAt(idx, {d}, p);
        \\    flagsAt(idx, (n.computed ? {d} : 0) | (n.optional ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, so, sp, mc, mo });
}

fn writeSpecialFunction(w: *Writer, comptime tag: usize) !void {
    const si = comptime slotOf(ast.Function, "id");
    const sp = comptime slotOf(ast.Function, "params");
    const sb = comptime slotOf(ast.Function, "body");
    const stp = comptime slotOf(ast.Function, "type_parameters");
    const srt = comptime slotOf(ast.Function, "return_type");
    const bt = comptime flagBit(ast.Function, "type");
    const tm = comptime enumMask(ast.FunctionType);
    const mg = comptime flagMask(ast.Function, "generator");
    const ma = comptime flagMask(ast.Function, "async");
    const md = comptime flagMask(ast.Function, "declare");
    try w.print(
        \\  function enc_function(n, kind) {{
        \\    const id = n.id == null ? NULL : enc_binding_identifier(n.id);
        \\    const params = encFormalParameters(n.params);
        \\    const body = n.body == null ? NULL : encNode(n.body);
        \\    const tp = n.typeParameters == null ? NULL : encNode(n.typeParameters);
        \\    const rt_ = n.returnType == null ? NULL : encNode(n.returnType);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, id);
        \\    slotAt(idx, {d}, params);
        \\    slotAt(idx, {d}, body);
        \\    slotAt(idx, {d}, tp);
        \\    slotAt(idx, {d}, rt_);
        \\    flagsAt(idx, ((kind & {d}) << {d}) | (n.generator ? {d} : 0) | (n.async ? {d} : 0) | (n.declare ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, si, sp, sb, stp, srt, tm, bt, mg, ma, md });
}

fn writeSpecialArrowFn(w: *Writer, comptime tag: usize) !void {
    const sp = comptime slotOf(ast.ArrowFunctionExpression, "params");
    const sb = comptime slotOf(ast.ArrowFunctionExpression, "body");
    const stp = comptime slotOf(ast.ArrowFunctionExpression, "type_parameters");
    const srt = comptime slotOf(ast.ArrowFunctionExpression, "return_type");
    const me = comptime flagMask(ast.ArrowFunctionExpression, "expression");
    const ma = comptime flagMask(ast.ArrowFunctionExpression, "async");
    try w.print(
        \\  function enc_arrow_function_expression(n) {{
        \\    const params = encFormalParameters(n.params);
        \\    const body = encNode(n.body);
        \\    const tp = n.typeParameters == null ? NULL : encNode(n.typeParameters);
        \\    const rt_ = n.returnType == null ? NULL : encNode(n.returnType);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, params);
        \\    slotAt(idx, {d}, body);
        \\    slotAt(idx, {d}, tp);
        \\    slotAt(idx, {d}, rt_);
        \\    flagsAt(idx, (n.expression ? {d} : 0) | (n.async ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sp, sb, stp, srt, me, ma });
}

fn writeSpecialFormalParameter(w: *Writer, comptime tag: usize) !void {
    const sp = comptime slotOf(ast.FormalParameter, "pattern");
    try w.print(
        \\  function enc_formal_parameter(p) {{
        \\    const pat = encBindingTarget(p);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, pat);
        \\    spanAt(idx, asStart(p), asEnd(p));
        \\    recordComments(p, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sp });
}

fn writeSpecialFormalParameters(w: *Writer, comptime tag: usize) !void {
    const si = comptime slotOf(ast.FormalParameters, "items");
    const sr = comptime slotOf(ast.FormalParameters, "rest");
    try w.print(
        \\  function encFormalParameters(params) {{
        \\    if (!params) {{
        \\      const idx = alloc();
        \\      tagAt(idx, {d});
        \\      spanAt(idx, 0, 0);
        \\      return idx;
        \\    }}
        \\    const items = [];
        \\    let rest = NULL;
        \\    for (let i = 0; i < params.length; i++) {{
        \\      const p = params[i];
        \\      if (p && p.type === "RestElement") rest = enc_binding_rest_element(p);
        \\      else if (p && p.type === "TSParameterProperty") items.push(encNode(p));
        \\      else if (p && p.type === "Identifier" && p.name === "this") items.push(enc_ts_this_parameter(p));
        \\      else items.push(enc_formal_parameter(p));
        \\    }}
        \\    const ids = items;
        \\    const start = extraCount;
        \\    for (let i = 0; i < ids.length; i++) pushExtra(ids[i]);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, ids.length);
        \\    slotAt(idx, {d}, start);
        \\    slotAt(idx, {d}, rest);
        \\    spanAt(idx, 0, 0);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, tag, si, sr });
}

fn writeSpecialClass(w: *Writer, comptime tag: usize) !void {
    const T = ast.Class;
    const sd = comptime slotOf(T, "decorators");
    const si = comptime slotOf(T, "id");
    const ss = comptime slotOf(T, "super_class");
    const sb = comptime slotOf(T, "body");
    const stp = comptime slotOf(T, "type_parameters");
    const ssta = comptime slotOf(T, "super_type_arguments");
    const simp = comptime slotOf(T, "implements");
    const bt = comptime flagBit(T, "type");
    const tm = comptime enumMask(ast.ClassType);
    const mab = comptime flagMask(T, "abstract");
    const mdc = comptime flagMask(T, "declare");
    _ = sd; // first IndexRange in struct
    try w.print(
        \\  function enc_class(n, kind) {{
        \\    const decs = encArr(n.decorators, encNode);
        \\    const id = n.id == null ? NULL : enc_binding_identifier(n.id);
        \\    const sc = n.superClass == null ? NULL : encNode(n.superClass);
        \\    const body = n.body == null ? NULL : encNode(n.body);
        \\    const tp = n.typeParameters == null ? NULL : encNode(n.typeParameters);
        \\    const sta = n.superTypeArguments == null ? NULL : encNode(n.superTypeArguments);
        \\    const imps = encArr(n.implements, encNode);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, decs.len);
        \\    slotAt(idx, 0, decs.start);
        \\    slotAt(idx, {d}, id);
        \\    slotAt(idx, {d}, sc);
        \\    slotAt(idx, {d}, body);
        \\    slotAt(idx, {d}, tp);
        \\    slotAt(idx, {d}, sta);
        \\    slotAt(idx, {d}, imps.start);
        \\    slotAt(idx, {d}, imps.len);
        \\    flagsAt(idx, ((kind & {d}) << {d}) | (n.abstract ? {d} : 0) | (n.declare ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, si, ss, sb, stp, ssta, simp, simp + 1, tm, bt, mab, mdc });
}

fn writeSpecialMethodDef(w: *Writer, comptime tag: usize) !void {
    const T = ast.MethodDefinition;
    const sk = comptime slotOf(T, "key");
    const sv = comptime slotOf(T, "value");
    const bk = comptime flagBit(T, "kind");
    const mc = comptime flagMask(T, "computed");
    const ms = comptime flagMask(T, "static");
    const mo = comptime flagMask(T, "override");
    const mp = comptime flagMask(T, "optional");
    const mab = comptime flagMask(T, "abstract");
    const ba = comptime flagBit(T, "accessibility");
    try w.print(
        \\  function enc_method_definition(n, abstract) {{
        \\    const decs = encArr(n.decorators, encNode);
        \\    const k = n.computed ? encNode(n.key) : encPropertyKey(n.key);
        \\    const v = encNode(n.value);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, decs.len);
        \\    slotAt(idx, 0, decs.start);
        \\    slotAt(idx, {d}, k);
        \\    slotAt(idx, {d}, v);
        \\    flagsAt(idx,
        \\      ((METHOD_KINDS_INV[n.kind] | 0) << {d}) |
        \\      (n.computed ? {d} : 0) |
        \\      (n.static ? {d} : 0) |
        \\      (n.override ? {d} : 0) |
        \\      (n.optional ? {d} : 0) |
        \\      (abstract ? {d} : 0) |
        \\      (ACCESSIBILITY_INV(n.accessibility) << {d}));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, sv, bk, mc, ms, mo, mp, mab, ba });
}

fn writeSpecialPropertyDef(w: *Writer, comptime tag: usize) !void {
    const T = ast.PropertyDefinition;
    const sk = comptime slotOf(T, "key");
    const sv = comptime slotOf(T, "value");
    const sta = comptime slotOf(T, "type_annotation");
    const mc = comptime flagMask(T, "computed");
    const ms = comptime flagMask(T, "static");
    const macc = comptime flagMask(T, "accessor");
    const md = comptime flagMask(T, "declare");
    const mo = comptime flagMask(T, "override");
    const mp = comptime flagMask(T, "optional");
    const mdef = comptime flagMask(T, "definite");
    const mr = comptime flagMask(T, "readonly");
    const mab = comptime flagMask(T, "abstract");
    const bacc = comptime flagBit(T, "accessibility");
    try w.print(
        \\  function enc_property_definition(n, accessor, abstract) {{
        \\    const decs = encArr(n.decorators, encNode);
        \\    const k = n.computed ? encNode(n.key) : encPropertyKey(n.key);
        \\    const v = n.value == null ? NULL : encNode(n.value);
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, decs.len);
        \\    slotAt(idx, 0, decs.start);
        \\    slotAt(idx, {d}, k);
        \\    slotAt(idx, {d}, v);
        \\    slotAt(idx, {d}, ta);
        \\    flagsAt(idx,
        \\      (n.computed ? {d} : 0) |
        \\      (n.static ? {d} : 0) |
        \\      (accessor ? {d} : 0) |
        \\      (n.declare ? {d} : 0) |
        \\      (n.override ? {d} : 0) |
        \\      (n.optional ? {d} : 0) |
        \\      (n.definite ? {d} : 0) |
        \\      (n.readonly ? {d} : 0) |
        \\      (abstract ? {d} : 0) |
        \\      (ACCESSIBILITY_INV(n.accessibility) << {d}));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, sv, sta, mc, ms, macc, md, mo, mp, mdef, mr, mab, bacc });
}

fn writeSpecialObjectProperty(w: *Writer, comptime tag: usize) !void {
    const T = ast.ObjectProperty;
    const sk = comptime slotOf(T, "key");
    const sv = comptime slotOf(T, "value");
    const bk = comptime flagBit(T, "kind");
    const mm = comptime flagMask(T, "method");
    const msh = comptime flagMask(T, "shorthand");
    const mc = comptime flagMask(T, "computed");
    try w.print(
        \\  function enc_object_property(n) {{
        \\    const k = n.key == null ? NULL : (n.computed ? encNode(n.key) : encPropertyKey(n.key));
        \\    const v = n.value == null ? NULL : encNode(n.value);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, k); slotAt(idx, {d}, v);
        \\    flagsAt(idx, ((PROPERTY_KINDS_INV[n.kind] | 0) << {d}) | (n.method ? {d} : 0) | (n.shorthand ? {d} : 0) | (n.computed ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, sv, bk, mm, msh, mc });
}

fn writeSpecialBindingProperty(w: *Writer, comptime tag: usize) !void {
    const T = ast.BindingProperty;
    const sk = comptime slotOf(T, "key");
    const sv = comptime slotOf(T, "value");
    const msh = comptime flagMask(T, "shorthand");
    const mc = comptime flagMask(T, "computed");
    try w.print(
        \\  function enc_binding_property(p) {{
        \\    const k = p.key == null ? NULL : (p.computed ? encNode(p.key) : encPropertyKey(p.key));
        \\    const v = p.value == null ? NULL : encBindingTarget(p.value);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, k); slotAt(idx, {d}, v);
        \\    flagsAt(idx, (p.shorthand ? {d} : 0) | (p.computed ? {d} : 0));
        \\    spanAt(idx, asStart(p), asEnd(p));
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, sv, msh, mc });
}

fn writeSpecialArrayPattern(w: *Writer, comptime tag: usize) !void {
    const T = ast.ArrayPattern;
    const sr = comptime slotOf(T, "rest");
    const sdec = comptime slotOf(T, "decorators");
    const sta = comptime slotOf(T, "type_annotation");
    const mopt = comptime flagMask(T, "optional");
    try w.print(
        \\  function enc_array_pattern(n) {{
        \\    const els = n.elements || [];
        \\    let rest = NULL;
        \\    const items = [];
        \\    for (let i = 0; i < els.length; i++) {{
        \\      const e = els[i];
        \\      if (e == null) items.push(null);
        \\      else if (e.type === "RestElement") rest = enc_binding_rest_element(e);
        \\      else items.push(e);
        \\    }}
        \\    const r = encArrHoles(items, encBindingTarget);
        \\    const decs = encArr(n.decorators, encNode);
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, r.len);
        \\    slotAt(idx, 0, r.start);
        \\    slotAt(idx, {d}, rest);
        \\    slotAt(idx, {d}, decs.start); slotAt(idx, {d}, decs.len);
        \\    slotAt(idx, {d}, ta);
        \\    flagsAt(idx, n.optional ? {d} : 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sr, sdec, sdec + 1, sta, mopt });
}

fn writeSpecialObjectPattern(w: *Writer, comptime tag: usize) !void {
    const T = ast.ObjectPattern;
    const sr = comptime slotOf(T, "rest");
    const sdec = comptime slotOf(T, "decorators");
    const sta = comptime slotOf(T, "type_annotation");
    const mopt = comptime flagMask(T, "optional");
    try w.print(
        \\  function enc_object_pattern(n) {{
        \\    const props = n.properties || [];
        \\    let rest = NULL;
        \\    const items = [];
        \\    for (let i = 0; i < props.length; i++) {{
        \\      const p = props[i];
        \\      if (p && p.type === "RestElement") rest = enc_binding_rest_element(p);
        \\      else items.push(p);
        \\    }}
        \\    const r = encArr(items, enc_binding_property);
        \\    const decs = encArr(n.decorators, encNode);
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, r.len);
        \\    slotAt(idx, 0, r.start);
        \\    slotAt(idx, {d}, rest);
        \\    slotAt(idx, {d}, decs.start); slotAt(idx, {d}, decs.len);
        \\    slotAt(idx, {d}, ta);
        \\    flagsAt(idx, n.optional ? {d} : 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sr, sdec, sdec + 1, sta, mopt });
}

fn writeSpecialProgram(w: *Writer, comptime tag: usize) !void {
    const sb = comptime slotOf(ast.Program, "body");
    const sh = comptime slotOf(ast.Program, "hashbang");
    const bh = comptime flagBit(ast.Program, "hashbang");
    const mh = comptime flagMask(ast.Program, "hashbang");
    _ = bh;
    try w.print(
        \\  function enc_program(n) {{
        \\    const body = encArr(n.body, encNode);
        \\    const hb = n.hashbang && typeof n.hashbang.value === "string" ? encStr(n.hashbang.value) : null;
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, body.len);
        \\    slotAt(idx, {d}, body.start);
        \\    if (hb) {{ slotAt(idx, {d}, hb.start); slotAt(idx, {d}, hb.end); }}
        \\    flagsAt(idx, (n.sourceType === "script" ? 0 : 1) | (hb ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sb, sh, sh + 1, mh });
}

fn writeSpecialDirective(w: *Writer, comptime tag: usize) !void {
    const se = comptime slotOf(ast.Directive, "expression");
    const sv = comptime slotOf(ast.Directive, "value");
    try w.print(
        \\  function enc_directive(n) {{
        \\    const e = encNode(n.expression);
        \\    const dv = encStr(n.directive);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, e);
        \\    slotAt(idx, {d}, dv.start); slotAt(idx, {d}, dv.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, se, sv, sv + 1 });
}

fn writeSpecialJSXText(w: *Writer, comptime tag: usize) !void {
    const sv = comptime slotOf(ast.JSXText, "value");
    try w.print(
        \\  function enc_jsx_text(n) {{
        \\    const v = encStr(n.value || "");
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, v.start); slotAt(idx, {d}, v.end);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sv, sv + 1 });
}

fn writeSigParams(w: *Writer, comptime label: []const u8, comptime tag: usize, comptime T: type) !void {
    const stp = comptime slotOf(T, "type_parameters");
    const sp = comptime slotOf(T, "params");
    const srt = comptime slotOf(T, "return_type");
    try w.print(
        \\  function enc_{s}(n) {{
        \\    const tp = n.typeParameters == null ? NULL : encNode(n.typeParameters);
        \\    const params = encFormalParameters(n.params);
        \\    const rt_ = n.returnType == null ? NULL : encNode(n.returnType);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, tp); slotAt(idx, {d}, params); slotAt(idx, {d}, rt_);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ label, tag, stp, sp, srt });
}

fn writeSpecialTSFunctionType(w: *Writer, comptime tag: usize) !void {
    try writeSigParams(w, "ts_function_type", tag, ast.TSFunctionType);
}

fn writeSpecialTSConstructorType(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSConstructorType;
    const stp = comptime slotOf(T, "type_parameters");
    const sp = comptime slotOf(T, "params");
    const srt = comptime slotOf(T, "return_type");
    const mab = comptime flagMask(T, "abstract");
    try w.print(
        \\  function enc_ts_constructor_type(n) {{
        \\    const tp = n.typeParameters == null ? NULL : encNode(n.typeParameters);
        \\    const params = encFormalParameters(n.params);
        \\    const rt_ = n.returnType == null ? NULL : encNode(n.returnType);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, tp); slotAt(idx, {d}, params); slotAt(idx, {d}, rt_);
        \\    flagsAt(idx, n.abstract ? {d} : 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, stp, sp, srt, mab });
}

fn writeSpecialTSMethodSig(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSMethodSignature;
    const sk = comptime slotOf(T, "key");
    const stp = comptime slotOf(T, "type_parameters");
    const sp = comptime slotOf(T, "params");
    const srt = comptime slotOf(T, "return_type");
    const mc = comptime flagMask(T, "computed");
    const mo = comptime flagMask(T, "optional");
    const bk = comptime flagBit(T, "kind");
    try w.print(
        \\  function enc_ts_method_signature(n) {{
        \\    const k = n.computed ? encNode(n.key) : encPropertyKey(n.key);
        \\    const tp = n.typeParameters == null ? NULL : encNode(n.typeParameters);
        \\    const params = encFormalParameters(n.params);
        \\    const rt_ = n.returnType == null ? NULL : encNode(n.returnType);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, k); slotAt(idx, {d}, tp); slotAt(idx, {d}, params); slotAt(idx, {d}, rt_);
        \\    flagsAt(idx, (n.computed ? {d} : 0) | (n.optional ? {d} : 0) | ((TS_METHOD_SIGNATURE_KINDS_INV[n.kind] | 0) << {d}));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, stp, sp, srt, mc, mo, bk });
}

fn writeSpecialTSCallSig(w: *Writer, comptime tag: usize) !void {
    try writeSigParams(w, "ts_call_signature_declaration", tag, ast.TSCallSignatureDeclaration);
}

fn writeSpecialTSConstructSig(w: *Writer, comptime tag: usize) !void {
    try writeSigParams(w, "ts_construct_signature_declaration", tag, ast.TSConstructSignatureDeclaration);
}

fn writeSpecialTSMappedType(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSMappedType;
    const sk = comptime slotOf(T, "key");
    const sc = comptime slotOf(T, "constraint");
    const sn = comptime slotOf(T, "name_type");
    const sta = comptime slotOf(T, "type_annotation");
    const bo = comptime flagBit(T, "optional");
    const br = comptime flagBit(T, "readonly");
    try w.print(
        \\  function enc_ts_mapped_type(n) {{
        \\    const k = encNode(n.key);
        \\    const c = encNode(n.constraint);
        \\    const nt = n.nameType == null ? NULL : encNode(n.nameType);
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, k); slotAt(idx, {d}, c); slotAt(idx, {d}, nt); slotAt(idx, {d}, ta);
        \\    flagsAt(idx, (TS_MAPPED_OPTIONAL_INV(n.optional) << {d}) | (TS_MAPPED_READONLY_INV(n.readonly) << {d}));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, sc, sn, sta, bo, br });
}

fn writeSpecialTSModuleDecl(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSModuleDeclaration;
    const si = comptime slotOf(T, "id");
    const sb = comptime slotOf(T, "body");
    const bk = comptime flagBit(T, "kind");
    const md = comptime flagMask(T, "declare");
    try w.print(
        \\  function enc_ts_module_declaration(n) {{
        \\    const id = encNode(n.id);
        \\    const body = n.body == null ? NULL : encNode(n.body);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, id);
        \\    slotAt(idx, {d}, body);
        \\    flagsAt(idx, ((TS_MODULE_KINDS_INV[n.kind] | 0) << {d}) | (n.declare ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, si, sb, bk, md });
}

fn writeSpecialTSGlobalDecl(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSGlobalDeclaration;
    const si = comptime slotOf(T, "id");
    const sb = comptime slotOf(T, "body");
    const md = comptime flagMask(T, "declare");
    try w.print(
        \\  function enc_ts_global_declaration(n) {{
        \\    const id = encNode(n.id);
        \\    const body = encNode(n.body);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, id);
        \\    slotAt(idx, {d}, body);
        \\    flagsAt(idx, n.declare ? {d} : 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, si, sb, md });
}

fn writeSpecialTSThisParam(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSThisParameter;
    const sta = comptime slotOf(T, "type_annotation");
    try w.print(
        \\  function enc_ts_this_parameter(n) {{
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, ta);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sta });
}

fn writeSpecialTSPropertySig(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSPropertySignature;
    const sk = comptime slotOf(T, "key");
    const sta = comptime slotOf(T, "type_annotation");
    const mc = comptime flagMask(T, "computed");
    const mo = comptime flagMask(T, "optional");
    const mr = comptime flagMask(T, "readonly");
    try w.print(
        \\  function enc_ts_property_signature(n) {{
        \\    const k = n.computed ? encNode(n.key) : encPropertyKey(n.key);
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, k); slotAt(idx, {d}, ta);
        \\    flagsAt(idx, (n.computed ? {d} : 0) | (n.optional ? {d} : 0) | (n.readonly ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sk, sta, mc, mo, mr });
}

fn writeSpecialTSEnumMember(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSEnumMember;
    const sid = comptime slotOf(T, "id");
    const sin = comptime slotOf(T, "initializer");
    const mc = comptime flagMask(T, "computed");
    try w.print(
        \\  function enc_ts_enum_member(n) {{
        \\    const id = n.computed ? encNode(n.id) : encPropertyKey(n.id);
        \\    const init = n.initializer == null ? NULL : encNode(n.initializer);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    slotAt(idx, {d}, id); slotAt(idx, {d}, init);
        \\    flagsAt(idx, n.computed ? {d} : 0);
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sid, sin, mc });
}

fn writeSpecialTSIndexSig(w: *Writer, comptime tag: usize) !void {
    const T = ast.TSIndexSignature;
    const sp = comptime slotOf(T, "parameters");
    const sta = comptime slotOf(T, "type_annotation");
    const mr = comptime flagMask(T, "readonly");
    const ms = comptime flagMask(T, "static");
    _ = sp;
    try w.print(
        \\  function enc_ts_index_signature(n) {{
        \\    const ps = encArr(n.parameters, encBindingTarget);
        \\    const ta = n.typeAnnotation == null ? NULL : encNode(n.typeAnnotation);
        \\    const idx = alloc();
        \\    tagAt(idx, {d});
        \\    f0At(idx, ps.len);
        \\    slotAt(idx, 0, ps.start);
        \\    slotAt(idx, {d}, ta);
        \\    flagsAt(idx, (n.readonly ? {d} : 0) | (n.static ? {d} : 0));
        \\    spanAt(idx, asStart(n), asEnd(n));
        \\    recordComments(n, idx);
        \\    return idx;
        \\  }}
        \\
    , .{ tag, sta, mr, ms });
}

// Dispatcher

fn writeDispatcher(w: *Writer) !void {
    try w.writeAll(
        \\  // encoded node index -> its `.comments` array
        \\  const commentsByIdx = new Map();
        \\  function encNode(n) {
        \\    if (n == null) return NULL;
        \\    switch (n.type) {
        \\      case "Identifier": {
        \\        switch (n.kind) {
        \\          case "binding": return enc_binding_identifier(n);
        \\          case "name": return enc_identifier_name(n);
        \\          case "label": return enc_label_identifier(n);
        \\          default: return enc_identifier_reference(n);
        \\        }
        \\      }
        \\      case "PrivateIdentifier": return enc_private_identifier(n);
        \\      case "Literal": {
        \\        if (n.regex) return enc_regexp_literal(n);
        \\        if (typeof n.bigint === "string") return enc_bigint_literal(n);
        \\        const v = n.value;
        \\        if (v === null) return typeof n.raw === "string" && n.raw !== "null" ? enc_numeric_literal(n) : enc_null_literal(n);
        \\        if (typeof v === "boolean") return enc_boolean_literal(n);
        \\        if (typeof v === "string") return enc_string_literal(n);
        \\        if (typeof v === "number") return enc_numeric_literal(n);
        \\        throw new Error("yuku-codegen: unrecognised Literal value");
        \\      }
        \\      case "FunctionDeclaration": return enc_function(n, 0);
        \\      case "FunctionExpression": return enc_function(n, 1);
        \\      case "TSDeclareFunction": return enc_function(n, 2);
        \\      case "TSEmptyBodyFunctionExpression": return enc_function(n, 3);
        \\      case "ClassDeclaration": return enc_class(n, 0);
        \\      case "ClassExpression": return enc_class(n, 1);
        \\      case "MethodDefinition": return enc_method_definition(n, false);
        \\      case "TSAbstractMethodDefinition": return enc_method_definition(n, true);
        \\      case "PropertyDefinition": return enc_property_definition(n, false, false);
        \\      case "TSAbstractPropertyDefinition": return enc_property_definition(n, false, true);
        \\      case "AccessorProperty": return enc_property_definition(n, true, false);
        \\      case "TSAbstractAccessorProperty": return enc_property_definition(n, true, true);
        \\      case "RestElement": return enc_binding_rest_element(n);
        \\      case "TSModuleDeclaration": return n.global ? enc_ts_global_declaration(n) : enc_ts_module_declaration(n);
        \\      case "ExpressionStatement": return n.directive != null ? enc_directive(n) : enc_expression_statement(n);
        \\
    );
    inline for (@typeInfo(ast.NodeData).@"union".fields) |field| {
        const name = field.name;
        if (comptime skipGeneration(name)) continue;
        if (comptime skipInDispatcher(name)) continue;
        const etype = comptime meta.estreeType(name);
        try w.print("      case \"{s}\": return enc_{s}(n);\n", .{ etype, name });
    }
    try w.writeAll(
        \\      default: throw new Error("yuku-codegen: unsupported ESTree node type: " + n.type);
        \\    }
        \\  }
        \\
    );
}

/// nodes that have no direct ESTree dispatcher entry, either because a
/// hardcoded polymorphism branch above already handles their ESTree type,
/// or because they're only invoked indirectly through parent helpers.
fn skipInDispatcher(comptime name: []const u8) bool {
    @setEvalBranchQuota(20_000);
    const skipped = [_][]const u8{
        // ESTree polymorphism already routes these in the hardcoded prelude.
        "identifier_reference", "binding_identifier",    "identifier_name",
        "label_identifier",     "private_identifier",    "string_literal",
        "numeric_literal",      "bigint_literal",        "boolean_literal",
        "null_literal",         "regexp_literal",        "function",
        "class",                "method_definition",     "property_definition",
        "binding_rest_element", "ts_module_declaration", "ts_global_declaration",
        "expression_statement", "directive",
        // not directly addressable by ESTree (no `type:` string for these).
                    "formal_parameter",
        "formal_parameters",    "binding_property",      "ts_this_parameter",
    };
    for (skipped) |s| if (s.len == name.len and std.mem.eql(u8, s, name)) return true;
    return false;
}

// Final assembly: collect sections into one ArrayBuffer

fn writeAssemble(w: *Writer) !void {
    try w.print(
        \\  const progIdx = encNode(root);
        \\  const POSITION_INV = {{ "before": 0, "after": 1, "inside": 2 }};
        \\  // counting-sort comments by host into a prefix-sum offsets table,
        \\  // then write each comment at its slot in `commentBytes`.
        \\  const attachComments = commentsByIdx.size > 0;
        \\  let commentCount = 0;
        \\  let offsetsBytes = null;
        \\  let commentBytes = null;
        \\  if (attachComments) {{
        \\    for (const arr of commentsByIdx.values()) commentCount += arr.length;
        \\    const offsets = new Uint32Array(nodeCount + 1);
        \\    for (const [idx, arr] of commentsByIdx) offsets[idx] = arr.length;
        \\    let sum = 0;
        \\    for (let i = 0; i < nodeCount; i++) {{
        \\      const c = offsets[i];
        \\      offsets[i] = sum;
        \\      sum += c;
        \\    }}
        \\    offsets[nodeCount] = sum;
        \\    offsetsBytes = offsets.buffer;
        \\    commentBytes = new ArrayBuffer(commentCount * COMMENT_SIZE);
        \\    const cU8 = new Uint8Array(commentBytes);
        \\    const cDV = new DataView(commentBytes);
        \\    const cursor = new Uint32Array(nodeCount);
        \\    for (const [idx, arr] of commentsByIdx) {{
        \\      for (let j = 0; j < arr.length; j++) {{
        \\        const c = arr[j];
        \\        const slot = offsets[idx] + cursor[idx]; cursor[idx]++;
        \\        let f = 0;
        \\        if (c.type === "Block") f |= 1;
        \\        f |= ((POSITION_INV[c.position] ?? 0) & 3) << 1;
        \\        if (c.sameLine) f |= 8;
        \\        const v = encStr(typeof c.value === "string" ? c.value : "");
        \\        const o = slot * COMMENT_SIZE;
        \\        cU8[o + COMMENT_FLAGS_OFFSET] = f;
        \\        cDV.setUint32(o + COMMENT_VALUE_START_OFFSET, v.start, true);
        \\        cDV.setUint32(o + COMMENT_VALUE_END_OFFSET, v.end, true);
        \\      }}
        \\    }}
        \\  }}
        \\  const lineStartsCount = Array.isArray(lineStarts) ? lineStarts.length : 0;
        \\  let lineStartsBytes = null;
        \\  if (lineStartsCount > 0) {{
        \\    lineStartsBytes = new ArrayBuffer(lineStartsCount * 4);
        \\    const lsDV = new DataView(lineStartsBytes);
        \\    for (let i = 0; i < lineStartsCount; i++) lsDV.setUint32(i * 4, lineStarts[i] >>> 0, true);
        \\  }}
        \\  const totalNodeBytes = nodeCount * NODE_SIZE;
        \\  const totalExtraBytes = extraCount * 4;
        \\  const totalOffsetsBytes = attachComments ? (nodeCount + 1) * 4 : 0;
        \\  const totalCommentBytes = commentCount * COMMENT_SIZE;
        \\  const totalLineStartsBytes = lineStartsCount * 4;
        \\  const finalSize = HEADER_SIZE + totalNodeBytes + totalExtraBytes + poolLen + totalOffsetsBytes + totalCommentBytes + totalLineStartsBytes;
        \\  const out = new ArrayBuffer(finalSize);
        \\  const outU8 = new Uint8Array(out);
        \\  const outU32 = new Uint32Array(out, 0, (finalSize >>> 2));
        \\  outU32[{[u_nc]d}] = nodeCount;
        \\  outU32[{[u_ec]d}] = extraCount;
        \\  outU32[{[u_sp]d}] = poolLen;
        \\  outU32[{[u_src]d}] = 0;
        \\  outU32[{[u_cc]d}] = commentCount;
        \\  outU32[{[u_ls]d}] = lineStartsCount;
        \\  outU32[{[u_dc]d}] = 0;
        \\  outU32[{[u_pi]d}] = progIdx;
        \\  outU32[{[u_fl]d}] = attachComments ? FLAG_ATTACH_COMMENTS : 0;
        \\  outU32[{[u_fna]d}] = 0;
        \\  const nodesOff = HEADER_SIZE;
        \\  const extrasOff = nodesOff + totalNodeBytes;
        \\  const poolOff = extrasOff + totalExtraBytes;
        \\  const offsetsOff = poolOff + poolLen;
        \\  const commentsOff = offsetsOff + totalOffsetsBytes;
        \\  const lineStartsOff = commentsOff + totalCommentBytes;
        \\  outU8.set(new Uint8Array(nodeAB, 0, totalNodeBytes), nodesOff);
        \\  outU8.set(new Uint8Array(extras.buffer, 0, totalExtraBytes), extrasOff);
        \\  outU8.set(pool.subarray(0, poolLen), poolOff);
        \\  if (offsetsBytes !== null) outU8.set(new Uint8Array(offsetsBytes), offsetsOff);
        \\  if (commentBytes !== null) outU8.set(new Uint8Array(commentBytes), commentsOff);
        \\  if (lineStartsBytes !== null) outU8.set(new Uint8Array(lineStartsBytes), lineStartsOff);
        \\  return out;
        \\}}
        \\
    , .{
        .u_nc = rt.HDR_NODE_COUNT_U32,
        .u_ec = rt.HDR_EXTRA_COUNT_U32,
        .u_sp = rt.HDR_STRING_POOL_LEN_U32,
        .u_src = rt.HDR_SOURCE_LEN_U32,
        .u_cc = rt.HDR_COMMENT_COUNT_U32,
        .u_ls = rt.HDR_LINE_STARTS_COUNT_U32,
        .u_dc = rt.HDR_DIAG_COUNT_U32,
        .u_pi = rt.HDR_PROGRAM_INDEX_U32,
        .u_fl = rt.HDR_FLAGS_U32,
        .u_fna = rt.HDR_FIRST_NON_ASCII_U32,
    });
}
