# crashing the profiler ('core dumped'), in the new Zig version 0.17, was working before, let's see if we can renable this workflow
# name: Profiler

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#   workflow_dispatch:

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   benchmarks:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - uses: oven-sh/setup-bun@v2
#       - uses: mlugg/setup-zig@v2
#         with:
#           version: 0.17.0-dev.224+c166c49b1
#       - name: Load files
#         run: bun load-files
#       - name: Build profiler
#         run: zig build --release=fast
#       - name: Run profiler
#         uses: CodSpeedHQ/action@v4
#         with:
#           mode: simulation
#           run: ./zig-out/bin/profiler
